# Auto-generated — Civil 26 — Autodesk.Civil

class AccelerationUnitType:
    """.NET: Autodesk.Civil.AccelerationUnitType"""
    def __init__(self, *args) -> None: ...
    ...

class AlignmentDesignCheck(DesignCheck):
    """.NET: Autodesk.Civil.AlignmentDesignCheck"""
    def __init__(self, *args) -> None: ...
    DesignCheckType: AlignmentDesignCheckType
    Expression: str
    Description: str
    Name: str

class AlignmentDesignCheckCollection(DesignCheckCollection<Autodesk::Civil::AlignmentDesignCheck ^>):
    """.NET: Autodesk.Civil.AlignmentDesignCheckCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: AlignmentDesignCheck
    Item: AlignmentDesignCheck
    def Add(self, name: str, description: str, expression: str) -> AlignmentDesignCheck: ...
    def Clear(self, ) -> None: ...
    def Remove(self, name: str) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class AlignmentDesignCheckRoot:
    """.NET: Autodesk.Civil.AlignmentDesignCheckRoot"""
    def __init__(self, *args) -> None: ...
    TangentIntersectionDesignChecks: AlignmentDesignCheckCollection
    SuperelevationDesignChecks: AlignmentDesignCheckCollection
    SpiralDesignChecks: AlignmentDesignCheckCollection
    CurveDesignChecks: AlignmentDesignCheckCollection
    LineDesignChecks: AlignmentDesignCheckCollection

class AlignmentDesignCheckType:
    """.NET: Autodesk.Civil.AlignmentDesignCheckType"""
    def __init__(self, *args) -> None: ...
    ...

class AlignmentDividedPivotType:
    """.NET: Autodesk.Civil.AlignmentDividedPivotType"""
    def __init__(self, *args) -> None: ...
    ...

class AlignmentLockModeType:
    """.NET: Autodesk.Civil.AlignmentLockModeType"""
    def __init__(self, *args) -> None: ...
    ...

class AlignmentMedianTreatmentType:
    """.NET: Autodesk.Civil.AlignmentMedianTreatmentType"""
    def __init__(self, *args) -> None: ...
    ...

class AlignmentPointType:
    """.NET: Autodesk.Civil.AlignmentPointType"""
    def __init__(self, *args) -> None: ...
    ...

class AlignmentTransitionSegmentType:
    """.NET: Autodesk.Civil.AlignmentTransitionSegmentType"""
    def __init__(self, *args) -> None: ...
    ...

class AlignmentUndividedPivotType:
    """.NET: Autodesk.Civil.AlignmentUndividedPivotType"""
    def __init__(self, *args) -> None: ...
    ...

class AlignmentUpdateModeType:
    """.NET: Autodesk.Civil.AlignmentUpdateModeType"""
    def __init__(self, *args) -> None: ...
    ...

class AnchorLocationType:
    """.NET: Autodesk.Civil.AnchorLocationType"""
    def __init__(self, *args) -> None: ...
    ...

class AnchorPointType:
    """.NET: Autodesk.Civil.AnchorPointType"""
    def __init__(self, *args) -> None: ...
    ...

class AngleFormatType:
    """.NET: Autodesk.Civil.AngleFormatType"""
    def __init__(self, *args) -> None: ...
    ...

class AngleUnitType:
    """.NET: Autodesk.Civil.AngleUnitType"""
    def __init__(self, *args) -> None: ...
    ...

class AreaUnitType:
    """.NET: Autodesk.Civil.AreaUnitType"""
    def __init__(self, *args) -> None: ...
    ...

class ArrowHeadFitType:
    """.NET: Autodesk.Civil.ArrowHeadFitType"""
    def __init__(self, *args) -> None: ...
    ...

class ArrowHeadSizeType:
    """.NET: Autodesk.Civil.ArrowHeadSizeType"""
    def __init__(self, *args) -> None: ...
    ...

class ArrowHeadType:
    """.NET: Autodesk.Civil.ArrowHeadType"""
    def __init__(self, *args) -> None: ...
    ...

class AssemblyDisplayStyleType:
    """.NET: Autodesk.Civil.AssemblyDisplayStyleType"""
    def __init__(self, *args) -> None: ...
    ...

class AssemblyGroupNameType:
    """.NET: Autodesk.Civil.AssemblyGroupNameType"""
    def __init__(self, *args) -> None: ...
    ...

class BandLocationType:
    """.NET: Autodesk.Civil.BandLocationType"""
    def __init__(self, *args) -> None: ...
    ...

class BandType:
    """.NET: Autodesk.Civil.BandType"""
    def __init__(self, *args) -> None: ...
    ...

class BearingQuadrantType:
    """.NET: Autodesk.Civil.BearingQuadrantType"""
    def __init__(self, *args) -> None: ...
    ...

class BlockAttachmentType:
    """.NET: Autodesk.Civil.BlockAttachmentType"""
    def __init__(self, *args) -> None: ...
    ...

class CantPivotMethodType:
    """.NET: Autodesk.Civil.CantPivotMethodType"""
    def __init__(self, *args) -> None: ...
    ...

class CantPointType:
    """.NET: Autodesk.Civil.CantPointType"""
    def __init__(self, *args) -> None: ...
    ...

class CantStationRoundingType:
    """.NET: Autodesk.Civil.CantStationRoundingType"""
    def __init__(self, *args) -> None: ...
    ...

class CantViewDisplayStyleType:
    """.NET: Autodesk.Civil.CantViewDisplayStyleType"""
    def __init__(self, *args) -> None: ...
    ...

class CapitalizationType:
    """.NET: Autodesk.Civil.CapitalizationType"""
    def __init__(self, *args) -> None: ...
    ...

class CatchmentObjectType:
    """.NET: Autodesk.Civil.CatchmentObjectType"""
    def __init__(self, *args) -> None: ...
    ...

class CatchmentRainfallTravelTimeUnitType:
    """.NET: Autodesk.Civil.CatchmentRainfallTravelTimeUnitType"""
    def __init__(self, *args) -> None: ...
    ...

class CatchmentShallowConcentratedFlowSurfaceType:
    """.NET: Autodesk.Civil.CatchmentShallowConcentratedFlowSurfaceType"""
    def __init__(self, *args) -> None: ...
    ...

class CatchmentTimeOfConcentrationMethodType:
    """.NET: Autodesk.Civil.CatchmentTimeOfConcentrationMethodType"""
    def __init__(self, *args) -> None: ...
    ...

class CatchmentWatershedObjectType:
    """.NET: Autodesk.Civil.CatchmentWatershedObjectType"""
    def __init__(self, *args) -> None: ...
    ...

class CivilException(Exception):
    """.NET: Autodesk.Civil.CivilException"""
    def __init__(self, *args) -> None: ...
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @staticmethod
    def ErrorHandler(es: ErrorStatus, message: str) -> None: ...

class CivilVersion:
    """.NET: Autodesk.Civil.CivilVersion"""
    def __init__(self, *args) -> None: ...
    ...

class CivilWrapper<AcDbDatabase>:
    """.NET: Autodesk.Civil.CivilWrapper<AcDbDatabase>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbAlignStnLabelsDlgTemplate>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbAlignStnLabelsDlgTemplate>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbAlignment>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbAlignment>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbCorridor>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbCorridor>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbEntity>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbEntity>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbGraph>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbGraph>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbGraphProfile>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbGraphProfile>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbGraphStyle>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbGraphStyle>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbGraphStyleBands>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbGraphStyleBands>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbIntersection>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbIntersection>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbLabelStyleBlock>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbLabelStyleBlock>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbLabelStyleCollector>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbLabelStyleCollector>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbLabelStyleRadialLine>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbLabelStyleRadialLine>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbLabelStyleText>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbLabelStyleText>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbLabelStyleTick>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbLabelStyleTick>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbLabelStyleVectorArrow>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbLabelStyleVectorArrow>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbPipeStyle>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbPipeStyle>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbProfileSectionEntityStyle>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbProfileSectionEntityStyle>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbQuantityTakeoffCriteria>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbQuantityTakeoffCriteria>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbRoadwayStyleSet>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbRoadwayStyleSet>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbRuntimeState>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbRuntimeState>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbSampleLine>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbSampleLine>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbScheduleTableStyle>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbScheduleTableStyle>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbSection>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbSection>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbSlopePatternStyle>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbSlopePatternStyle>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbStructureStyle>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbStructureStyle>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbStyle>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbStyle>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbSurfaceStyle>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbSurfaceStyle>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccDbVAlignment>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccDbVAlignment>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccGeSCSCSConstraints>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccGeSCSCSConstraints>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccGeSCSSCSConstraints>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccGeSCSSCSConstraints>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccQuantityTakeoffResult::SECTIONAL_RESULT>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccQuantityTakeoffResult::SECTIONAL_RESULT>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccQuantityTakeoffResult>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccQuantityTakeoffResult>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccSlopeElevationTarget>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccSlopeElevationTarget>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<AeccWidthOffsetTarget>:
    """.NET: Autodesk.Civil.CivilWrapper<AeccWidthOffsetTarget>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<Autodesk::Civil::DatabaseServices::SampleSectionLinkData>:
    """.NET: Autodesk.Civil.CivilWrapper<Autodesk::Civil::DatabaseServices::SampleSectionLinkData>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<std::vector<Autodesk::Civil::DatabaseServices::SampleSectionLinkData \*\,std::allocator<Autodesk::Civil::DatabaseServices::SampleSectionLinkData \*> > >:
    """.NET: Autodesk.Civil.CivilWrapper<std::vector<Autodesk::Civil::DatabaseServices::SampleSectionLinkData \*\,std::allocator<Autodesk::Civil::DatabaseServices::SampleSectionLinkData \*> > >"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class CivilWrapper<tableCellComponentVec>:
    """.NET: Autodesk.Civil.CivilWrapper<tableCellComponentVec>"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class Constant:
    """.NET: Autodesk.Civil.Constant"""
    def __init__(self, *args) -> None: ...
    ...

class CorridorAlongCurveOption:
    """.NET: Autodesk.Civil.CorridorAlongCurveOption"""
    def __init__(self, *args) -> None: ...
    ...

class CorridorAlongOffsetTargetCurveOption:
    """.NET: Autodesk.Civil.CorridorAlongOffsetTargetCurveOption"""
    def __init__(self, *args) -> None: ...
    ...

class CorridorRegionLockType:
    """.NET: Autodesk.Civil.CorridorRegionLockType"""
    def __init__(self, *args) -> None: ...
    ...

class CrossSectionShapeType:
    """.NET: Autodesk.Civil.CrossSectionShapeType"""
    def __init__(self, *args) -> None: ...
    ...

class CrossingBreaklinesElevationType:
    """.NET: Autodesk.Civil.CrossingBreaklinesElevationType"""
    def __init__(self, *args) -> None: ...
    ...

class CurbReturnCurveGroupType:
    """.NET: Autodesk.Civil.CurbReturnCurveGroupType"""
    def __init__(self, *args) -> None: ...
    ...

class CurbReturnType:
    """.NET: Autodesk.Civil.CurbReturnType"""
    def __init__(self, *args) -> None: ...
    ...

class DecimalCharacterType:
    """.NET: Autodesk.Civil.DecimalCharacterType"""
    def __init__(self, *args) -> None: ...
    ...

class DeprecatedVersionAttribute(Attribute):
    """.NET: Autodesk.Civil.DeprecatedVersionAttribute"""
    def __init__(self, *args) -> None: ...
    Version: CivilVersion
    TypeId: object

class DesignCheck(CivilWrapper<AcDbDatabase>):
    """.NET: Autodesk.Civil.DesignCheck"""
    def __init__(self, *args) -> None: ...
    Expression: str
    Description: str
    Name: str

class DesignCheckCollection<Autodesk::Civil::AlignmentDesignCheck ^>:
    """.NET: Autodesk.Civil.DesignCheckCollection<Autodesk::Civil::AlignmentDesignCheck ^>"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: AlignmentDesignCheck
    Item: AlignmentDesignCheck
    def Add(self, name: str, description: str, expression: str) -> AlignmentDesignCheck: ...
    def Clear(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetObjectEnumerator(self, ) -> IEnumerator: ...
    def Remove(self, name: str) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class DesignCheckCollection<Autodesk::Civil::ProfileDesignCheck ^>:
    """.NET: Autodesk.Civil.DesignCheckCollection<Autodesk::Civil::ProfileDesignCheck ^>"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: ProfileDesignCheck
    Item: ProfileDesignCheck
    def Add(self, name: str, description: str, expression: str) -> ProfileDesignCheck: ...
    def Clear(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetObjectEnumerator(self, ) -> IEnumerator: ...
    def Remove(self, name: str) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class DesignSpeedLookupMethodType:
    """.NET: Autodesk.Civil.DesignSpeedLookupMethodType"""
    def __init__(self, *args) -> None: ...
    ...

class DimensionAnchorOptionType:
    """.NET: Autodesk.Civil.DimensionAnchorOptionType"""
    def __init__(self, *args) -> None: ...
    ...

class DimensionAnchorType:
    """.NET: Autodesk.Civil.DimensionAnchorType"""
    def __init__(self, *args) -> None: ...
    ...

class DirectionDisplayType:
    """.NET: Autodesk.Civil.DirectionDisplayType"""
    def __init__(self, *args) -> None: ...
    ...

class DirectionNameDisplayType:
    """.NET: Autodesk.Civil.DirectionNameDisplayType"""
    def __init__(self, *args) -> None: ...
    ...

class DistanceScaleFactorType:
    """.NET: Autodesk.Civil.DistanceScaleFactorType"""
    def __init__(self, *args) -> None: ...
    ...

class DrivingDirectionType:
    """.NET: Autodesk.Civil.DrivingDirectionType"""
    def __init__(self, *args) -> None: ...
    ...

class DropDecimalWholeType:
    """.NET: Autodesk.Civil.DropDecimalWholeType"""
    def __init__(self, *args) -> None: ...
    ...

class DropLeadingZeroType:
    """.NET: Autodesk.Civil.DropLeadingZeroType"""
    def __init__(self, *args) -> None: ...
    ...

class ElevationSourceType:
    """.NET: Autodesk.Civil.ElevationSourceType"""
    def __init__(self, *args) -> None: ...
    ...

class ElevationToUseType:
    """.NET: Autodesk.Civil.ElevationToUseType"""
    def __init__(self, *args) -> None: ...
    ...

class EntityNotFoundException(CivilException):
    """.NET: Autodesk.Civil.EntityNotFoundException"""
    def __init__(self, *args) -> None: ...
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str

class EntitySideType:
    """.NET: Autodesk.Civil.EntitySideType"""
    def __init__(self, *args) -> None: ...
    ...

class ErrorStatus:
    """.NET: Autodesk.Civil.ErrorStatus"""
    def __init__(self, *args) -> None: ...
    ...

class ErrorStatusText:
    """.NET: Autodesk.Civil.ErrorStatusText"""
    def __init__(self, *args) -> None: ...
    Text: str

class ExportDetermineElevationType:
    """.NET: Autodesk.Civil.ExportDetermineElevationType"""
    def __init__(self, *args) -> None: ...
    ...

class FeatureLineConnectDirectionType:
    """.NET: Autodesk.Civil.FeatureLineConnectDirectionType"""
    def __init__(self, *args) -> None: ...
    ...

class FeatureLineLayerSettingType:
    """.NET: Autodesk.Civil.FeatureLineLayerSettingType"""
    def __init__(self, *args) -> None: ...
    ...

class FeatureLineLayerType:
    """.NET: Autodesk.Civil.FeatureLineLayerType"""
    def __init__(self, *args) -> None: ...
    ...

class FeatureLinePointType:
    """.NET: Autodesk.Civil.FeatureLinePointType"""
    def __init__(self, *args) -> None: ...
    ...

class FlowUnitType:
    """.NET: Autodesk.Civil.FlowUnitType"""
    def __init__(self, *args) -> None: ...
    ...

class FreeHaulDisplayType:
    """.NET: Autodesk.Civil.FreeHaulDisplayType"""
    def __init__(self, *args) -> None: ...
    ...

class GeometryPointLabelOption:
    """.NET: Autodesk.Civil.GeometryPointLabelOption`1"""
    def __init__(self, *args) -> None: ...
    Selected: bool
    PointType: T

class GeometryPointSelector:
    """.NET: Autodesk.Civil.GeometryPointSelector`1"""
    def __init__(self, *args) -> None: ...
    Item: GeometryPointLabelOption
    def SelectAll(self, ) -> None: ...
    def UnSelectAll(self, ) -> None: ...

class GradeFormatType:
    """.NET: Autodesk.Civil.GradeFormatType"""
    def __init__(self, *args) -> None: ...
    ...

class GradeSlopeFormatType:
    """.NET: Autodesk.Civil.GradeSlopeFormatType"""
    def __init__(self, *args) -> None: ...
    ...

class GradingDistanceProjectionType:
    """.NET: Autodesk.Civil.GradingDistanceProjectionType"""
    def __init__(self, *args) -> None: ...
    ...

class GradingElevationProjectionType:
    """.NET: Autodesk.Civil.GradingElevationProjectionType"""
    def __init__(self, *args) -> None: ...
    ...

class GradingInteriorCornerOverlapSolutionType:
    """.NET: Autodesk.Civil.GradingInteriorCornerOverlapSolutionType"""
    def __init__(self, *args) -> None: ...
    ...

class GradingRelativeElevationProjectionType:
    """.NET: Autodesk.Civil.GradingRelativeElevationProjectionType"""
    def __init__(self, *args) -> None: ...
    ...

class GradingSearchOrderType:
    """.NET: Autodesk.Civil.GradingSearchOrderType"""
    def __init__(self, *args) -> None: ...
    ...

class GradingSlopeFormatType:
    """.NET: Autodesk.Civil.GradingSlopeFormatType"""
    def __init__(self, *args) -> None: ...
    ...

class GradingSurfaceProjectionType:
    """.NET: Autodesk.Civil.GradingSurfaceProjectionType"""
    def __init__(self, *args) -> None: ...
    ...

class GradingTargetType:
    """.NET: Autodesk.Civil.GradingTargetType"""
    def __init__(self, *args) -> None: ...
    ...

class HighSideShoulderMethodType:
    """.NET: Autodesk.Civil.HighSideShoulderMethodType"""
    def __init__(self, *args) -> None: ...
    ...

class HighsideLocationType:
    """.NET: Autodesk.Civil.HighsideLocationType"""
    def __init__(self, *args) -> None: ...
    ...

class IProperty:
    """.NET: Autodesk.Civil.IProperty"""
    def __init__(self, *args) -> None: ...
    Value: object
    IsOverridable: bool
    Overridden: bool
    Locked: bool

class ImpliedPointOfIntersectionDisplayType:
    """.NET: Autodesk.Civil.ImpliedPointOfIntersectionDisplayType"""
    def __init__(self, *args) -> None: ...
    ...

class InternalC3DPipesToStmMigration:
    """.NET: Autodesk.Civil.InternalC3DPipesToStmMigration"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Migrate(pDwgDb: Database, stmFileName: str, pipeNetworkIds: ObjectIdCollection) -> bool: ...

class KrigingSemivariogramType:
    """.NET: Autodesk.Civil.KrigingSemivariogramType"""
    def __init__(self, *args) -> None: ...
    ...

class LabelContentDisplayType:
    """.NET: Autodesk.Civil.LabelContentDisplayType"""
    def __init__(self, *args) -> None: ...
    ...

class LabelInsertionType:
    """.NET: Autodesk.Civil.LabelInsertionType"""
    def __init__(self, *args) -> None: ...
    ...

class LabelInsideCurveType:
    """.NET: Autodesk.Civil.LabelInsideCurveType"""
    def __init__(self, *args) -> None: ...
    ...

class LabelMaskType:
    """.NET: Autodesk.Civil.LabelMaskType"""
    def __init__(self, *args) -> None: ...
    ...

class LabelRotationType:
    """.NET: Autodesk.Civil.LabelRotationType"""
    def __init__(self, *args) -> None: ...
    ...

class LabelStyleLengthType:
    """.NET: Autodesk.Civil.LabelStyleLengthType"""
    def __init__(self, *args) -> None: ...
    ...

class LabelTextAttachmentType:
    """.NET: Autodesk.Civil.LabelTextAttachmentType"""
    def __init__(self, *args) -> None: ...
    ...

class LabelingPromptType:
    """.NET: Autodesk.Civil.LabelingPromptType"""
    def __init__(self, *args) -> None: ...
    ...

class LandXMLImportAlignmentType:
    """.NET: Autodesk.Civil.LandXMLImportAlignmentType"""
    def __init__(self, *args) -> None: ...
    ...

class LandXMLImportFeatureLineSite:
    """.NET: Autodesk.Civil.LandXMLImportFeatureLineSite"""
    def __init__(self, *args) -> None: ...
    ...

class LatLongDirectionType:
    """.NET: Autodesk.Civil.LatLongDirectionType"""
    def __init__(self, *args) -> None: ...
    ...

class LayoutModeType:
    """.NET: Autodesk.Civil.LayoutModeType"""
    def __init__(self, *args) -> None: ...
    ...

class LeaderAttachmentBehaviorType:
    """.NET: Autodesk.Civil.LeaderAttachmentBehaviorType"""
    def __init__(self, *args) -> None: ...
    ...

class LeaderAttachmentType:
    """.NET: Autodesk.Civil.LeaderAttachmentType"""
    def __init__(self, *args) -> None: ...
    ...

class LeaderShapeType:
    """.NET: Autodesk.Civil.LeaderShapeType"""
    def __init__(self, *args) -> None: ...
    ...

class LeaderTailVisibilityType:
    """.NET: Autodesk.Civil.LeaderTailVisibilityType"""
    def __init__(self, *args) -> None: ...
    ...

class LeaderVisibilityType:
    """.NET: Autodesk.Civil.LeaderVisibilityType"""
    def __init__(self, *args) -> None: ...
    ...

class LinearUnitType:
    """.NET: Autodesk.Civil.LinearUnitType"""
    def __init__(self, *args) -> None: ...
    ...

class LinkCreationType:
    """.NET: Autodesk.Civil.LinkCreationType"""
    def __init__(self, *args) -> None: ...
    ...

class LowSideShoulderMethodType:
    """.NET: Autodesk.Civil.LowSideShoulderMethodType"""
    def __init__(self, *args) -> None: ...
    ...

class MassHaulLineDisplayStyleType:
    """.NET: Autodesk.Civil.MassHaulLineDisplayStyleType"""
    def __init__(self, *args) -> None: ...
    ...

class MassHaulLineHatchDisplayStyleType:
    """.NET: Autodesk.Civil.MassHaulLineHatchDisplayStyleType"""
    def __init__(self, *args) -> None: ...
    ...

class MassHaulViewDisplayStyleType:
    """.NET: Autodesk.Civil.MassHaulViewDisplayStyleType"""
    def __init__(self, *args) -> None: ...
    ...

class MatchLineLabelLocationType:
    """.NET: Autodesk.Civil.MatchLineLabelLocationType"""
    def __init__(self, *args) -> None: ...
    ...

class NetworkDefaultLayoutCommandType:
    """.NET: Autodesk.Civil.NetworkDefaultLayoutCommandType"""
    def __init__(self, *args) -> None: ...
    ...

class OrientationReferenceType:
    """.NET: Autodesk.Civil.OrientationReferenceType"""
    def __init__(self, *args) -> None: ...
    ...

class ParcelAnalysisType:
    """.NET: Autodesk.Civil.ParcelAnalysisType"""
    def __init__(self, *args) -> None: ...
    ...

class ParcelRemainderDistributionType:
    """.NET: Autodesk.Civil.ParcelRemainderDistributionType"""
    def __init__(self, *args) -> None: ...
    ...

class ParcelSelectionType:
    """.NET: Autodesk.Civil.ParcelSelectionType"""
    def __init__(self, *args) -> None: ...
    ...

class ParcelSolutionType:
    """.NET: Autodesk.Civil.ParcelSolutionType"""
    def __init__(self, *args) -> None: ...
    ...

class PipeNetworkPartDisplayType:
    """.NET: Autodesk.Civil.PipeNetworkPartDisplayType"""
    def __init__(self, *args) -> None: ...
    ...

class PipeSectionLabelPlacementType:
    """.NET: Autodesk.Civil.PipeSectionLabelPlacementType"""
    def __init__(self, *args) -> None: ...
    ...

class PlacementOptionType:
    """.NET: Autodesk.Civil.PlacementOptionType"""
    def __init__(self, *args) -> None: ...
    ...

class PlanViewAlignType:
    """.NET: Autodesk.Civil.PlanViewAlignType"""
    def __init__(self, *args) -> None: ...
    ...

class PlottedUnitDisplayType:
    """.NET: Autodesk.Civil.PlottedUnitDisplayType"""
    def __init__(self, *args) -> None: ...
    ...

class PointCloudDefaultFileExtensionType:
    """.NET: Autodesk.Civil.PointCloudDefaultFileExtensionType"""
    def __init__(self, *args) -> None: ...
    ...

class PointCloudDisplayStyleType:
    """.NET: Autodesk.Civil.PointCloudDisplayStyleType"""
    def __init__(self, *args) -> None: ...
    ...

class PointCloudElevationRangeCreationType:
    """.NET: Autodesk.Civil.PointCloudElevationRangeCreationType"""
    def __init__(self, *args) -> None: ...
    ...

class PointCloudRangeColorSchemeType:
    """.NET: Autodesk.Civil.PointCloudRangeColorSchemeType"""
    def __init__(self, *args) -> None: ...
    ...

class PointCloudRegionType:
    """.NET: Autodesk.Civil.PointCloudRegionType"""
    def __init__(self, *args) -> None: ...
    ...

class PointCloudSurfaceType:
    """.NET: Autodesk.Civil.PointCloudSurfaceType"""
    def __init__(self, *args) -> None: ...
    ...

class PointCouldColorSchemeType:
    """.NET: Autodesk.Civil.PointCouldColorSchemeType"""
    def __init__(self, *args) -> None: ...
    ...

class PointFileFormatType:
    """.NET: Autodesk.Civil.PointFileFormatType"""
    def __init__(self, *args) -> None: ...
    ...

class PointNamesExistType:
    """.NET: Autodesk.Civil.PointNamesExistType"""
    def __init__(self, *args) -> None: ...
    ...

class PointNotOnEntityException(CivilException):
    """.NET: Autodesk.Civil.PointNotOnEntityException"""
    def __init__(self, *args) -> None: ...
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str

class PointNumbersAssignedType:
    """.NET: Autodesk.Civil.PointNumbersAssignedType"""
    def __init__(self, *args) -> None: ...
    ...

class PointNumbersExistType:
    """.NET: Autodesk.Civil.PointNumbersExistType"""
    def __init__(self, *args) -> None: ...
    ...

class PointNumbersSuppliedType:
    """.NET: Autodesk.Civil.PointNumbersSuppliedType"""
    def __init__(self, *args) -> None: ...
    ...

class PressureUnitType:
    """.NET: Autodesk.Civil.PressureUnitType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileApplyCurveType:
    """.NET: Autodesk.Civil.ProfileApplyCurveType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileCircularVerticalConstraintType:
    """.NET: Autodesk.Civil.ProfileCircularVerticalConstraintType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileCurveType:
    """.NET: Autodesk.Civil.ProfileCurveType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileDesignCheck(DesignCheck):
    """.NET: Autodesk.Civil.ProfileDesignCheck"""
    def __init__(self, *args) -> None: ...
    DesignCheckType: ProfileDesignCheckType
    Expression: str
    Description: str
    Name: str

class ProfileDesignCheckCollection(DesignCheckCollection<Autodesk::Civil::ProfileDesignCheck ^>):
    """.NET: Autodesk.Civil.ProfileDesignCheckCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: ProfileDesignCheck
    Item: ProfileDesignCheck
    def Add(self, name: str, description: str, expression: str) -> ProfileDesignCheck: ...
    def Clear(self, ) -> None: ...
    def Remove(self, name: str) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class ProfileDesignCheckRoot:
    """.NET: Autodesk.Civil.ProfileDesignCheckRoot"""
    def __init__(self, *args) -> None: ...
    CurveDesignChecks: ProfileDesignCheckCollection
    LineDesignChecks: ProfileDesignCheckCollection

class ProfileDesignCheckType:
    """.NET: Autodesk.Civil.ProfileDesignCheckType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileParabolicVerticalConstraintType:
    """.NET: Autodesk.Civil.ProfileParabolicVerticalConstraintType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfilePointType:
    """.NET: Autodesk.Civil.ProfilePointType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileViewDatumType:
    """.NET: Autodesk.Civil.ProfileViewDatumType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileViewPlotType:
    """.NET: Autodesk.Civil.ProfileViewPlotType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileViewSplitDatumType:
    """.NET: Autodesk.Civil.ProfileViewSplitDatumType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileViewSplitStationType:
    """.NET: Autodesk.Civil.ProfileViewSplitStationType"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileViewStartCornerType:
    """.NET: Autodesk.Civil.ProfileViewStartCornerType"""
    def __init__(self, *args) -> None: ...
    ...

class ProjecitonPercentageType:
    """.NET: Autodesk.Civil.ProjecitonPercentageType"""
    def __init__(self, *args) -> None: ...
    ...

class ProjecitonRule:
    """.NET: Autodesk.Civil.ProjecitonRule"""
    def __init__(self, *args) -> None: ...
    ...

class ProjectionUtil:
    """.NET: Autodesk.Civil.ProjectionUtil"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def IsProfileProjectionObject(projectionId: ObjectId, gsMarker: IntPtr) -> bool: ...
    @staticmethod
    def IsSectionProjectionObject(projectionId: ObjectId, gsMarker: IntPtr) -> bool: ...

class Property<Autodesk::AutoCAD::Colors::Color ^\,AcCmColor\,Autodesk::Civil::CastOp<Autodesk::AutoCAD::Colors::Color ^\,AcCmColor> >(TreeOidWrapper):
    """.NET: Autodesk.Civil.Property<Autodesk::AutoCAD::Colors::Color ^\,AcCmColor\,Autodesk::Civil::CastOp<Autodesk::AutoCAD::Colors::Color ^\,AcCmColor> >"""
    def __init__(self, *args) -> None: ...
    Value: Color
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Property<Autodesk::AutoCAD::DatabaseServices::ObjectIdCollection ^\,std::vector<AeccAttribute\,std::allocator<AeccAttribute> >\,Autodesk::Civil::CastOp<Autodesk::AutoCAD::DatabaseServices::ObjectIdCollection ^\,std::vector<AeccAttribute\,std::allocator<AeccAttribute> > > >(TreeOidWrapper):
    """.NET: Autodesk.Civil.Property<Autodesk::AutoCAD::DatabaseServices::ObjectIdCollection ^\,std::vector<AeccAttribute\,std::allocator<AeccAttribute> >\,Autodesk::Civil::CastOp<Autodesk::AutoCAD::DatabaseServices::ObjectIdCollection ^\,std::vector<AeccAttribute\,std::allocator<AeccAttribute> > > >"""
    def __init__(self, *args) -> None: ...
    Value: ObjectIdCollection
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Property<Autodesk::AutoCAD::DatabaseServices::ObjectId\,AcDbObjectId\,Autodesk::Civil::CastOp<Autodesk::AutoCAD::DatabaseServices::ObjectId\,AcDbObjectId> >(TreeOidWrapper):
    """.NET: Autodesk.Civil.Property<Autodesk::AutoCAD::DatabaseServices::ObjectId\,AcDbObjectId\,Autodesk::Civil::CastOp<Autodesk::AutoCAD::DatabaseServices::ObjectId\,AcDbObjectId> >"""
    def __init__(self, *args) -> None: ...
    Value: ObjectId
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Property<System::String ^\,AecRmCString\,Autodesk::Civil::CastOp<System::String ^\,AecRmCString> >(TreeOidWrapper):
    """.NET: Autodesk.Civil.Property<System::String ^\,AecRmCString\,Autodesk::Civil::CastOp<System::String ^\,AecRmCString> >"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Property<bool\,bool\,Autodesk::Civil::CastOp<bool\,bool> >(TreeOidWrapper):
    """.NET: Autodesk.Civil.Property<bool\,bool\,Autodesk::Civil::CastOp<bool\,bool> >"""
    def __init__(self, *args) -> None: ...
    Value: bool
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Property<double\,double\,Autodesk::Civil::CastOp<double\,double> >(TreeOidWrapper):
    """.NET: Autodesk.Civil.Property<double\,double\,Autodesk::Civil::CastOp<double\,double> >"""
    def __init__(self, *args) -> None: ...
    Value: float
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Property<int\,int\,Autodesk::Civil::CastOp<int\,int> >(TreeOidWrapper):
    """.NET: Autodesk.Civil.Property<int\,int\,Autodesk::Civil::CastOp<int\,int> >"""
    def __init__(self, *args) -> None: ...
    Value: int
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Property<unsigned int\,int\,Autodesk::Civil::CastOp<unsigned int\,int> >(TreeOidWrapper):
    """.NET: Autodesk.Civil.Property<unsigned int\,int\,Autodesk::Civil::CastOp<unsigned int\,int> >"""
    def __init__(self, *args) -> None: ...
    Value: int
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyAnchorPoint(Property<int\,int\,Autodesk::Civil::CastOp<int\,int> >):
    """.NET: Autodesk.Civil.PropertyAnchorPoint"""
    def __init__(self, *args) -> None: ...
    Value: AnchorPointType
    Value: int
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyAngle(PropertyDouble):
    """.NET: Autodesk.Civil.PropertyAngle"""
    def __init__(self, *args) -> None: ...
    Value: float
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyArrowhead(PropertyString):
    """.NET: Autodesk.Civil.PropertyArrowhead"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyBlock(PropertyString):
    """.NET: Autodesk.Civil.PropertyBlock"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyBoolean(Property<bool\,bool\,Autodesk::Civil::CastOp<bool\,bool> >):
    """.NET: Autodesk.Civil.PropertyBoolean"""
    def __init__(self, *args) -> None: ...
    Value: bool
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyColor(Property<Autodesk::AutoCAD::Colors::Color ^\,AcCmColor\,Autodesk::Civil::CastOp<Autodesk::AutoCAD::Colors::Color ^\,AcCmColor> >):
    """.NET: Autodesk.Civil.PropertyColor"""
    def __init__(self, *args) -> None: ...
    Value: Color
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyDouble(Property<double\,double\,Autodesk::Civil::CastOp<double\,double> >):
    """.NET: Autodesk.Civil.PropertyDouble"""
    def __init__(self, *args) -> None: ...
    Value: float
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyEnum(Property<int\,int\,Autodesk::Civil::CastOp<int\,int> >):
    """.NET: Autodesk.Civil.PropertyEnum`1"""
    def __init__(self, *args) -> None: ...
    Value: T
    Value: int
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyExpression(PropertyString):
    """.NET: Autodesk.Civil.PropertyExpression"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyFeatureLineStylePriority(Property<Autodesk::AutoCAD::DatabaseServices::ObjectIdCollection ^\,std::vector<AeccAttribute\,std::allocator<AeccAttribute> >\,Autodesk::Civil::CastOp<Autodesk::AutoCAD::DatabaseServices::ObjectIdCollection ^\,std::vector<AeccAttribute\,std::allocator<AeccAttribute> > > >):
    """.NET: Autodesk.Civil.PropertyFeatureLineStylePriority"""
    def __init__(self, *args) -> None: ...
    Value: ObjectIdCollection
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyInt(Property<int\,int\,Autodesk::Civil::CastOp<int\,int> >):
    """.NET: Autodesk.Civil.PropertyInt"""
    def __init__(self, *args) -> None: ...
    Value: int
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyLayer(PropertyString):
    """.NET: Autodesk.Civil.PropertyLayer"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyLinetype(PropertyString):
    """.NET: Autodesk.Civil.PropertyLinetype"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyMText(PropertyString):
    """.NET: Autodesk.Civil.PropertyMText"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyMaterial(PropertyString):
    """.NET: Autodesk.Civil.PropertyMaterial"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyNameTemplate(PropertyString):
    """.NET: Autodesk.Civil.PropertyNameTemplate"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyObjectId(Property<Autodesk::AutoCAD::DatabaseServices::ObjectId\,AcDbObjectId\,Autodesk::Civil::CastOp<Autodesk::AutoCAD::DatabaseServices::ObjectId\,AcDbObjectId> >):
    """.NET: Autodesk.Civil.PropertyObjectId"""
    def __init__(self, *args) -> None: ...
    Value: ObjectId
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyObjectName(PropertyString):
    """.NET: Autodesk.Civil.PropertyObjectName"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyString(Property<System::String ^\,AecRmCString\,Autodesk::Civil::CastOp<System::String ^\,AecRmCString> >):
    """.NET: Autodesk.Civil.PropertyString"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyTextStyle(PropertyString):
    """.NET: Autodesk.Civil.PropertyTextStyle"""
    def __init__(self, *args) -> None: ...
    Value: str
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PropertyUInt(Property<unsigned int\,int\,Autodesk::Civil::CastOp<unsigned int\,int> >):
    """.NET: Autodesk.Civil.PropertyUInt"""
    def __init__(self, *args) -> None: ...
    Value: int
    IsOverridable: bool
    Overridden: bool
    Locked: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class QuantityTakeoffLengthComputeType:
    """.NET: Autodesk.Civil.QuantityTakeoffLengthComputeType"""
    def __init__(self, *args) -> None: ...
    ...

class QuantityTakeoffPipeLengthType:
    """.NET: Autodesk.Civil.QuantityTakeoffPipeLengthType"""
    def __init__(self, *args) -> None: ...
    ...

class QuantityTakeoffReportExtentType:
    """.NET: Autodesk.Civil.QuantityTakeoffReportExtentType"""
    def __init__(self, *args) -> None: ...
    ...

class QuantityTakeoffReportType:
    """.NET: Autodesk.Civil.QuantityTakeoffReportType"""
    def __init__(self, *args) -> None: ...
    ...

class ROWCleanupType:
    """.NET: Autodesk.Civil.ROWCleanupType"""
    def __init__(self, *args) -> None: ...
    ...

class RadiusLookupMethodType:
    """.NET: Autodesk.Civil.RadiusLookupMethodType"""
    def __init__(self, *args) -> None: ...
    ...

class RailAlignmentPivotType:
    """.NET: Autodesk.Civil.RailAlignmentPivotType"""
    def __init__(self, *args) -> None: ...
    ...

class RoadwaySideType:
    """.NET: Autodesk.Civil.RoadwaySideType"""
    def __init__(self, *args) -> None: ...
    ...

class RotationDirType:
    """.NET: Autodesk.Civil.RotationDirType"""
    def __init__(self, *args) -> None: ...
    ...

class RoundingType:
    """.NET: Autodesk.Civil.RoundingType"""
    def __init__(self, *args) -> None: ...
    ...

class SectionViewElevationRangeType:
    """.NET: Autodesk.Civil.SectionViewElevationRangeType"""
    def __init__(self, *args) -> None: ...
    ...

class SheetCreateType:
    """.NET: Autodesk.Civil.SheetCreateType"""
    def __init__(self, *args) -> None: ...
    ...

class SheetSetType:
    """.NET: Autodesk.Civil.SheetSetType"""
    def __init__(self, *args) -> None: ...
    ...

class ShoulderMethodType:
    """.NET: Autodesk.Civil.ShoulderMethodType"""
    def __init__(self, *args) -> None: ...
    ...

class SignType:
    """.NET: Autodesk.Civil.SignType"""
    def __init__(self, *args) -> None: ...
    ...

class SlopeFormatType:
    """.NET: Autodesk.Civil.SlopeFormatType"""
    def __init__(self, *args) -> None: ...
    ...

class SlopePatternLengthType:
    """.NET: Autodesk.Civil.SlopePatternLengthType"""
    def __init__(self, *args) -> None: ...
    ...

class SlopePatternOffsetType:
    """.NET: Autodesk.Civil.SlopePatternOffsetType"""
    def __init__(self, *args) -> None: ...
    ...

class SlopePatternStartType:
    """.NET: Autodesk.Civil.SlopePatternStartType"""
    def __init__(self, *args) -> None: ...
    ...

class SlopePatternSymbolType:
    """.NET: Autodesk.Civil.SlopePatternSymbolType"""
    def __init__(self, *args) -> None: ...
    ...

class SpeedUnitType:
    """.NET: Autodesk.Civil.SpeedUnitType"""
    def __init__(self, *args) -> None: ...
    ...

class SpiralType:
    """.NET: Autodesk.Civil.SpiralType"""
    def __init__(self, *args) -> None: ...
    ...

class StationDelimiterCharacterType:
    """.NET: Autodesk.Civil.StationDelimiterCharacterType"""
    def __init__(self, *args) -> None: ...
    ...

class StationDelimiterPositionType:
    """.NET: Autodesk.Civil.StationDelimiterPositionType"""
    def __init__(self, *args) -> None: ...
    ...

class StationFormatType:
    """.NET: Autodesk.Civil.StationFormatType"""
    def __init__(self, *args) -> None: ...
    ...

class StructureColumnComponentType:
    """.NET: Autodesk.Civil.StructureColumnComponentType"""
    def __init__(self, *args) -> None: ...
    ...

class StructureProfileLabelPlacementType:
    """.NET: Autodesk.Civil.StructureProfileLabelPlacementType"""
    def __init__(self, *args) -> None: ...
    ...

class StyleConflictResolverType:
    """.NET: Autodesk.Civil.StyleConflictResolverType"""
    def __init__(self, *args) -> None: ...
    ...

class SubassemblyNameType:
    """.NET: Autodesk.Civil.SubassemblyNameType"""
    def __init__(self, *args) -> None: ...
    ...

class SuperElevationViewDisplayStyleType:
    """.NET: Autodesk.Civil.SuperElevationViewDisplayStyleType"""
    def __init__(self, *args) -> None: ...
    ...

class SuperelevationAttainmentRegionType:
    """.NET: Autodesk.Civil.SuperelevationAttainmentRegionType"""
    def __init__(self, *args) -> None: ...
    ...

class SuperelevationCorridorType:
    """.NET: Autodesk.Civil.SuperelevationCorridorType"""
    def __init__(self, *args) -> None: ...
    ...

class SuperelevationCriticalStationType:
    """.NET: Autodesk.Civil.SuperelevationCriticalStationType"""
    def __init__(self, *args) -> None: ...
    ...

class SuperelevationCrossSegmentType:
    """.NET: Autodesk.Civil.SuperelevationCrossSegmentType"""
    def __init__(self, *args) -> None: ...
    ...

class SuperelevationPointType:
    """.NET: Autodesk.Civil.SuperelevationPointType"""
    def __init__(self, *args) -> None: ...
    ...

class SuperelevationStationRoundingType:
    """.NET: Autodesk.Civil.SuperelevationStationRoundingType"""
    def __init__(self, *args) -> None: ...
    ...

class SuperelevationTransitionRegionType:
    """.NET: Autodesk.Civil.SuperelevationTransitionRegionType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceBoundaryType:
    """.NET: Autodesk.Civil.SurfaceBoundaryType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceBreaklineType:
    """.NET: Autodesk.Civil.SurfaceBreaklineType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceDrawObjectType:
    """.NET: Autodesk.Civil.SurfaceDrawObjectType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceException(CivilException):
    """.NET: Autodesk.Civil.SurfaceException"""
    def __init__(self, *args) -> None: ...
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str

class SurfaceExtractionSettingsType:
    """.NET: Autodesk.Civil.SurfaceExtractionSettingsType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceOpeartionStatusType:
    """.NET: Autodesk.Civil.SurfaceOpeartionStatusType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfacePointOutputLocationsType:
    """.NET: Autodesk.Civil.SurfacePointOutputLocationsType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfacePointSelectionType:
    """.NET: Autodesk.Civil.SurfacePointSelectionType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceRegionOptionsType:
    """.NET: Autodesk.Civil.SurfaceRegionOptionsType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceSimplifyType:
    """.NET: Autodesk.Civil.SurfaceSimplifyType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceSmoothType:
    """.NET: Autodesk.Civil.SurfaceSmoothType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceStatus:
    """.NET: Autodesk.Civil.SurfaceStatus"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceStatusText:
    """.NET: Autodesk.Civil.SurfaceStatusText"""
    def __init__(self, *args) -> None: ...
    Text: str

class SurfaceSurveyQueryType:
    """.NET: Autodesk.Civil.SurfaceSurveyQueryType"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceType:
    """.NET: Autodesk.Civil.SurfaceType"""
    def __init__(self, *args) -> None: ...
    ...

class SurveyException(CivilException):
    """.NET: Autodesk.Civil.SurveyException"""
    def __init__(self, *args) -> None: ...
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str

class SurveyProject(DisposableWrapper):
    """.NET: Autodesk.Civil.SurveyProject"""
    def __init__(self, *args) -> None: ...
    ProjectGUID: Guid
    ProjectName: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Close(self, ) -> None: ...
    def GetSurveyQueryCollection(self, ) -> SurveyQueryCollection: ...
    def IsOpen(self, ) -> bool: ...
    def Open(self, openMode: bool) -> None: ...

class SurveyProjectCollection(DisposableWrapper):
    """.NET: Autodesk.Civil.SurveyProjectCollection"""
    def __init__(self, *args) -> None: ...
    Item: SurveyProject
    Count: int
    WorkingFolder: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def GetCurrentProject(self, ) -> SurveyProject: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetItem(self, surveyProjectPath: str) -> SurveyProject: ...
    def GetObjectEnumerator(self, ) -> IEnumerator: ...

class SurveyQuery(DisposableWrapper):
    """.NET: Autodesk.Civil.SurveyQuery"""
    def __init__(self, *args) -> None: ...
    Description: str
    GUID: Guid
    Name: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class SurveyQueryCollection(DisposableWrapper):
    """.NET: Autodesk.Civil.SurveyQueryCollection"""
    def __init__(self, *args) -> None: ...
    Item: SurveyQuery
    Count: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetItem(self, queryName: str) -> ArrayList: ...
    def GetObjectEnumerator(self, ) -> IEnumerator: ...

class SurveyStatus:
    """.NET: Autodesk.Civil.SurveyStatus"""
    def __init__(self, *args) -> None: ...
    ...

class SurveyStatusText:
    """.NET: Autodesk.Civil.SurveyStatusText"""
    def __init__(self, *args) -> None: ...
    Text: str

class SweptCurveLocation:
    """.NET: Autodesk.Civil.SweptCurveLocation"""
    def __init__(self, *args) -> None: ...
    ...

class TableSegmentDataType:
    """.NET: Autodesk.Civil.TableSegmentDataType"""
    def __init__(self, *args) -> None: ...
    ...

class TableTitleDirectionType:
    """.NET: Autodesk.Civil.TableTitleDirectionType"""
    def __init__(self, *args) -> None: ...
    ...

class TaperInputType:
    """.NET: Autodesk.Civil.TaperInputType"""
    def __init__(self, *args) -> None: ...
    ...

class TextBorderType:
    """.NET: Autodesk.Civil.TextBorderType"""
    def __init__(self, *args) -> None: ...
    ...

class TextJustificationType:
    """.NET: Autodesk.Civil.TextJustificationType"""
    def __init__(self, *args) -> None: ...
    ...

class TimeUnitType:
    """.NET: Autodesk.Civil.TimeUnitType"""
    def __init__(self, *args) -> None: ...
    ...

class TransitionInputType:
    """.NET: Autodesk.Civil.TransitionInputType"""
    def __init__(self, *args) -> None: ...
    ...

class TransitionType:
    """.NET: Autodesk.Civil.TransitionType"""
    def __init__(self, *args) -> None: ...
    ...

class TreeOidWrapper(DisposableWrapper):
    """.NET: Autodesk.Civil.TreeOidWrapper"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Utility:
    """.NET: Autodesk.Civil.Utility"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def PolarPoint(refPoint: list, angle: float, distance: float) -> list: ...

class VectorMeasurementType:
    """.NET: Autodesk.Civil.VectorMeasurementType"""
    def __init__(self, *args) -> None: ...
    ...

class ViewFrameAngleType:
    """.NET: Autodesk.Civil.ViewFrameAngleType"""
    def __init__(self, *args) -> None: ...
    ...

class ViewFrameLabelLocationType:
    """.NET: Autodesk.Civil.ViewFrameLabelLocationType"""
    def __init__(self, *args) -> None: ...
    ...

class VolumeSurfaceType:
    """.NET: Autodesk.Civil.VolumeSurfaceType"""
    def __init__(self, *args) -> None: ...
    ...

class VolumeUnitType:
    """.NET: Autodesk.Civil.VolumeUnitType"""
    def __init__(self, *args) -> None: ...
    ...

class WaterdropObjectType:
    """.NET: Autodesk.Civil.WaterdropObjectType"""
    def __init__(self, *args) -> None: ...
    ...

class WatershedType:
    """.NET: Autodesk.Civil.WatershedType"""
    def __init__(self, *args) -> None: ...
    ...

class WideningByMethod:
    """.NET: Autodesk.Civil.WideningByMethod"""
    def __init__(self, *args) -> None: ...
    ...

class WideningSide:
    """.NET: Autodesk.Civil.WideningSide"""
    def __init__(self, *args) -> None: ...
    ...
