# Auto-generated — Civil 26 — Autodesk.Civil.ApplicationServices

class CivilApplication:
    """.NET: Autodesk.Civil.ApplicationServices.CivilApplication"""
    def __init__(self, *args) -> None: ...
    SurveyProjects: SurveyProjectCollection
    ActiveProduct: ProductType
    ActiveDocument: CivilDocument

class CivilDocument(DisposableWrapper):
    """.NET: Autodesk.Civil.ApplicationServices.CivilDocument"""
    def __init__(self, *args) -> None: ...
    IsDriveActive: bool
    IsSectionEditorCorridorReferenceObject: bool
    IsCorridorSectionViewActive: bool
    SubassemblyCollection: SubassemblyCollection
    AssemblyCollection: AssemblyCollection
    CorridorCollection: CorridorCollection
    CorridorState: CorridorState
    NetworkState: PipeNetworkState
    ParcelUDPs: UDPCollection
    ParcelUDPClassifications: UDPClassificationCollection
    PointUDPs: UDPCollection
    PointUDPClassifications: UDPClassificationCollection
    PointGroups: PointGroupCollection
    CogoPoints: CogoPointCollection
    Styles: StylesRoot
    Settings: SettingsRoot
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def GetAlignmentIds(self, ) -> ObjectIdCollection: ...
    def GetAlignmentTableIds(self, ) -> ObjectIdCollection: ...
    def GetAllPointIds(self, ) -> ObjectIdCollection: ...
    def GetBridgeIds(self, ) -> ObjectIdCollection: ...
    def GetCatchmentGroups(self, ) -> CatchmentGroupCollection: ...
    @staticmethod
    def GetCivilDocument(database: Database) -> CivilDocument: ...
    def GetGeneralSegmentLabelIds(self, ) -> ObjectIdCollection: ...
    def GetIntersectionIds(self, ) -> ObjectIdCollection: ...
    def GetLegendTableIds(self, ) -> ObjectIdCollection: ...
    def GetNoteLabelIds(self, ) -> ObjectIdCollection: ...
    def GetParcelSegmentTableIds(self, ) -> ObjectIdCollection: ...
    def GetParcelTableIds(self, ) -> ObjectIdCollection: ...
    def GetPipeNetworkIds(self, ) -> ObjectIdCollection: ...
    def GetPointTableIds(self, ) -> ObjectIdCollection: ...
    def GetSiteIds(self, ) -> ObjectIdCollection: ...
    def GetSitelessAlignmentId(self, name: str) -> ObjectId: ...
    def GetSitelessAlignmentIds(self, ) -> ObjectIdCollection: ...
    def GetSitelessFeatureLineIds(self, ) -> ObjectIdCollection: ...
    def GetSurfaceIds(self, ) -> ObjectIdCollection: ...
    def GetViewFrameGroupIds(self, ) -> ObjectIdCollection: ...

class ProductType:
    """.NET: Autodesk.Civil.ApplicationServices.ProductType"""
    def __init__(self, *args) -> None: ...
    ...
