# Auto-generated — Civil 26 — Autodesk.AutoCAD.ApplicationServices

class Application(Application):
    """.NET: Autodesk.AutoCAD.ApplicationServices.Application"""
    def __init__(self, *args) -> None: ...
    UIBindings: DataBindings
    InfoCenter: InfoCenter
    MenuGroups: object
    MenuBar: object
    Preferences: object
    IsInCustomizationMode: bool
    DisplayTextScreen: bool
    StatusBar: StatusBar
    NonInPlaceMainWindow: Window
    DocumentWindowCollection: DocumentWindowCollection
    AcadApplication: object
    @staticmethod
    def AddDefaultContextMenuExtension(menuExtension: ContextMenuExtension) -> None: ...
    @staticmethod
    def AddObjectContextMenuExtension(runtimeClass: RXClass, menuExtension: ContextMenuExtension) -> None: ...
    @staticmethod
    def CommitModalWindow(commitValue: bool) -> None: ...
    @staticmethod
    def DoDragDrop(dragSource: DependencyObject, data: object, allowedEffects: DragDropEffects, target: DropTarget) -> None: ...
    @staticmethod
    def InvokeContextHelp(window: IntPtr, contextId: int, helpPrefix: str, hlpevent: HelpEventArgs) -> None: ...
    @staticmethod
    def InvokeHelp(fileName: str, topic: str) -> None: ...
    @staticmethod
    def InvokeHelpForExternal(functionName: str) -> bool: ...
    @staticmethod
    def IsConnectEnabled() -> bool: ...
    @staticmethod
    def LoadMainMenu(filename: str) -> bool: ...
    @staticmethod
    def LoadPartialMenu(filename: str) -> bool: ...
    @staticmethod
    def PostSearchQuery(searchString: str) -> None: ...
    @staticmethod
    def ReloadAllMenus() -> None: ...
    @staticmethod
    def RemoveDefaultContextMenuExtension(menuExtension: ContextMenuExtension) -> None: ...
    @staticmethod
    def RemoveObjectContextMenuExtension(runtimeClass: RXClass, menuExtension: ContextMenuExtension) -> None: ...
    @staticmethod
    def SetCurrentWorkspace(workspacename: str) -> bool: ...
    @staticmethod
    def ShowModalDialog(owner: IntPtr, formToShow: Form, persistSizeAndPosition: bool) -> DialogResult: ...
    @staticmethod
    def ShowModalWindow(owner: IntPtr, htmlPage: Uri, persistSizeAndPosition: bool) -> bool: ...
    @staticmethod
    def ShowModelessDialog(owner: IntPtr, formToShow: Form, persistSizeAndPosition: bool) -> None: ...
    @staticmethod
    def ShowModelessWindow(owner: IntPtr, htmlPage: Uri, persistSizeAndPosition: bool) -> None: ...
    @staticmethod
    def ToSystemDrawingPoint(point: Point) -> Point: ...
    @staticmethod
    def ToSystemDrawingSize(point: Size) -> Size: ...
    @staticmethod
    def ToSystemWindowsPoint(point: Point) -> Point: ...
    @staticmethod
    def ToSystemWindowsSize(point: Size) -> Size: ...
    @staticmethod
    def UnloadPartialMenu(filename: str) -> bool: ...

class BeginCloseAllEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.BeginCloseAllEventArgs"""
    def __init__(self, *args) -> None: ...
    IsVetoed: bool

class BeginCloseAllEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.BeginCloseAllEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: BeginCloseAllEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: BeginCloseAllEventArgs) -> None: ...

class BeginDoubleClickEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.BeginDoubleClickEventArgs"""
    def __init__(self, *args) -> None: ...
    Location: Point3d

class BeginDoubleClickEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.BeginDoubleClickEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: BeginDoubleClickEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: BeginDoubleClickEventArgs) -> None: ...

class BeginExtractionEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.BeginExtractionEventArgs"""
    def __init__(self, *args) -> None: ...
    def QueueForExtraction(self, idObject: ObjectId, viewableId: str) -> None: ...

class BeginExtractionEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.BeginExtractionEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: BeginExtractionEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: BeginExtractionEventArgs) -> None: ...

class BeginQuitEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.BeginQuitEventArgs"""
    def __init__(self, *args) -> None: ...
    IsVetoed: bool

class BeginQuitEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.BeginQuitEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: BeginQuitEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: BeginQuitEventArgs) -> None: ...

class CheckingOutEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.CheckingOutEventArgs"""
    def __init__(self, *args) -> None: ...
    CheckOutSet: ObjectIdCollection
    Transaction: LongTransaction
    def Veto(self, ) -> None: ...

class CheckingOutEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.CheckingOutEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: CheckingOutEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: CheckingOutEventArgs) -> None: ...

class CommandEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.CommandEventArgs"""
    def __init__(self, *args) -> None: ...
    GlobalCommandName: str

class CommandEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.CommandEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: CommandEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: CommandEventArgs) -> None: ...

class ConfigurationSectionNameAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.ApplicationServices.ConfigurationSectionNameAttribute"""
    def __init__(self, *args) -> None: ...
    Name: str
    TypeId: object

class DatabaseExtension:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DatabaseExtension"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Audit(db: Database, bFixErrors: bool, bCmdLnEcho: bool) -> None: ...

class Document(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.ApplicationServices.Document"""
    def __init__(self, *args) -> None: ...
    Name: str
    CommandInProgress: str
    Window: Window
    Editor: Editor
    IsNamedDrawing: bool
    IsActive: bool
    IsReadOnly: bool
    GraphicsManager: Manager
    UserData: Hashtable
    TransactionManager: TransactionManager
    Database: Database
    FormatForSave: DocumentSaveFormat
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr) -> Document: ...
    def DowngradeDocOpen(self, bPromptForSave: bool) -> None: ...
    def GetLispSymbol(self, name: str) -> object: ...
    def LockDocument(self, lockMode: DocumentLockMode, globalCommandName: str, localCommandName: str, promptIfFails: bool) -> DocumentLock: ...
    def LockMode(self, bIncludeMyLocks: bool) -> DocumentLockMode: ...
    def PopDbmod(self, ) -> None: ...
    def PushDbmod(self, ) -> None: ...
    def SendStringToExecute(self, command: str, activate: bool, wrapUpInactiveDoc: bool, echoCommand: bool) -> None: ...
    def SetLispSymbol(self, name: str, value: object) -> None: ...
    def TryGetDatabase(self, ) -> Database: ...
    def UpgradeDocOpen(self, ) -> None: ...

class DocumentActivationChangedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentActivationChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    NewValue: bool

class DocumentActivationChangedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentActivationChangedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentActivationChangedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentActivationChangedEventArgs) -> None: ...

class DocumentBeginCloseEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentBeginCloseEventArgs"""
    def __init__(self, *args) -> None: ...
    def Veto(self, ) -> None: ...

class DocumentBeginCloseEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentBeginCloseEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentBeginCloseEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentBeginCloseEventArgs) -> None: ...

class DocumentClosedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentClosedEventArgs"""
    def __init__(self, *args) -> None: ...
    RecentDocument: RecentDocument

class DocumentClosedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentClosedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentClosedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentClosedEventArgs) -> None: ...

class DocumentCollection(MarshalByRefObject):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentCollection"""
    def __init__(self, *args) -> None: ...
    DefaultFormatForSave: DocumentSaveFormat
    IsApplicationContext: bool
    DocumentActivationEnabled: bool
    CurrentDocument: Document
    MdiActiveDocument: Document
    Count: int
    def AppContextNewDocument(self, templateFileName: str) -> None: ...
    def AppContextOpenDocument(self, fileName: str) -> None: ...
    def AppContextRecoverDocument(self, fileName: str) -> None: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def ExecuteInApplicationContext(self, callback: ExecuteInApplicationContextCallback, data: object) -> None: ...
    def ExecuteInCommandContextAsync(self, callback: Func, data: object) -> ExecutionResult: ...
    def GetDocument(self, db: Database) -> Document: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetPendingDocumentForSwitch(self, ) -> Tuple: ...

class DocumentCollectionEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentCollectionEventArgs"""
    def __init__(self, *args) -> None: ...
    Document: Document

class DocumentCollectionEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentCollectionEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentCollectionEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentCollectionEventArgs) -> None: ...

class DocumentCollectionExtension:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentCollectionExtension"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Add(docCol: DocumentCollection, templateFileName: str) -> Document: ...
    @staticmethod
    def CloseAll(docCol: DocumentCollection) -> None: ...
    @staticmethod
    def Open(docCol: DocumentCollection, fileName: str, forReadOnly: bool, password: str) -> Document: ...

class DocumentDestroyedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentDestroyedEventArgs"""
    def __init__(self, *args) -> None: ...
    FileName: str

class DocumentDestroyedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentDestroyedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentDestroyedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentDestroyedEventArgs) -> None: ...

class DocumentExtension:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentExtension"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CapturePreviewImage(doc: Document, width: int, height: int) -> Bitmap: ...
    @staticmethod
    def CloseAndDiscard(doc: Document) -> None: ...
    @staticmethod
    def CloseAndSave(doc: Document, fileName: str) -> None: ...
    @staticmethod
    def FromAcadDocument(acadDocument: object) -> Document: ...
    @staticmethod
    def GetAcadDocument(doc: Document) -> object: ...
    @staticmethod
    def GetDocumentWindow(document: Document) -> DocumentWindow: ...
    @staticmethod
    def GetStatusBar(doc: Document) -> StatusBar: ...

class DocumentLock:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentLock"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class DocumentLockMode:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentLockMode"""
    def __init__(self, *args) -> None: ...
    ...

class DocumentLockModeChangeVetoedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentLockModeChangeVetoedEventArgs"""
    def __init__(self, *args) -> None: ...
    GlobalCommandName: str
    Document: Document

class DocumentLockModeChangeVetoedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentLockModeChangeVetoedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentLockModeChangeVetoedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentLockModeChangeVetoedEventArgs) -> None: ...

class DocumentLockModeChangedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentLockModeChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    GlobalCommandName: str
    CurrentMode: DocumentLockMode
    MyCurrentMode: DocumentLockMode
    MyPreviousMode: DocumentLockMode
    Document: Document
    def Veto(self, ) -> None: ...

class DocumentLockModeChangedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentLockModeChangedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentLockModeChangedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentLockModeChangedEventArgs) -> None: ...

class DocumentLockModeWillChangeEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentLockModeWillChangeEventArgs"""
    def __init__(self, *args) -> None: ...
    GlobalCommandName: str
    CurrentMode: DocumentLockMode
    MyCurrentMode: DocumentLockMode
    MyNewMode: DocumentLockMode
    Document: Document

class DocumentLockModeWillChangeEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentLockModeWillChangeEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentLockModeWillChangeEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentLockModeWillChangeEventArgs) -> None: ...

class DocumentPinStateChangedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentPinStateChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    RecentDocument: RecentDocument

class DocumentPinStateChangedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentPinStateChangedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentPinStateChangedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentPinStateChangedEventArgs) -> None: ...

class DocumentSaveFormat:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentSaveFormat"""
    def __init__(self, *args) -> None: ...
    ...

class DocumentWindowActivatedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentWindowActivatedEventArgs"""
    def __init__(self, *args) -> None: ...
    DocumentWindow: DocumentWindow

class DocumentWindowActivatedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentWindowActivatedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentWindowActivatedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentWindowActivatedEventArgs) -> None: ...

class DocumentWindowCollection:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentWindowCollection"""
    def __init__(self, *args) -> None: ...
    IsSynchronized: bool
    SyncRoot: object
    ActiveDocumentWindow: DocumentWindow
    Count: int
    def AddDocumentWindow(self, title: str, htmlPage: Uri) -> DocumentWindow: ...
    def ArrangeIcons(self, ) -> None: ...
    def Cascade(self, ) -> None: ...
    def CopyTo(self, array: Array, index: int) -> None: ...
    def Dispose(self, ) -> None: ...
    def FindDocumentWindowByHandle(self, handle: IntPtr) -> DocumentWindow: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def MoveDocumentWindow(self, documentWindow: DocumentWindow, newIndex: int) -> bool: ...
    def TileHorizontally(self, ) -> None: ...
    def TileVertically(self, ) -> None: ...

class DocumentWindowDockedEventArgs(DocumentWindowFloatedOrDockedEventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentWindowDockedEventArgs"""
    def __init__(self, *args) -> None: ...
    DocumentWindow: DocumentWindow

class DocumentWindowDockedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentWindowDockedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentWindowDockedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentWindowDockedEventArgs) -> None: ...

class DocumentWindowFloatedEventArgs(DocumentWindowFloatedOrDockedEventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentWindowFloatedEventArgs"""
    def __init__(self, *args) -> None: ...
    DocumentWindow: DocumentWindow

class DocumentWindowFloatedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentWindowFloatedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentWindowFloatedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentWindowFloatedEventArgs) -> None: ...

class DocumentWindowFloatedOrDockedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentWindowFloatedOrDockedEventArgs"""
    def __init__(self, *args) -> None: ...
    DocumentWindow: DocumentWindow

class DocumentWindowToBeDockedEventArgs(DocumentWindowFloatedOrDockedEventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentWindowToBeDockedEventArgs"""
    def __init__(self, *args) -> None: ...
    DocumentWindow: DocumentWindow

class DocumentWindowToBeDockedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DocumentWindowToBeDockedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DocumentWindowToBeDockedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DocumentWindowToBeDockedEventArgs) -> None: ...

class DrawingOpenEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.DrawingOpenEventArgs"""
    def __init__(self, *args) -> None: ...
    Database: Database
    FileName: str

class DrawingOpenEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.DrawingOpenEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DrawingOpenEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DrawingOpenEventArgs) -> None: ...

class EndExtractionEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.EndExtractionEventArgs"""
    def __init__(self, *args) -> None: ...
    def AddProperty(self, idObject: ObjectId, propertyCategory: str, propertyName: str, propertyValue: object, units: str, hidden: bool) -> None: ...

class EndExtractionEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.EndExtractionEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EndExtractionEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EndExtractionEventArgs) -> None: ...

class ExecuteInApplicationContextCallback:
    """.NET: Autodesk.AutoCAD.ApplicationServices.ExecuteInApplicationContextCallback"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, userData: object, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, userData: object) -> None: ...

class IConfigurationSection:
    """.NET: Autodesk.AutoCAD.ApplicationServices.IConfigurationSection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    def Close(self, ) -> None: ...
    def Contains(self, name: str) -> bool: ...
    def ContainsSubsection(self, name: str) -> bool: ...
    def CreateSubsection(self, name: str) -> IConfigurationSection: ...
    def Delete(self, name: str) -> None: ...
    def DeleteSubsection(self, name: str) -> None: ...
    def OpenSubsection(self, name: str) -> IConfigurationSection: ...
    def ReadProperty(self, name: str, defaultValue: object) -> object: ...
    def WriteProperty(self, name: str, value: object) -> None: ...

class InplaceTextEditor(TextEditor):
    """.NET: Autodesk.AutoCAD.ApplicationServices.InplaceTextEditor"""
    def __init__(self, *args) -> None: ...
    CanPaste: bool
    CanCopy: bool
    CanCut: bool
    UndoRecordingDisabled: bool
    Wysiwyg: bool
    alginment: AlignmentType
    LayerColor: Color
    CanExitEditor: bool
    ToolbarOptionHidden: bool
    ToolbarHidden: bool
    ForcedOpaqueBackground: bool
    OpaqueBackground: bool
    RulerHidden: bool
    RulerSupported: bool
    SpellerEnabled: bool
    ParagraphSupported: bool
    MultiAttribute: bool
    Text: bool
    SimpleMText: bool
    TableCell: bool
    Annotative: bool
    CanRedo: bool
    CanUndo: bool
    Current: InplaceTextEditor
    EndOfText: TextEditorLocation
    StartOfText: TextEditorLocation
    DefaultStackAlignment: FlowAlign
    DefaultStackScale: float
    StackCount: int
    VerticalTTF: bool
    VerticalSHX: bool
    FontCount: int
    TabOnlyDelimiter: bool
    AutoListEnabled: bool
    NumberingEnabled: bool
    AutoCAPS: bool
    ActualHeight: float
    ActualWidth: float
    TextHeight: float
    DefinedHeight: float
    DefinedWidth: float
    Attachment: AttachmentPoint
    StyleCount: int
    IsAnnotativeStyle: bool
    Style: ObjectId
    Paragraphs: list
    Wipeout: TextEditorWipeout
    Cursor: TextEditorCursor
    Selection: TextEditorSelection
    Columns: TextEditorColumns
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def AddUndoMarker(self, undoType: TextUndoType) -> None: ...
    def AttachmentMenus(self, pos: Point, parent: Window) -> None: ...
    def ColumnMenus(self, pos: Point, parent: Window) -> None: ...
    def ColumnsDialog(self, staticColumnCount: int) -> None: ...
    def ContextMenus(self, pos: Point, parent: Window) -> None: ...
    def Copy(self, ) -> None: ...
    def Cut(self, ) -> None: ...
    def DrawHightlight(self, ) -> None: ...
    def FieldDialog(self, field: Field) -> None: ...
    def FindAndReplaceDialog(self, ) -> None: ...
    def FindMatchItem(self, flags: int, findStr: str) -> None: ...
    def HelpDialog(self, ) -> None: ...
    def HightlightColorDialog(self, ) -> None: ...
    def ImportTextDialog(self, ) -> None: ...
    def InsertFile(self, filename: str) -> None: ...
    @staticmethod
    def Invoke(text: DBText, appendedEntities: list) -> None: ...
    def LineSpaceMenus(self, pos: Point, parent: Window) -> None: ...
    def NewFeatureWorkShop(self, ) -> None: ...
    def NumberingMenus(self, pos: Point, parent: Window) -> None: ...
    def OtherSymbol(self, ) -> None: ...
    def ParagraphDialog(self, ) -> None: ...
    def Paste(self, ) -> None: ...
    def PasteWithoutFormats(self, ) -> None: ...
    def Redo(self, ) -> None: ...
    def RemoveHightlight(self, ) -> None: ...
    def ReplaceAllMatches(self, flags: int, findStr: str, replaceStr: str) -> None: ...
    def ReplaceCurrentMatch(self, flags: int, findStr: str, replaceStr: str) -> None: ...
    def SetStaticColumnsWithCount(self, columnCount: int) -> None: ...
    def SpellDictionaryDialog(self, ) -> None: ...
    def SpellSettingDialog(self, ) -> None: ...
    def StackPropertyDialog(self, ) -> None: ...
    def SymbolMenus(self, pos: Point, parent: Window) -> None: ...
    def Undo(self, ) -> None: ...
    def WipeoutDialog(self, ) -> None: ...

class InplaceTextEditorSettings(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.ApplicationServices.InplaceTextEditorSettings"""
    def __init__(self, *args) -> None: ...
    DefinedHeight: float
    SimpleMText: bool
    TabSupported: bool
    Type: EntityType
    Flags: EditFlags
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class LayoutSwitchedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.LayoutSwitchedEventArgs"""
    def __init__(self, *args) -> None: ...
    NewLayout: str

class LayoutSwitchedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.LayoutSwitchedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: LayoutSwitchedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: LayoutSwitchedEventArgs) -> None: ...

class LayoutSwitchingEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.LayoutSwitchingEventArgs"""
    def __init__(self, *args) -> None: ...
    NewLayout: str
    OldLayout: str

class LayoutSwitchingEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.LayoutSwitchingEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: LayoutSwitchingEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: LayoutSwitchingEventArgs) -> None: ...

class LispWillStartEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.LispWillStartEventArgs"""
    def __init__(self, *args) -> None: ...
    FirstLine: str

class LispWillStartEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.LispWillStartEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: LispWillStartEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: LispWillStartEventArgs) -> None: ...

class LongTransactionEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.LongTransactionEventArgs"""
    def __init__(self, *args) -> None: ...
    Transaction: LongTransaction

class LongTransactionEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.LongTransactionEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: LongTransactionEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: LongTransactionEventArgs) -> None: ...

class LongTransactionManager(RXObject):
    """.NET: Autodesk.AutoCAD.ApplicationServices.LongTransactionManager"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def AbortLongTransaction(self, transId: ObjectId, keepObjs: bool) -> None: ...
    def AddClassFilter(self, filter: RXClass) -> None: ...
    def CheckIn(self, transId: ObjectId, errorMap: IdMapping, keepObjs: bool) -> None: ...
    def CheckOut(self, checkoutSet: ObjectIdCollection, toBlock: ObjectId, errorMap: IdMapping, blkRef: ObjectId) -> ObjectId: ...
    def CurrentLongTransactionFor(self, doc: Document) -> ObjectId: ...
    def IsFiltered(self, A_0: RXClass) -> bool: ...

class Marshaler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.Marshaler"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AdsNameToSelectionSet(pointerToAdsName: IntPtr) -> SelectionSet: ...
    @staticmethod
    def SelectionSetToAdsName(selectionSet: SelectionSet, pointerToAdsName: IntPtr) -> None: ...

class ModelessOperationEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.ModelessOperationEventArgs"""
    def __init__(self, *args) -> None: ...
    Context: str

class ModelessOperationEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.ModelessOperationEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: ModelessOperationEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: ModelessOperationEventArgs) -> None: ...

class PreTranslateMessageEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.PreTranslateMessageEventArgs"""
    def __init__(self, *args) -> None: ...
    Handled: bool
    Message: MSG

class PreTranslateMessageEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.PreTranslateMessageEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PreTranslateMessageEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PreTranslateMessageEventArgs) -> None: ...

class ProfileEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.ProfileEventArgs"""
    def __init__(self, *args) -> None: ...
    ProfileName: str

class ProfileEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.ProfileEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: ProfileEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: ProfileEventArgs) -> None: ...

class RecentDocument:
    """.NET: Autodesk.AutoCAD.ApplicationServices.RecentDocument"""
    def __init__(self, *args) -> None: ...
    IsClosed: bool
    IsPinned: bool
    Preview: BitmapSource
    CurrentlyOpenBy: str
    LastOpenedTime: ValueType
    LastSavedBy: str
    Version: str
    Path: str
    @staticmethod
    def FromPath(path: str) -> RecentDocument: ...

class RecentDocumentCollection(ReadOnlyObservableCollection):
    """.NET: Autodesk.AutoCAD.ApplicationServices.RecentDocumentCollection"""
    def __init__(self, *args) -> None: ...
    UsePinnedItems: bool
    Instance: RecentDocumentCollection
    Count: int
    Item: RecentDocument
    def Dispose(self, ) -> None: ...
    @staticmethod
    def Remove(path: str) -> None: ...

class SystemVariableChangedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.SystemVariableChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    Changed: bool
    Name: str

class SystemVariableChangedEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.SystemVariableChangedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: SystemVariableChangedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: SystemVariableChangedEventArgs) -> None: ...

class SystemVariableChangingEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.SystemVariableChangingEventArgs"""
    def __init__(self, *args) -> None: ...
    Name: str

class SystemVariableChangingEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.SystemVariableChangingEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: SystemVariableChangingEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: SystemVariableChangingEventArgs) -> None: ...

class TabbedDialogAction:
    """.NET: Autodesk.AutoCAD.ApplicationServices.TabbedDialogAction"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, ) -> None: ...

class TabbedDialogEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.TabbedDialogEventArgs"""
    def __init__(self, *args) -> None: ...
    def AddTab(self, name: str, extension: TabbedDialogExtension) -> None: ...

class TabbedDialogEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.TabbedDialogEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: TabbedDialogEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: TabbedDialogEventArgs) -> None: ...

class TabbedDialogExtension:
    """.NET: Autodesk.AutoCAD.ApplicationServices.TabbedDialogExtension"""
    def __init__(self, *args) -> None: ...
    OnApply: TabbedDialogAction
    OnHelp: TabbedDialogAction
    OnCancel: TabbedDialogAction
    OnOk: TabbedDialogAction
    Control: object
    @staticmethod
    def SetDirty(control: object, dirty: bool) -> None: ...

class TransactionManager(TransactionManager):
    """.NET: Autodesk.AutoCAD.ApplicationServices.TransactionManager"""
    def __init__(self, *args) -> None: ...
    TopTransaction: Transaction
    NumberOfOpenedObjects: int
    NumberOfActiveTransactions: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def EnableGraphicsFlush(self, doEnable: bool) -> None: ...
    def FlushGraphics(self, ) -> None: ...
    def StartTransaction(self, ) -> Transaction: ...

class UnknownCommandEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.ApplicationServices.UnknownCommandEventArgs"""
    def __init__(self, *args) -> None: ...
    GlobalCommandName: str

class UnknownCommandEventHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.UnknownCommandEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: UnknownCommandEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: UnknownCommandEventArgs) -> None: ...

class UserConfigurationManager(MarshalByRefObject):
    """.NET: Autodesk.AutoCAD.ApplicationServices.UserConfigurationManager"""
    def __init__(self, *args) -> None: ...
    def OpenCurrentProfile(self, ) -> IConfigurationSection: ...
    def OpenDialogSection(self, dialog: object) -> IConfigurationSection: ...
    def OpenGlobalSection(self, ) -> IConfigurationSection: ...
    def SetCurrentProfile(self, profileName: str) -> None: ...

class WhoHasInfo:
    """.NET: Autodesk.AutoCAD.ApplicationServices.WhoHasInfo"""
    def __init__(self, *args) -> None: ...
    OpenTime: str
    ComputerName: str
    UserName: str
    IsFileLocked: bool

class XrefFileLock(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.ApplicationServices.XrefFileLock"""
    def __init__(self, *args) -> None: ...
    OutOfSyncBlockIds: ObjectIdCollection
    XloadCtlType: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def ConsistencyCheck(selectedBlockId: ObjectId) -> ObjectIdCollection: ...
    @staticmethod
    def ConsistencyCheckLocal(selectedBlockId: ObjectId) -> ObjectIdCollection: ...
    @staticmethod
    def GetXloadCtlType(selectedBlockId: ObjectId) -> int: ...
    @staticmethod
    def LockFile(selectedBlockId: ObjectId) -> XrefFileLock: ...
    def ReleaseFile(self, skipSaveback: bool, reload: bool) -> None: ...
    @staticmethod
    def ReloadFile(blocks: ObjectIdCollection, xldCtlType: int) -> None: ...
