# Auto-generated — Civil 26 — Autodesk.AutoCAD.ApplicationServices.Core

class Application:
    """.NET: Autodesk.AutoCAD.ApplicationServices.Core.Application"""
    def __init__(self, *args) -> None: ...
    IsAdpDisabled: bool
    UnmanagedResources: UnmanagedResources
    LongTransactionManager: LongTransactionManager
    RecentDocuments: RecentDocumentCollection
    Publisher: Publisher
    UserConfigurationManager: UserConfigurationManager
    Version: Version
    IsInBackgroundMode: bool
    IsInPlaceServer: bool
    HasPickFirst: bool
    IsQuiescent: bool
    MainWindow: Window
    DocumentManager: DocumentCollection
    @staticmethod
    def EvaluateDiesel(dieselCmd: str) -> str: ...
    @staticmethod
    def GetSystemVariable(name: str) -> object: ...
    @staticmethod
    def GetWhoHasInfo(pathname: str) -> WhoHasInfo: ...
    @staticmethod
    def Invoke(args: ResultBuffer) -> ResultBuffer: ...
    @staticmethod
    def IsFileLocked(pathname: str) -> bool: ...
    @staticmethod
    def LoadJSScript(urlJSFile: Uri) -> None: ...
    @staticmethod
    def Quit() -> None: ...
    @staticmethod
    def SetSystemVariable(name: str, value: object) -> None: ...
    @staticmethod
    def ShowAlertDialog(message: str) -> None: ...
    @staticmethod
    def ShowModalWindow(owner: Window, formToShow: Window, persistSizeAndPosition: bool) -> Nullable: ...
    @staticmethod
    def ShowModelessWindow(owner: Window, formToShow: Window, persistSizeAndPosition: bool) -> None: ...
    @staticmethod
    def TryGetSystemVariable(name: str) -> object: ...
    @staticmethod
    def UpdateScreen() -> None: ...

class CreateContextMenuHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.Core.CreateContextMenuHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, type: Type, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> AcEdUIContext: ...
    def Invoke(self, type: Type) -> AcEdUIContext: ...

class EnableWinFormHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.Core.EnableWinFormHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, o: object, enable: bool, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> bool: ...
    def Invoke(self, o: object, enable: bool) -> bool: ...

class FilterMessageWinFormsHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.Core.FilterMessageWinFormsHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, msg: tagMSG, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> bool: ...
    def Invoke(self, msg: tagMSG) -> bool: ...

class OnIdleWinFormsHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.Core.OnIdleWinFormsHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, ) -> None: ...

class OnWinFormsLoadedHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.Core.OnWinFormsLoadedHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, ) -> None: ...

class OnWpfLoadedHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.Core.OnWpfLoadedHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, ) -> None: ...

class PreProcessMessageWinFormsHandler:
    """.NET: Autodesk.AutoCAD.ApplicationServices.Core.PreProcessMessageWinFormsHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, msg: tagMSG, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> bool: ...
    def Invoke(self, msg: tagMSG) -> bool: ...
