# Auto-generated — Civil 26 — Autodesk.AutoCAD.Windows

class ColorDialog:
    """.NET: Autodesk.AutoCAD.Windows.ColorDialog"""
    def __init__(self, *args) -> None: ...
    Color: Color
    IncludeByBlockByLayer: bool
    def SetDialogTabs(self, value: ColorTabs) -> None: ...
    def ShowDialog(self, ) -> DialogResult: ...
    def ShowModal(self, ) -> Nullable: ...

class ContextMenuExtension(Menu):
    """.NET: Autodesk.AutoCAD.Windows.ContextMenuExtension"""
    def __init__(self, *args) -> None: ...
    Title: str
    MenuItems: MenuItemCollection
    def Dispose(self, ) -> None: ...

class DefaultPane:
    """.NET: Autodesk.AutoCAD.Windows.DefaultPane"""
    def __init__(self, *args) -> None: ...
    ...

class DockSides:
    """.NET: Autodesk.AutoCAD.Windows.DockSides"""
    def __init__(self, *args) -> None: ...
    ...

class DocumentWindow(Window):
    """.NET: Autodesk.AutoCAD.Windows.DocumentWindow"""
    def __init__(self, *args) -> None: ...
    IsFloating: bool
    CanUpdate: bool
    Document: object
    Title: str
    CanClose: bool
    Text: str
    DeviceIndependentSize: Size
    DeviceIndependentLocation: Point
    Visible: bool
    WindowState: State
    Handle: IntPtr
    UnmanagedWindow: IntPtr
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Activate(self, ) -> None: ...
    def Close(self, ) -> None: ...

class DocumentWindowLoadedEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.DocumentWindowLoadedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class DocumentWindowUpdatedEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.DocumentWindowUpdatedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class DrawingDocumentWindow(DocumentWindow):
    """.NET: Autodesk.AutoCAD.Windows.DrawingDocumentWindow"""
    def __init__(self, *args) -> None: ...
    Document: Document
    IsFloating: bool
    CanUpdate: bool
    Document: object
    Title: str
    CanClose: bool
    Text: str
    DeviceIndependentSize: Size
    DeviceIndependentLocation: Point
    Visible: bool
    WindowState: State
    Handle: IntPtr
    UnmanagedWindow: IntPtr
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class DropTarget:
    """.NET: Autodesk.AutoCAD.Windows.DropTarget"""
    def __init__(self, *args) -> None: ...
    def OnDragEnter(self, e: DragEventArgs) -> None: ...
    def OnDragLeave(self, ) -> None: ...
    def OnDragOver(self, e: DragEventArgs) -> None: ...
    def OnDrop(self, e: DragEventArgs) -> None: ...

class IconType:
    """.NET: Autodesk.AutoCAD.Windows.IconType"""
    def __init__(self, *args) -> None: ...
    ...

class InfoCenter:
    """.NET: Autodesk.AutoCAD.Windows.InfoCenter"""
    def __init__(self, *args) -> None: ...
    UPIXMLData: str
    SubAwareClientInfo: str
    Host: HwndSource
    KeepFocus: bool
    Visible: bool
    def InfoToolbarSizeChanged(self, bExpand: bool) -> None: ...
    def InvokeToolbarMoveEvent(self, ) -> None: ...
    def InvokeToolbarResizeEvent(self, width: int) -> None: ...
    def LaunchSubAwareModule(self, resReqid: int, strCourseId: str, strModuleId: str) -> None: ...

class InfoToolbarMoveDelegate:
    """.NET: Autodesk.AutoCAD.Windows.InfoToolbarMoveDelegate"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, ) -> None: ...

class InfoToolbarResizeTo:
    """.NET: Autodesk.AutoCAD.Windows.InfoToolbarResizeTo"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, width: int, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, width: int) -> None: ...

class LayerTransparencyDialog:
    """.NET: Autodesk.AutoCAD.Windows.LayerTransparencyDialog"""
    def __init__(self, *args) -> None: ...
    Percent: int
    def ShowDialog(self, ) -> DialogResult: ...
    def ShowModal(self, ) -> Nullable: ...

class LineWeightDialog:
    """.NET: Autodesk.AutoCAD.Windows.LineWeightDialog"""
    def __init__(self, *args) -> None: ...
    LineWeight: LineWeight
    IncludeByBlockByLayer: bool
    def ShowDialog(self, ) -> DialogResult: ...
    def ShowModal(self, ) -> Nullable: ...

class LinetypeDialog:
    """.NET: Autodesk.AutoCAD.Windows.LinetypeDialog"""
    def __init__(self, *args) -> None: ...
    Linetype: ObjectId
    IncludeByBlockByLayer: bool
    def ShowDialog(self, ) -> DialogResult: ...
    def ShowModal(self, ) -> Nullable: ...

class Menu:
    """.NET: Autodesk.AutoCAD.Windows.Menu"""
    def __init__(self, *args) -> None: ...
    MenuItems: MenuItemCollection

class MenuItem(Menu):
    """.NET: Autodesk.AutoCAD.Windows.MenuItem"""
    def __init__(self, *args) -> None: ...
    Icon: Icon
    Checked: bool
    Visible: bool
    Enabled: bool
    Text: str
    MenuItems: MenuItemCollection

class MenuItemCollection:
    """.NET: Autodesk.AutoCAD.Windows.MenuItemCollection"""
    def __init__(self, *args) -> None: ...
    Item: MenuItem
    IsReadOnly: bool
    IsFixedSize: bool
    Count: int
    def Add(self, value: MenuItem) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: MenuItem) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: MenuItem) -> int: ...
    def Insert(self, index: int, value: MenuItem) -> None: ...
    def Remove(self, value: MenuItem) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class OpenFileDialog:
    """.NET: Autodesk.AutoCAD.Windows.OpenFileDialog"""
    def __init__(self, *args) -> None: ...
    Filename: str
    def GetFilenames(self, ) -> list: ...
    def ShowDialog(self, ) -> DialogResult: ...
    def ShowModal(self, ) -> Nullable: ...

class OpenFileOrFolderDialog:
    """.NET: Autodesk.AutoCAD.Windows.OpenFileOrFolderDialog"""
    def __init__(self, *args) -> None: ...
    FileOrFoldername: str
    def ShowDialog(self, ) -> DialogResult: ...

class Palette:
    """.NET: Autodesk.AutoCAD.Windows.Palette"""
    def __init__(self, *args) -> None: ...
    PaletteSet: PaletteSet
    Name: str

class PaletteActivatedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.PaletteActivatedEventArgs"""
    def __init__(self, *args) -> None: ...
    Deactivated: Palette
    Activated: Palette

class PaletteActivatedEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteActivatedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PaletteActivatedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PaletteActivatedEventArgs) -> None: ...

class PaletteAddContextMenuEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.PaletteAddContextMenuEventArgs"""
    def __init__(self, *args) -> None: ...
    RightClickTab: int
    HitFlag: int
    RemoveMenuItems: List
    MenuItems: List

class PaletteAddContextMenuEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteAddContextMenuEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PaletteAddContextMenuEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PaletteAddContextMenuEventArgs) -> None: ...

class PaletteEnterSizeMoveEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.PaletteEnterSizeMoveEventArgs"""
    def __init__(self, *args) -> None: ...
    EnterSizeMove: bool

class PaletteEnterSizeMoveEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteEnterSizeMoveEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PaletteEnterSizeMoveEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PaletteEnterSizeMoveEventArgs) -> None: ...

class PalettePersistEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.PalettePersistEventArgs"""
    def __init__(self, *args) -> None: ...
    ConfigurationSection: IConfigurationSection

class PalettePersistEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PalettePersistEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PalettePersistEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PalettePersistEventArgs) -> None: ...

class PaletteSet(Window):
    """.NET: Autodesk.AutoCAD.Windows.PaletteSet"""
    def __init__(self, *args) -> None: ...
    Icon: Icon
    Location: Point
    Size: Size
    Anchored: bool
    MinimumSize: Size
    DeviceIndependentMinimumSize: Size
    DeviceIndependentLocation: Point
    DeviceIndependentSize: Size
    Visible: bool
    LargeDarkThemedIcon: Icon
    DarkThemedIcon: Icon
    LargeLightThemedIcon: Icon
    LightThemedIcon: Icon
    PaletteSize: Size
    Dock: DockSides
    KeepFocus: bool
    TitleBarLocation: PaletteSetTitleBarLocation
    Opacity: int
    Count: int
    Name: str
    Item: Palette
    RolledUp: bool
    AutoRollUp: bool
    DockEnabled: DockSides
    Style: PaletteSetStyles
    Text: str
    WindowState: State
    Handle: IntPtr
    UnmanagedWindow: IntPtr
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Activate(self, index: int) -> None: ...
    def Add(self, name: str, htmlPage: Uri) -> Palette: ...
    def AddVisual(self, name: str, control: Visual, bResizeContentToPaletteSize: bool) -> Palette: ...
    def AddVisualBrowser(self, name: str, control: Visual, htmlPage: str, scriptableName: str, bShowBrowserFirst: bool) -> Palette: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def EnableTransparency(self, value: bool) -> bool: ...
    def FloatControl(self, value: Rect) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetThemedIcon(self, bBigIcon: bool) -> Icon: ...
    def InitializeFloatingPosition(self, value: Rect) -> None: ...
    def RecalculateDockSiteLayout(self, ) -> None: ...
    def Remove(self, index: int) -> None: ...
    def SetThemedIcon(self, value: Icon, theme: ColorThemeEnum) -> None: ...
    def switchVisualBrowser(self, index: int, bVisual: bool, url: str) -> None: ...

class PaletteSetDestroyEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetDestroyEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class PaletteSetDockSite:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetDockSite"""
    def __init__(self, *args) -> None: ...
    def CanDock(self, mousePosition: Point) -> Nullable: ...
    def Dock(self, paletteset: PaletteSet) -> bool: ...
    def Initialize(self, paletteset: PaletteSet, desiredSize: Size, dockSyle: int) -> None: ...
    def Uninitialize(self, ) -> None: ...

class PaletteSetFocusedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetFocusedEventArgs"""
    def __init__(self, *args) -> None: ...
    ...

class PaletteSetFocusedEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetFocusedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PaletteSetFocusedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PaletteSetFocusedEventArgs) -> None: ...

class PaletteSetHelpEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetHelpEventArgs"""
    def __init__(self, *args) -> None: ...
    ...

class PaletteSetHelpEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetHelpEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PaletteSetHelpEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PaletteSetHelpEventArgs) -> None: ...

class PaletteSetMoveEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetMoveEventArgs"""
    def __init__(self, *args) -> None: ...
    y: int
    X: int

class PaletteSetMoveEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetMoveEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PaletteSetMoveEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PaletteSetMoveEventArgs) -> None: ...

class PaletteSetShowDockBarEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetShowDockBarEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PaletteShowDockBarEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PaletteShowDockBarEventArgs) -> None: ...

class PaletteSetSizeEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetSizeEventArgs"""
    def __init__(self, *args) -> None: ...
    DeviceIndependentHeight: float
    DeviceIndependentWidth: float
    Height: int
    Width: int

class PaletteSetSizeEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetSizeEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PaletteSetSizeEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PaletteSetSizeEventArgs) -> None: ...

class PaletteSetStateEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetStateEventArgs"""
    def __init__(self, *args) -> None: ...
    NewState: StateEventIndex

class PaletteSetStateEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetStateEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PaletteSetStateEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PaletteSetStateEventArgs) -> None: ...

class PaletteSetStyles:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetStyles"""
    def __init__(self, *args) -> None: ...
    ...

class PaletteSetTitleBarLocation:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetTitleBarLocation"""
    def __init__(self, *args) -> None: ...
    ...

class PaletteSetTitleBarLocationChangeEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.PaletteSetTitleBarLocationChangeEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class PaletteShowDockBarEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.PaletteShowDockBarEventArgs"""
    def __init__(self, *args) -> None: ...
    ShowDockBar: bool

class Pane(StatusBarItem):
    """.NET: Autodesk.AutoCAD.Windows.Pane"""
    def __init__(self, *args) -> None: ...
    MaximumWidth: int
    MinimumWidth: int
    Style: PaneStyles
    Text: str
    Visible: bool
    Enabled: bool
    ToolTipText: str
    Icon: Icon
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class PaneCollection:
    """.NET: Autodesk.AutoCAD.Windows.PaneCollection"""
    def __init__(self, *args) -> None: ...
    Item: Pane
    IsReadOnly: bool
    IsFixedSize: bool
    Count: int
    def Add(self, value: Pane) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Pane) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: Pane) -> int: ...
    def Insert(self, index: int, value: Pane) -> None: ...
    def Remove(self, value: Pane) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class PaneStyles:
    """.NET: Autodesk.AutoCAD.Windows.PaneStyles"""
    def __init__(self, *args) -> None: ...
    ...

class PlotStyleDialog:
    """.NET: Autodesk.AutoCAD.Windows.PlotStyleDialog"""
    def __init__(self, *args) -> None: ...
    PlotStyle: str
    IncludeByBlockByLayer: bool
    def ShowDialog(self, ) -> DialogResult: ...
    def ShowModal(self, ) -> Nullable: ...

class SaveFileDialog:
    """.NET: Autodesk.AutoCAD.Windows.SaveFileDialog"""
    def __init__(self, *args) -> None: ...
    Filename: str
    def ShowDialog(self, ) -> DialogResult: ...
    def ShowModal(self, ) -> Nullable: ...

class StateEventIndex:
    """.NET: Autodesk.AutoCAD.Windows.StateEventIndex"""
    def __init__(self, *args) -> None: ...
    ...

class StatusBar:
    """.NET: Autodesk.AutoCAD.Windows.StatusBar"""
    def __init__(self, *args) -> None: ...
    Window: Window
    TrayItems: TrayItemCollection
    Panes: PaneCollection
    def CloseBubbleWindows(self, ) -> None: ...
    def GetDefaultPane(self, pane: DefaultPane) -> Pane: ...
    def RemoveDefaultPane(self, pane: DefaultPane) -> None: ...
    def Update(self, ) -> None: ...

class StatusBarItem(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Windows.StatusBarItem"""
    def __init__(self, *args) -> None: ...
    Visible: bool
    Enabled: bool
    ToolTipText: str
    Icon: Icon
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def PointToClient(self, p: Point) -> Point: ...
    def PointToScreen(self, p: Point) -> Point: ...

class StatusBarMouseDownEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.StatusBarMouseDownEventArgs"""
    def __init__(self, *args) -> None: ...
    Button: MouseButtons
    DoubleClick: bool
    Y: int
    X: int

class StatusBarMouseDownEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.StatusBarMouseDownEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: StatusBarMouseDownEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: StatusBarMouseDownEventArgs) -> None: ...

class TrayItem(StatusBarItem):
    """.NET: Autodesk.AutoCAD.Windows.TrayItem"""
    def __init__(self, *args) -> None: ...
    Visible: bool
    Enabled: bool
    ToolTipText: str
    Icon: Icon
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def CloseBubbleWindows(self, ) -> None: ...
    def ShowBubbleWindow(self, bubble: TrayItemBubbleWindow) -> None: ...

class TrayItemBubbleWindow(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Windows.TrayItemBubbleWindow"""
    def __init__(self, *args) -> None: ...
    Text2: str
    HyperLink: str
    HyperText: str
    Text: str
    Title: str
    IconType: IconType
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class TrayItemBubbleWindowCloseReason:
    """.NET: Autodesk.AutoCAD.Windows.TrayItemBubbleWindowCloseReason"""
    def __init__(self, *args) -> None: ...
    ...

class TrayItemBubbleWindowClosedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Windows.TrayItemBubbleWindowClosedEventArgs"""
    def __init__(self, *args) -> None: ...
    CloseReason: TrayItemBubbleWindowCloseReason

class TrayItemBubbleWindowClosedEventHandler:
    """.NET: Autodesk.AutoCAD.Windows.TrayItemBubbleWindowClosedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: TrayItemBubbleWindowClosedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: TrayItemBubbleWindowClosedEventArgs) -> None: ...

class TrayItemCollection:
    """.NET: Autodesk.AutoCAD.Windows.TrayItemCollection"""
    def __init__(self, *args) -> None: ...
    Item: TrayItem
    IsReadOnly: bool
    IsFixedSize: bool
    Count: int
    def Add(self, value: TrayItem) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: TrayItem) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: TrayItem) -> int: ...
    def Insert(self, index: int, value: TrayItem) -> None: ...
    def Remove(self, value: TrayItem) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class Visuals:
    """.NET: Autodesk.AutoCAD.Windows.Visuals"""
    def __init__(self, *args) -> None: ...
    PickBitmap: Image
    PickSetBitmap: Image
    ApplicationIcon: Icon

class WPFDocumentWindow(DocumentWindow):
    """.NET: Autodesk.AutoCAD.Windows.WPFDocumentWindow"""
    def __init__(self, *args) -> None: ...
    IsFloating: bool
    CanUpdate: bool
    Document: object
    Title: str
    CanClose: bool
    Text: str
    DeviceIndependentSize: Size
    DeviceIndependentLocation: Point
    Visible: bool
    WindowState: State
    Handle: IntPtr
    UnmanagedWindow: IntPtr
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Window(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Windows.Window"""
    def __init__(self, *args) -> None: ...
    Text: str
    DeviceIndependentSize: Size
    DeviceIndependentLocation: Point
    Visible: bool
    WindowState: State
    Handle: IntPtr
    UnmanagedWindow: IntPtr
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Close(self, ) -> None: ...
    def Focus(self, ) -> bool: ...
    @staticmethod
    def FromHandle(handle: IntPtr) -> Window: ...
    @staticmethod
    def GetDeviceIndependentScale(hWnd: IntPtr) -> Vector: ...

class WindowExtension:
    """.NET: Autodesk.AutoCAD.Windows.WindowExtension"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetIcon(window: Window) -> Icon: ...
    @staticmethod
    def GetLocation(window: Window) -> Point: ...
    @staticmethod
    def GetSize(window: Window) -> Size: ...
    @staticmethod
    def SetIcon(window: Window, value: Icon) -> None: ...
    @staticmethod
    def SetLocation(window: Window, value: Point) -> None: ...
    @staticmethod
    def SetSize(window: Window, value: Size) -> None: ...
