# Auto-generated — Civil 26 — Autodesk.AutoCAD.Windows.ToolPalette

class AcTcToolReactorImpl:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.AcTcToolReactorImpl"""
    def __init__(self, *args) -> None: ...
    ...

class ContextMenuMode:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.ContextMenuMode"""
    def __init__(self, *args) -> None: ...
    ...

class CustomToolBase:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.CustomToolBase"""
    def __init__(self, *args) -> None: ...
    EditMode: int
    CurrentShapeId: Guid
    FlyoutPackageID: Guid
    ToolImage: str
    ToolName: str
    ToolGuid: Guid
    def BeginEdit(self, ) -> None: ...
    def BeginMultipleEdit(self, tools: object, stockToolIds: object) -> None: ...
    def CreateCommandTool(self, palette: Package, toolName: str, bitmapName: ImageInfo, macro: str) -> Tool: ...
    def CreateFlyoutTool(self, palette: Package, shapePackage: Package, toolNameOverride: str) -> Tool: ...
    def CreatePalette(self, catalogName: Catalog, paletteName: str) -> Palette: ...
    def CreateShapeCatalog(self, shapeName: str) -> Package: ...
    def CreateStockTool(self, catalogName: str) -> Catalog: ...
    def CreateTool(self, palette: Package, toolNameOverride: str, toolImageOverride: ImageInfo) -> Tool: ...
    def Customize(self, contextFlag: int, menuHandle: int, idCommandFirst: int, idCommandLast: int, paletteId: Guid) -> int: ...
    def Dispose(self, ) -> None: ...
    def DoModal(self, propertyValue: str, activeShapes: ObjectIdCollection) -> None: ...
    def DragEnter(self, data: IDataObject, keyState: int, point: POINTL, effect: int) -> None: ...
    def DragLeave(self, ) -> None: ...
    def DragOver(self, keyState: int, pt: POINTL, effect: int) -> None: ...
    def Drop(self, data: IDataObject, keyState: int, pt: POINTL, effect: int) -> None: ...
    def DropCallback(self, entity: Entity) -> bool: ...
    def Dropped(self, url: str) -> None: ...
    def Edit(self, property: object, parentWindow: IntPtr, success: bool) -> None: ...
    def Editable(self, dispatchId: int, editable: int) -> None: ...
    def EndEdit(self, bEditCancelled: bool) -> None: ...
    def EndMultipleEdit(self, tools: object, stockToolIds: object, editCancelled: bool) -> None: ...
    def Execute(self, flag: int, window: int, point: int, keyState: int) -> None: ...
    def ExecuteCallback(self, ) -> bool: ...
    def GetCommandString(self, idCommand: int) -> str: ...
    def GetContextMenu(self, contextFlag: int, menu: int, idCommandFirst: int, idCommandLast: int) -> int: ...
    def GetCustomPropertyCtrl(self, id: object, lcid: int, programId: str) -> None: ...
    def GetData(self, staticProperties: object, dynamicProperties: object) -> None: ...
    def GetDisplayName(self, dispatchId: int, propertyName: str) -> None: ...
    def GetDisplayString(self, dispatchId: int, value: str) -> None: ...
    def GetDragDropContextInfo(self, pIUnknown: object, toolName: str, flag: int) -> None: ...
    def GetDropTarget(self, ) -> object: ...
    def GetMenuHelp(self, idCmd: int) -> str: ...
    def GetPredefinedStrings(self, dispatchId: int, value: tagCALPOLESTR, cookie: tagCADWORD) -> None: ...
    def GetPredefinedValue(self, dispatchId: int, cookie: int, value: object) -> None: ...
    def GetPropTextColor(self, id: object, textColor: int) -> None: ...
    def GetPropertyIcon(self, id: object, icon: object) -> None: ...
    def GetPropertyWeight(self, id: object, pPropertyWeight: int) -> None: ...
    def GetStockTool(self, ) -> object: ...
    def GetToolProperties(self, ) -> object: ...
    def GetUnspecifiedString(self, id: object) -> str: ...
    def InvokeCommand(self, idCommand: int, window: int) -> None: ...
    def InvokeMenuCommand(self, idCmd: int, paletteId: Guid, windowHandle: int) -> int: ...
    def IsFullView(self, id: object, visible: bool, integralHeight: int) -> None: ...
    def IsUnspecifiedAllowed(self, id: object, returnValue: bool) -> int: ...
    def IsValueUnspecified(self, id: object, returnValue: bool) -> int: ...
    def Load(self, xmlElement: object) -> None: ...
    def MapPropertyToPage(self, dispatchId: int, clsid: Guid) -> None: ...
    def MultipleEdit(self, tools: object, stockToolIds: object, parentWindow: int, success: bool) -> None: ...
    def New(self, ) -> None: ...
    def Refreshed(self, url: str) -> None: ...
    def Save(self, xmlElement: object) -> None: ...
    def SetEditorWindow(self, editorWindow: IntPtr, propertyInspector: object) -> None: ...
    def SetFlyoutTools(self, flyoutToolIds: object) -> None: ...
    def SetToolProperties(self, toolProperties: object) -> None: ...
    def SetUnspecified(self, id: object, isUnspecified: bool) -> None: ...
    def ShowProperty(self, dispatchId: int, show: int) -> None: ...
    def ValidateEditChanges(self, ) -> None: ...

class DragHandler:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.DragHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, pTool: ValueType, dwKeyState: int, tpOperationFlag: TPOperationFlag, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, pTool: ValueType, dwKeyState: int, tpOperationFlag: TPOperationFlag) -> None: ...

class DropPointHandler:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.DropPointHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, point: Point3d, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, point: Point3d) -> None: ...

class ExecutionContext:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.ExecutionContext"""
    def __init__(self, *args) -> None: ...
    ...

class FlyoutEntryAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.FlyoutEntryAttribute"""
    def __init__(self, *args) -> None: ...
    DispId: int
    TypeId: object

class PerPropertyBrowsingEntryAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.PerPropertyBrowsingEntryAttribute"""
    def __init__(self, *args) -> None: ...
    Weight: int
    IntegralHeight: int
    IsFullView: bool
    TextColor: int
    EllipsisBmpType: int
    EllipsisBmpResource: str
    LeftIconType: int
    LefIconResource: str
    ProgId: str
    DispId: int
    TypeId: object

class PickHandler:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.PickHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, pTool: ValueType, dwKeyState: int, tpOperationFlag: TPOperationFlag, nIndex: int, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, pTool: ValueType, dwKeyState: int, tpOperationFlag: TPOperationFlag, nIndex: int) -> None: ...

class ReturnStatus:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.ReturnStatus"""
    def __init__(self, *args) -> None: ...
    ...

class TPOperationFlag:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.TPOperationFlag"""
    def __init__(self, *args) -> None: ...
    ...

class ToolAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.ToolAttribute"""
    def __init__(self, *args) -> None: ...
    ToolImage: str
    ToolName: str
    TypeId: object

class ToolEditFlags:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.ToolEditFlags"""
    def __init__(self, *args) -> None: ...
    ...

class ToolItemInfo:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.ToolItemInfo"""
    def __init__(self, *args) -> None: ...
    ...

class ToolReactorManager:
    """.NET: Autodesk.AutoCAD.Windows.ToolPalette.ToolReactorManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Instance() -> ToolReactorManager: ...
    def invokeToolContextMenu(self, itemId: Guid, nIndex: int) -> None: ...
    def invokeToolDrag(self, itemId: Guid, dwKeyState: int, point: Point3d) -> None: ...
    def invokeToolPick(self, itemId: Guid, dwKeyState: int) -> None: ...
