# Auto-generated — Navisworks 24 — Autodesk.Navisworks.Api

class AnimationBehavior:
    """.NET: Autodesk.Navisworks.Api.AnimationBehavior"""
    def __init__(self, *args) -> None: ...
    ...

class AppearanceOverrides:
    """.NET: Autodesk.Navisworks.Api.AppearanceOverrides"""
    def __init__(self, *args) -> None: ...
    MaterialOverrides: Collection

class Application:
    """.NET: Autodesk.Navisworks.Api.Application"""
    def __init__(self, *args) -> None: ...
    IsUserDataCollectionEnabled: bool
    IsAutomated: bool
    DragDrop: ApplicationDragDrop
    Options: ApplicationOptions
    Resources: ApplicationResources
    Plugins: ApplicationPlugins
    Gui: IApplicationGui
    Version: ApplicationVersion
    Automation: ApplicationAutomation
    MainDocument: Document
    ActiveDocument: Document
    Documents: ReadOnlyCollection
    Title: str
    @staticmethod
    def BeginProgress(title: str, message: str) -> Progress: ...
    @staticmethod
    def EndProgress() -> None: ...
    @staticmethod
    def GetCustomColors() -> list: ...
    @staticmethod
    def LoadDocumentInfo(fileName: str) -> DocumentInfo: ...
    @staticmethod
    def PostUserMessage(internalId: str, source: str, category: MessageCenterCategory, message: str, extendedMessage: str, messageFlags: int) -> None: ...
    @staticmethod
    def RegisterBitmap(bitmap: Bitmap) -> int: ...
    @staticmethod
    def SetCustomColors(customColors: list) -> None: ...
    @staticmethod
    def TryLoadDocumentInfo(fileName: str) -> DocumentInfo: ...
    @staticmethod
    def UnregisterBitmap(bitmapIndex: int) -> bool: ...

class Assignee(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Assignee"""
    def __init__(self, *args) -> None: ...
    Assigned: bool
    DisplayName: str
    InternalId: str
    IsReadOnly: bool
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Assignee: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ToString(self, ) -> str: ...
    def Unassign(self, ) -> None: ...

class AxisAndAngleResult:
    """.NET: Autodesk.Navisworks.Api.AxisAndAngleResult"""
    def __init__(self, *args) -> None: ...
    Angle: float
    Axis: UnitVector3D

class BoundingBox2D(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.BoundingBox2D"""
    def __init__(self, *args) -> None: ...
    Area: float
    Size: Vector2D
    Center: Point2D
    HasArea: bool
    IsEmpty: bool
    Max: Point2D
    Min: Point2D
    IsReadOnly: bool
    IsDisposed: bool
    def Contains(self, box: BoundingBox2D) -> bool: ...
    def Equals(self, obj: object) -> bool: ...
    def Extend(self, box: BoundingBox2D) -> BoundingBox2D: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> BoundingBox2D: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Intersect(self, box: BoundingBox2D) -> BoundingBox2D: ...
    def Intersects(self, box: BoundingBox2D) -> bool: ...
    def ToString(self, ) -> str: ...
    def Translate(self, offset: Vector2D) -> BoundingBox2D: ...

class BoundingBox3D(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.BoundingBox3D"""
    def __init__(self, *args) -> None: ...
    Empty: BoundingBox3D
    SurfaceArea: float
    Volume: float
    Size: Vector3D
    Center: Point3D
    HasSurfaceArea: bool
    HasVolume: bool
    IsEmpty: bool
    Max: Point3D
    Min: Point3D
    IsReadOnly: bool
    IsDisposed: bool
    def ClosestPoint(self, point: Point3D) -> Point3D: ...
    def Contains(self, box: BoundingBox3D) -> bool: ...
    def Equals(self, obj: object) -> bool: ...
    def Extend(self, point: Point3D) -> BoundingBox3D: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> BoundingBox3D: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Intersect(self, box: BoundingBox3D) -> BoundingBox3D: ...
    def Intersects(self, box: BoundingBox3D) -> bool: ...
    def ToString(self, ) -> str: ...
    def Translate(self, offset: Vector3D) -> BoundingBox3D: ...

class CameraMode:
    """.NET: Autodesk.Navisworks.Api.CameraMode"""
    def __init__(self, *args) -> None: ...
    ...

class CanceledOperationException(Exception):
    """.NET: Autodesk.Navisworks.Api.CanceledOperationException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CategorisationForTracking:
    """.NET: Autodesk.Navisworks.Api.CategorisationForTracking"""
    def __init__(self, *args) -> None: ...
    ...

class CivilAlignment:
    """.NET: Autodesk.Navisworks.Api.CivilAlignment"""
    def __init__(self, *args) -> None: ...
    EndStation: float
    StartStation: float
    Name: str
    def GetDistanceForStation(self, station: float) -> float: ...
    def GetMajorStationDistance(self, ) -> int: ...
    def GetNextMajorStation(self, station: float) -> float: ...
    def GetNextStation(self, station: float, stationDelta: float) -> float: ...
    def GetPointForDistance(self, distance: float, position: Point3D, direction: UnitVector3D) -> bool: ...
    def GetStationLabel(self, station: float) -> str: ...

class ClipPlane(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.ClipPlane"""
    def __init__(self, *args) -> None: ...
    Distance: float
    XAxis: UnitVector3D
    Normal: UnitVector3D
    Transform: Transform3D
    Plane: LcLPlane3f
    Alignment: ClipPlaneAlignment
    Origin: Point3D
    State: ClipPlaneState
    Enabled: bool
    Default: bool
    IsReadOnly: bool
    IsDisposed: bool
    def AlignToOrientation(self, align: ClipPlaneAlignment, up: UnitVector3D, front: UnitVector3D) -> None: ...
    def AlignToPick(self, align: ClipPlaneAlignment, origin: Point3D, normal: UnitVector3D, xAxis: UnitVector3D) -> None: ...
    def ApplyTransform(self, trans: Transform3D) -> None: ...
    def CopyFrom(self, from_: ClipPlane) -> None: ...
    def Initialize(self, align: ClipPlaneAlignment, origin: Point3D, up: UnitVector3D, front: UnitVector3D, normal: UnitVector3D, xAxis: UnitVector3D) -> bool: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> ClipPlane: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Move(self, dist: float) -> None: ...
    def Reset(self, ) -> None: ...
    def Translate(self, offset: Vector3D) -> None: ...

class ClipPlaneAlignment:
    """.NET: Autodesk.Navisworks.Api.ClipPlaneAlignment"""
    def __init__(self, *args) -> None: ...
    ...

class ClipPlaneSet(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.ClipPlaneSet"""
    def __init__(self, *args) -> None: ...
    BoxTransform: Transform3D
    Range: BoundingBox3D
    Box: BoundingBox3D
    Enabled: bool
    CurrentPlaneIndex: int
    Linked: bool
    CurrentPlane: ClipPlane
    Mode: ClipPlaneSetMode
    IsReadOnly: bool
    IsDisposed: bool
    def Clips(self, point: Point3D) -> bool: ...
    def CopyFrom(self, other: ClipPlaneSet) -> None: ...
    def FitToBox(self, boundingBox: BoundingBox3D) -> None: ...
    def Get(self, index: int) -> ClipPlane: ...
    def GetOrientedBox(self, box: BoundingBox3D, rotation: Rotation3D) -> None: ...
    def GetTransform(self, index: int) -> Transform3D: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> ClipPlaneSet: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def IsOffsetPlanes(self, other: ClipPlaneSet) -> bool: ...
    def SetOrientedBox(self, box: BoundingBox3D, rotation: Rotation3D) -> None: ...
    def SetTransform(self, index: int, trans: Transform3D) -> None: ...
    def Size(self, ) -> int: ...
    def Transform(self, trans: Transform3D) -> None: ...
    def Translate(self, index: int, offset: Vector3D) -> None: ...
    @staticmethod
    def ValueEquals(value1: ClipPlaneSet, value2: ClipPlaneSet) -> bool: ...

class ClipPlaneSetMode:
    """.NET: Autodesk.Navisworks.Api.ClipPlaneSetMode"""
    def __init__(self, *args) -> None: ...
    ...

class ClipPlaneState:
    """.NET: Autodesk.Navisworks.Api.ClipPlaneState"""
    def __init__(self, *args) -> None: ...
    ...

class Color(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Color"""
    def __init__(self, *args) -> None: ...
    Blue: Color
    Green: Color
    Red: Color
    White: Color
    Black: Color
    IsBlack: bool
    B: float
    G: float
    R: float
    IsReadOnly: bool
    Item: float
    IsDisposed: bool
    def Add(self, color: Color) -> Color: ...
    def Equals(self, obj: object) -> bool: ...
    @staticmethod
    def FromByteRGB(red: int, green: int, blue: int) -> Color: ...
    def GetClampedByteValue(self, index: int) -> int: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Color: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Multiply(self, value: float) -> Color: ...
    def Subtract(self, color: Color) -> Color: ...
    def ToString(self, ) -> str: ...
    def ToVector3D(self, ) -> Vector3D: ...

class Comment(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Comment"""
    def __init__(self, *args) -> None: ...
    Id: int
    CreationDate: DateTime
    Author: Assignee
    Status: CommentStatus
    Body: str
    IsReadOnly: bool
    IsDisposed: bool
    def CreateCopy(self, ) -> Comment: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Comment: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ToString(self, ) -> str: ...

class CommentCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.CommentCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: Comment
    IsDisposed: bool
    def Add(self, item: Comment) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: Comment) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: Comment) -> int: ...
    def Insert(self, index: int, item: Comment) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> CommentCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Remove(self, item: Comment) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...

class CommentStatus:
    """.NET: Autodesk.Navisworks.Api.CommentStatus"""
    def __init__(self, *args) -> None: ...
    ...

class Cursor:
    """.NET: Autodesk.Navisworks.Api.Cursor"""
    def __init__(self, *args) -> None: ...
    ...

class DataProperty(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.DataProperty"""
    def __init__(self, *args) -> None: ...
    Value: VariantData
    CombinedName: NamedConstant
    Name: str
    DisplayName: str
    IsReadOnly: bool
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> DataProperty: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ParseCompatibleValue(self, formattedValue: str) -> VariantData: ...
    def ToString(self, ) -> str: ...
    def TryParseCompatibleValue(self, formattedValue: str) -> VariantData: ...

class DataPropertyCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.DataPropertyCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: DataProperty
    IsDisposed: bool
    def Add(self, item: DataProperty) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: DataProperty) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def FindPropertyByCombinedName(self, name: NamedConstant) -> DataProperty: ...
    def FindPropertyByDisplayName(self, name: str) -> DataProperty: ...
    def FindPropertyByName(self, name: str) -> DataProperty: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: DataProperty) -> int: ...
    def Insert(self, index: int, item: DataProperty) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> DataPropertyCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Remove(self, item: DataProperty) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...

class DataPropertyNames:
    """.NET: Autodesk.Navisworks.Api.DataPropertyNames"""
    def __init__(self, *args) -> None: ...
    RevitElementIdValue: str
    MicrostationElementIdValue: str
    AutoCadEntityHandleValue: str
    ItemUnit: str
    ItemCreator: str
    ItemFileName: str
    ItemSourceFileName: str
    ItemGuid: str
    ItemLayer: str
    ItemSourceFile: str
    ItemMaterial: str
    ItemRequired: str
    ItemHidden: str
    ItemIcon: str
    ItemInternalType: str
    ItemType: str
    ItemName: str

class Document:
    """.NET: Autodesk.Navisworks.Api.Document"""
    def __init__(self, *args) -> None: ...
    FrontRightTopViewUpVector: Vector3D
    FrontRightTopViewVector: Vector3D
    RightVector: Vector3D
    FrontVector: Vector3D
    UpVector: Vector3D
    IsDisposed: bool
    ActiveView: View
    Views: ReadOnlyCollection
    State: LcOwDocument
    ActiveSheetType: SheetType
    ActiveSheet: SheetInfo
    Hyperlinks: DocumentHyperlinks
    Database: DocumentDatabase
    HomeView: Viewpoint
    CurrentMeasurement: DocumentCurrentMeasurement
    SavedViewpoints: DocumentSavedViewpoints
    CurrentViewpoint: DocumentCurrentViewpoint
    CurrentComments: DocumentCurrentComments
    Alignments: DocumentAlignments
    Grids: DocumentGrids
    DocumentInfo: DocumentInfoPart
    Models: DocumentModels
    Tool: DocumentTool
    SelectionSets: DocumentSelectionSets
    CurrentSearch: DocumentCurrentSearch
    CurrentSelection: DocumentCurrentSelection
    Takeoff: IDocumentTakeoff
    Clash: IDocumentClash
    Timeliner: IDocumentTimeliner
    Title: str
    CurrentFileName: str
    SuggestedFileName: str
    IsClear: bool
    IsUndoDisabled: bool
    NextRedo: str
    NextUndo: str
    IsActiveTransaction: bool
    CanDescribeAsAggregate: bool
    Units: Units
    IsModified: bool
    FileVersion: DocumentFileVersion
    FileName: str
    def AppendFile(self, fileName: str) -> None: ...
    def AppendFiles(self, fileNames: IEnumerable) -> None: ...
    def AppendSheet(self, sheet: SheetInfo) -> None: ...
    def BeginTransaction(self, displayName: str) -> Transaction: ...
    def Clear(self, ) -> None: ...
    def CloseFileHandles(self, ) -> None: ...
    def ConvertSheet(self, sheetId: str) -> None: ...
    def CreateCommentWithUniqueId(self, body: str, status: CommentStatus, author: Assignee) -> Comment: ...
    def DescribeAsAggregate(self, ) -> str: ...
    def Dispose(self, ) -> None: ...
    def EndDisableUndo(self, ) -> None: ...
    def ExportAsDwf(self, fileName: str) -> None: ...
    def ExportToNwd(self, fileName: str, options: NwdExportOptions) -> None: ...
    def GenerateImage(self, style: ImageGenerationStyle, width: int, height: int, maxTimeHint: float, enableSectioning: bool) -> Bitmap: ...
    def GetBoundingBox(self, ignoreHidden: bool) -> BoundingBox3D: ...
    def GetPointInfo(self, worldPoint: Point3D) -> IEnumerable: ...
    def MergeFile(self, fileName: str) -> None: ...
    def MergeFiles(self, fileNames: IEnumerable) -> None: ...
    def MergeSheet(self, sheet: SheetInfo) -> None: ...
    def OpenAggregate(self, aggregateJson: str, progressMedia: str) -> None: ...
    def OpenFile(self, fileName: str) -> None: ...
    def PublishFile(self, fileName: str, options: NwdExportOptions, properties: PublishProperties) -> None: ...
    def Redo(self, ) -> None: ...
    def RemoveFile(self, index: int) -> None: ...
    def ResolveReference(self, reference: SavedItemReference) -> SavedItem: ...
    def Rollback(self, ) -> None: ...
    def SaveFile(self, fileName: str, fileVersion: DocumentFileVersion) -> None: ...
    def SetActiveSheet(self, sheetId: str) -> None: ...
    def SetGraduatedBackground(self, topColor: Color, bottomColor: Color) -> None: ...
    def SetHorizonBackground(self, skyTopColor: Color, skyBottomColor: Color, groundTopColor: Color, groundBottomColor: Color) -> None: ...
    def SetPlainBackground(self, color: Color) -> None: ...
    def ShowMatchingItemInSheet(self, sheetId: str, item: ModelItem) -> None: ...
    def StartDisableUndo(self, ) -> None: ...
    def ToString(self, ) -> str: ...
    def TryAppendFile(self, fileName: str) -> bool: ...
    def TryAppendFiles(self, fileNames: IEnumerable) -> bool: ...
    def TryAppendSheet(self, sheet: SheetInfo) -> bool: ...
    def TryCloseFileHandles(self, ) -> bool: ...
    def TryConvertSheet(self, sheetId: str) -> bool: ...
    def TryDescribeAsAggregate(self, aggregateJson: str) -> bool: ...
    def TryExportToNwd(self, fileName: str, options: NwdExportOptions) -> bool: ...
    def TryMergeFile(self, fileName: str) -> bool: ...
    def TryMergeFiles(self, fileNames: IEnumerable) -> bool: ...
    def TryMergeSheet(self, sheet: SheetInfo) -> bool: ...
    def TryOpenAggregate(self, aggregateJson: str, progressMedia: str) -> bool: ...
    def TryOpenFile(self, fileName: str) -> bool: ...
    def TryPublishFile(self, fileName: str, options: NwdExportOptions, properties: PublishProperties) -> bool: ...
    def TryRedo(self, ) -> bool: ...
    def TryRemoveFile(self, index: int) -> bool: ...
    def TryRollback(self, ) -> bool: ...
    def TrySaveFile(self, fileName: str, fileVersion: DocumentFileVersion) -> bool: ...
    def TrySetActiveSheet(self, sheetId: str) -> bool: ...
    def TryUndo(self, ) -> bool: ...
    def Undo(self, ) -> None: ...
    def UpdateFiles(self, ) -> bool: ...

class DocumentEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.DocumentEventArgs"""
    def __init__(self, *args) -> None: ...
    Document: Document

class DocumentFileException(IOException):
    """.NET: Autodesk.Navisworks.Api.DocumentFileException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class DocumentFileVersion:
    """.NET: Autodesk.Navisworks.Api.DocumentFileVersion"""
    def __init__(self, *args) -> None: ...
    ...

class DocumentInfo(GroupItem):
    """.NET: Autodesk.Navisworks.Api.DocumentInfo"""
    def __init__(self, *args) -> None: ...
    FileVersionGuid: Guid
    SourceGuid: Guid
    PropertyCategories: InfoPropertyCategoryCollection
    CurrentSheet: SheetInfo
    CurrentSheetId: str
    IsReadOnly: bool
    Children: SavedItemCollection
    Guid: Guid
    IsGroup: bool
    Parent: GroupItem
    Comments: CommentCollection
    DisplayName: str
    IsDisposed: bool
    def FindSheet(self, id: str) -> SheetInfo: ...
    def IndexOfSheetId(self, id: str) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> DocumentInfo: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class DocumentInfoParts:
    """.NET: Autodesk.Navisworks.Api.DocumentInfoParts"""
    def __init__(self, *args) -> None: ...
    ...

class EulerAngleResult:
    """.NET: Autodesk.Navisworks.Api.EulerAngleResult"""
    def __init__(self, *args) -> None: ...
    Z: float
    Y: float
    X: float

class FileInteractiveResolvedEventArgs(FileResolutionEventArgs):
    """.NET: Autodesk.Navisworks.Api.FileInteractiveResolvedEventArgs"""
    def __init__(self, *args) -> None: ...
    ResolvedFileReference: str
    Response: FileResolutionResponse
    ResolveToOpen: bool
    ReferringFileNameAsSaved: str
    ReferringFileName: str
    FileReferenceType: FileReferenceType
    FileReference: str
    Resolver: FileReferenceResolver

class FileInteractiveResolvingEventArgs(FileResolutionEventArgs):
    """.NET: Autodesk.Navisworks.Api.FileInteractiveResolvingEventArgs"""
    def __init__(self, *args) -> None: ...
    Handled: bool
    Response: FileResolutionResponse
    ResolvedFileReference: str
    DisplayString: str
    ResolveToOpen: bool
    ReferringFileNameAsSaved: str
    ReferringFileName: str
    FileReferenceType: FileReferenceType
    FileReference: str
    Resolver: FileReferenceResolver

class FileReferenceResolveResult:
    """.NET: Autodesk.Navisworks.Api.FileReferenceResolveResult"""
    def __init__(self, *args) -> None: ...
    FileNameToOpen: str
    ResolvedFileReference: str
    Response: FileResolutionResponse

class FileReferenceResolver(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.FileReferenceResolver"""
    def __init__(self, *args) -> None: ...
    InteractiveDisplayString: str
    ReferringFileNameAsSaved: str
    ReferringFileName: str
    IsReadOnly: bool
    IsDisposed: bool
    def GetSearchPath(self, ) -> str: ...
    @staticmethod
    def InternalClearGlobalCache() -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> FileReferenceResolver: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Resolve(self, fileReference: str, resolveToOpen: bool) -> FileReferenceResolveResult: ...
    def SetSearchPath(self, search_path: str) -> None: ...

class FileReferenceResolverEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.FileReferenceResolverEventArgs"""
    def __init__(self, *args) -> None: ...
    Resolver: FileReferenceResolver

class FileReferenceType:
    """.NET: Autodesk.Navisworks.Api.FileReferenceType"""
    def __init__(self, *args) -> None: ...
    ...

class FileResolutionEventArgs(FileReferenceResolverEventArgs):
    """.NET: Autodesk.Navisworks.Api.FileResolutionEventArgs"""
    def __init__(self, *args) -> None: ...
    ResolveToOpen: bool
    ReferringFileNameAsSaved: str
    ReferringFileName: str
    FileReferenceType: FileReferenceType
    FileReference: str
    Resolver: FileReferenceResolver

class FileResolutionResponse:
    """.NET: Autodesk.Navisworks.Api.FileResolutionResponse"""
    def __init__(self, *args) -> None: ...
    ...

class FileResolvedEventArgs(FileResolutionEventArgs):
    """.NET: Autodesk.Navisworks.Api.FileResolvedEventArgs"""
    def __init__(self, *args) -> None: ...
    FileNameToOpen: str
    ResolvedFileReferenceType: FileReferenceType
    ResolvedFileReference: str
    ResolveToOpen: bool
    ReferringFileNameAsSaved: str
    ReferringFileName: str
    FileReferenceType: FileReferenceType
    FileReference: str
    Resolver: FileReferenceResolver

class FileResolvingEventArgs(FileResolutionEventArgs):
    """.NET: Autodesk.Navisworks.Api.FileResolvingEventArgs"""
    def __init__(self, *args) -> None: ...
    Handled: bool
    FileNameToOpen: str
    ResolvedFileReference: str
    ResolveToOpen: bool
    ReferringFileNameAsSaved: str
    ReferringFileName: str
    FileReferenceType: FileReferenceType
    FileReference: str
    Resolver: FileReferenceResolver

class FileSaveEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.FileSaveEventArgs"""
    def __init__(self, *args) -> None: ...
    IsPublish: bool
    SaveComplete: bool
    FileName: str

class FileUpdateEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.FileUpdateEventArgs"""
    def __init__(self, *args) -> None: ...
    AnyFilesUpdated: bool

class FolderItem(GroupItem):
    """.NET: Autodesk.Navisworks.Api.FolderItem"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Children: SavedItemCollection
    Guid: Guid
    IsGroup: bool
    Parent: GroupItem
    Comments: CommentCollection
    DisplayName: str
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> FolderItem: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class Graphics(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Graphics"""
    def __init__(self, *args) -> None: ...
    PolygonTessellationWindingRule: TessellationWindingRule
    WindowHeight: int
    WindowWidth: int
    IsReadOnly: bool
    IsDisposed: bool
    def Arc(self, center: Point3D, start: Point3D, end: Point3D, normal: Vector3D, filled: bool) -> None: ...
    def BeginComplexPolygon(self, vertexProperties: VertexProperties) -> None: ...
    def BeginComplexPolygonContour(self, ) -> None: ...
    def BeginModelContext(self, ) -> None: ...
    def BeginPolygon(self, vertexProperties: VertexProperties) -> None: ...
    def BeginUserContext(self, ) -> None: ...
    def BeginWindowContext(self, ) -> None: ...
    def BezierSegment(self, start: Point2D, control: Point2D, end: Point2D, resolution: int) -> None: ...
    def Bitmap(self, index: int, origin: Point2D, width: int, height: int, alpha: float) -> None: ...
    def Blend(self, blendOn: bool) -> None: ...
    def CanRenderText2D(self, fontInfo: TextFontInfo, text: str) -> bool: ...
    def Circle(self, centre: Point3D, normal: Vector3D, radius: float, filled: bool) -> None: ...
    def Color(self, colorValue: Color, alphaValue: float) -> None: ...
    def Cone(self, start: Point3D, end: Point3D, startRadius: float, endRadius: float) -> None: ...
    def Cuboid(self, origin: Point3D, xVector: Vector3D, yVector: Vector3D, zVector: Vector3D, filled: bool) -> None: ...
    def Cylinder(self, start: Point3D, end: Point3D, radius: float) -> None: ...
    def DepthMask(self, depthMaskOn: bool) -> None: ...
    def DepthTest(self, depthTestOn: bool) -> None: ...
    def Ellipse(self, centre: Point2D, xRadius: float, yRadius: float, filled: bool, resolution: int) -> None: ...
    def EndComplexPolygon(self, ) -> None: ...
    def EndComplexPolygonContour(self, ) -> None: ...
    def EndModelContext(self, ) -> None: ...
    def EndPolygon(self, ) -> None: ...
    def EndUserContext(self, ) -> None: ...
    def EndWindowContext(self, ) -> None: ...
    def GetFontMetrics(self, fontInfo: TextFontInfo, metrics: TextFontMetrics) -> bool: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Graphics: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Lighting(self, lightingOn: bool) -> None: ...
    def Line(self, start: Point3D, end: Point3D) -> None: ...
    def LineStipple(self, factor: int, pattern: int) -> None: ...
    def LineWidth(self, width: float) -> None: ...
    def Point(self, point3D: Point3D) -> None: ...
    def Polyline2D(self, points: Point2DList) -> None: ...
    def Polyline3D(self, points: Point3DList) -> None: ...
    def Rectangle(self, origin: Point3D, xVector: Vector3D, yVector: Vector3D, filled: bool) -> None: ...
    def SetTexture(self, imageId: int) -> None: ...
    def Sphere(self, center: Point3D, radius: float) -> None: ...
    def Text2D(self, fontInfo: TextFontInfo, text: str, origin: Point2D, offsetX: int, offsetY: int) -> TextExtents2D: ...
    def Text2DExtents(self, fontInfo: TextFontInfo, text: str) -> TextExtents2D: ...
    def TextureCoordinate(self, coordinate: Point2D) -> None: ...
    def Triangle(self, point1: Point3D, point2: Point3D, point3: Point3D, filled: bool) -> None: ...
    def Vertex(self, coordinate: Point3D) -> None: ...
    def VertexColor(self, color: Color, alpha: float) -> None: ...
    def VertexNormal(self, normal: Vector3D) -> None: ...

class GridIntersection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.GridIntersection"""
    def __init__(self, *args) -> None: ...
    DisplayName: str
    Line2Direction: UnitVector3D
    Line1Direction: UnitVector3D
    Position: Point3D
    Level: GridLevel
    Line2: GridLine
    Line1: GridLine
    IsReadOnly: bool
    IsDisposed: bool
    def FormatCombinedDisplayString(self, point: Point3D, conversionFactor: float) -> str: ...
    def FormatIntersectionDisplayString(self, point: Point3D, conversionFactor: float) -> str: ...
    def FormatLevelDisplayString(self, point: Point3D, conversionFactor: float) -> str: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GridIntersection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class GridLevel(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.GridLevel"""
    def __init__(self, *args) -> None: ...
    Elevation: float
    DisplayName: str
    IsReadOnly: bool
    IsDisposed: bool
    def ClosestIntersection(self, point: Point3D) -> GridIntersection: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GridLevel: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class GridLevelCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.GridLevelCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: GridLevel
    IsDisposed: bool
    def Add(self, item: GridLevel) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: GridLevel) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: GridLevel) -> int: ...
    def Insert(self, index: int, item: GridLevel) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GridLevelCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Remove(self, item: GridLevel) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...

class GridLine(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.GridLine"""
    def __init__(self, *args) -> None: ...
    Segments: GridLineSegmentCollection
    DisplayName: str
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GridLine: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class GridLineCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.GridLineCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: GridLine
    IsDisposed: bool
    def Add(self, item: GridLine) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: GridLine) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: GridLine) -> int: ...
    def Insert(self, index: int, item: GridLine) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GridLineCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Remove(self, item: GridLine) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...

class GridLineSegment(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.GridLineSegment"""
    def __init__(self, *args) -> None: ...
    CurveType: GridSegmentCurveType
    EndPoint: Point2D
    MidPoint: Point2D
    StartPoint: Point2D
    IsReadOnly: bool
    IsDisposed: bool
    def DistanceTo(self, pnt: Point2D) -> float: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GridLineSegment: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def WhichSide(self, pnt: Point2D) -> float: ...

class GridLineSegmentCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.GridLineSegmentCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: GridLineSegment
    IsDisposed: bool
    def Add(self, item: GridLineSegment) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: GridLineSegment) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: GridLineSegment) -> int: ...
    def Insert(self, index: int, item: GridLineSegment) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GridLineSegmentCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Remove(self, item: GridLineSegment) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...

class GridSegmentCurveType:
    """.NET: Autodesk.Navisworks.Api.GridSegmentCurveType"""
    def __init__(self, *args) -> None: ...
    ...

class GridSystem(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.GridSystem"""
    def __init__(self, *args) -> None: ...
    UpDirection: UnitVector3D
    Origin: Point3D
    Lines: GridLineCollection
    LockedLevel: GridLevel
    Levels: GridLevelCollection
    DisplayName: str
    IsReadOnly: bool
    IsDisposed: bool
    def ClosestIntersection(self, point: Point3D) -> GridIntersection: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GridSystem: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class GridSystemCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.GridSystemCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: GridSystem
    IsDisposed: bool
    def Add(self, item: GridSystem) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: GridSystem) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: GridSystem) -> int: ...
    def Insert(self, index: int, item: GridSystem) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GridSystemCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Remove(self, item: GridSystem) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...

class GridsData(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.GridsData"""
    def __init__(self, *args) -> None: ...
    RenderMode: GridsRenderMode
    ActiveSystem: GridSystem
    IsReadOnly: bool
    Systems: ReadOnlyCollection
    IsDisposed: bool
    def CreateCopy(self, ) -> GridsData: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GridsData: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class GridsOptions:
    """.NET: Autodesk.Navisworks.Api.GridsOptions"""
    def __init__(self, *args) -> None: ...
    OtherColor: Color
    BelowColor: Color
    AboveColor: Color
    XRayMode: bool
    Enabled: bool

class GridsRenderMode:
    """.NET: Autodesk.Navisworks.Api.GridsRenderMode"""
    def __init__(self, *args) -> None: ...
    ...

class GroupItem(SavedItem):
    """.NET: Autodesk.Navisworks.Api.GroupItem"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Children: SavedItemCollection
    Guid: Guid
    IsGroup: bool
    Parent: GroupItem
    Comments: CommentCollection
    DisplayName: str
    IsDisposed: bool
    def CreateCopyWithoutChildren(self, ) -> GroupItem: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GroupItem: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class HelpIdResult:
    """.NET: Autodesk.Navisworks.Api.HelpIdResult"""
    def __init__(self, *args) -> None: ...
    Handled: bool
    Id: str

class Hyperlink(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Hyperlink"""
    def __init__(self, *args) -> None: ...
    URL: str
    Name: str
    IsReadOnly: bool
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Hyperlink: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ToString(self, ) -> str: ...

class HyperlinkCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.HyperlinkCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: Hyperlink
    IsDisposed: bool
    def Add(self, item: Hyperlink) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: Hyperlink) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: Hyperlink) -> int: ...
    def Insert(self, index: int, item: Hyperlink) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> HyperlinkCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Remove(self, item: Hyperlink) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...

class IHasDynamicProperties:
    """.NET: Autodesk.Navisworks.Api.IHasDynamicProperties"""
    def __init__(self, *args) -> None: ...
    DynamicMemberNames: IEnumerable
    def GetProperty(self, name: str) -> object: ...
    def SetProperty(self, name: str, value: object) -> object: ...

class ImageGenerationStyle:
    """.NET: Autodesk.Navisworks.Api.ImageGenerationStyle"""
    def __init__(self, *args) -> None: ...
    ...

class InfoPropertyCategory(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.InfoPropertyCategory"""
    def __init__(self, *args) -> None: ...
    DisplayName: str
    Properties: DataPropertyCollection
    IsReadOnly: bool
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> InfoPropertyCategory: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class InfoPropertyCategoryCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.InfoPropertyCategoryCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Item: InfoPropertyCategory
    Count: int
    IsDisposed: bool
    def GetEnumerator(self, ) -> IEnumerator: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> InfoPropertyCategoryCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def InternalGetEnumerator(self, ) -> IEnumerator: ...

class KeyModifiers:
    """.NET: Autodesk.Navisworks.Api.KeyModifiers"""
    def __init__(self, *args) -> None: ...
    ...

class MaterialOverride:
    """.NET: Autodesk.Navisworks.Api.MaterialOverride"""
    def __init__(self, *args) -> None: ...
    Transparency: Nullable
    Color: Color
    Item: ModelItem

class Matrix3(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Matrix3"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    def Determinant(self, ) -> float: ...
    def Equals(self, matrix: Matrix3, tolerance: float) -> bool: ...
    def Get(self, row: int, column: int) -> float: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Matrix3: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def IsIdentity(self, ) -> bool: ...
    def IsZero(self, ) -> bool: ...
    def ToString(self, ) -> str: ...

class MeasurementType:
    """.NET: Autodesk.Navisworks.Api.MeasurementType"""
    def __init__(self, *args) -> None: ...
    ...

class MessageCenterCategory:
    """.NET: Autodesk.Navisworks.Api.MessageCenterCategory"""
    def __init__(self, *args) -> None: ...
    ...

class Model(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Model"""
    def __init__(self, *args) -> None: ...
    SchemaDefinitions: SchemaDefinitionCollection
    SourceGuid: Guid
    Guid: Guid
    PublishProperties: PublishProperties
    HasRightVector: bool
    RightVector: UnitVector3D
    FrontVector: UnitVector3D
    HasFrontVector: bool
    NorthVector: UnitVector3D
    HasNorthVector: bool
    UpVector: UnitVector3D
    HasUpVector: bool
    Creator: str
    SourceFileName: str
    FileName: str
    Units: Units
    RootItem: ModelItem
    IsReadOnly: bool
    IsTransformReflected: bool
    Transform: Transform3D
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Model: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class ModelCreatorNames:
    """.NET: Autodesk.Navisworks.Api.ModelCreatorNames"""
    def __init__(self, *args) -> None: ...
    ArchicadExporter: str
    MicrostationExporter: str
    MaxExporter: str
    RevitExporter: str
    ZAndFReader: str
    StlReader: str
    SketchUpReader: str
    RvmReader: str
    RieglReader: str
    ParasolidReader: str
    LeicaReader: str
    JTOpenReader: str
    FaroReader: str
    InventorReader: str
    IgesReader: str
    StepReader: str
    IfcReader: str
    Cis2Reader: str
    DwfReader: str
    AsciiLaserReader: str
    SatReader: str
    MicrostationReader: str
    The3DStudioReader: str
    AutodeskRealDwgReader: str

class ModelGeometry(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.ModelGeometry"""
    def __init__(self, *args) -> None: ...
    ActiveTransform: Transform3D
    OriginalTransform: Transform3D
    BoundingBox: BoundingBox3D
    OriginalTransparency: float
    OriginalColor: Color
    ActiveTransparency: float
    ActiveColor: Color
    IsSolid: bool
    PrimitiveTypes: PrimitiveTypes
    PrimitiveCount: int
    FragmentCount: int
    Item: ModelItem
    IsReadOnly: bool
    PermanentTransform: Transform3D
    PermanentOverrideTransform: Transform3D
    PermanentTransparency: float
    PermanentColor: Color
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> ModelGeometry: ...
    @staticmethod
    def InternalCustomCreator(handleIn: IntPtr, source: NativeHandle) -> ModelGeometry: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class ModelItem(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.ModelItem"""
    def __init__(self, *args) -> None: ...
    ClassDisplayName: str
    ClassName: str
    DisplayName: str
    Transform: Transform3D
    Geometry: ModelGeometry
    HasGeometry: bool
    Model: Model
    HasModel: bool
    IsCollection: bool
    IsLayer: bool
    IsInsert: bool
    IsComposite: bool
    InstanceGuid: Guid
    InstanceHashCode: int
    IsReadOnly: bool
    IsFrozen: bool
    IsRequired: bool
    IsHidden: bool
    PropertyCategories: PropertyCategoryCollection
    Instances: ModelItemEnumerableCollection
    Self: ModelItemEnumerableCollection
    Ancestors: ModelItemEnumerableCollection
    AncestorsAndSelf: ModelItemEnumerableCollection
    Descendants: ModelItemEnumerableCollection
    DescendantsAndSelf: ModelItemEnumerableCollection
    Children: ModelItemEnumerableCollection
    Parent: ModelItem
    IsDisposed: bool
    def BoundingBox(self, ignoreHidden: bool) -> BoundingBox3D: ...
    def Equals(self, obj: object) -> bool: ...
    def FindFirstGeometry(self, ) -> ModelGeometry: ...
    def FindFirstObjectAncestor(self, ) -> ModelItem: ...
    def GetHashCode(self, ) -> int: ...
    def GetUserFilteredPropertyCategories(self, ) -> PropertyCategoryCollection: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> ModelItem: ...
    @staticmethod
    def InternalCustomCreator(handleIn: IntPtr, source: NativeHandle) -> ModelItem: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def IsSameInstance(self, item: ModelItem) -> bool: ...

class ModelItemCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.ModelItemCollection"""
    def __init__(self, *args) -> None: ...
    IsEmpty: bool
    First: ModelItem
    IsReadOnly: bool
    Descendants: ModelItemEnumerableCollection
    DescendantsAndSelf: ModelItemEnumerableCollection
    Item: ModelItem
    InternalIsReadOnly: bool
    Count: int
    IsDisposed: bool
    def Add(self, item: ModelItem) -> None: ...
    def AddAllInstances(self, ) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def AreAllInstancesSelected(self, ) -> bool: ...
    def BoundingBox(self, ignoreHidden: bool) -> BoundingBox3D: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: ModelItem) -> bool: ...
    def CopyFrom(self, from_: ModelItemCollection) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> ModelItemCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def InternalGetEnumerator(self, ) -> IEnumerator: ...
    def InternalGetPaths(self, ) -> LcOaPathLinkVector: ...
    def Invert(self, doc: Document) -> None: ...
    def IsAnyContained(self, value: ModelItemCollection) -> bool: ...
    def IsContained(self, item: ModelItem) -> bool: ...
    def IsContentsIntersected(self, value: ModelItemCollection) -> bool: ...
    def IsDisjoint(self, ) -> bool: ...
    def IsSelected(self, item: ModelItem) -> bool: ...
    def MakeDisjoint(self, ) -> None: ...
    def Minimize(self, ) -> None: ...
    def Remove(self, item: ModelItem) -> bool: ...
    @staticmethod
    def ValueEquals(value1: ModelItemCollection, value2: ModelItemCollection) -> bool: ...
    def Where(self, conditions: SearchConditionCollection) -> IEnumerable: ...

class ModelItemEnumerableCollection:
    """.NET: Autodesk.Navisworks.Api.ModelItemEnumerableCollection"""
    def __init__(self, *args) -> None: ...
    Empty: ModelItemEnumerableCollection
    First: ModelItem
    def CopyTo(self, to: ICollection) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def InternalGetEnumerator(self, ) -> IEnumerator: ...
    def ToString(self, ) -> str: ...
    def Where(self, conditions: SearchConditionCollection) -> IEnumerable: ...
    def WhereInstanceGuid(self, value: Guid) -> IEnumerable: ...

class NamedConstant(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.NamedConstant"""
    def __init__(self, *args) -> None: ...
    Value: int
    BaseName: str
    Name: str
    DisplayName: str
    IsReadOnly: bool
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> NamedConstant: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ToString(self, ) -> str: ...
    def UserEquals(self, other: NamedConstant) -> bool: ...

class NamedConstantCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.NamedConstantCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: NamedConstant
    IsDisposed: bool
    def Contains(self, item: NamedConstant) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: NamedConstant) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> NamedConstantCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class NativeHandle:
    """.NET: Autodesk.Navisworks.Api.NativeHandle"""
    def __init__(self, *args) -> None: ...
    IsDisposed: bool
    IsReadOnly: bool
    def Dispose(self, ) -> None: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def ReferenceEquals(objA: NativeHandle, objB: NativeHandle) -> bool: ...
    def ToString(self, ) -> str: ...

class NwdExportOptions(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.NwdExportOptions"""
    def __init__(self, *args) -> None: ...
    FileVersion: int
    ExcludeHiddenItems: bool
    PreventObjectPropertyExport: bool
    EmbedXrefs: bool
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> NwdExportOptions: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class PickItemResult:
    """.NET: Autodesk.Navisworks.Api.PickItemResult"""
    def __init__(self, *args) -> None: ...
    Normal: UnitVector3D
    ResultBits: PickResults
    Point: Point3D
    ModelItem: ModelItem

class PickPrimitives:
    """.NET: Autodesk.Navisworks.Api.PickPrimitives"""
    def __init__(self, *args) -> None: ...
    ...

class PickResults:
    """.NET: Autodesk.Navisworks.Api.PickResults"""
    def __init__(self, *args) -> None: ...
    ...

class Point2D(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Point2D"""
    def __init__(self, *args) -> None: ...
    DistanceSquared: float
    Distance: float
    Origin: Point2D
    IsOrigin: bool
    Y: float
    X: float
    IsReadOnly: bool
    Item: float
    IsDisposed: bool
    def Add(self, vector: Vector2D) -> Point2D: ...
    def DistanceTo(self, other: Point2D) -> float: ...
    def DistanceToSquared(self, other: Point2D) -> float: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Point2D: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Subtract(self, point: Point2D) -> Vector2D: ...
    def ToData(self, ) -> VariantData: ...
    def ToString(self, ) -> str: ...
    @staticmethod
    def TolerantEquals(point0: Point2D, point1: Point2D, tolerance: float) -> bool: ...

class Point2DList(LcLPos2fListBase):
    """.NET: Autodesk.Navisworks.Api.Point2DList"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    def Add(self, point: Point2D) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Point2DList: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class Point3D(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Point3D"""
    def __init__(self, *args) -> None: ...
    DistanceSquared: float
    Distance: float
    Origin: Point3D
    IsOrigin: bool
    Z: float
    Y: float
    X: float
    IsReadOnly: bool
    Item: float
    IsDisposed: bool
    def Add(self, vector: Vector3D) -> Point3D: ...
    def DistanceTo(self, other: Point3D) -> float: ...
    def DistanceToSquared(self, other: Point3D) -> float: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Point3D: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Subtract(self, point: Point3D) -> Vector3D: ...
    def ToData(self, ) -> VariantData: ...
    def ToString(self, ) -> str: ...
    def ToVector3D(self, ) -> Vector3D: ...
    @staticmethod
    def TolerantEquals(point0: Point3D, point1: Point3D, tolerance: float) -> bool: ...

class Point3DList(LcLPos3fListBase):
    """.NET: Autodesk.Navisworks.Api.Point3DList"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    def Add(self, point: Point3D) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Point3DList: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class PointInfo:
    """.NET: Autodesk.Navisworks.Api.PointInfo"""
    def __init__(self, *args) -> None: ...
    LongInfo: IEnumerable
    ShortInfo: str
    InternalName: str
    DisplayName: str

class PrimitiveTypes:
    """.NET: Autodesk.Navisworks.Api.PrimitiveTypes"""
    def __init__(self, *args) -> None: ...
    ...

class Progress(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Progress"""
    def __init__(self, *args) -> None: ...
    WorkingFileName: str
    IsCanceled: bool
    IsReadOnly: bool
    IsDisposed: bool
    def BeginSubOperation(self, fractionOfRemainingTime: float, message: str) -> None: ...
    def Cancel(self, ) -> None: ...
    def EndSubOperation(self, completed: bool) -> None: ...
    def Hide(self, ) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Progress: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ReportError(self, errorCode: int, message: str, isFileError: bool) -> bool: ...
    def Show(self, ) -> None: ...
    def Update(self, fractionDone: float) -> bool: ...

class ProgressBeginningEventArgs(ProgressEventArgs):
    """.NET: Autodesk.Navisworks.Api.ProgressBeginningEventArgs"""
    def __init__(self, *args) -> None: ...
    Title: str
    Handled: bool

class ProgressEndedEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.ProgressEndedEventArgs"""
    def __init__(self, *args) -> None: ...
    ...

class ProgressErrorReportingEventArgs(ProgressEventArgs):
    """.NET: Autodesk.Navisworks.Api.ProgressErrorReportingEventArgs"""
    def __init__(self, *args) -> None: ...
    Canceled: bool
    IsFileError: bool
    Message: str
    ErrorCode: int
    Progress: Progress
    Handled: bool

class ProgressEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.ProgressEventArgs"""
    def __init__(self, *args) -> None: ...
    Handled: bool

class ProgressMessageReportingEventArgs(ProgressEventArgs):
    """.NET: Autodesk.Navisworks.Api.ProgressMessageReportingEventArgs"""
    def __init__(self, *args) -> None: ...
    Message: str
    Progress: Progress
    Handled: bool

class ProgressSubOperationBeganEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.ProgressSubOperationBeganEventArgs"""
    def __init__(self, *args) -> None: ...
    Message: str
    FractionOfRemainingTime: float
    Progress: Progress

class ProgressSubOperationEndedEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.ProgressSubOperationEndedEventArgs"""
    def __init__(self, *args) -> None: ...
    Completed: bool
    Progress: Progress

class ProgressUpdatingEventArgs(ProgressEventArgs):
    """.NET: Autodesk.Navisworks.Api.ProgressUpdatingEventArgs"""
    def __init__(self, *args) -> None: ...
    Canceled: bool
    SubOperationFractionDone: float
    OverallFractionDone: float
    Progress: Progress
    Handled: bool

class ProgressVisibilityEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.ProgressVisibilityEventArgs"""
    def __init__(self, *args) -> None: ...
    WantVisible: bool
    Progress: Progress

class ProjectionResult:
    """.NET: Autodesk.Navisworks.Api.ProjectionResult"""
    def __init__(self, *args) -> None: ...
    Depth: float
    Y: int
    X: int

class PropertyCategory:
    """.NET: Autodesk.Navisworks.Api.PropertyCategory"""
    def __init__(self, *args) -> None: ...
    IsEditable: bool
    IsDisposed: bool
    HasBinaryData: bool
    SchemaData: SchemaData
    HasSchemaData: bool
    HasStringStableId: bool
    HasInt64StableId: bool
    HasStableId: bool
    Properties: DataPropertyCollection
    CombinedName: NamedConstant
    DisplayName: str
    Name: str
    def Dispose(self, ) -> None: ...
    def GetBinaryData(self, ) -> list: ...
    def GetInt64StableId(self, ) -> int: ...
    def GetStringStableId(self, ) -> str: ...
    def ToString(self, ) -> str: ...

class PropertyCategoryCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.PropertyCategoryCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    def FindCategoryByCombinedName(self, combinedName: NamedConstant) -> PropertyCategory: ...
    def FindCategoryByDisplayName(self, displayName: str) -> PropertyCategory: ...
    def FindCategoryByName(self, name: str) -> PropertyCategory: ...
    def FindCategoryWithStableId(self, ) -> PropertyCategory: ...
    def FindPropertyByCombinedName(self, categoryCombinedName: NamedConstant, propertyCombinedName: NamedConstant) -> DataProperty: ...
    def FindPropertyByDisplayName(self, categoryDisplayName: str, propertyDisplayName: str) -> DataProperty: ...
    def FindPropertyByName(self, categoryName: str, propertyName: str) -> DataProperty: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> PropertyCategoryCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def InternalGetEnumerator(self, ) -> IEnumerator: ...
    def InternalToJson(self, ) -> str: ...

class PropertyCategoryNames:
    """.NET: Autodesk.Navisworks.Api.PropertyCategoryNames"""
    def __init__(self, *args) -> None: ...
    RevitElementId: str
    MicrostationElementId: str
    Microstation: str
    AutoCadEntityHandle: str
    AutoCad: str
    XRef: str
    Hyperlinks: str
    Geometry: str
    Transform: str
    Material: str
    Item: str

class PublishProperties(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.PublishProperties"""
    def __init__(self, *args) -> None: ...
    EmbedDatabaseProperties: bool
    AllowResave: bool
    HasBeenResaved: bool
    DisplayAtPassword: bool
    DisplayOnOpen: bool
    HasPassword: bool
    Keywords: str
    Comments: str
    PublishedFor: str
    Copyright: str
    ExpiryDate: DateTime
    HasExpiryDate: bool
    PublishDate: DateTime
    Publisher: str
    Author: str
    Subject: str
    Title: str
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> PublishProperties: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def RemoveExpiryDate(self, ) -> None: ...
    def RemovePassword(self, ) -> None: ...
    def SetPassword(self, password: str) -> None: ...

class Rotation3D(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Rotation3D"""
    def __init__(self, *args) -> None: ...
    Identity: Rotation3D
    D: float
    C: float
    B: float
    A: float
    IsReadOnly: bool
    Item: float
    IsDisposed: bool
    @staticmethod
    def CreateFromEulerAngles(x: float, y: float, z: float) -> Rotation3D: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Rotation3D: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Invert(self, ) -> Rotation3D: ...
    def IsIdentity(self, ) -> bool: ...
    def Normalize(self, ) -> Rotation3D: ...
    def ToAxisAndAngle(self, ) -> AxisAndAngleResult: ...
    def ToEulerAngles(self, ) -> EulerAngleResult: ...
    def ToString(self, ) -> str: ...
    def TolerantEquals(self, rotation: Rotation3D, tolerance: float) -> bool: ...

class Rule(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Rule"""
    def __init__(self, *args) -> None: ...
    SomeParamsAreSet: bool
    AllParamsAreSet: bool
    IsImplemented: bool
    IsEnabled: bool
    DisplayName: str
    IsReadOnly: bool
    IsDisposed: bool
    def CreateCopy(self, ) -> Rule: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Rule: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    @staticmethod
    def ValueEquals(value1: Rule, value2: Rule) -> bool: ...

class RuleCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.RuleCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: Rule
    IsDisposed: bool
    def Add(self, item: Rule) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: Rule) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def CreateCopy(self, ) -> RuleCollection: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: Rule) -> int: ...
    def Insert(self, index: int, item: Rule) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> RuleCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def MergeInContents(self, source: RuleCollection) -> None: ...
    def Remove(self, item: Rule) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    @staticmethod
    def ValueEquals(value1: RuleCollection, value2: RuleCollection) -> bool: ...

class RuntimeLoaderException(InvalidOperationException):
    """.NET: Autodesk.Navisworks.Api.RuntimeLoaderException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class SavedItem(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.SavedItem"""
    def __init__(self, *args) -> None: ...
    Guid: Guid
    IsGroup: bool
    Parent: GroupItem
    Comments: CommentCollection
    DisplayName: str
    IsReadOnly: bool
    IsDisposed: bool
    def CanTransform(self, ) -> bool: ...
    def CreateCopy(self, ) -> SavedItem: ...
    def CreateNewInstance(self, ) -> SavedItem: ...
    def CreateUniqueCopy(self, ) -> SavedItem: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SavedItem: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def MakeDisplayNameUnique(self, group: GroupItem, salt: str) -> None: ...
    def Transform(self, transform: Transform3D) -> None: ...

class SavedItemChangedAction:
    """.NET: Autodesk.Navisworks.Api.SavedItemChangedAction"""
    def __init__(self, *args) -> None: ...
    ...

class SavedItemChangedEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.SavedItemChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    NewItem: SavedItem
    NewIndex: int
    NewParent: GroupItem
    OldItem: SavedItem
    OldIndex: int
    OldParent: GroupItem
    EditedParts: SavedItemParts
    Action: SavedItemChangedAction

class SavedItemCollection:
    """.NET: Autodesk.Navisworks.Api.SavedItemCollection"""
    def __init__(self, *args) -> None: ...
    Item: SavedItem
    IsReadOnly: bool
    Count: int
    def Add(self, item: SavedItem) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def CanAdd(self, item: SavedItem) -> bool: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: SavedItem) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: SavedItem) -> int: ...
    def IndexOfDisplayName(self, displayName: str) -> int: ...
    def IndexOfGuid(self, value: Guid) -> int: ...
    def Insert(self, index: int, item: SavedItem) -> None: ...
    def InternalGetEnumerator(self, ) -> IEnumerator: ...
    def Remove(self, item: SavedItem) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    def Sort(self, ) -> None: ...
    def SortDescendantsAndSelf(self, ) -> None: ...

class SavedItemParts:
    """.NET: Autodesk.Navisworks.Api.SavedItemParts"""
    def __init__(self, *args) -> None: ...
    ...

class SavedItemReference(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.SavedItemReference"""
    def __init__(self, *args) -> None: ...
    DocumentPartId: str
    SavedItemId: str
    IsNull: bool
    IsReadOnly: bool
    DisplayString: str
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SavedItemReference: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ToString(self, ) -> str: ...

class SavedViewpoint(SavedItem):
    """.NET: Autodesk.Navisworks.Api.SavedViewpoint"""
    def __init__(self, *args) -> None: ...
    Viewpoint: Viewpoint
    IsReadOnly: bool
    ContainsAppearanceOverrides: bool
    ContainsVisibilityOverrides: bool
    Guid: Guid
    IsGroup: bool
    Parent: GroupItem
    Comments: CommentCollection
    DisplayName: str
    IsDisposed: bool
    def GetAppearanceOverrides(self, ) -> AppearanceOverrides: ...
    def GetVisibilityOverrides(self, ) -> VisibilityOverrides: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SavedViewpoint: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class SavedViewpointAnimation(GroupItem):
    """.NET: Autodesk.Navisworks.Api.SavedViewpointAnimation"""
    def __init__(self, *args) -> None: ...
    Loops: bool
    Smoothing: SavedViewpointAnimationSmoothing
    IsReadOnly: bool
    Children: SavedItemCollection
    Guid: Guid
    IsGroup: bool
    Parent: GroupItem
    Comments: CommentCollection
    DisplayName: str
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SavedViewpointAnimation: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class SavedViewpointAnimationCut(SavedItem):
    """.NET: Autodesk.Navisworks.Api.SavedViewpointAnimationCut"""
    def __init__(self, *args) -> None: ...
    Delay: float
    IsReadOnly: bool
    Guid: Guid
    IsGroup: bool
    Parent: GroupItem
    Comments: CommentCollection
    DisplayName: str
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SavedViewpointAnimationCut: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class SavedViewpointAnimationSmoothing:
    """.NET: Autodesk.Navisworks.Api.SavedViewpointAnimationSmoothing"""
    def __init__(self, *args) -> None: ...
    ...

class Search(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Search"""
    def __init__(self, *args) -> None: ...
    IsClear: bool
    Locations: SearchLocations
    PruneBelowMatch: bool
    SearchConditions: SearchConditionCollection
    Selection: Selection
    IsReadOnly: bool
    IsDisposed: bool
    def CanMerge(self, spec: Search) -> bool: ...
    def Clear(self, ) -> None: ...
    def FindAll(self, document: Document, reportProgress: bool) -> ModelItemCollection: ...
    def FindFirst(self, document: Document, reportProgress: bool) -> ModelItem: ...
    def FindIncremental(self, document: Document, reportProgress: bool) -> IEnumerable: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Search: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Merge(self, search: Search) -> None: ...
    def TryMerge(self, search: Search) -> bool: ...
    @staticmethod
    def ValueEquals(value1: Search, value2: Search) -> bool: ...

class SearchCondition(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.SearchCondition"""
    def __init__(self, *args) -> None: ...
    Value: VariantData
    Comparison: SearchConditionComparison
    Options: SearchConditionOptions
    PropertyCombinedName: NamedConstant
    CategoryCombinedName: NamedConstant
    IsReadOnly: bool
    IsDisposed: bool
    def CompareWith(self, comparison: SearchConditionComparison, value: VariantData) -> SearchCondition: ...
    def DisplayStringContains(self, value: str) -> SearchCondition: ...
    def DisplayStringWildcard(self, value: str) -> SearchCondition: ...
    def EqualValue(self, value: VariantData) -> SearchCondition: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def HasCategoryByCombinedName(combinedName: NamedConstant) -> SearchCondition: ...
    @staticmethod
    def HasCategoryByDisplayName(displayName: str) -> SearchCondition: ...
    @staticmethod
    def HasCategoryByName(name: str) -> SearchCondition: ...
    @staticmethod
    def HasPropertyByCombinedName(categoryCombinedName: NamedConstant, propertyCombinedName: NamedConstant) -> SearchCondition: ...
    @staticmethod
    def HasPropertyByDisplayName(categoryDisplayName: str, propertyDisplayName: str) -> SearchCondition: ...
    @staticmethod
    def HasPropertyByName(categoryName: str, propertyName: str) -> SearchCondition: ...
    def IgnoreStringValueAccents(self, ) -> SearchCondition: ...
    def IgnoreStringValueCase(self, ) -> SearchCondition: ...
    def IgnoreStringValueCharWidths(self, ) -> SearchCondition: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SearchCondition: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Negate(self, ) -> SearchCondition: ...
    def SameType(self, type: VariantDataType) -> SearchCondition: ...
    def StartGroup(self, ) -> SearchCondition: ...
    def ToString(self, ) -> str: ...

class SearchConditionCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.SearchConditionCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: SearchCondition
    IsDisposed: bool
    def Add(self, item: SearchCondition) -> None: ...
    def AddGroup(self, from_: IEnumerable) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: SearchCondition) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: SearchCondition) -> int: ...
    def Insert(self, index: int, item: SearchCondition) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SearchConditionCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Remove(self, item: SearchCondition) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...

class SearchConditionComparison:
    """.NET: Autodesk.Navisworks.Api.SearchConditionComparison"""
    def __init__(self, *args) -> None: ...
    ...

class SearchConditionOptions:
    """.NET: Autodesk.Navisworks.Api.SearchConditionOptions"""
    def __init__(self, *args) -> None: ...
    ...

class SearchLocations:
    """.NET: Autodesk.Navisworks.Api.SearchLocations"""
    def __init__(self, *args) -> None: ...
    ...

class Selection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Selection"""
    def __init__(self, *args) -> None: ...
    IsClear: bool
    SelectionSources: SelectionSourceCollection
    HasSelectionSources: bool
    ExplicitSelection: ModelItemCollection
    HasExplicitSelection: bool
    IsReadOnly: bool
    IsDisposed: bool
    def Clear(self, ) -> None: ...
    def CopyFrom(self, from_: ModelItemCollection) -> None: ...
    def GetSelectedItems(self, document: Document) -> ModelItemCollection: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Selection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def SelectAll(self, ) -> None: ...
    @staticmethod
    def ValueEquals(value1: Selection, value2: Selection) -> bool: ...

class SelectionBehavior:
    """.NET: Autodesk.Navisworks.Api.SelectionBehavior"""
    def __init__(self, *args) -> None: ...
    ...

class SelectionSet(SavedItem):
    """.NET: Autodesk.Navisworks.Api.SelectionSet"""
    def __init__(self, *args) -> None: ...
    Search: Search
    HasSearch: bool
    ExplicitModelItems: ModelItemCollection
    HasExplicitModelItems: bool
    IsReadOnly: bool
    Guid: Guid
    IsGroup: bool
    Parent: GroupItem
    Comments: CommentCollection
    DisplayName: str
    IsDisposed: bool
    def CopyFrom(self, search: Search) -> None: ...
    def GetSelectedItems(self, document: Document) -> ModelItemCollection: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SelectionSet: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    @staticmethod
    def ValueEquals(value1: SelectionSet, value2: SelectionSet) -> bool: ...

class SelectionSource(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.SelectionSource"""
    def __init__(self, *args) -> None: ...
    DisplayName: str
    IsReadOnly: bool
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def GetRoot(self, ) -> str: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SelectionSource: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ToString(self, ) -> str: ...
    def TryGetSearch(self, document: Document) -> Search: ...
    def TryGetSelectedItems(self, document: Document) -> ModelItemCollection: ...

class SelectionSourceCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.SelectionSourceCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Item: SelectionSource
    InternalIsReadOnly: bool
    Count: int
    IsDisposed: bool
    def Add(self, item: SelectionSource) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: SelectionSource) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: SelectionSource) -> int: ...
    def Insert(self, index: int, item: SelectionSource) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SelectionSourceCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def InternalGetEnumerator(self, ) -> IEnumerator: ...
    def Remove(self, item: SelectionSource) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    @staticmethod
    def ValueEquals(value1: SelectionSourceCollection, value2: SelectionSourceCollection) -> bool: ...

class SelectionValueEquals:
    """.NET: Autodesk.Navisworks.Api.SelectionValueEquals"""
    def __init__(self, *args) -> None: ...
    def Equals(self, x: Selection, y: Selection) -> bool: ...
    def GetHashCode(self, x: Selection) -> int: ...

class ServerType:
    """.NET: Autodesk.Navisworks.Api.ServerType"""
    def __init__(self, *args) -> None: ...
    ...

class SheetInfo(SavedItem):
    """.NET: Autodesk.Navisworks.Api.SheetInfo"""
    def __init__(self, *args) -> None: ...
    SourceGuid: Guid
    IsLoaded: bool
    Thumbnail: str
    PropertyCategories: InfoPropertyCategoryCollection
    SheetType: SheetType
    Id: str
    IsReadOnly: bool
    Guid: Guid
    IsGroup: bool
    Parent: GroupItem
    Comments: CommentCollection
    DisplayName: str
    IsDisposed: bool
    def CheckIsConvertedForLoad(self, ) -> bool: ...
    def CheckIsConvertedForSearch(self, ) -> bool: ...
    def ContainsMatchingItem(self, item: ModelItem) -> bool: ...
    def CreateUniqueCopy(self, ) -> SheetInfo: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SheetInfo: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class SheetType:
    """.NET: Autodesk.Navisworks.Api.SheetType"""
    def __init__(self, *args) -> None: ...
    ...

class SimulationType:
    """.NET: Autodesk.Navisworks.Api.SimulationType"""
    def __init__(self, *args) -> None: ...
    ...

class StereoBehaviorMode:
    """.NET: Autodesk.Navisworks.Api.StereoBehaviorMode"""
    def __init__(self, *args) -> None: ...
    ...

class TessellationWindingRule:
    """.NET: Autodesk.Navisworks.Api.TessellationWindingRule"""
    def __init__(self, *args) -> None: ...
    ...

class TextExtents2D(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.TextExtents2D"""
    def __init__(self, *args) -> None: ...
    Origin: Point2D
    Bounds: BoundingBox2D
    IsReadOnly: bool
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> TextExtents2D: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ToString(self, ) -> str: ...

class TextFontInfo(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.TextFontInfo"""
    def __init__(self, *args) -> None: ...
    Strikeout: bool
    Italic: bool
    Weight: int
    PointSize: int
    Typeface: str
    IsReadOnly: bool
    IsDisposed: bool
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> TextFontInfo: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ToString(self, ) -> str: ...

class TextFontMetrics(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.TextFontMetrics"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> TextFontMetrics: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class Tool:
    """.NET: Autodesk.Navisworks.Api.Tool"""
    def __init__(self, *args) -> None: ...
    ...

class TooltipResult:
    """.NET: Autodesk.Navisworks.Api.TooltipResult"""
    def __init__(self, *args) -> None: ...
    Id: int
    DisplayName: str

class Transaction:
    """.NET: Autodesk.Navisworks.Api.Transaction"""
    def __init__(self, *args) -> None: ...
    IsCommitted: bool
    IsDisposed: bool
    Document: Document
    DisplayName: str
    def Commit(self, ) -> None: ...
    def Dispose(self, ) -> None: ...

class Transform3D(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Transform3D"""
    def __init__(self, *args) -> None: ...
    Translation: Vector3D
    Linear: Matrix3
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def CreateIdentity() -> Transform3D: ...
    @staticmethod
    def CreateTranslation(translation: Vector3D) -> Transform3D: ...
    def Equals(self, obj: object) -> bool: ...
    def Factor(self, worldCenter: Vector3D) -> Transform3DComponents: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Transform3D: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Inverse(self, ) -> Transform3D: ...
    def IsAffine(self, ) -> bool: ...
    def IsIdentity(self, ) -> bool: ...
    def IsLinear(self, ) -> bool: ...
    def IsRotation(self, ) -> bool: ...
    def IsTranslation(self, ) -> bool: ...
    def IsUniformScale(self, ) -> bool: ...
    @staticmethod
    def Multiply(leftTransform: Transform3D, rightTransform: Transform3D) -> Transform3D: ...
    def ToString(self, ) -> str: ...
    def TolerantEquals(self, transform: Transform3D, tolerance: float) -> bool: ...
    @staticmethod
    def TranslateRight(translation: Vector3D, transform: Transform3D) -> Transform3D: ...

class Transform3DComponents(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Transform3DComponents"""
    def __init__(self, *args) -> None: ...
    Translation: Vector3D
    Rotation: Rotation3D
    ScaleOrientation: Rotation3D
    Scale: Vector3D
    IsReadOnly: bool
    IsDisposed: bool
    def Combine(self, ) -> Transform3D: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Transform3DComponents: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ToString(self, ) -> str: ...

class UnitConversion(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.UnitConversion"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> UnitConversion: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    @staticmethod
    def ScaleFactor(from_: Units, to: Units) -> float: ...

class UnitVector3D(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.UnitVector3D"""
    def __init__(self, *args) -> None: ...
    UnitZ: UnitVector3D
    UnitY: UnitVector3D
    UnitX: UnitVector3D
    IsZero: bool
    Z: float
    Y: float
    X: float
    IsReadOnly: bool
    Item: float
    IsDisposed: bool
    def Add(self, value: float) -> Vector3D: ...
    def Angle(self, vector: UnitVector3D) -> float: ...
    def AngleWithReference(self, vector: UnitVector3D, reference: UnitVector3D) -> float: ...
    def Cross(self, vector: Vector3D) -> Vector3D: ...
    def DirectionEquals(self, vector: Vector3D, tolerance: float) -> bool: ...
    def Divide(self, value: float) -> Vector3D: ...
    def Dot(self, vector: Vector3D) -> float: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> UnitVector3D: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Multiply(self, value: float) -> Vector3D: ...
    def Negate(self, ) -> UnitVector3D: ...
    def Subtract(self, value: float) -> Vector3D: ...
    def ToString(self, ) -> str: ...
    def ToVector3D(self, ) -> Vector3D: ...
    @staticmethod
    def TolerantEquals(vector0: UnitVector3D, vector1: UnitVector3D, tolerance: float) -> bool: ...

class Units:
    """.NET: Autodesk.Navisworks.Api.Units"""
    def __init__(self, *args) -> None: ...
    ...

class UserMessageEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.UserMessageEventArgs"""
    def __init__(self, *args) -> None: ...
    MessageFlags: int
    ExtendedMessage: str
    Message: str
    Category: MessageCenterCategory
    Source: str
    InternalId: str

class VariantData(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.VariantData"""
    def __init__(self, *args) -> None: ...
    IsInt64: bool
    IsNat64: bool
    IsNat32: bool
    IsPoint2D: bool
    IsPoint3D: bool
    IsNamedConstant: bool
    IsDateTime: bool
    IsDisplayString: bool
    IsIdentifierString: bool
    IsBoolean: bool
    IsInt32: bool
    IsDoubleAngle: bool
    IsDoubleVolume: bool
    IsDoubleArea: bool
    IsDoubleLength: bool
    IsDouble: bool
    IsAnyDouble: bool
    IsNone: bool
    DataType: VariantDataType
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def ElementName() -> str: ...
    def Equals(self, obj: object) -> bool: ...
    @staticmethod
    def FromBoolean(value: bool) -> VariantData: ...
    @staticmethod
    def FromDateTime(value: DateTime) -> VariantData: ...
    @staticmethod
    def FromDisplayString(value: str) -> VariantData: ...
    @staticmethod
    def FromDouble(value: float) -> VariantData: ...
    @staticmethod
    def FromDoubleAngle(value: float) -> VariantData: ...
    @staticmethod
    def FromDoubleArea(value: float) -> VariantData: ...
    @staticmethod
    def FromDoubleLength(value: float) -> VariantData: ...
    @staticmethod
    def FromDoubleVolume(value: float) -> VariantData: ...
    @staticmethod
    def FromIdentifierString(value: str) -> VariantData: ...
    @staticmethod
    def FromInt32(value: int) -> VariantData: ...
    @staticmethod
    def FromInt64(value: int) -> VariantData: ...
    @staticmethod
    def FromNamedConstant(value: NamedConstant) -> VariantData: ...
    @staticmethod
    def FromNat32(value: int) -> VariantData: ...
    @staticmethod
    def FromNat64(value: int) -> VariantData: ...
    @staticmethod
    def FromNone() -> VariantData: ...
    @staticmethod
    def FromPoint2D(x: float, y: float) -> VariantData: ...
    @staticmethod
    def FromPoint3D(x: float, y: float, z: float) -> VariantData: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> VariantData: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    @staticmethod
    def ReadFromXml(type_attrib_value: str, element_content_value: str, include_names: bool) -> VariantData: ...
    def ToAnyDouble(self, ) -> float: ...
    def ToBoolean(self, ) -> bool: ...
    def ToDateTime(self, ) -> DateTime: ...
    def ToDisplayString(self, ) -> str: ...
    def ToDouble(self, ) -> float: ...
    def ToDoubleAngle(self, ) -> float: ...
    def ToDoubleArea(self, ) -> float: ...
    def ToDoubleLength(self, ) -> float: ...
    def ToDoubleVolume(self, ) -> float: ...
    def ToIdentifierString(self, ) -> str: ...
    def ToInt32(self, ) -> int: ...
    def ToInt64(self, ) -> int: ...
    def ToNamedConstant(self, ) -> NamedConstant: ...
    def ToNat32(self, ) -> int: ...
    def ToNat64(self, ) -> int: ...
    def ToPoint2D(self, ) -> Point2D: ...
    def ToPoint3D(self, ) -> Point3D: ...
    def ToSerializableString(self, str: str) -> None: ...
    def ToString(self, ) -> str: ...
    @staticmethod
    def XmlAttribName() -> str: ...
    def XmlAttribValue(self, value: str) -> bool: ...
    def XmlElementContent(self, content: str, include_names: bool) -> bool: ...

class VariantDataCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.VariantDataCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: VariantData
    IsDisposed: bool
    def Contains(self, item: VariantData) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: VariantData) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> VariantDataCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class VariantDataType:
    """.NET: Autodesk.Navisworks.Api.VariantDataType"""
    def __init__(self, *args) -> None: ...
    ...

class Vector2D(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Vector2D"""
    def __init__(self, *args) -> None: ...
    UnitY: Vector2D
    UnitX: Vector2D
    Zero: Vector2D
    LengthSquared: float
    Length: float
    IsZero: bool
    Y: float
    X: float
    IsReadOnly: bool
    Item: float
    IsDisposed: bool
    def Add(self, value: float) -> Vector2D: ...
    def Angle(self, vector: Vector2D) -> float: ...
    def AngleWithReference(self, vector: Vector2D, reference: Vector2D) -> float: ...
    def Cross(self, vector: Vector2D) -> float: ...
    def DirectionEquals(self, vector: Vector2D, tolerance: float) -> bool: ...
    def Divide(self, value: float) -> Vector2D: ...
    def Dot(self, vector: Vector2D) -> float: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Vector2D: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Invert(self, ) -> Vector2D: ...
    def Multiply(self, value: float) -> Vector2D: ...
    def Negate(self, ) -> Vector2D: ...
    def Normalize(self, ) -> Vector2D: ...
    def Subtract(self, value: float) -> Vector2D: ...
    def ToPoint2D(self, ) -> Point2D: ...
    def ToString(self, ) -> str: ...
    @staticmethod
    def TolerantEquals(vector0: Vector2D, vector1: Vector2D, tolerance: float) -> bool: ...

class Vector3D(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Vector3D"""
    def __init__(self, *args) -> None: ...
    UnitZ: Vector3D
    UnitY: Vector3D
    UnitX: Vector3D
    Zero: Vector3D
    LengthSquared: float
    Length: float
    IsZero: bool
    Z: float
    Y: float
    X: float
    IsReadOnly: bool
    Item: float
    IsDisposed: bool
    def Add(self, value: float) -> Vector3D: ...
    def Angle(self, vector: Vector3D) -> float: ...
    def AngleWithReference(self, vector: Vector3D, reference: Vector3D) -> float: ...
    def Cross(self, vector: Vector3D) -> Vector3D: ...
    def DirectionEquals(self, vector: UnitVector3D, tolerance: float) -> bool: ...
    def Divide(self, value: float) -> Vector3D: ...
    def Dot(self, vector: Vector3D) -> float: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Vector3D: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Invert(self, ) -> Vector3D: ...
    def Multiply(self, matrix: Matrix3) -> Vector3D: ...
    def Negate(self, ) -> Vector3D: ...
    def Normalize(self, ) -> Vector3D: ...
    def Subtract(self, value: float) -> Vector3D: ...
    def ToColor(self, ) -> Color: ...
    def ToPoint3D(self, ) -> Point3D: ...
    def ToString(self, ) -> str: ...
    @staticmethod
    def TolerantEquals(vector0: Vector3D, vector1: Vector3D, tolerance: float) -> bool: ...

class VertexProperties:
    """.NET: Autodesk.Navisworks.Api.VertexProperties"""
    def __init__(self, *args) -> None: ...
    ...

class View:
    """.NET: Autodesk.Navisworks.Api.View"""
    def __init__(self, *args) -> None: ...
    Height: int
    Width: int
    IsInteractive: bool
    IsDisposed: bool
    Viewer: LcOpKernelExViewer
    Document: Document
    def CopyViewpointFrom(self, viewpoint: Viewpoint, change: ViewChange) -> None: ...
    def CreateViewpointCopy(self, ) -> Viewpoint: ...
    def Dispose(self, ) -> None: ...
    def EndInteractive(self, ) -> None: ...
    def FocusOnCurrentSelection(self, ) -> None: ...
    def GenerateImage(self, style: ImageGenerationStyle, width: int, height: int, maxTimeHint: float, enableSectioning: bool) -> Bitmap: ...
    def GetClippingPlanes(self, ) -> str: ...
    def GetRedlines(self, ) -> str: ...
    def LookFromFrontRightTop(self, ) -> None: ...
    def PickItemFromPoint(self, x: int, y: int, pickingWidth: int, asRendered: bool, pickPrimitives: PickPrimitives) -> PickItemResult: ...
    def PickItemFromRectangle(self, x: int, y: int, width: int, height: int, asRendered: bool, pickPrimitives: PickPrimitives) -> PickItemResult: ...
    def PickItemsFromRectangle(self, x: int, y: int, width: int, height: int, containedOnly: bool, asRendered: bool) -> ModelItemCollection: ...
    def ProjectPoint(self, point: Point3D, sectionClip: bool, frustumClip: bool) -> ProjectionResult: ...
    def RequestDelayedRedraw(self, redrawRequests: ViewRedrawRequests) -> None: ...
    def SetClippingPlanes(self, jsonClipPlaneSet: str) -> None: ...
    def SetRedlines(self, jsonRedlineCollection: str) -> None: ...
    def StartInteractive(self, ) -> None: ...
    def TrySetClippingPlanes(self, jsonClipPlaneSet: str) -> bool: ...
    def TrySetRedlines(self, jsonRedlineCollection: str) -> bool: ...

class ViewChange:
    """.NET: Autodesk.Navisworks.Api.ViewChange"""
    def __init__(self, *args) -> None: ...
    ...

class ViewEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.ViewEventArgs"""
    def __init__(self, *args) -> None: ...
    View: View

class ViewRedrawRequests:
    """.NET: Autodesk.Navisworks.Api.ViewRedrawRequests"""
    def __init__(self, *args) -> None: ...
    ...

class Viewpoint(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Viewpoint"""
    def __init__(self, *args) -> None: ...
    InternalViewpoint: LcNvViewPoint
    ClipPlanes: ClipPlaneSet
    IsReadOnly: bool
    HasViewer: bool
    HasTool: bool
    HasRenderStyle: bool
    HasLighting: bool
    HasWorldUpVector: bool
    HasFocalDistance: bool
    HasLinearSpeed: bool
    HasAngularSpeed: bool
    ViewerCameraMode: CameraMode
    ViewerAvatar: str
    Tool: Tool
    Lighting: ViewpointLighting
    WorldUpVector: UnitVector3D
    RenderStyle: ViewpointRenderStyle
    FocalDistance: float
    AngularSpeed: float
    LinearSpeed: float
    Rotation: Rotation3D
    Projection: ViewpointProjection
    FarPlaneDistance: float
    NearPlaneDistance: float
    ShutterSpeed: float
    ApertureDiameter: float
    HorizontalScale: float
    ImageFit: ViewpointImageFit
    FarDistanceType: ViewpointDistanceType
    FarDistance: float
    NearDistanceType: ViewpointDistanceType
    NearDistance: float
    RightOffsetAtFocalDistance: float
    UpOffsetAtFocalDistance: float
    RightOffsetFactor: float
    UpOffsetFactor: float
    HorizontalExtentAtFocalDistance: float
    VerticalExtentAtFocalDistance: float
    HeightField: float
    AspectRatio: float
    Position: Point3D
    IsDisposed: bool
    def AlignDirection(self, direction: Vector3D) -> None: ...
    def AlignUp(self, up: Vector3D) -> None: ...
    def CreateCopy(self, ) -> Viewpoint: ...
    def GetCamera(self, ) -> str: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Viewpoint: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def PointAt(self, to: Point3D) -> None: ...
    def SetCamera(self, cameraJson: str) -> None: ...
    def SetExtentsAtFocalDistance(self, horizontal: float, vertical: float) -> None: ...
    def TrySetCamera(self, cameraJson: str) -> bool: ...
    def ZoomBox(self, box: BoundingBox3D) -> None: ...

class ViewpointDistanceType:
    """.NET: Autodesk.Navisworks.Api.ViewpointDistanceType"""
    def __init__(self, *args) -> None: ...
    ...

class ViewpointImageFit:
    """.NET: Autodesk.Navisworks.Api.ViewpointImageFit"""
    def __init__(self, *args) -> None: ...
    ...

class ViewpointLighting:
    """.NET: Autodesk.Navisworks.Api.ViewpointLighting"""
    def __init__(self, *args) -> None: ...
    ...

class ViewpointProjection:
    """.NET: Autodesk.Navisworks.Api.ViewpointProjection"""
    def __init__(self, *args) -> None: ...
    ...

class ViewpointRenderStyle:
    """.NET: Autodesk.Navisworks.Api.ViewpointRenderStyle"""
    def __init__(self, *args) -> None: ...
    ...

class ViewpointStereoProjection:
    """.NET: Autodesk.Navisworks.Api.ViewpointStereoProjection"""
    def __init__(self, *args) -> None: ...
    ...

class VisibilityOverrides:
    """.NET: Autodesk.Navisworks.Api.VisibilityOverrides"""
    def __init__(self, *args) -> None: ...
    Hidden: ModelItemCollection
