# Auto-generated — Navisworks 24 — Autodesk.Navisworks.Api.ApplicationParts

class ApplicationAutomation:
    """.NET: Autodesk.Navisworks.Api.ApplicationParts.ApplicationAutomation"""
    def __init__(self, *args) -> None: ...
    def AddPluginAssembly(self, fileName: str) -> None: ...
    def AppendFile(self, fileName: str) -> None: ...
    def CreateCache(self, fileNameToCache: str) -> None: ...
    def DisableProgress(self, ) -> None: ...
    def EnableProgress(self, ) -> None: ...
    def ExecuteAddInPlugin(self, pluginId: str, parameters: list) -> int: ...
    def ExportNWD(self, fileName: str, options: NwdExportOptions) -> None: ...
    def GenerateThumbnail(self, width: int, height: int, fileName: str) -> None: ...
    def GenerateThumbnailByRayTrace(self, width: int, height: int, fileName: str) -> None: ...
    def OpenFile(self, fileName: str, moreFiles: list) -> None: ...
    def Print(self, printer: str, driver: str, port: str) -> None: ...
    def PublishNWD(self, fileName: str, options: NwdExportOptions, properties: PublishProperties) -> None: ...
    def SaveFile(self, fileName: str) -> None: ...

class ApplicationDragDrop:
    """.NET: Autodesk.Navisworks.Api.ApplicationParts.ApplicationDragDrop"""
    def __init__(self, *args) -> None: ...
    Format: str
    def DecodeData(self, data: IDataObject, processId: int) -> bool: ...
    def DecodeDataWpf(self, data: IDataObject, processId: int) -> bool: ...

class ApplicationOptions:
    """.NET: Autodesk.Navisworks.Api.ApplicationParts.ApplicationOptions"""
    def __init__(self, *args) -> None: ...
    Grids: GridsOptions

class ApplicationPlugins:
    """.NET: Autodesk.Navisworks.Api.ApplicationParts.ApplicationPlugins"""
    def __init__(self, *args) -> None: ...
    PluginRecords: ReadOnlyCollection
    def AddPluginAssembly(self, fileName: str) -> None: ...
    def ExecuteAddInPlugin(self, pluginId: str, parameters: list) -> int: ...
    def FindInterfaces(self, interfaceId: str) -> ReadOnlyCollection: ...
    def FindPlugin(self, pluginId: str) -> PluginRecord: ...

class ApplicationResources:
    """.NET: Autodesk.Navisworks.Api.ApplicationParts.ApplicationResources"""
    def __init__(self, *args) -> None: ...
    def GetString(self, name: str) -> str: ...
    def GetStringSafe(self, name: str) -> str: ...
    def TryGetString(self, name: str) -> str: ...

class ApplicationVersion:
    """.NET: Autodesk.Navisworks.Api.ApplicationParts.ApplicationVersion"""
    def __init__(self, *args) -> None: ...
    Build: int
    RuntimeLanguage: str
    RuntimeProductName: str
    Runtime: str
    IsRuntimeBeta: bool
    RuntimeMinor: int
    RuntimeMajor: int
    IsApiStable: bool
    ApiMinor: int
    ApiMajor: int

class IApplicationGui:
    """.NET: Autodesk.Navisworks.Api.ApplicationParts.IApplicationGui"""
    def __init__(self, *args) -> None: ...
    ServerType: ServerType
    SignInUserId: str
    SignInUserName: str
    MainWindow: IWin32Window
    def GetDockPanePluginVisibility(self, pluginId: str) -> bool: ...
    def IsSignedIn(self, ) -> bool: ...
    def SetDockPanePluginActive(self, pluginId: str) -> None: ...
    def SetDockPanePluginVisibility(self, pluginId: str, visible: bool) -> None: ...
    def SetRaiseIdle(self, raiseIdle: Action) -> None: ...
    def SignIn(self, ) -> bool: ...
    def SignOut(self, ) -> bool: ...
