# Auto-generated — Navisworks 24 — Autodesk.Navisworks.Api.ComApi

class ComApiBridge:
    """.NET: Autodesk.Navisworks.Api.ComApi.ComApiBridge"""
    def __init__(self, *args) -> None: ...
    State: InwOpState10
    @staticmethod
    def ToInwOaPath(modelItem: ModelItem) -> InwOaPath: ...
    @staticmethod
    def ToInwOpAnonView(viewpoint: Viewpoint) -> InwOpAnonView: ...
    @staticmethod
    def ToInwOpSelection(modelItemCollection: ModelItemCollection) -> InwOpSelection: ...
    @staticmethod
    def ToModelItem(path: InwOaPath) -> ModelItem: ...
    @staticmethod
    def ToModelItemCollection(selection: InwOpSelection) -> ModelItemCollection: ...
    @staticmethod
    def ToViewpoint(anonView: InwOpAnonView) -> Viewpoint: ...
