# Auto-generated — Navisworks 24 — Autodesk.Navisworks.Api.Data

class DatabaseActionType:
    """.NET: Autodesk.Navisworks.Api.Data.DatabaseActionType"""
    def __init__(self, *args) -> None: ...
    ...

class DatabaseChange:
    """.NET: Autodesk.Navisworks.Api.Data.DatabaseChange"""
    def __init__(self, *args) -> None: ...
    RowId: int
    ChangedType: DatabaseChangeTypes
    TableName: str

class DatabaseChangeCollection:
    """.NET: Autodesk.Navisworks.Api.Data.DatabaseChangeCollection"""
    def __init__(self, *args) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def InternalGetEnumerator(self, ) -> IEnumerator: ...
    def ToString(self, ) -> str: ...
    def Where(self, tableNames: str, changeType: DatabaseChangeTypes) -> IEnumerable: ...

class DatabaseChangeTypes:
    """.NET: Autodesk.Navisworks.Api.Data.DatabaseChangeTypes"""
    def __init__(self, *args) -> None: ...
    ...

class DatabaseChangedAction:
    """.NET: Autodesk.Navisworks.Api.Data.DatabaseChangedAction"""
    def __init__(self, *args) -> None: ...
    ...

class DatabaseChangedEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.Data.DatabaseChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    Changes: DatabaseChangeCollection
    ActionType: DatabaseActionType
    Action: DatabaseChangedAction

class DatabaseException(InvalidOperationException):
    """.NET: Autodesk.Navisworks.Api.Data.DatabaseException"""
    def __init__(self, *args) -> None: ...
    ErrorCode: int
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class ModelTransformEventArgs(EventArgs):
    """.NET: Autodesk.Navisworks.Api.Data.ModelTransformEventArgs"""
    def __init__(self, *args) -> None: ...
    AllowChange: bool
    GetSourceIsUI: bool
    Model: Model
    LinearUnits: Units
    TransformReverses: bool
    Transform: Transform3D

class NavisWorksDataReader(DbDataReader):
    """.NET: Autodesk.Navisworks.Api.Data.NavisWorksDataReader"""
    def __init__(self, *args) -> None: ...
    Item: object
    Item: object
    RecordsAffected: int
    IsClosed: bool
    HasRows: bool
    FieldCount: int
    Depth: int
    VisibleFieldCount: int
    def Close(self, ) -> None: ...
    def GetBoolean(self, ordinal: int) -> bool: ...
    def GetByte(self, ordinal: int) -> int: ...
    def GetBytes(self, ordinal: int, dataOffset: int, buffer: list, bufferOffset: int, length: int) -> int: ...
    def GetChar(self, ordinal: int) -> str: ...
    def GetChars(self, ordinal: int, dataOffset: int, buffer: list, bufferOffset: int, length: int) -> int: ...
    def GetDataTypeName(self, ordinal: int) -> str: ...
    def GetDateTime(self, ordinal: int) -> DateTime: ...
    def GetDecimal(self, ordinal: int) -> Decimal: ...
    def GetDouble(self, ordinal: int) -> float: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetFieldType(self, ordinal: int) -> Type: ...
    def GetFloat(self, ordinal: int) -> float: ...
    def GetGuid(self, ordinal: int) -> Guid: ...
    def GetInt16(self, ordinal: int) -> int: ...
    def GetInt32(self, ordinal: int) -> int: ...
    def GetInt64(self, ordinal: int) -> int: ...
    def GetName(self, ordinal: int) -> str: ...
    def GetOrdinal(self, name: str) -> int: ...
    def GetSchemaTable(self, ) -> DataTable: ...
    def GetString(self, ordinal: int) -> str: ...
    def GetValue(self, ordinal: int) -> object: ...
    def GetValues(self, values: list) -> int: ...
    def IsDBNull(self, ordinal: int) -> bool: ...
    def NextResult(self, ) -> bool: ...
    def Read(self, ) -> bool: ...

class NavisworksCommand(DbCommand):
    """.NET: Autodesk.Navisworks.Api.Data.NavisworksCommand"""
    def __init__(self, *args) -> None: ...
    Parameters: NavisworksParameterCollection
    Connection: NavisworksConnection
    UpdatedRowSource: UpdateRowSource
    DesignTimeVisible: bool
    CommandType: CommandType
    CommandTimeout: int
    CommandText: str
    Connection: DbConnection
    Parameters: DbParameterCollection
    Transaction: DbTransaction
    Site: ISite
    Container: IContainer
    def Cancel(self, ) -> None: ...
    def CreateParameter(self, ) -> NavisworksParameter: ...
    def ExecuteNonQuery(self, ) -> int: ...
    def ExecuteReader(self, behavior: CommandBehavior) -> NavisWorksDataReader: ...
    def ExecuteScalar(self, ) -> object: ...
    def Prepare(self, ) -> None: ...

class NavisworksConnection(DbConnection):
    """.NET: Autodesk.Navisworks.Api.Data.NavisworksConnection"""
    def __init__(self, *args) -> None: ...
    State: ConnectionState
    ServerVersion: str
    Database: str
    DataSource: str
    ConnectionString: str
    ConnectionTimeout: int
    Site: ISite
    Container: IContainer
    def BeginDbTransaction(self, A_0: IsolationLevel) -> DbTransaction: ...
    def ChangeDatabase(self, databaseName: str) -> None: ...
    def Close(self, ) -> None: ...
    def CreateCommand(self, ) -> NavisworksCommand: ...
    def GetSchema(self, collectionName: str, restrictionValues: list) -> DataTable: ...
    def InternalGetConnection(self, ) -> LcUSQLiteConnection: ...
    def Open(self, ) -> None: ...

class NavisworksDataAdapter(DbDataAdapter):
    """.NET: Autodesk.Navisworks.Api.Data.NavisworksDataAdapter"""
    def __init__(self, *args) -> None: ...
    UpdateCommand: NavisworksCommand
    DeleteCommand: NavisworksCommand
    InsertCommand: NavisworksCommand
    SelectCommand: NavisworksCommand
    DeleteCommand: DbCommand
    InsertCommand: DbCommand
    SelectCommand: DbCommand
    UpdateBatchSize: int
    UpdateCommand: DbCommand
    AcceptChangesDuringFill: bool
    AcceptChangesDuringUpdate: bool
    ContinueUpdateOnError: bool
    FillLoadOption: LoadOption
    MissingMappingAction: MissingMappingAction
    MissingSchemaAction: MissingSchemaAction
    ReturnProviderSpecificTypes: bool
    TableMappings: DataTableMappingCollection
    Site: ISite
    Container: IContainer
    def Update(self, dt: DataSet, datatable_name: str) -> int: ...

class NavisworksParameter(DbParameter):
    """.NET: Autodesk.Navisworks.Api.Data.NavisworksParameter"""
    def __init__(self, *args) -> None: ...
    Value: object
    SourceVersion: DataRowVersion
    SourceColumnNullMapping: bool
    SourceColumn: str
    Size: int
    ParameterName: str
    IsNullable: bool
    Direction: ParameterDirection
    DbType: DbType
    Precision: int
    Scale: int
    def ResetDbType(self, ) -> None: ...

class NavisworksParameterCollection(DbParameterCollection):
    """.NET: Autodesk.Navisworks.Api.Data.NavisworksParameterCollection"""
    def __init__(self, *args) -> None: ...
    Item: NavisworksParameter
    Item: NavisworksParameter
    SyncRoot: object
    IsSynchronized: bool
    IsReadOnly: bool
    IsFixedSize: bool
    Count: int
    Item: DbParameter
    Item: DbParameter
    def Add(self, parameter: NavisworksParameter) -> int: ...
    def AddRange(self, values: Array) -> None: ...
    def AddWithValue(self, parameterName: str, value: object) -> NavisworksParameter: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: str) -> bool: ...
    def CopyTo(self, values: Array, index: int) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, parameterName: str) -> int: ...
    def Insert(self, index: int, value: object) -> None: ...
    def Remove(self, value: object) -> None: ...
    def RemoveAt(self, parameterName: str) -> None: ...

class NavisworksTransaction(DbTransaction):
    """.NET: Autodesk.Navisworks.Api.Data.NavisworksTransaction"""
    def __init__(self, *args) -> None: ...
    Connection: NavisworksConnection
    IsolationLevel: IsolationLevel
    Connection: DbConnection
    def Commit(self, ) -> None: ...
    def Rollback(self, ) -> None: ...
