# Auto-generated — Navisworks 24 — Autodesk.Navisworks.Api.DocumentParts

class DocumentAlignments:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentAlignments"""
    def __init__(self, *args) -> None: ...
    ActiveAlignmentIndex: int
    Enabled: bool
    def Any(self, ) -> bool: ...
    def GetAlignments(self, ) -> IEnumerable: ...

class DocumentCurrentComments:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentCurrentComments"""
    def __init__(self, *args) -> None: ...
    Value: CommentCollection
    def CreateCopy(self, ) -> CommentCollection: ...
    def ToCommentCollection(self, ) -> CommentCollection: ...

class DocumentCurrentMeasurement:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentCurrentMeasurement"""
    def __init__(self, *args) -> None: ...
    CanConvertToRedlines: bool
    Tool: Tool
    Difference: Vector3D
    HasDifference: bool
    EndPoint: Point3D
    HasEndPoint: bool
    FirstPoint: Point3D
    HasFirstPoint: bool
    ToolMeasurementType: MeasurementType
    MeasurementType: MeasurementType
    MeasurementValue: float
    HasMeasurement: bool
    def AddRedlinesToCurrentSavedViewpoint(self, ) -> None: ...

class DocumentCurrentSearch:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentCurrentSearch"""
    def __init__(self, *args) -> None: ...
    IsClear: bool
    Value: Search
    def Clear(self, ) -> None: ...
    def CopyFrom(self, search: Search) -> None: ...
    def CreateCopy(self, ) -> Search: ...
    def ToSearch(self, ) -> Search: ...

class DocumentCurrentSelection:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentCurrentSelection"""
    def __init__(self, *args) -> None: ...
    IsEmpty: bool
    SelectedItems: ModelItemCollection
    Value: Selection
    def Add(self, item: ModelItem) -> None: ...
    def AddRange(self, range: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CreateCopy(self, ) -> Selection: ...
    def Remove(self, item: ModelItem) -> None: ...
    def SelectAll(self, ) -> None: ...
    def ToSelection(self, ) -> Selection: ...

class DocumentCurrentViewpoint:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentCurrentViewpoint"""
    def __init__(self, *args) -> None: ...
    Value: Viewpoint
    def CopyFrom(self, viewpoint: Viewpoint) -> None: ...
    def CreateCopy(self, ) -> Viewpoint: ...
    def ToViewpoint(self, ) -> Viewpoint: ...

class DocumentDatabase:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentDatabase"""
    def __init__(self, *args) -> None: ...
    ExistLiveTransaction: bool
    Value: NavisworksConnection
    def BeginTransaction(self, action: DatabaseChangedAction) -> NavisworksTransaction: ...
    def Dispose(self, ) -> None: ...
    def EnableTableUndoable(self, tableName: str) -> None: ...
    def ToNavisworksConnection(self, ) -> NavisworksConnection: ...

class DocumentGrids:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentGrids"""
    def __init__(self, *args) -> None: ...
    Systems: GridSystemCollection
    RenderMode: GridsRenderMode
    ActiveSystem: GridSystem
    def SetSystemLockedLevel(self, system: GridSystem, level: GridLevel) -> None: ...

class DocumentHyperlinks:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentHyperlinks"""
    def __init__(self, *args) -> None: ...
    def DeleteHyperlinks(self, modelItem: ModelItem) -> None: ...
    def GetHyperlinks(self, modelItem: ModelItem) -> HyperlinkCollection: ...
    def ResetAllHyperlinks(self, ) -> None: ...
    def ResetHyperlinks(self, modelItem: ModelItem) -> None: ...
    def SetHyperlinks(self, modelItem: ModelItem, links: HyperlinkCollection) -> None: ...

class DocumentInfoPart:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentInfoPart"""
    def __init__(self, *args) -> None: ...
    Value: DocumentInfo
    def AddCopy(self, parent: GroupItem, item: SavedItem) -> None: ...
    def AddUniqueCopy(self, item: SavedItem, sourceFileName: str) -> None: ...
    def CreateCopy(self, ) -> DocumentInfo: ...
    def EditDisplayName(self, item: SavedItem, newDisplayName: str) -> None: ...
    def InsertCopy(self, parent: GroupItem, index: int, item: SavedItem) -> None: ...
    def InsertUniqueCopy(self, parent: GroupItem, index: int, item: SavedItem, sourceFileName: str) -> None: ...
    def Move(self, oldParent: GroupItem, oldIndex: int, newParent: GroupItem, newIndex: int) -> None: ...
    def Remove(self, parent: GroupItem, item: SavedItem) -> bool: ...
    def RemoveAt(self, parent: GroupItem, index: int) -> None: ...
    def ReplaceWithCopy(self, parent: GroupItem, index: int, item: SavedItem) -> None: ...
    def ToDocumentInfo(self, ) -> DocumentInfo: ...

class DocumentModels:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentModels"""
    def __init__(self, *args) -> None: ...
    First: Model
    RootItemDescendants: ModelItemEnumerableCollection
    RootItemDescendantsAndSelf: ModelItemEnumerableCollection
    RootItems: ModelItemEnumerableCollection
    Item: Model
    IsReadOnly: bool
    Count: int
    def Contains(self, item: Model) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def CreateCollection(self, ) -> ModelItemCollection: ...
    def CreateCollectionFromRootItems(self, ) -> ModelItemCollection: ...
    def CreateIndexPath(self, item: ModelItem) -> Collection: ...
    def CreatePathId(self, item: ModelItem) -> ModelItemPathId: ...
    def FindIdForModelItem(self, item: ModelItem) -> int: ...
    def FindModelItemsById(self, modelIndex: int, id: int) -> ModelItemCollection: ...
    def GetAllHiddenAtModelState(self, ) -> ModelItemCollection: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: Model) -> int: ...
    def InternalAdd(self, model: Model) -> None: ...
    def InternalClear(self, ) -> None: ...
    def InternalGetEnumerator(self, ) -> IEnumerator: ...
    def InternalInsert(self, index: int, item: Model) -> None: ...
    def InternalRemove(self, item: Model) -> bool: ...
    def InternalRemoveAt(self, index: int) -> None: ...
    def IsFrozen(self, items: IEnumerable) -> bool: ...
    def IsHidden(self, items: IEnumerable) -> bool: ...
    def IsRequired(self, items: IEnumerable) -> bool: ...
    def MakeVisible(self, items: IEnumerable) -> None: ...
    def OverridePermanentColor(self, items: IEnumerable, color: Color) -> None: ...
    def OverridePermanentTransform(self, items: IEnumerable, transform: Transform3D, updateModelTransform: bool) -> None: ...
    def OverridePermanentTransparency(self, items: IEnumerable, transparency: float) -> None: ...
    def OverrideTemporaryColor(self, items: IEnumerable, color: Color) -> None: ...
    def OverrideTemporaryTransparency(self, items: IEnumerable, transparency: float) -> None: ...
    def ResetAllFrozen(self, ) -> None: ...
    def ResetAllHidden(self, ) -> None: ...
    def ResetAllHiddenToModelState(self, ) -> None: ...
    def ResetAllPermanentMaterials(self, ) -> None: ...
    def ResetAllPermanentTransforms(self, ) -> None: ...
    def ResetAllRequired(self, ) -> None: ...
    def ResetAllTemporaryMaterials(self, ) -> None: ...
    def ResetPermanentMaterials(self, items: IEnumerable) -> None: ...
    def ResetPermanentTransform(self, items: IEnumerable) -> None: ...
    def ResetTemporaryMaterials(self, items: IEnumerable) -> None: ...
    def ResolveIndexPath(self, path: IEnumerable) -> ModelItem: ...
    def ResolvePathId(self, pathId: ModelItemPathId) -> ModelItem: ...
    def SetFrozen(self, items: IEnumerable, value: bool) -> None: ...
    def SetHidden(self, items: IEnumerable, value: bool) -> None: ...
    def SetModelUnitsAndTransform(self, model: Model, units: Units, transform: Transform3D, transformReflected: bool) -> None: ...
    def SetRequired(self, items: IEnumerable, value: bool) -> None: ...

class DocumentSavedViewpoints:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentSavedViewpoints"""
    def __init__(self, *args) -> None: ...
    CurrentSavedViewpoint: SavedItem
    RootItem: FolderItem
    Value: SavedItemCollection
    Id: str
    def AddComment(self, item: SavedItem, comment: Comment) -> None: ...
    def AddCopy(self, parent: GroupItem, item: SavedItem) -> None: ...
    def CaptureRuntimeOverrides(self, ) -> SavedViewpoint: ...
    def Clear(self, ) -> None: ...
    def CopyFrom(self, value: SavedItemCollection) -> None: ...
    def CreateCopy(self, ) -> Collection: ...
    def CreateIndexPath(self, item: SavedItem) -> Collection: ...
    def CreateReference(self, item: SavedItem) -> SavedItemReference: ...
    def EditComments(self, item: SavedItem, newComments: CommentCollection) -> None: ...
    def EditDisplayName(self, item: SavedItem, newDisplayName: str) -> None: ...
    def InsertCopy(self, parent: GroupItem, index: int, item: SavedItem) -> None: ...
    def Move(self, oldParent: GroupItem, oldIndex: int, newParent: GroupItem, newIndex: int) -> None: ...
    def Remove(self, parent: GroupItem, item: SavedItem) -> bool: ...
    def RemoveAt(self, parent: GroupItem, index: int) -> None: ...
    def ReplaceFromCurrentView(self, savedViewpoint: SavedViewpoint) -> None: ...
    def ReplaceWithCopy(self, parent: GroupItem, index: int, item: SavedItem) -> None: ...
    def ResolveGuid(self, value: Guid) -> SavedItem: ...
    def ResolveIndexPath(self, path: IEnumerable) -> SavedItem: ...
    def ResolveReference(self, reference: SavedItemReference) -> SavedItem: ...
    def ToSavedItemCollection(self, ) -> SavedItemCollection: ...

class DocumentSelectionSets:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentSelectionSets"""
    def __init__(self, *args) -> None: ...
    RootItem: FolderItem
    Value: SavedItemCollection
    Id: str
    def AddComment(self, item: SavedItem, comment: Comment) -> None: ...
    def AddCopy(self, parent: GroupItem, item: SavedItem) -> None: ...
    def Clear(self, ) -> None: ...
    def CopyFrom(self, value: SavedItemCollection) -> None: ...
    def CreateCopy(self, ) -> Collection: ...
    def CreateIndexPath(self, item: SavedItem) -> Collection: ...
    def CreateReference(self, item: SavedItem) -> SavedItemReference: ...
    def CreateSelectionSource(self, item: SavedItem) -> SelectionSource: ...
    def EditComments(self, item: SavedItem, newComments: CommentCollection) -> None: ...
    def EditDisplayName(self, item: SavedItem, newDisplayName: str) -> None: ...
    def InsertCopy(self, parent: GroupItem, index: int, item: SavedItem) -> None: ...
    def Move(self, oldParent: GroupItem, oldIndex: int, newParent: GroupItem, newIndex: int) -> None: ...
    def Remove(self, parent: GroupItem, item: SavedItem) -> bool: ...
    def RemoveAt(self, parent: GroupItem, index: int) -> None: ...
    def ReplaceWithCopy(self, parent: GroupItem, index: int, item: SavedItem) -> None: ...
    def ResolveGuid(self, value: Guid) -> SavedItem: ...
    def ResolveIndexPath(self, path: IEnumerable) -> SavedItem: ...
    def ResolveReference(self, reference: SavedItemReference) -> SavedItem: ...
    def ResolveSelectionSource(self, source: SelectionSource) -> SavedItem: ...
    def ToSavedItemCollection(self, ) -> SavedItemCollection: ...

class DocumentTool:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.DocumentTool"""
    def __init__(self, *args) -> None: ...
    CustomToolPluginId: str
    Value: Tool
    def Set(self, tool: Tool) -> None: ...
    def SetCustomToolPlugin(self, toolPlugin: ToolPlugin) -> None: ...
    def ToTool(self, ) -> Tool: ...

class IDocumentClash:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.IDocumentClash"""
    def __init__(self, *args) -> None: ...
    ...

class IDocumentTakeoff:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.IDocumentTakeoff"""
    def __init__(self, *args) -> None: ...
    ...

class IDocumentTimeliner:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.IDocumentTimeliner"""
    def __init__(self, *args) -> None: ...
    ...

class ModelItemPathId:
    """.NET: Autodesk.Navisworks.Api.DocumentParts.ModelItemPathId"""
    def __init__(self, *args) -> None: ...
    PathId: str
    ModelIndex: int
