# Auto-generated — Navisworks 24 — Autodesk.Navisworks.Api.Schema

class BooleanField(SimpleField):
    """.NET: Autodesk.Navisworks.Api.Schema.BooleanField"""
    def __init__(self, *args) -> None: ...
    DefaultValue: bool
    IsReadOnly: bool
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsDisposed: bool
    def GetValue(self, accessor: ReadAccessor) -> bool: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> BooleanField: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def SetValue(self, accessor: EditAccessor, value: bool) -> None: ...

class ComplexField(Field):
    """.NET: Autodesk.Navisworks.Api.Schema.ComplexField"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> ComplexField: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class ConceptCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Schema.ConceptCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: str
    IsDisposed: bool
    def Add(self, item: str) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: str) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: str) -> int: ...
    def Insert(self, index: int, item: str) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> ConceptCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Remove(self, item: str) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...

class DoubleField(SimpleField):
    """.NET: Autodesk.Navisworks.Api.Schema.DoubleField"""
    def __init__(self, *args) -> None: ...
    UnitGroup: UnitGroup
    DefaultValue: float
    IsReadOnly: bool
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsDisposed: bool
    def GetValue(self, accessor: ReadAccessor) -> float: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> DoubleField: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def SetValue(self, accessor: EditAccessor, value: float) -> None: ...

class EditAccessor(ReadAccessor):
    """.NET: Autodesk.Navisworks.Api.Schema.EditAccessor"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> EditAccessor: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class Field(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Schema.Field"""
    def __init__(self, *args) -> None: ...
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Field: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    @staticmethod
    def ValueEquals(value1: Field, value2: Field) -> bool: ...

class FieldCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Schema.FieldCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: Field
    IsDisposed: bool
    def Add(self, item: Field) -> None: ...
    def AddRange(self, from_: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: Field) -> bool: ...
    def CopyFrom(self, from_: IEnumerable) -> None: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: Field) -> int: ...
    def Insert(self, index: int, item: Field) -> None: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> FieldCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def Remove(self, item: Field) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...

class GroupField(ComplexField):
    """.NET: Autodesk.Navisworks.Api.Schema.GroupField"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GroupField: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class GuidField(SimpleField):
    """.NET: Autodesk.Navisworks.Api.Schema.GuidField"""
    def __init__(self, *args) -> None: ...
    TargetConcept: str
    OwnershipSemantics: GuidFieldOwnershipType
    DefaultValue: Guid
    IsReadOnly: bool
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsDisposed: bool
    def GetValue(self, accessor: ReadAccessor) -> Guid: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> GuidField: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def SetValue(self, accessor: EditAccessor, value: Guid) -> None: ...

class GuidFieldOwnershipType:
    """.NET: Autodesk.Navisworks.Api.Schema.GuidFieldOwnershipType"""
    def __init__(self, *args) -> None: ...
    ...

class Int32Field(SimpleField):
    """.NET: Autodesk.Navisworks.Api.Schema.Int32Field"""
    def __init__(self, *args) -> None: ...
    DefaultValue: int
    IsReadOnly: bool
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsDisposed: bool
    def GetValue(self, accessor: ReadAccessor) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> Int32Field: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def SetValue(self, accessor: EditAccessor, value: int) -> None: ...

class ReadAccessor(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Schema.ReadAccessor"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> ReadAccessor: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def IsValid(self, instance: SchemaData) -> bool: ...

class SchemaBuilder(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Schema.SchemaBuilder"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    def AddConcept(self, concpt: str) -> None: ...
    def AddField(self, field: Field) -> None: ...
    def BuildDefinition(self, ) -> SchemaDefinition: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SchemaBuilder: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class SchemaData(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Schema.SchemaData"""
    def __init__(self, *args) -> None: ...
    EditAccessor: EditAccessor
    ReadAccessor: ReadAccessor
    Definition: SchemaDefinition
    IsReadOnly: bool
    IsDisposed: bool
    def Copy(self, ) -> SchemaData: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SchemaData: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def ValueCompares(self, rhs: SchemaData) -> int: ...
    @staticmethod
    def ValueEquals(value1: SchemaData, value2: SchemaData) -> bool: ...

class SchemaDefinition(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Schema.SchemaDefinition"""
    def __init__(self, *args) -> None: ...
    Fields: FieldCollection
    Concepts: ConceptCollection
    IsReadOnly: bool
    IsDisposed: bool
    def CreateData(self, ) -> SchemaData: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SchemaDefinition: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    @staticmethod
    def ValueEquals(value1: SchemaDefinition, value2: SchemaDefinition) -> bool: ...

class SchemaDefinitionCollection(NativeHandle):
    """.NET: Autodesk.Navisworks.Api.Schema.SchemaDefinitionCollection"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Count: int
    Item: SchemaDefinition
    IsDisposed: bool
    def Contains(self, item: SchemaDefinition) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: SchemaDefinition) -> int: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SchemaDefinitionCollection: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class SimpleField(Field):
    """.NET: Autodesk.Navisworks.Api.Schema.SimpleField"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> SimpleField: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class StringField(SimpleField):
    """.NET: Autodesk.Navisworks.Api.Schema.StringField"""
    def __init__(self, *args) -> None: ...
    DefaultValue: str
    IsReadOnly: bool
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsDisposed: bool
    def GetValue(self, accessor: ReadAccessor) -> str: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> StringField: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def SetValue(self, accessor: EditAccessor, value: str) -> None: ...

class StructField(GroupField):
    """.NET: Autodesk.Navisworks.Api.Schema.StructField"""
    def __init__(self, *args) -> None: ...
    Fields: FieldCollection
    IsReadOnly: bool
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsDisposed: bool
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> StructField: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...

class UnitGroup:
    """.NET: Autodesk.Navisworks.Api.Schema.UnitGroup"""
    def __init__(self, *args) -> None: ...
    ...

class VectorField(ComplexField):
    """.NET: Autodesk.Navisworks.Api.Schema.VectorField"""
    def __init__(self, *args) -> None: ...
    CollectionType: VectorFieldCollectionType
    ValueField: Field
    IsReadOnly: bool
    Concepts: ConceptCollection
    DisplayNameId: str
    Id: str
    IsDisposed: bool
    def GetCount(self, accessor: ReadAccessor) -> int: ...
    def GetIndexAccessor(self, accessor: EditAccessor, index: int) -> EditAccessor: ...
    @staticmethod
    def InternalCreator(handleIn: IntPtr, ownership: NativeHandleOwnership, parent: NativeHandle) -> VectorField: ...
    @staticmethod
    def InternalFactory(reserved: NativeHandleInit) -> NativeHandle: ...
    def SetCount(self, accessor: EditAccessor, count: int) -> None: ...

class VectorFieldCollectionType:
    """.NET: Autodesk.Navisworks.Api.Schema.VectorFieldCollectionType"""
    def __init__(self, *args) -> None: ...
    ...
