# Auto-generated — Civil 26 — Autodesk.AutoCAD.Colors

class Color(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Colors.Color"""
    def __init__(self, *args) -> None: ...
    DictionaryKey: str
    DictionaryKeyLength: int
    EntityColor: EntityColor
    HasBookName: bool
    HasColorName: bool
    ColorNameForDisplay: str
    BookName: str
    ColorName: str
    PenIndex: int
    ColorIndex: int
    Blue: int
    Green: int
    Red: int
    IsNone: bool
    IsForeground: bool
    IsByPen: bool
    IsByAci: bool
    IsByBlock: bool
    IsByLayer: bool
    IsByColor: bool
    Explanation: str
    Description: str
    ColorMethod: ColorMethod
    ColorValue: Color
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Audit(self, auditInfo: AuditInfo) -> None: ...
    def Clone(self, ) -> object: ...
    def CompareTo(self, obj: object) -> int: ...
    @staticmethod
    def DwgIn(inputFiler: DwgFiler) -> Color: ...
    def DwgOut(self, outputFiler: DwgFiler) -> None: ...
    @staticmethod
    def DxfIn(inputFiler: DxfFiler, groupCodeOffset: int) -> Color: ...
    def DxfOut(self, outputFiler: DxfFiler, groupCodeOffset: int) -> None: ...
    def Equals(self, obj: object) -> bool: ...
    @staticmethod
    def FromColor(value: Color) -> Color: ...
    @staticmethod
    def FromColorIndex(colorMethod: ColorMethod, colorIndex: int) -> Color: ...
    @staticmethod
    def FromDictionaryName(name: str) -> Color: ...
    @staticmethod
    def FromEntityColor(eclr: EntityColor) -> Color: ...
    @staticmethod
    def FromNames(colorName: str, bookName: str) -> Color: ...
    @staticmethod
    def FromRgb(red: int, green: int, blue: int) -> Color: ...
    @staticmethod
    def GetColorValue(colorIndex: int, backgroundColor: Color) -> Color: ...
    def GetHashCode(self, ) -> int: ...
    def ToString(self, provider: IFormatProvider) -> str: ...

class ColorConverter(TypeConverter):
    """.NET: Autodesk.AutoCAD.Colors.ColorConverter"""
    def __init__(self, *args) -> None: ...
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object) -> object: ...
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object, destinationType: Type) -> object: ...

class ColorMethod:
    """.NET: Autodesk.AutoCAD.Colors.ColorMethod"""
    def __init__(self, *args) -> None: ...
    ...

class EntityColor:
    """.NET: Autodesk.AutoCAD.Colors.EntityColor"""
    def __init__(self, *args) -> None: ...
    IsLayerFrozenOrOff: bool
    IsNone: bool
    IsLayerFrozen: bool
    IsLayerOff: bool
    IsForeground: bool
    IsByPen: bool
    IsByAci: bool
    IsByBlock: bool
    IsByLayer: bool
    IsByColor: bool
    Blue: int
    Green: int
    Red: int
    PenIndex: int
    LayerIndex: int
    ColorIndex: int
    TrueColor: int
    ColorMethod: ColorMethod
    @staticmethod
    def LookUpAci(red: int, green: int, blue: int) -> int: ...
    @staticmethod
    def LookUpRgb(colorIndex: int) -> int: ...

class EntityColorCollection:
    """.NET: Autodesk.AutoCAD.Colors.EntityColorCollection"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: EntityColor
    IsReadOnly: bool
    IsFixedSize: bool
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: EntityColor) -> int: ...
    def AddRange(self, range: list) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: EntityColor) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> EntityColorCollectionEnumerator: ...
    def IndexOf(self, value: EntityColor) -> int: ...
    def Insert(self, index: int, value: EntityColor) -> None: ...
    def Remove(self, value: EntityColor) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimToSize(self, ) -> None: ...

class EntityColorCollectionEnumerator:
    """.NET: Autodesk.AutoCAD.Colors.EntityColorCollectionEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: EntityColor
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class Transparency:
    """.NET: Autodesk.AutoCAD.Colors.Transparency"""
    def __init__(self, *args) -> None: ...
    IsSolid: bool
    IsClear: bool
    IsInvalid: bool
    IsByLayer: bool
    IsByBlock: bool
    IsByAlpha: bool
    Alpha: int
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def ToString(self, provider: IFormatProvider) -> str: ...

class TransparencyCollection:
    """.NET: Autodesk.AutoCAD.Colors.TransparencyCollection"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: Transparency
    IsReadOnly: bool
    IsFixedSize: bool
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: Transparency) -> int: ...
    def AddRange(self, range: list) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Transparency) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> TransparencyCollectionEnumerator: ...
    def IndexOf(self, value: Transparency) -> int: ...
    def Insert(self, index: int, value: Transparency) -> None: ...
    def Remove(self, value: Transparency) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimToSize(self, ) -> None: ...

class TransparencyCollectionEnumerator:
    """.NET: Autodesk.AutoCAD.Colors.TransparencyCollectionEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: Transparency
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class TransparencyMethod:
    """.NET: Autodesk.AutoCAD.Colors.TransparencyMethod"""
    def __init__(self, *args) -> None: ...
    ...
