# Auto-generated — Civil 26 — Autodesk.AutoCAD.ComponentModel

class IPropertyProvider:
    """.NET: Autodesk.AutoCAD.ComponentModel.IPropertyProvider"""
    def __init__(self, *args) -> None: ...
    def GetProperties(self, instance: object) -> PropertyDescriptorCollection: ...

class ITypeDescriptor:
    """.NET: Autodesk.AutoCAD.ComponentModel.ITypeDescriptor"""
    def __init__(self, *args) -> None: ...
    HasPerInstancePropertyProviders: bool
    def AddPerInstancePropertyProvider(self, pp: IPropertyProvider) -> None: ...
    def AddProperty(self, prop: PropertyDescriptor) -> None: ...
    def GetPerInstancePropertyProviders(self, ) -> ReadOnlyCollection: ...
    def ModifyPropertyCollection(self, defaultProps: PropertyDescriptorCollection, instance: object) -> PropertyDescriptorCollection: ...
    def RemovePerInstancePropertyProvider(self, pp: IPropertyProvider) -> None: ...
    def RemoveProperty(self, prop: PropertyDescriptor) -> None: ...

class PropertyDescriptorBase(PropertyDescriptor):
    """.NET: Autodesk.AutoCAD.ComponentModel.PropertyDescriptorBase`2"""
    def __init__(self, *args) -> None: ...
    DisplayName: str
    PropertyType: Type
    IsReadOnly: bool
    ComponentType: Type
    Converter: TypeConverter
    ConverterFromRegisteredType: TypeConverter
    IsLocalizable: bool
    SerializationVisibility: DesignerSerializationVisibility
    SupportsChangeEvents: bool
    Attributes: AttributeCollection
    Category: str
    Description: str
    IsBrowsable: bool
    Name: str
    DesignTimeOnly: bool
    def CanResetValue(self, component: object) -> bool: ...
    def ResetValue(self, component: object) -> None: ...
    def ShouldSerializeValue(self, component: object) -> bool: ...

class PropertyProviderAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.ComponentModel.PropertyProviderAttribute"""
    def __init__(self, *args) -> None: ...
    PropertyProviderType: Type
    TypeId: object

class TypeDescriptionProvider(TypeDescriptionProvider):
    """.NET: Autodesk.AutoCAD.ComponentModel.TypeDescriptionProvider`1"""
    def __init__(self, *args) -> None: ...
    RequireRegisteredTypes: Nullable
    def GetTypeDescriptor(self, objectType: Type, instance: object) -> ICustomTypeDescriptor: ...

class TypeDescriptor:
    """.NET: Autodesk.AutoCAD.ComponentModel.TypeDescriptor"""
    def __init__(self, *args) -> None: ...
    HasPerInstancePropertyProviders: bool
    def AddPerInstancePropertyProvider(self, pp: IPropertyProvider) -> None: ...
    def AddProperty(self, prop: PropertyDescriptor) -> None: ...
    def GetPerInstancePropertyProviders(self, ) -> ReadOnlyCollection: ...
    def ModifyPropertyCollection(self, defaultProps: PropertyDescriptorCollection, instance: object) -> PropertyDescriptorCollection: ...
    def RemovePerInstancePropertyProvider(self, pp: IPropertyProvider) -> None: ...
    def RemoveProperty(self, prop: PropertyDescriptor) -> None: ...

class TypeManager:
    """.NET: Autodesk.AutoCAD.ComponentModel.TypeManager"""
    def __init__(self, *args) -> None: ...
    Item: ITypeDescriptor
    Instance: TypeManager
