# Auto-generated — Civil 26 — Autodesk.AutoCAD.Geometry

class AugmentedPolylineCurve3d(PolylineCurve3d):
    """.NET: Autodesk.AutoCAD.Geometry.AugmentedPolylineCurve3d"""
    def __init__(self, *args) -> None: ...
    ApproximateTolerance: float
    D2Vectors: Vector3dCollection
    D1Vectors: Vector3dCollection
    Points: Point3dCollection
    NumberOfFitPoints: int
    HasFitData: bool
    EndPoint: Point3d
    StartPoint: Point3d
    EndParameter: float
    StartParameter: float
    NumberOfControlPoints: int
    Knots: KnotCollection
    NumberOfKnots: int
    Order: int
    Degree: int
    IsRational: bool
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> AugmentedPolylineCurve3d: ...
    def GetD2VectorAt(self, index: int) -> Vector3d: ...
    def GetPointAt(self, index: int) -> Point3d: ...
    def GetVectorAt(self, index: int) -> Vector3d: ...
    def SetD2VectorAt(self, index: int, point: Vector3d) -> None: ...
    def SetPointAt(self, index: int, point: Point3d) -> None: ...
    def SetVectorAt(self, index: int, point: Vector3d) -> None: ...

class BoundBlock2d(Entity2d):
    """.NET: Autodesk.AutoCAD.Geometry.BoundBlock2d"""
    def __init__(self, *args) -> None: ...
    IsBox: bool
    Direction2: Vector2d
    Direction1: Vector2d
    BasePoint: Point2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Contains(self, point: Point2d) -> bool: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> BoundBlock2d: ...
    def Extend(self, point: Point2d) -> None: ...
    def GetMaximumPoint(self, ) -> Point2d: ...
    def GetMinimumPoint(self, ) -> Point2d: ...
    def IsDisjoint(self, block: BoundBlock2d) -> bool: ...
    def Set(self, basePoint: Point2d, direction1: Vector2d, direction2: Vector2d) -> None: ...
    def Swell(self, distance: float) -> None: ...

class BoundBlock3d(Entity3d):
    """.NET: Autodesk.AutoCAD.Geometry.BoundBlock3d"""
    def __init__(self, *args) -> None: ...
    IsBox: bool
    Direction3: Vector3d
    Direction2: Vector3d
    Direction1: Vector3d
    BasePoint: Point3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Contains(self, pointToTest: Point3d) -> bool: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> BoundBlock3d: ...
    def Extend(self, pointToInclude: Point3d) -> None: ...
    def GetMaximumPoint(self, ) -> Point3d: ...
    def GetMinimumPoint(self, ) -> Point3d: ...
    def IsDisjoint(self, block: BoundBlock3d) -> bool: ...
    def Set(self, basePoint: Point3d, dir1: Vector3d, dir2: Vector3d, dir3: Vector3d) -> None: ...
    def Swell(self, distance: float) -> None: ...

class BoundedPlane(PlanarEntity):
    """.NET: Autodesk.AutoCAD.Geometry.BoundedPlane"""
    def __init__(self, *args) -> None: ...
    Coefficients: PlanarEquationCoefficients
    Normal: Vector3d
    PointOnPlane: Point3d
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> BoundedPlane: ...
    def IntersectWith(self, plane: BoundedPlane, tolerance: Tolerance) -> LineSegment3d: ...
    def Set(self, p1: Point3d, origin: Point3d, p2: Point3d) -> None: ...

class CircularArc2d(Curve2d):
    """.NET: Autodesk.AutoCAD.Geometry.CircularArc2d"""
    def __init__(self, *args) -> None: ...
    EndPoint: Point2d
    StartPoint: Point2d
    ReferenceVector: Vector2d
    IsClockWise: bool
    EndAngle: float
    StartAngle: float
    Radius: float
    Center: Point2d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> CircularArc2d: ...
    def GetTangent(self, point: Point2d, tolerance: Tolerance) -> Line2d: ...
    def IntersectWith(self, arc: CircularArc2d, tolerance: Tolerance) -> list: ...
    def IsInside(self, point: Point2d, tolerance: Tolerance) -> bool: ...
    def Set(self, curve1: Curve2d, curve2: Curve2d, curve3: Curve2d, parameter1: float, parameter2: float, parameter3: float) -> None: ...
    def SetAngles(self, startAngle: float, endAngle: float) -> None: ...
    def SetToComplement(self, ) -> None: ...

class CircularArc3d(Curve3d):
    """.NET: Autodesk.AutoCAD.Geometry.CircularArc3d"""
    def __init__(self, *args) -> None: ...
    EndPoint: Point3d
    StartPoint: Point3d
    EndAngle: float
    StartAngle: float
    Radius: float
    ReferenceVector: Vector3d
    Normal: Vector3d
    Center: Point3d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def ClosestPointToPlane(self, plane: PlanarEntity, tolerance: Tolerance) -> list: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> CircularArc3d: ...
    def GetPlane(self, ) -> Plane: ...
    def GetTangent(self, pointValue: Point3d, tolerance: Tolerance) -> Line3d: ...
    def IntersectWith(self, plane: PlanarEntity, tolerance: Tolerance) -> list: ...
    def IsInside(self, pointValue: Point3d, tolerance: Tolerance) -> bool: ...
    def ProjectedIntersectWith(self, line: LinearEntity3d, projectionDirection: Vector3d, tolerance: Tolerance) -> list: ...
    def Set(self, curve1: Curve3d, curve2: Curve3d, curve3: Curve3d, param1: float, param2: float, param3: float) -> None: ...
    def SetAngles(self, startAngle: float, endAngle: float) -> None: ...
    def SetAxes(self, normal: Vector3d, referenceVector: Vector3d) -> None: ...

class ClipBoundary2d(Entity2d):
    """.NET: Autodesk.AutoCAD.Geometry.ClipBoundary2d"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def ClipPolygon(self, rawVertices: Point2dCollection) -> ClipBoundary2dData: ...
    def ClipPolyline(self, rawVertices: Point2dCollection) -> ClipBoundary2dData: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> ClipBoundary2d: ...
    def Set(self, firstCorner: Point2d, secondCorner: Point2d) -> ClipError: ...

class ClipBoundary2dData:
    """.NET: Autodesk.AutoCAD.Geometry.ClipBoundary2dData"""
    def __init__(self, *args) -> None: ...
    ClippedSegmentSourceLabel: IntegerCollection
    ClipCondition: ClipCondition
    ClippedVertices: Point2dCollection
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: ClipBoundary2dData) -> bool: ...

class ClipCondition:
    """.NET: Autodesk.AutoCAD.Geometry.ClipCondition"""
    def __init__(self, *args) -> None: ...
    ...

class ClipError:
    """.NET: Autodesk.AutoCAD.Geometry.ClipError"""
    def __init__(self, *args) -> None: ...
    ...

class CompositeCurve2d(Curve2d):
    """.NET: Autodesk.AutoCAD.Geometry.CompositeCurve2d"""
    def __init__(self, *args) -> None: ...
    EndPoint: Point2d
    StartPoint: Point2d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> CompositeCurve2d: ...
    def GetCurves(self, ) -> list: ...
    def GlobalToLocalParameter(self, value: float) -> CompositeParameter: ...
    def LocalToGlobalParameter(self, value: CompositeParameter) -> float: ...
    def SetCurves(self, curves: list) -> None: ...

class CompositeCurve3d(Curve3d):
    """.NET: Autodesk.AutoCAD.Geometry.CompositeCurve3d"""
    def __init__(self, *args) -> None: ...
    EndPoint: Point3d
    StartPoint: Point3d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> CompositeCurve3d: ...
    def GetCurves(self, ) -> list: ...
    def GlobalToLocalParameter(self, value: float) -> CompositeParameter: ...
    def LocalToGlobalParameter(self, value: CompositeParameter) -> float: ...

class CompositeParameter:
    """.NET: Autodesk.AutoCAD.Geometry.CompositeParameter"""
    def __init__(self, *args) -> None: ...
    LocalParameter: float
    SegmentIndex: int
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: CompositeParameter, tolerance: Tolerance) -> bool: ...

class Cone(Surface):
    """.NET: Autodesk.AutoCAD.Geometry.Cone"""
    def __init__(self, *args) -> None: ...
    Apex: Point3d
    ReferenceAxis: Vector3d
    AxisOfSymmetry: Vector3d
    IsOuterNormal: bool
    Height: Interval
    HalfAngle: float
    BaseCenter: Point3d
    BaseRadius: float
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Cone: ...
    def GetAngles(self, ) -> list: ...
    def GetHalfAngles(self, ) -> list: ...
    def GetHeightAt(self, parameter: float) -> float: ...
    def IntersectWith(self, linearEntity: LinearEntity3d, tolerance: Tolerance) -> list: ...
    def IsClosed(self, tolerance: Tolerance) -> bool: ...
    def Set(self, cosineAngle: float, sineAngle: float, baseCenter: Point3d, baseRadius: float, axisOfSymmetry: Vector3d, refAxis: Vector3d, height: Interval, startAngle: float, endAngle: float) -> None: ...
    def SetAngles(self, startAngle: float, endAngle: float) -> None: ...

class CoordinateSystem2d:
    """.NET: Autodesk.AutoCAD.Geometry.CoordinateSystem2d"""
    def __init__(self, *args) -> None: ...
    Yaxis: Vector2d
    Xaxis: Vector2d
    Origin: Point2d
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: CoordinateSystem2d, tolerance: Tolerance) -> bool: ...
    def ToString(self, format: str, provider: IFormatProvider) -> str: ...

class CoordinateSystem3d:
    """.NET: Autodesk.AutoCAD.Geometry.CoordinateSystem3d"""
    def __init__(self, *args) -> None: ...
    Zaxis: Vector3d
    Yaxis: Vector3d
    Xaxis: Vector3d
    Origin: Point3d
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: CoordinateSystem3d, tolerance: Tolerance) -> bool: ...
    def ToString(self, format: str, provider: IFormatProvider) -> str: ...

class CubicSplineCurve2d(SplineEntity2d):
    """.NET: Autodesk.AutoCAD.Geometry.CubicSplineCurve2d"""
    def __init__(self, *args) -> None: ...
    NumFitPoints: int
    HasFitData: bool
    EndPoint: Point2d
    StartPoint: Point2d
    EndParameter: float
    StartParameter: float
    NumControlPoints: int
    Knots: KnotCollection
    NumKnots: int
    Order: int
    Degree: int
    IsRational: bool
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> CubicSplineCurve2d: ...
    def GetFirstDerivativeAt(self, index: int) -> Vector2d: ...
    def GetFitPointAt(self, index: int) -> Point2d: ...
    def SetFirstDerivativeAt(self, index: int, derivative: Vector2d) -> None: ...
    def SetFitPointAt(self, index: int, point: Point2d) -> None: ...

class CubicSplineCurve3d(SplineEntity3d):
    """.NET: Autodesk.AutoCAD.Geometry.CubicSplineCurve3d"""
    def __init__(self, *args) -> None: ...
    NumberOfFitPoints: int
    HasFitData: bool
    EndPoint: Point3d
    StartPoint: Point3d
    EndParameter: float
    StartParameter: float
    NumberOfControlPoints: int
    Knots: KnotCollection
    NumberOfKnots: int
    Order: int
    Degree: int
    IsRational: bool
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> CubicSplineCurve3d: ...
    def FirstDerivativeAt(self, i: int) -> Vector3d: ...
    def FitPointAt(self, i: int) -> Point3d: ...
    def SetFirstDerivativeAt(self, i: int, derivative: Vector3d) -> None: ...
    def SetFitPointAt(self, i: int, point: Point3d) -> None: ...

class Curve2d(Entity2d):
    """.NET: Autodesk.AutoCAD.Geometry.Curve2d"""
    def __init__(self, *args) -> None: ...
    EndPoint: Point2d
    StartPoint: Point2d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Curve2d: ...
    def EvaluatePoint(self, parameter: float) -> Point2d: ...
    def Explode(self, interval: Interval) -> list: ...
    def GetArea(self, startParameter: float, endParameter: float, tolerance: Tolerance) -> float: ...
    def GetBoundBlockOf(self, range: Interval) -> BoundBlock2d: ...
    def GetClosestPointTo(self, curve: Curve2d, tolerance: Tolerance) -> list: ...
    def GetDistanceTo(self, curve: Curve2d, tolerance: Tolerance) -> float: ...
    def GetInterval(self, ) -> Interval: ...
    def GetLength(self, fromParameter: float, toParameter: float, tolerance: Tolerance) -> float: ...
    def GetNormalPoint(self, point: Point2d, tolerance: Tolerance) -> PointOnCurve2d: ...
    def GetOrthoBoundBlockOf(self, range: Interval) -> BoundBlock2d: ...
    def GetParameterAtLength(self, datumParameter: float, length: float, parameterDirection: bool, tolerance: Tolerance) -> float: ...
    def GetParameterOf(self, point: Point2d, tolerance: Tolerance) -> float: ...
    def GetReverseParameterCurve(self, ) -> Curve2d: ...
    def GetSamplePoints(self, fromParameter: float, toParameter: float, approxEps: float) -> list: ...
    def GetSplitCurves(self, value: float) -> list: ...
    def GetTrimmedOffset(self, distance: float, extensionType: OffsetCurveExtensionType, tolerance: Tolerance) -> list: ...
    def IsClosed(self, tolerance: Tolerance) -> bool: ...
    def IsDegenerate(self, result: Entity2d, tolerance: Tolerance) -> bool: ...
    def IsLinear(self, line: Line2d, tolerance: Tolerance) -> bool: ...
    def IsOn(self, point: Point2d, value: float, tolerance: Tolerance) -> bool: ...
    def IsPeriodic(self, period: float) -> bool: ...
    def SetInterval(self, value: Interval) -> None: ...

class Curve2dCollection(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Geometry.Curve2dCollection"""
    def __init__(self, *args) -> None: ...
    Item: Curve2d
    IsReadOnly: bool
    IsFixedSize: bool
    Count: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Add(self, value: Curve2d) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Curve2d) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: Curve2d) -> int: ...
    def Insert(self, index: int, value: Curve2d) -> None: ...
    def Remove(self, value: Curve2d) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class Curve3d(Entity3d):
    """.NET: Autodesk.AutoCAD.Geometry.Curve3d"""
    def __init__(self, *args) -> None: ...
    EndPoint: Point3d
    StartPoint: Point3d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Curve3d: ...
    def EvaluatePoint(self, value: float) -> Point3d: ...
    def Explode(self, interval: Interval) -> list: ...
    def GetArea(self, startingParameter: float, endingParameter: float, tolerance: Tolerance) -> float: ...
    def GetBoundBlockOf(self, range: Interval) -> BoundBlock3d: ...
    def GetClosestPointTo(self, curve3d: Curve3d, tolerance: Tolerance) -> list: ...
    def GetDistanceTo(self, curve: Curve3d, tolerance: Tolerance) -> float: ...
    def GetInterval(self, ) -> Interval: ...
    def GetLength(self, fromParameter: float, toParameter: float, tolerance: float) -> float: ...
    def GetNewSamplePoints(self, fromParameter: float, toParameter: float, chordHeight: float) -> list: ...
    def GetNormalPoint(self, point: Point3d, tolerance: Tolerance) -> PointOnCurve3d: ...
    def GetOrthoBoundBlockOf(self, range: Interval) -> BoundBlock3d: ...
    def GetOrthoProjectEntity(self, projectionPlane: Plane, tolerance: Tolerance) -> Entity3d: ...
    def GetParameterAtLength(self, datumParameter: float, length: float, direction: bool, tolerance: float) -> float: ...
    def GetParameterOf(self, point: Point3d, tolerance: Tolerance) -> float: ...
    def GetProjectedClosestPointTo(self, curve3d: Curve3d, projectDirection: Vector3d, tolerance: Tolerance) -> list: ...
    def GetProjectedEntity(self, projectionPlane: Plane, projectDirection: Vector3d, tolerance: Tolerance) -> Entity3d: ...
    def GetReverseParameterCurve(self, ) -> Curve3d: ...
    def GetSamplePoints(self, fromParameter: float, toParameter: float, chordHeight: float) -> list: ...
    def GetSplitCurves(self, value: float) -> list: ...
    def GetTrimmedOffset(self, distance: float, planeNormal: Vector3d, extensionType: OffsetCurveExtensionType, tolerance: Tolerance) -> list: ...
    def IsClosed(self, tolerance: Tolerance) -> bool: ...
    def IsCoplanarWith(self, curve3d: Curve3d, plane: Plane, tolerance: Tolerance) -> bool: ...
    def IsDegenerate(self, result: Entity3d, tolerance: Tolerance) -> bool: ...
    def IsLinear(self, line: Line3d, tolerance: Tolerance) -> bool: ...
    def IsOn(self, point: Point3d, value: float, tolerance: Tolerance) -> bool: ...
    def IsPeriodic(self, period: float) -> bool: ...
    def IsPlanar(self, plane: Plane, tolerance: Tolerance) -> bool: ...
    def SetInterval(self, value: Interval) -> None: ...

class Curve3dCollection(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Geometry.Curve3dCollection"""
    def __init__(self, *args) -> None: ...
    Item: Curve3d
    IsReadOnly: bool
    IsFixedSize: bool
    Count: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Add(self, value: Curve3d) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Curve3d) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: Curve3d) -> int: ...
    def Insert(self, index: int, value: Curve3d) -> None: ...
    def Remove(self, value: Curve3d) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class CurveBoundary(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Geometry.CurveBoundary"""
    def __init__(self, *args) -> None: ...
    IsOwnerOfCurves: bool
    Contour: CurveBoundaryData
    NumElements: int
    DegenerateCurve: Curve2d
    DegeneratePosition: Position3d
    IsDegenerate: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Clone(self, ) -> object: ...
    def Set(self, numElements: int, curve3ds: list, curve2ds: list, orientation3d: bool, orientation2d: bool) -> None: ...
    def SetToOwnCurves(self, ) -> None: ...

class CurveBoundaryData:
    """.NET: Autodesk.AutoCAD.Geometry.CurveBoundaryData"""
    def __init__(self, *args) -> None: ...
    Orientation2d: bool
    Orientation3d: bool
    def Equals(self, obj: object) -> bool: ...
    def GetCurve2ds(self, ) -> list: ...
    def GetCurve3ds(self, ) -> list: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: CurveBoundaryData) -> bool: ...

class CurveCurveIntersector2d(Entity2d):
    """.NET: Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d"""
    def __init__(self, *args) -> None: ...
    OverlapDirection: bool
    OverlapCount: int
    NumberOfIntersectionPoints: int
    Tolerance: Tolerance
    Curve2: Curve2d
    Curve1: Curve2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def ChangeCurveOrder(self, ) -> None: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> CurveCurveIntersector2d: ...
    def GetIntersectionParameters(self, intersection: int) -> list: ...
    def GetIntersectionPoint(self, number: int) -> Point2d: ...
    def GetIntersectionPointTolerance(self, intersection: int) -> float: ...
    def GetIntersectionRanges(self, ) -> list: ...
    def GetOverlapRanges(self, overlapNumber: int) -> list: ...
    def GetPointOnCurve1(self, intersection: int) -> PointOnCurve2d: ...
    def GetPointOnCurve2(self, intersection: int) -> PointOnCurve2d: ...
    def IsTangential(self, intersection: int) -> bool: ...
    def IsTransversal(self, intersection: int) -> bool: ...
    def OrderWithRegardsTo1(self, ) -> None: ...
    def OrderWithRegardsTo2(self, ) -> None: ...
    def Set(self, curve1: Curve2d, curve2: Curve2d, range1: Interval, range2: Interval, tolerance: Tolerance) -> None: ...

class CurveCurveIntersector3d(Entity3d):
    """.NET: Autodesk.AutoCAD.Geometry.CurveCurveIntersector3d"""
    def __init__(self, *args) -> None: ...
    NumberOfIntersectionPoints: int
    Tolerance: Tolerance
    PlaneNormal: Vector3d
    Curve2: Curve3d
    Curve1: Curve3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def ChangeCurveOrder(self, ) -> None: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> CurveCurveIntersector3d: ...
    def GetIntersectionParameters(self, intersection: int) -> list: ...
    def GetIntersectionPoint(self, intersection: int) -> Point3d: ...
    def GetIntersectionPointTolerance(self, intersection: int) -> float: ...
    def GetIntersectionRanges(self, ) -> list: ...
    def GetOverlapRanges(self, overlap: int) -> list: ...
    def GetPointOnCurve1(self, intersection: int) -> PointOnCurve3d: ...
    def GetPointOnCurve2(self, intersection: int) -> PointOnCurve3d: ...
    def IsTangential(self, intersection: int) -> bool: ...
    def IsTransversal(self, intersection: int) -> bool: ...
    def OrderWithRegardsTo1(self, ) -> None: ...
    def OrderWithRegardsTo2(self, ) -> None: ...
    def OverlapCount(self, ) -> int: ...
    def OverlapDirection(self, ) -> bool: ...
    def Set(self, curve1: Curve3d, curve2: Curve3d, range1: Interval, range2: Interval, planeNormal: Vector3d, tolerance: Tolerance) -> None: ...

class Cylinder(Surface):
    """.NET: Autodesk.AutoCAD.Geometry.Cylinder"""
    def __init__(self, *args) -> None: ...
    Height: Interval
    IsOuterNormal: bool
    ReferenceAxis: Vector3d
    AxisOfSymmetry: Vector3d
    Origin: Point3d
    Radius: float
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Cylinder: ...
    def GetAngles(self, ) -> list: ...
    def GetHeightAt(self, parameter: float) -> float: ...
    def IntersectWith(self, linearEntity: LinearEntity3d, tolerance: Tolerance) -> list: ...
    def IsClosed(self, tolerance: Tolerance) -> bool: ...
    def Set(self, radius: float, origin: Point3d, axisOfSymmetry: Vector3d, referenceAxis: Vector3d, height: Interval, startAngle: float, endAngle: float) -> None: ...
    def SetAngles(self, startAngle: float, endAngle: float) -> None: ...

class DoubleCollection:
    """.NET: Autodesk.AutoCAD.Geometry.DoubleCollection"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: float
    IsReadOnly: bool
    IsFixedSize: bool
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: float) -> int: ...
    def AddRange(self, range: list) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: float) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> DoubleCollectionEnumerator: ...
    def IndexOf(self, value: float) -> int: ...
    def Insert(self, index: int, value: float) -> None: ...
    def Remove(self, value: float) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimToSize(self, ) -> None: ...

class DoubleCollectionEnumerator:
    """.NET: Autodesk.AutoCAD.Geometry.DoubleCollectionEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: float
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class EllipticalArc2d(Curve2d):
    """.NET: Autodesk.AutoCAD.Geometry.EllipticalArc2d"""
    def __init__(self, *args) -> None: ...
    IsClockWise: bool
    EndPoint: Point2d
    StartPoint: Point2d
    EndAngle: float
    StartAngle: float
    MajorAxis: Vector2d
    MinorAxis: Vector2d
    MajorRadius: float
    MinorRadius: float
    Center: Point2d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> EllipticalArc2d: ...
    def IntersectWith(self, line: LinearEntity2d, tolerance: Tolerance) -> list: ...
    def IsCircular(self, tolerance: Tolerance) -> bool: ...
    def IsInside(self, point: Point2d, tolerance: Tolerance) -> bool: ...
    def Set(self, center: Point2d, majorAxis: Vector2d, minorAxis: Vector2d, majorRadius: float, minorRadius: float, startAngle: float, endAngle: float) -> None: ...
    def SetAngles(self, startAngle: float, endAngle: float) -> None: ...
    def SetAxes(self, majorAxis: Vector2d, minorAxis: Vector2d) -> None: ...

class EllipticalArc3d(Curve3d):
    """.NET: Autodesk.AutoCAD.Geometry.EllipticalArc3d"""
    def __init__(self, *args) -> None: ...
    EndPoint: Point3d
    StartPoint: Point3d
    EndAngle: float
    StartAngle: float
    MajorRadius: float
    MinorRadius: float
    MajorAxis: Vector3d
    MinorAxis: Vector3d
    Normal: Vector3d
    Center: Point3d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def ClosestPointToPlane(self, plane: PlanarEntity, tolerance: Tolerance) -> list: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> EllipticalArc3d: ...
    def GetPlane(self, ) -> Plane: ...
    def IntersectWith(self, plane: PlanarEntity, tolerance: Tolerance) -> list: ...
    def IsCircular(self, tolerance: Tolerance) -> bool: ...
    def IsInside(self, pointValue: Point3d, tolerance: Tolerance) -> bool: ...
    def ProjectedIntersectWith(self, line: LinearEntity3d, projectionDirection: Vector3d, tolerance: Tolerance) -> list: ...
    def Set(self, center: Point3d, majorAxis: Vector3d, minorAxis: Vector3d, majorRadius: float, minorRadius: float, startAngle: float, endAngle: float) -> None: ...
    def SetAngles(self, startAngle: float, endAngle: float) -> None: ...
    def SetAxes(self, majorAxis: Vector3d, minorAxis: Vector3d) -> None: ...

class Entity2d(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Geometry.Entity2d"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Clone(self, ) -> object: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Entity2d: ...
    def IsEqualTo(self, entity: Entity2d, tolerance: Tolerance) -> bool: ...
    def IsOn(self, point: Point2d, tolerance: Tolerance) -> bool: ...
    def Mirror(self, line: Line2d) -> None: ...
    def RotateBy(self, angle: float, point: Point2d) -> None: ...
    def ScaleBy(self, scaleFactor: float, point: Point2d) -> None: ...
    def TransformBy(self, transform: Matrix2d) -> None: ...
    def TranslateBy(self, translateVector: Vector2d) -> None: ...

class Entity3d(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Geometry.Entity3d"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Clone(self, ) -> object: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Entity3d: ...
    def IsEqualTo(self, entity: Entity3d, tolerance: Tolerance) -> bool: ...
    def IsOn(self, point: Point3d, tolerance: Tolerance) -> bool: ...
    def Mirror(self, plane: Plane) -> None: ...
    def RotateBy(self, angle: float, vector: Vector3d, point: Point3d) -> None: ...
    def ScaleBy(self, scaleFactor: float, point: Point3d) -> None: ...
    def TransformBy(self, transform: Matrix3d) -> None: ...
    def TranslateBy(self, translateVector: Vector3d) -> None: ...

class ErrorCondition:
    """.NET: Autodesk.AutoCAD.Geometry.ErrorCondition"""
    def __init__(self, *args) -> None: ...
    ...

class ExternalBoundedSurface(Surface):
    """.NET: Autodesk.AutoCAD.Geometry.ExternalBoundedSurface"""
    def __init__(self, *args) -> None: ...
    IsOwnerOfSurface: bool
    NumContours: int
    IsExternalSurface: bool
    IsNurbs: bool
    IsTorus: bool
    IsCone: bool
    IsCylinder: bool
    IsSphere: bool
    IsPlane: bool
    ExternalBaseSurface: ExternalSurface
    BaseSurface: Surface
    ExternalSurfaceDefinition: IntPtr
    IsDefined: bool
    ExternalSurfaceKind: ExternalEntityKind
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> ExternalBoundedSurface: ...
    def GetContours(self, ) -> list: ...
    def Set(self, surfaceDef: IntPtr, surfaceKind: ExternalEntityKind) -> None: ...
    def SetToOwnSurface(self, ) -> None: ...

class ExternalCurve2d(Curve2d):
    """.NET: Autodesk.AutoCAD.Geometry.ExternalCurve2d"""
    def __init__(self, *args) -> None: ...
    NurbCurve: NurbCurve2d
    IsOwnerOfCurve: bool
    ExternalCurveKind: ExternalEntityKind
    ExternalCurve: IntPtr
    IsDefined: bool
    IsNurbCurve: bool
    EndPoint: Point2d
    StartPoint: Point2d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> ExternalCurve2d: ...
    def Set(self, curveDef: IntPtr, curveKind: ExternalEntityKind) -> None: ...
    def SetToOwnCurve(self, ) -> None: ...

class ExternalCurve3d(Curve3d):
    """.NET: Autodesk.AutoCAD.Geometry.ExternalCurve3d"""
    def __init__(self, *args) -> None: ...
    ExternalCurveKind: ExternalEntityKind
    NativeCurve: Curve3d
    IsNativeCurve: bool
    IsDefined: bool
    IsNurbCurve: bool
    IsEllipticalArc: bool
    IsCircularArc: bool
    IsLineSegment: bool
    IsRay: bool
    IsLine: bool
    EndPoint: Point3d
    StartPoint: Point3d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> ExternalCurve3d: ...

class ExternalEntityKind:
    """.NET: Autodesk.AutoCAD.Geometry.ExternalEntityKind"""
    def __init__(self, *args) -> None: ...
    ...

class ExternalSurface(Surface):
    """.NET: Autodesk.AutoCAD.Geometry.ExternalSurface"""
    def __init__(self, *args) -> None: ...
    IsOwnerOfSurface: bool
    nativeSurface: Surface
    IsNativeSurface: bool
    IsDefined: bool
    IsNurbSurface: bool
    IsTorus: bool
    IsCone: bool
    IsCylinder: bool
    IsSphere: bool
    IsPlane: bool
    ExternalSurfaceKind: ExternalEntityKind
    ExternalSurfaceDefiniton: IntPtr
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> ExternalSurface: ...
    def Set(self, surfaceDef: IntPtr, surfaceKind: ExternalEntityKind) -> None: ...
    def SetToOwnSurface(self, ) -> None: ...

class GeoDataLonLatAltInfo:
    """.NET: Autodesk.AutoCAD.Geometry.GeoDataLonLatAltInfo"""
    def __init__(self, *args) -> None: ...
    Altitude: float
    Latitude: float
    Longitude: float

class Int32Collection:
    """.NET: Autodesk.AutoCAD.Geometry.Int32Collection"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: int
    IsReadOnly: bool
    IsFixedSize: bool
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: int) -> int: ...
    def AddRange(self, range: list) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: int) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> Int32CollectionEnumerator: ...
    def IndexOf(self, value: int) -> int: ...
    def Insert(self, index: int, value: int) -> None: ...
    def Remove(self, value: int) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimToSize(self, ) -> None: ...

class Int32CollectionEnumerator:
    """.NET: Autodesk.AutoCAD.Geometry.Int32CollectionEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: int
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class IntPtrCollection:
    """.NET: Autodesk.AutoCAD.Geometry.IntPtrCollection"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: IntPtr
    IsReadOnly: bool
    IsFixedSize: bool
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: IntPtr) -> int: ...
    def AddRange(self, range: list) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: IntPtr) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IntPtrCollectionEnumerator: ...
    def IndexOf(self, value: IntPtr) -> int: ...
    def Insert(self, index: int, value: IntPtr) -> None: ...
    def Remove(self, value: IntPtr) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimToSize(self, ) -> None: ...

class IntPtrCollectionEnumerator:
    """.NET: Autodesk.AutoCAD.Geometry.IntPtrCollectionEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: IntPtr
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class IntegerCollection:
    """.NET: Autodesk.AutoCAD.Geometry.IntegerCollection"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: int
    IsReadOnly: bool
    IsFixedSize: bool
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: int) -> int: ...
    def AddRange(self, range: list) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: int) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IntegerCollectionEnumerator: ...
    def IndexOf(self, value: int) -> int: ...
    def Insert(self, index: int, value: int) -> None: ...
    def Remove(self, value: int) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimToSize(self, ) -> None: ...

class IntegerCollectionEnumerator:
    """.NET: Autodesk.AutoCAD.Geometry.IntegerCollectionEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: int
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class Interval(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Geometry.Interval"""
    def __init__(self, *args) -> None: ...
    IsSingleton: bool
    IsUnbounded: bool
    IsBoundedBelow: bool
    IsBoundedAbove: bool
    IsBounded: bool
    Tolerance: float
    Length: float
    Element: float
    UpperBound: float
    LowerBound: float
    Unbounded: Interval
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Contains(self, value: float) -> bool: ...
    def GetBounds(self, ) -> list: ...
    def GetMerge(self, otherInterval: Interval) -> Interval: ...
    def IntersectWith(self, otherInterval: Interval) -> Interval: ...
    def IsContinuousAtUpper(self, otherInterval: Interval) -> bool: ...
    def IsDisjoint(self, otherInterval: Interval) -> bool: ...
    def IsEqualAtLower(self, value: float) -> bool: ...
    def IsEqualAtUpper(self, value: float) -> bool: ...
    def IsOverlapAtUpper(self, otherInterval: Interval, overlap: Interval) -> bool: ...
    def IsPeriodicallyOn(self, period: float, value: float) -> bool: ...
    def Subtract(self, otherInterval: Interval) -> list: ...

class KnotCollection(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Geometry.KnotCollection"""
    def __init__(self, *args) -> None: ...
    NumberOfIntervals: int
    EndParameter: float
    StartParameter: float
    Tolerance: float
    Count: int
    Item: float
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Add(self, value: float) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: float) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetDistinctKnots(self, ) -> DoubleCollection: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetInterval(self, order: int, parameter: float, interval: Interval) -> int: ...
    def GetMultiplicityAt(self, i: int) -> int: ...
    def Insert(self, index: int, value: float) -> None: ...
    def IsOn(self, knot: float) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    def Reverse(self, ) -> None: ...
    def SetRange(self, lower: float, upper: float) -> None: ...
    def Split(self, parameter: float, multiplicityLast: int, multiplicityFirst: int) -> list: ...

class KnotParameterizationEnum:
    """.NET: Autodesk.AutoCAD.Geometry.KnotParameterizationEnum"""
    def __init__(self, *args) -> None: ...
    ...

class Line2d(LinearEntity2d):
    """.NET: Autodesk.AutoCAD.Geometry.Line2d"""
    def __init__(self, *args) -> None: ...
    Direction: Vector2d
    PointOnLine: Point2d
    EndPoint: Point2d
    StartPoint: Point2d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Line2d: ...
    def Set(self, point1: Point2d, point2: Point2d) -> None: ...

class Line2dCollection:
    """.NET: Autodesk.AutoCAD.Geometry.Line2dCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Line2d
    def Add(self, value: Line2d) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Line2d) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: Line2d) -> int: ...
    def Insert(self, index: int, value: Line2d) -> None: ...
    def Remove(self, value: Line2d) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class Line3d(LinearEntity3d):
    """.NET: Autodesk.AutoCAD.Geometry.Line3d"""
    def __init__(self, *args) -> None: ...
    Direction: Vector3d
    PointOnLine: Point3d
    EndPoint: Point3d
    StartPoint: Point3d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Line3d: ...
    def Set(self, point1: Point3d, point2: Point3d) -> None: ...

class LineSegment2d(LinearEntity2d):
    """.NET: Autodesk.AutoCAD.Geometry.LineSegment2d"""
    def __init__(self, *args) -> None: ...
    Length: float
    EndPoint: Point2d
    MidPoint: Point2d
    StartPoint: Point2d
    Direction: Vector2d
    PointOnLine: Point2d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def BaryComb(self, blendCoefficient: float) -> Point2d: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> LineSegment2d: ...
    def GetBisector(self, ) -> Line2d: ...
    def GetSegmentLength(self, fromParameter: float, toParameter: float, tolerance: Tolerance) -> float: ...
    def Set(self, curve1: Curve2d, curve2: Curve2d, parameter1: float, parameter2: float) -> None: ...

class LineSegment3d(LinearEntity3d):
    """.NET: Autodesk.AutoCAD.Geometry.LineSegment3d"""
    def __init__(self, *args) -> None: ...
    Length: float
    EndPoint: Point3d
    MidPoint: Point3d
    StartPoint: Point3d
    Direction: Vector3d
    PointOnLine: Point3d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def BaryComb(self, blendCoefficient: float) -> Point3d: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> LineSegment3d: ...
    def GetBisector(self, ) -> Plane: ...
    def Set(self, curve1: Curve3d, curve2: Curve3d, parameter1: float, parameter2: float) -> None: ...

class LinearEntity2d(Curve2d):
    """.NET: Autodesk.AutoCAD.Geometry.LinearEntity2d"""
    def __init__(self, *args) -> None: ...
    Direction: Vector2d
    PointOnLine: Point2d
    EndPoint: Point2d
    StartPoint: Point2d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> LinearEntity2d: ...
    def GetLine(self, ) -> Line2d: ...
    def GetPerpendicularLine(self, point: Point2d) -> Line2d: ...
    def IntersectWith(self, line: LinearEntity2d, tolerance: Tolerance) -> list: ...
    def IsColinearTo(self, line: LinearEntity2d, tolerance: Tolerance) -> bool: ...
    def IsParallelTo(self, line: LinearEntity2d, tolerance: Tolerance) -> bool: ...
    def IsPerpendicularTo(self, line: LinearEntity2d, tolerance: Tolerance) -> bool: ...
    def Overlap(self, line: LinearEntity2d, tolerance: Tolerance) -> LinearEntity2d: ...

class LinearEntity3d(Curve3d):
    """.NET: Autodesk.AutoCAD.Geometry.LinearEntity3d"""
    def __init__(self, *args) -> None: ...
    Direction: Vector3d
    PointOnLine: Point3d
    EndPoint: Point3d
    StartPoint: Point3d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> LinearEntity3d: ...
    def GetLine(self, ) -> Line3d: ...
    def GetPerpendicularPlane(self, intersectionPoint: Point3d) -> Plane: ...
    def IntersectWith(self, plane: PlanarEntity, tolerance: Tolerance) -> list: ...
    def IsColinearTo(self, line: LinearEntity3d, tolerance: Tolerance) -> bool: ...
    def IsOn(self, plane: Plane, tolerance: Tolerance) -> bool: ...
    def IsParallelTo(self, plane: PlanarEntity, tolerance: Tolerance) -> bool: ...
    def IsPerpendicularTo(self, plane: PlanarEntity, tolerance: Tolerance) -> bool: ...
    def Overlap(self, line: LinearEntity3d, tolerance: Tolerance) -> LinearEntity3d: ...
    def ProjectedIntersectWith(self, line: LinearEntity3d, projectionDirection: Vector3d, tolerance: Tolerance) -> list: ...

class Matrix2d:
    """.NET: Autodesk.AutoCAD.Geometry.Matrix2d"""
    def __init__(self, *args) -> None: ...
    ElementAt: float
    CoordinateSystem2d: CoordinateSystem2d
    Translation: Vector2d
    @staticmethod
    def AlignCoordinateSystem(fromOrigin: Point2d, fromE0: Vector2d, fromE1: Vector2d, toOrigin: Point2d, toE0: Vector2d, toE1: Vector2d) -> Matrix2d: ...
    @staticmethod
    def Displacement(vector: Vector2d) -> Matrix2d: ...
    def Equals(self, obj: object) -> bool: ...
    def GetDeterminant(self, ) -> float: ...
    def GetHashCode(self, ) -> int: ...
    def GetScale(self, ) -> float: ...
    def Inverse(self, ) -> Matrix2d: ...
    def IsConformal(self, info: Matrix2dInfo) -> bool: ...
    def IsEqualTo(self, a: Matrix2d, tolerance: Tolerance) -> bool: ...
    def IsScaledOrtho(self, tolerance: Tolerance) -> bool: ...
    def IsSingular(self, tolerance: Tolerance) -> bool: ...
    def IsUniscaledOrtho(self, tolerance: Tolerance) -> bool: ...
    @staticmethod
    def Mirroring(line: Line2d) -> Matrix2d: ...
    def Multiply(self, matrix: Matrix2d) -> Matrix2d: ...
    def PostMultiplyBy(self, rightSide: Matrix2d) -> Matrix2d: ...
    def PreMultiplyBy(self, leftSide: Matrix2d) -> Matrix2d: ...
    @staticmethod
    def Rotation(angle: float, center: Point2d) -> Matrix2d: ...
    @staticmethod
    def Scaling(scaleAll: float, center: Point2d) -> Matrix2d: ...
    def ToArray(self, ) -> list: ...
    def ToString(self, format: str, provider: IFormatProvider) -> str: ...
    def Transpose(self, ) -> Matrix2d: ...

class Matrix2dBuilder:
    """.NET: Autodesk.AutoCAD.Geometry.Matrix2dBuilder"""
    def __init__(self, *args) -> None: ...
    ElementAt: float
    def ToMatrix2d(self, ) -> Matrix2d: ...

class Matrix2dInfo:
    """.NET: Autodesk.AutoCAD.Geometry.Matrix2dInfo"""
    def __init__(self, *args) -> None: ...
    Reflex: Vector2d
    IsMirror: bool
    Angle: float
    Scale: float
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: Matrix2dInfo, tolerance: Tolerance) -> bool: ...
    def ToString(self, provider: IFormatProvider) -> str: ...

class Matrix3d:
    """.NET: Autodesk.AutoCAD.Geometry.Matrix3d"""
    def __init__(self, *args) -> None: ...
    ElementAt: float
    Normal: float
    CoordinateSystem3d: CoordinateSystem3d
    Translation: Vector3d
    Identity: Matrix3d
    @staticmethod
    def AlignCoordinateSystem(fromOrigin: Point3d, fromXAxis: Vector3d, fromYAxis: Vector3d, fromZAxis: Vector3d, toOrigin: Point3d, toXAxis: Vector3d, toYAxis: Vector3d, toZAxis: Vector3d) -> Matrix3d: ...
    @staticmethod
    def Displacement(vector: Vector3d) -> Matrix3d: ...
    def Equals(self, obj: object) -> bool: ...
    def GetDeterminant(self, ) -> float: ...
    def GetHashCode(self, ) -> int: ...
    def GetScale(self, ) -> float: ...
    def Inverse(self, ) -> Matrix3d: ...
    def IsEqualTo(self, mat: Matrix3d, tolerance: Tolerance) -> bool: ...
    def IsInverse(self, inv: Matrix3d, tolerance: Tolerance) -> bool: ...
    def IsScaledOrtho(self, tolerance: Tolerance) -> bool: ...
    def IsSingular(self, tolerance: Tolerance) -> bool: ...
    def IsUniscaledOrtho(self, tolerance: Tolerance) -> bool: ...
    @staticmethod
    def Mirroring(pointValue: Point3d) -> Matrix3d: ...
    @staticmethod
    def PlaneToWorld(normal: Vector3d) -> Matrix3d: ...
    def PostMultiplyBy(self, rightSide: Matrix3d) -> Matrix3d: ...
    def PreMultiplyBy(self, leftSide: Matrix3d) -> Matrix3d: ...
    @staticmethod
    def Projection(projectionPlane: Plane, projectDir: Vector3d) -> Matrix3d: ...
    @staticmethod
    def Rotation(angle: float, axis: Vector3d, center: Point3d) -> Matrix3d: ...
    @staticmethod
    def Scaling(scaleAll: float, center: Point3d) -> Matrix3d: ...
    def ToArray(self, ) -> list: ...
    def ToString(self, format: str, provider: IFormatProvider) -> str: ...
    def Transpose(self, ) -> Matrix3d: ...
    @staticmethod
    def WorldToPlane(normal: Vector3d) -> Matrix3d: ...

class Matrix3dBuilder:
    """.NET: Autodesk.AutoCAD.Geometry.Matrix3dBuilder"""
    def __init__(self, *args) -> None: ...
    ElementAt: float
    def ToMatrix3d(self, ) -> Matrix3d: ...

class NurbCurve2d(SplineEntity2d):
    """.NET: Autodesk.AutoCAD.Geometry.NurbCurve2d"""
    def __init__(self, *args) -> None: ...
    DefinitionData: NurbCurve2dData
    FitData: NurbCurve2dFitData
    EvalMode: bool
    FitKnotParameterization: KnotParameterizationEnum
    NumWeights: int
    FitTolerance: Tolerance
    NumFitPoints: int
    HasFitData: bool
    EndPoint: Point2d
    StartPoint: Point2d
    EndParameter: float
    StartParameter: float
    NumControlPoints: int
    Knots: KnotCollection
    NumKnots: int
    Order: int
    Degree: int
    IsRational: bool
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def AddControlPointAt(self, newKnot: float, point: Point2d, weight: float) -> None: ...
    def AddFitPointAt(self, index: int, point: Point2d) -> bool: ...
    def AddKnot(self, newKnot: float) -> None: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> NurbCurve2d: ...
    def DeleteControlPointAt(self, index: int) -> None: ...
    def DeleteFitPointAt(self, index: int) -> bool: ...
    def ElevateDegree(self, plusDegree: int) -> None: ...
    def GetFitPointAt(self, index: int) -> Point2d: ...
    def GetFitTangents(self, ) -> list: ...
    def GetParametersOfC1Discontinuity(self, tolerance: Tolerance) -> DoubleCollection: ...
    def GetParametersOfG1Discontinuity(self, tolerance: Tolerance) -> DoubleCollection: ...
    def GetWeightAt(self, index: int) -> float: ...
    def HardTrimByParams(self, newStartParameter: float, newEndParameter: float) -> None: ...
    def InsertKnot(self, newKnot: float) -> None: ...
    def JoinWith(self, curve: NurbCurve2d) -> None: ...
    def MakeClosed(self, ) -> None: ...
    def MakeNonPeriodic(self, ) -> None: ...
    def MakeOpen(self, ) -> None: ...
    def MakePeriodic(self, ) -> None: ...
    def MakeRational(self, weight: float) -> None: ...
    def PurgeFitData(self, ) -> bool: ...
    def SetEvaluateMode(self, evaluateMode: bool) -> None: ...
    def SetFitData(self, fitKnots: KnotCollection, fitPoints: Point2dCollection, startTangent: Vector2d, endTangent: Vector2d, fitTolerance: Tolerance, periodic: bool) -> None: ...
    def SetFitPointAt(self, index: int, point: Point2d) -> bool: ...
    def SetFitTangents(self, startTangent: Vector2d, endTangent: Vector2d) -> bool: ...
    def SetWeightAt(self, index: int, value: float) -> None: ...

class NurbCurve2dData:
    """.NET: Autodesk.AutoCAD.Geometry.NurbCurve2dData"""
    def __init__(self, *args) -> None: ...
    Weights: DoubleCollection
    Knots: KnotCollection
    ControlPoints: Point2dCollection
    Periodic: bool
    Rational: bool
    Degree: int
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: NurbCurve2dData) -> bool: ...

class NurbCurve2dFitData:
    """.NET: Autodesk.AutoCAD.Geometry.NurbCurve2dFitData"""
    def __init__(self, *args) -> None: ...
    KnotParam: KnotParameterizationEnum
    EndTangent: Vector2d
    StartTangent: Vector2d
    TangentsExist: bool
    FitTolerance: Tolerance
    Degree: int
    FitPoints: Point2dCollection
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: NurbCurve2dFitData) -> bool: ...

class NurbCurve3d(SplineEntity3d):
    """.NET: Autodesk.AutoCAD.Geometry.NurbCurve3d"""
    def __init__(self, *args) -> None: ...
    DefinitionData: NurbCurve3dData
    FitData: NurbCurve3dFitData
    EvalMode: bool
    FitKnotParameterization: KnotParameterizationEnum
    NumWeights: int
    FitTolerance: Tolerance
    NumFitPoints: int
    HasFitData: bool
    EndPoint: Point3d
    StartPoint: Point3d
    EndParameter: float
    StartParameter: float
    NumberOfControlPoints: int
    Knots: KnotCollection
    NumberOfKnots: int
    Order: int
    Degree: int
    IsRational: bool
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def AddControlPointAt(self, newKnot: float, point: Point3d, weight: float) -> None: ...
    def AddFitPointAt(self, index: int, point: Point3d) -> bool: ...
    def AddKnot(self, newKnot: float) -> None: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> NurbCurve3d: ...
    def DeleteControlPointAt(self, index: int) -> None: ...
    def DeleteFitPointAt(self, index: int) -> bool: ...
    def ElevateDegree(self, plusDegree: int) -> None: ...
    def GetFitPointAt(self, index: int) -> Point3d: ...
    def GetFitTangents(self, ) -> list: ...
    def GetParametersOfC1Discontinuity(self, tolerance: Tolerance) -> DoubleCollection: ...
    def GetParametersOfG1Discontinuity(self, tolerance: Tolerance) -> DoubleCollection: ...
    def GetWeightAt(self, index: int) -> float: ...
    def HardTrimByParams(self, newStartParameter: float, newEndParameter: float) -> None: ...
    def InsertKnot(self, newKnot: float) -> None: ...
    def JoinWith(self, curve: NurbCurve3d) -> None: ...
    def MakeClosed(self, ) -> None: ...
    def MakeNonPeriodic(self, ) -> None: ...
    def MakeOpen(self, ) -> None: ...
    def MakePeriodic(self, ) -> None: ...
    def MakeRational(self, weight: float) -> None: ...
    def PurgeFitData(self, ) -> bool: ...
    def SetEvaluateMode(self, evaluateMode: bool) -> None: ...
    def SetFitData(self, fitKnots: KnotCollection, fitPoints: Point3dCollection, startTangent: Vector3d, endTangent: Vector3d, fitTolerance: Tolerance, periodic: bool) -> None: ...
    def SetFitPointAt(self, index: int, point: Point3d) -> bool: ...
    def SetFitTangents(self, startTangent: Vector3d, endTangent: Vector3d) -> bool: ...
    def SetWeightAt(self, index: int, value: float) -> None: ...

class NurbCurve3dData:
    """.NET: Autodesk.AutoCAD.Geometry.NurbCurve3dData"""
    def __init__(self, *args) -> None: ...
    Weights: DoubleCollection
    Knots: KnotCollection
    ControlPoints: Point3dCollection
    Periodic: bool
    Rational: bool
    Degree: int
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: NurbCurve3dData) -> bool: ...

class NurbCurve3dFitData:
    """.NET: Autodesk.AutoCAD.Geometry.NurbCurve3dFitData"""
    def __init__(self, *args) -> None: ...
    KnotParam: KnotParameterizationEnum
    EndTangent: Vector3d
    StartTangent: Vector3d
    TangentsExist: bool
    FitTolerance: Tolerance
    Degree: int
    FitPoints: Point3dCollection
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: NurbCurve3dFitData) -> bool: ...

class NurbSurface(Surface):
    """.NET: Autodesk.AutoCAD.Geometry.NurbSurface"""
    def __init__(self, *args) -> None: ...
    VKnots: KnotCollection
    NumKnotsInV: int
    UKnots: KnotCollection
    NumKnotsInU: int
    PeriodicInV: float
    PeriodicInU: float
    IsPeriodicInV: bool
    IsPeriodicInU: bool
    Weights: DoubleCollection
    ControlPoints: Point3dCollection
    NumControlPointsInV: int
    DegreeInV: int
    NumControlPointsInU: int
    DegreeInU: int
    SingularityInV: int
    SingularityInU: int
    IsRationalInV: bool
    IsRationalInU: bool
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> NurbSurface: ...
    def GetDefinition(self, ) -> NurbSurfaceDefinition: ...
    def Set(self, degreeU: int, degreeV: int, propsInU: int, propsInV: int, numControlPointsInU: int, numControlPointsInV: int, controlPoints: Point3dCollection, weights: DoubleCollection, knotsInU: KnotCollection, knotsInV: KnotCollection, tolerance: Tolerance) -> None: ...

class NurbSurfaceDefinition:
    """.NET: Autodesk.AutoCAD.Geometry.NurbSurfaceDefinition"""
    def __init__(self, *args) -> None: ...
    NumberOfControlPointsInV: int
    NumberOfControlPointsInU: int
    PropertiesInV: int
    PropertiesInU: int
    DegreeInV: int
    DegreeInU: int
    VKnots: KnotCollection
    UKnots: KnotCollection
    Weights: DoubleCollection
    ControlPoints: Point3dCollection
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: NurbSurfaceDefinition) -> bool: ...

class OffsetCurve2d(Curve2d):
    """.NET: Autodesk.AutoCAD.Geometry.OffsetCurve2d"""
    def __init__(self, *args) -> None: ...
    Transformation: Matrix2d
    ParameterDirection: bool
    OffsetDistance: float
    Curve: Curve2d
    EndPoint: Point2d
    StartPoint: Point2d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> OffsetCurve2d: ...

class OffsetCurve3d(Curve3d):
    """.NET: Autodesk.AutoCAD.Geometry.OffsetCurve3d"""
    def __init__(self, *args) -> None: ...
    Transformation: Matrix3d
    ParameterDirection: bool
    OffsetDistance: float
    Normal: Vector3d
    Curve: Curve3d
    EndPoint: Point3d
    StartPoint: Point3d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> OffsetCurve3d: ...

class OffsetCurveExtensionType:
    """.NET: Autodesk.AutoCAD.Geometry.OffsetCurveExtensionType"""
    def __init__(self, *args) -> None: ...
    ...

class OffsetSurface(Surface):
    """.NET: Autodesk.AutoCAD.Geometry.OffsetSurface"""
    def __init__(self, *args) -> None: ...
    OffsetDist: float
    ConstructionSurface: Surface
    OriginalSurface: Surface
    IsTorus: bool
    IsCone: bool
    IsCylinder: bool
    IsSphere: bool
    IsBoundedPlane: bool
    IsPlane: bool
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> OffsetSurface: ...
    def Set(self, surface: Surface, offsetDistance: float) -> None: ...

class PlanarEntity(Surface):
    """.NET: Autodesk.AutoCAD.Geometry.PlanarEntity"""
    def __init__(self, *args) -> None: ...
    Coefficients: PlanarEquationCoefficients
    Normal: Vector3d
    PointOnPlane: Point3d
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def ClosestPointToLinearEntity(self, line: LinearEntity3d, tolerance: Tolerance) -> list: ...
    def ClosestPointToPlanarEntity(self, otherPlane: PlanarEntity, tolerance: Tolerance) -> list: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> PlanarEntity: ...
    def GetCoordinateSystem(self, ) -> CoordinateSystem3d: ...
    def IntersectWith(self, linearEntity: LinearEntity3d, tolerance: Tolerance) -> list: ...
    def IsCoplanarTo(self, otherPlanarEntity: PlanarEntity, tolerance: Tolerance) -> bool: ...
    def IsParallelTo(self, otherPlanarEntity: PlanarEntity, tolerance: Tolerance) -> bool: ...
    def IsPerpendicularTo(self, linearEntity: PlanarEntity, tolerance: Tolerance) -> bool: ...

class PlanarEquationCoefficients:
    """.NET: Autodesk.AutoCAD.Geometry.PlanarEquationCoefficients"""
    def __init__(self, *args) -> None: ...
    D: float
    C: float
    B: float
    A: float

class Plane(PlanarEntity):
    """.NET: Autodesk.AutoCAD.Geometry.Plane"""
    def __init__(self, *args) -> None: ...
    Coefficients: PlanarEquationCoefficients
    Normal: Vector3d
    PointOnPlane: Point3d
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Plane: ...
    def GetSignedDistanceTo(self, pointValue: Point3d) -> float: ...
    def IntersectWith(self, boundPlane: BoundedPlane, tolerance: Tolerance) -> LineSegment3d: ...
    def Set(self, a: float, b: float, c: float, d: float) -> None: ...

class Point2d:
    """.NET: Autodesk.AutoCAD.Geometry.Point2d"""
    def __init__(self, *args) -> None: ...
    Origin: Point2d
    Coordinate: float
    Y: float
    X: float
    def Add(self, value: Vector2d) -> Point2d: ...
    def DivideBy(self, value: float) -> Point2d: ...
    def Equals(self, obj: object) -> bool: ...
    def GetAsVector(self, ) -> Vector2d: ...
    def GetDistanceTo(self, point: Point2d) -> float: ...
    def GetHashCode(self, ) -> int: ...
    def GetVectorTo(self, point: Point2d) -> Vector2d: ...
    def IsEqualTo(self, a: Point2d, tolerance: Tolerance) -> bool: ...
    def Mirror(self, line: Line2d) -> Point2d: ...
    def MultiplyBy(self, value: float) -> Point2d: ...
    def RotateBy(self, angle: float, origin: Point2d) -> Point2d: ...
    def ScaleBy(self, scaleFactor: float, origin: Point2d) -> Point2d: ...
    def Subtract(self, value: Vector2d) -> Point2d: ...
    def ToArray(self, ) -> list: ...
    def ToString(self, format: str, provider: IFormatProvider) -> str: ...
    def TransformBy(self, leftSide: Matrix2d) -> Point2d: ...

class Point2dCollection:
    """.NET: Autodesk.AutoCAD.Geometry.Point2dCollection"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: Point2d
    IsReadOnly: bool
    IsFixedSize: bool
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: Point2d) -> int: ...
    def AddRange(self, range: list) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Point2d) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> Point2dCollectionEnumerator: ...
    def IndexOf(self, value: Point2d) -> int: ...
    def Insert(self, index: int, value: Point2d) -> None: ...
    def Remove(self, value: Point2d) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimToSize(self, ) -> None: ...

class Point2dCollectionEnumerator:
    """.NET: Autodesk.AutoCAD.Geometry.Point2dCollectionEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: Point2d
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class Point3d:
    """.NET: Autodesk.AutoCAD.Geometry.Point3d"""
    def __init__(self, *args) -> None: ...
    Coordinate: float
    Origin: Point3d
    Z: float
    Y: float
    X: float
    def Add(self, value: Vector3d) -> Point3d: ...
    def Convert2d(self, plane: PlanarEntity) -> Point2d: ...
    def DistanceTo(self, point: Point3d) -> float: ...
    def DivideBy(self, value: float) -> Point3d: ...
    def Equals(self, obj: object) -> bool: ...
    def GetAsVector(self, ) -> Vector3d: ...
    def GetHashCode(self, ) -> int: ...
    def GetVectorTo(self, point: Point3d) -> Vector3d: ...
    def IsEqualTo(self, point: Point3d, tolerance: Tolerance) -> bool: ...
    def Mirror(self, plane: Plane) -> Point3d: ...
    def MultiplyBy(self, value: float) -> Point3d: ...
    def OrthoProject(self, plane: Plane) -> Point3d: ...
    def Project(self, plane: Plane, vector: Vector3d) -> Point3d: ...
    def RotateBy(self, angle: float, vector: Vector3d, centerPoint: Point3d) -> Point3d: ...
    def ScaleBy(self, scaleFactor: float, centerPoint: Point3d) -> Point3d: ...
    def Subtract(self, value: Vector3d) -> Point3d: ...
    def ToArray(self, ) -> list: ...
    def ToString(self, format: str, provider: IFormatProvider) -> str: ...
    def TransformBy(self, leftSide: Matrix3d) -> Point3d: ...

class Point3dCollection(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Geometry.Point3dCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Point3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Add(self, value: Point3d) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Point3d) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: Point3d) -> int: ...
    def Insert(self, index: int, value: Point3d) -> None: ...
    def Remove(self, value: Point3d) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class PointEntity2d(Entity2d):
    """.NET: Autodesk.AutoCAD.Geometry.PointEntity2d"""
    def __init__(self, *args) -> None: ...
    Point: Point2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> PointEntity2d: ...

class PointEntity3d(Entity3d):
    """.NET: Autodesk.AutoCAD.Geometry.PointEntity3d"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> PointEntity3d: ...
    def GetPoint(self, ) -> Point3d: ...

class PointOnCurve2d(PointEntity2d):
    """.NET: Autodesk.AutoCAD.Geometry.PointOnCurve2d"""
    def __init__(self, *args) -> None: ...
    Point: Point2d
    Parameter: float
    Curve: Curve2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> PointOnCurve2d: ...
    def GetDerivative(self, order: int, curve: Curve2d, parameter: float) -> Vector2d: ...
    def GetPointAtParameter(self, parameter: float) -> Point2d: ...
    def GetPointOnCurve(self, curve: Curve2d, parameter: float) -> Point2d: ...

class PointOnCurve3d(PointEntity3d):
    """.NET: Autodesk.AutoCAD.Geometry.PointOnCurve3d"""
    def __init__(self, *args) -> None: ...
    Point: Point3d
    Parameter: float
    Curve: Curve3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> PointOnCurve3d: ...
    def GetCurvature(self, parameter: float) -> float: ...
    @staticmethod
    def GetDerivative(order: int, curve: Curve3d, parameter: float) -> Vector3d: ...
    def GetPointAtParameter(self, parameter: float) -> Point3d: ...
    @staticmethod
    def GetPointOnCurve(curve: Curve3d, parameter: float) -> Point3d: ...
    def IsSingular(self, tolerance: Tolerance) -> bool: ...

class PointOnSurface(PointEntity3d):
    """.NET: Autodesk.AutoCAD.Geometry.PointOnSurface"""
    def __init__(self, *args) -> None: ...
    Parameter: Point2d
    Surface: Surface
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> PointOnSurface: ...
    @staticmethod
    def GetInverseTangentVector(vector: Vector3d, surf: Surface, point: Point2d) -> Vector2d: ...
    @staticmethod
    def GetMixedPartial(surf: Surface, point: Point2d) -> Vector3d: ...
    @staticmethod
    def GetNormal(surf: Surface, point: Point2d) -> Vector3d: ...
    @staticmethod
    def GetPoint(surface: Surface, point: Point2d) -> Point3d: ...
    @staticmethod
    def GetTangentVector(vector: Vector2d, vectorSurface: Surface, pointer: Point2d) -> Vector3d: ...
    @staticmethod
    def GetUDerivative(order: int, surface: Surface, point: Point2d) -> Vector3d: ...
    @staticmethod
    def GetVDerivative(order: int, surface: Surface, point: Point2d) -> Vector3d: ...

class PolylineCurve2d(SplineEntity2d):
    """.NET: Autodesk.AutoCAD.Geometry.PolylineCurve2d"""
    def __init__(self, *args) -> None: ...
    NumberOfFitPoints: int
    HasFitData: bool
    EndPoint: Point2d
    StartPoint: Point2d
    EndParameter: float
    StartParameter: float
    NumControlPoints: int
    Knots: KnotCollection
    NumKnots: int
    Order: int
    Degree: int
    IsRational: bool
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> PolylineCurve2d: ...
    def FitPointAt(self, i: int) -> Point2d: ...
    def SetFitPointAt(self, i: int, point: Point2d) -> None: ...

class PolylineCurve3d(SplineEntity3d):
    """.NET: Autodesk.AutoCAD.Geometry.PolylineCurve3d"""
    def __init__(self, *args) -> None: ...
    NumberOfFitPoints: int
    HasFitData: bool
    EndPoint: Point3d
    StartPoint: Point3d
    EndParameter: float
    StartParameter: float
    NumberOfControlPoints: int
    Knots: KnotCollection
    NumberOfKnots: int
    Order: int
    Degree: int
    IsRational: bool
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> PolylineCurve3d: ...
    def FitPointAt(self, i: int) -> Point3d: ...
    def SetFitPointAt(self, i: int, point: Point3d) -> None: ...

class Position2d(PointEntity2d):
    """.NET: Autodesk.AutoCAD.Geometry.Position2d"""
    def __init__(self, *args) -> None: ...
    Point: Point2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Position2d: ...
    def Set(self, x: float, y: float) -> None: ...

class Position3d(PointEntity3d):
    """.NET: Autodesk.AutoCAD.Geometry.Position3d"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Position3d: ...
    def Set(self, x: float, y: float, z: float) -> None: ...

class Ray2d(LinearEntity2d):
    """.NET: Autodesk.AutoCAD.Geometry.Ray2d"""
    def __init__(self, *args) -> None: ...
    Direction: Vector2d
    PointOnLine: Point2d
    EndPoint: Point2d
    StartPoint: Point2d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Ray2d: ...
    def Set(self, point1: Point2d, point2: Point2d) -> None: ...

class Ray3d(LinearEntity3d):
    """.NET: Autodesk.AutoCAD.Geometry.Ray3d"""
    def __init__(self, *args) -> None: ...
    Direction: Vector3d
    PointOnLine: Point3d
    EndPoint: Point3d
    StartPoint: Point3d
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Ray3d: ...
    def Set(self, point1: Point3d, point2: Point3d) -> None: ...

class Scale2d:
    """.NET: Autodesk.AutoCAD.Geometry.Scale2d"""
    def __init__(self, *args) -> None: ...
    Coordinate: float
    Y: float
    X: float
    def Equals(self, obj: object) -> bool: ...
    @staticmethod
    def ExtractScale(mat: Matrix2d) -> Scale2d: ...
    def GetHashCode(self, ) -> int: ...
    def GetMatrix(self, ) -> Matrix2d: ...
    def Inverse(self, ) -> Scale2d: ...
    def IsEqualTo(self, a: Scale2d, tolerance: Tolerance) -> bool: ...
    def IsProportional(self, tolerance: Tolerance) -> bool: ...
    def MultiplyBy(self, factor: float) -> Scale2d: ...
    def PostMultiplyBy(self, rightSide: Scale2d) -> Scale2d: ...
    def PreMultiplyBy(self, leftSide: Scale2d) -> Scale2d: ...
    @staticmethod
    def RemoveScale(mat: Matrix2d) -> Scale2d: ...
    def ToArray(self, ) -> list: ...
    def ToString(self, format: str, provider: IFormatProvider) -> str: ...

class Scale3d:
    """.NET: Autodesk.AutoCAD.Geometry.Scale3d"""
    def __init__(self, *args) -> None: ...
    Coordinate: float
    Z: float
    Y: float
    X: float
    def Equals(self, obj: object) -> bool: ...
    @staticmethod
    def ExtractScale(mat: Matrix3d) -> Scale3d: ...
    def GetHashCode(self, ) -> int: ...
    def GetMatrix(self, ) -> Matrix3d: ...
    def Inverse(self, ) -> Scale3d: ...
    def IsEqualTo(self, scaleVector: Scale3d, tolerance: Tolerance) -> bool: ...
    def IsProportional(self, tolerance: Tolerance) -> bool: ...
    def MultiplyBy(self, s: float) -> Scale3d: ...
    def PostMultiplyBy(self, rightSide: Scale3d) -> Scale3d: ...
    def PreMultiplyBy(self, leftSide: Scale3d) -> Scale3d: ...
    @staticmethod
    def RemoveScale(mat: Matrix3d) -> Scale3d: ...
    def ToArray(self, ) -> list: ...
    def ToString(self, format: str, provider: IFormatProvider) -> str: ...

class Sphere(Surface):
    """.NET: Autodesk.AutoCAD.Geometry.Sphere"""
    def __init__(self, *args) -> None: ...
    IsOuterNormal: bool
    SouthPole: Point3d
    NorthPole: Point3d
    ReferenceAxis: Vector3d
    NorthAxis: Vector3d
    Center: Point3d
    Radius: float
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Sphere: ...
    def GetAnglesInU(self, ) -> list: ...
    def GetAnglesInV(self, ) -> list: ...
    def IntersectWith(self, linearEntity: LinearEntity3d, tolerance: Tolerance) -> list: ...
    def IsClosed(self, tolerance: Tolerance) -> bool: ...
    def Set(self, radius: float, center: Point3d, northAxis: Vector3d, referenceAxis: Vector3d, startAngleU: float, endAngleU: float, startAngleV: float, endAngleV: float) -> None: ...
    def SetAnglesInU(self, startAngle: float, endAngle: float) -> None: ...
    def SetAnglesInV(self, startAngle: float, endAngle: float) -> None: ...

class SplineEntity2d(Curve2d):
    """.NET: Autodesk.AutoCAD.Geometry.SplineEntity2d"""
    def __init__(self, *args) -> None: ...
    HasFitData: bool
    EndPoint: Point2d
    StartPoint: Point2d
    EndParameter: float
    StartParameter: float
    NumControlPoints: int
    Knots: KnotCollection
    NumKnots: int
    Order: int
    Degree: int
    IsRational: bool
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock2d
    BoundBlock: BoundBlock2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> SplineEntity2d: ...
    def GetContinuityAtKnot(self, index: int, tolerance: Tolerance) -> int: ...
    def GetControlPointAt(self, index: int) -> Point2d: ...
    def GetKnotAt(self, index: int) -> float: ...
    def SetControlPointAt(self, index: int, point: Point2d) -> None: ...
    def SetKnotAt(self, index: int, value: float) -> None: ...

class SplineEntity3d(Curve3d):
    """.NET: Autodesk.AutoCAD.Geometry.SplineEntity3d"""
    def __init__(self, *args) -> None: ...
    HasFitData: bool
    EndPoint: Point3d
    StartPoint: Point3d
    EndParameter: float
    StartParameter: float
    NumberOfControlPoints: int
    Knots: KnotCollection
    NumberOfKnots: int
    Order: int
    Degree: int
    IsRational: bool
    HasEndPoint: bool
    HasStartPoint: bool
    OrthoBoundBlock: BoundBlock3d
    BoundBlock: BoundBlock3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def ControlPointAt(self, i: int) -> Point3d: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> SplineEntity3d: ...
    def GetContinuityAtKnot(self, i: int, tolerance: Tolerance) -> int: ...
    def KnotAt(self, i: int) -> float: ...
    def SetControlPointAt(self, i: int, point: Point3d) -> None: ...
    def SetKnotAt(self, i: int, value: float) -> None: ...

class Surface(Entity3d):
    """.NET: Autodesk.AutoCAD.Geometry.Surface"""
    def __init__(self, *args) -> None: ...
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def ClosestPointTo(self, point: Point3d, tolerance: Tolerance) -> Point3d: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Surface: ...
    def DistanceTo(self, point: Point3d, tolerance: Tolerance) -> float: ...
    def EvaluatePoint(self, parameter: Point2d, derivOrder: int, derivatives: Vector3dCollection, normal: Vector3d) -> Point3d: ...
    def GetClosestPointTo(self, point: Point3d, tolerance: Tolerance) -> PointOnSurface: ...
    def GetEnvelope(self, ) -> list: ...
    def IsClosedInU(self, tolerance: Tolerance) -> bool: ...
    def IsClosedInV(self, tolerance: Tolerance) -> bool: ...
    def IsOn(self, point: Point3d, parameterPoint: Point2d, tolerance: Tolerance) -> bool: ...
    def ParameterOf(self, point: Point3d, tolerance: Tolerance) -> Point2d: ...

class SurfaceSurfaceIntersector(Entity3d):
    """.NET: Autodesk.AutoCAD.Geometry.SurfaceSurfaceIntersector"""
    def __init__(self, *args) -> None: ...
    Tolerance: Tolerance
    NumResults: int
    Surface2: Surface
    Surface1: Surface
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> SurfaceSurfaceIntersector: ...
    def GetDimension(self, number: int) -> int: ...
    def GetIntersectPointParameters(self, number: int) -> list: ...
    def GetIntersectionConfigurations(self, number: int) -> SurfaceSurfaceIntersectorConfigurations: ...
    def GetType(self, number: int) -> SurfaceSurfaceIntersectorType: ...
    def IntersectCurve(self, number: int, isExternal: bool) -> Curve3d: ...
    def IntersectParameterCurve(self, number: int, isExternal: bool, isFirst: bool) -> Curve2d: ...
    def IntersectPoint(self, number: int) -> Point3d: ...
    def Set(self, surface1: Surface, surface2: Surface, tolerance: Tolerance) -> None: ...

class SurfaceSurfaceIntersectorConfiguration:
    """.NET: Autodesk.AutoCAD.Geometry.SurfaceSurfaceIntersectorConfiguration"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceSurfaceIntersectorConfigurations:
    """.NET: Autodesk.AutoCAD.Geometry.SurfaceSurfaceIntersectorConfigurations"""
    def __init__(self, *args) -> None: ...
    Dimension: int
    IntersectionType: SurfaceSurfaceIntersectorType
    Surface2Right: SurfaceSurfaceIntersectorConfiguration
    Surface1Right: SurfaceSurfaceIntersectorConfiguration
    Surface2Left: SurfaceSurfaceIntersectorConfiguration
    Surface1Left: SurfaceSurfaceIntersectorConfiguration
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqualTo(self, a: SurfaceSurfaceIntersectorConfigurations) -> bool: ...

class SurfaceSurfaceIntersectorType:
    """.NET: Autodesk.AutoCAD.Geometry.SurfaceSurfaceIntersectorType"""
    def __init__(self, *args) -> None: ...
    ...

class Tolerance:
    """.NET: Autodesk.AutoCAD.Geometry.Tolerance"""
    def __init__(self, *args) -> None: ...
    Global: Tolerance
    EqualVector: float
    EqualPoint: float

class Torus(Surface):
    """.NET: Autodesk.AutoCAD.Geometry.Torus"""
    def __init__(self, *args) -> None: ...
    IsHollow: bool
    IsDegenerate: bool
    IsDoughnut: bool
    IsVortex: bool
    IsApple: bool
    IsLemon: bool
    IsOuterNormal: bool
    ReferenceAxis: Vector3d
    AxisOfSymmetry: Vector3d
    Center: Point3d
    MinorRadius: float
    MajorRadius: float
    ReverseNormal: Surface
    IsNormalReversed: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Torus: ...
    def GetAnglesInU(self, ) -> list: ...
    def GetAnglesInV(self, ) -> list: ...
    def IntersectWith(self, linearEntity: LinearEntity3d, tolerance: Tolerance) -> list: ...
    def Set(self, majorRadius: float, minorRadius: float, origin: Point3d, axisOfSymmetry: Vector3d, refAxis: Vector3d, startAngleU: float, endAngleU: float, startAngleV: float, endAngleV: float) -> None: ...
    def SetAnglesInU(self, startAngle: float, endAngle: float) -> None: ...
    def SetAnglesInV(self, startAngle: float, endAngle: float) -> None: ...

class UInt32Collection:
    """.NET: Autodesk.AutoCAD.Geometry.UInt32Collection"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: int
    IsReadOnly: bool
    IsFixedSize: bool
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: int) -> int: ...
    def AddRange(self, range: list) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: int) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> UInt32CollectionEnumerator: ...
    def IndexOf(self, value: int) -> int: ...
    def Insert(self, index: int, value: int) -> None: ...
    def Remove(self, value: int) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimToSize(self, ) -> None: ...

class UInt32CollectionEnumerator:
    """.NET: Autodesk.AutoCAD.Geometry.UInt32CollectionEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: int
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class Vector2d:
    """.NET: Autodesk.AutoCAD.Geometry.Vector2d"""
    def __init__(self, *args) -> None: ...
    LengthSqrd: float
    Length: float
    Angle: float
    Coordinate: float
    Y: float
    X: float
    YAxis: Vector2d
    XAxis: Vector2d
    def Add(self, v: Vector2d) -> Vector2d: ...
    def DivideBy(self, value: float) -> Vector2d: ...
    def DotProduct(self, v: Vector2d) -> float: ...
    def Equals(self, obj: object) -> bool: ...
    def GetAngleTo(self, vector: Vector2d) -> float: ...
    def GetHashCode(self, ) -> int: ...
    def GetNormal(self, tolerance: Tolerance) -> Vector2d: ...
    def GetPerpendicularVector(self, ) -> Vector2d: ...
    def IsCodirectionalTo(self, vector: Vector2d, tolerance: Tolerance) -> bool: ...
    def IsEqualTo(self, vector: Vector2d, tolerance: Tolerance) -> bool: ...
    def IsParallelTo(self, vector: Vector2d, tolerance: Tolerance) -> bool: ...
    def IsPerpendicularTo(self, vector: Vector2d, tolerance: Tolerance) -> bool: ...
    def IsUnitLength(self, tolerance: Tolerance) -> bool: ...
    def IsZeroLength(self, tolerance: Tolerance) -> bool: ...
    def Mirror(self, line: Vector2d) -> Vector2d: ...
    def MultiplyBy(self, value: float) -> Vector2d: ...
    def Negate(self, ) -> Vector2d: ...
    def RotateBy(self, angle: float) -> Vector2d: ...
    def Subtract(self, v: Vector2d) -> Vector2d: ...
    def ToArray(self, ) -> list: ...
    def ToString(self, format: str, provider: IFormatProvider) -> str: ...
    def TransformBy(self, leftSide: Matrix2d) -> Vector2d: ...

class Vector2dCollection:
    """.NET: Autodesk.AutoCAD.Geometry.Vector2dCollection"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: Vector2d
    IsReadOnly: bool
    IsFixedSize: bool
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: Vector2d) -> int: ...
    def AddRange(self, range: list) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Vector2d) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> Vector2dCollectionEnumerator: ...
    def IndexOf(self, value: Vector2d) -> int: ...
    def Insert(self, index: int, value: Vector2d) -> None: ...
    def Remove(self, value: Vector2d) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimToSize(self, ) -> None: ...

class Vector2dCollectionEnumerator:
    """.NET: Autodesk.AutoCAD.Geometry.Vector2dCollectionEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: Vector2d
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class Vector3d:
    """.NET: Autodesk.AutoCAD.Geometry.Vector3d"""
    def __init__(self, *args) -> None: ...
    LargestElement: int
    LengthSqrd: float
    Length: float
    Coordinate: float
    ZAxis: Vector3d
    YAxis: Vector3d
    XAxis: Vector3d
    Z: float
    Y: float
    X: float
    def Add(self, v: Vector3d) -> Vector3d: ...
    def AngleOnPlane(self, plane: PlanarEntity) -> float: ...
    def Convert2d(self, plane: PlanarEntity) -> Vector2d: ...
    def CrossProduct(self, vector: Vector3d) -> Vector3d: ...
    def DivideBy(self, value: float) -> Vector3d: ...
    def DotProduct(self, v: Vector3d) -> float: ...
    def Equals(self, obj: object) -> bool: ...
    def GetAngleTo(self, vector: Vector3d, referenceVector: Vector3d) -> float: ...
    def GetHashCode(self, ) -> int: ...
    def GetNormal(self, tolerance: Tolerance) -> Vector3d: ...
    def GetPerpendicularVector(self, ) -> Vector3d: ...
    def IsCodirectionalTo(self, vector: Vector3d, tolerance: Tolerance) -> bool: ...
    def IsEqualTo(self, vector: Vector3d, tolerance: Tolerance) -> bool: ...
    def IsParallelTo(self, vector: Vector3d, tolerance: Tolerance) -> bool: ...
    def IsPerpendicularTo(self, vector: Vector3d, tolerance: Tolerance) -> bool: ...
    def IsUnitLength(self, tolerance: Tolerance) -> bool: ...
    def IsZeroLength(self, tolerance: Tolerance) -> bool: ...
    def Mirror(self, normalToPlane: Vector3d) -> Vector3d: ...
    def MultiplyBy(self, value: float) -> Vector3d: ...
    def Negate(self, ) -> Vector3d: ...
    def OrthoProjectTo(self, planeNormal: Vector3d) -> Vector3d: ...
    def ProjectTo(self, planeNormal: Vector3d, projectDirection: Vector3d) -> Vector3d: ...
    def RotateBy(self, angle: float, axis: Vector3d) -> Vector3d: ...
    def Subtract(self, v: Vector3d) -> Vector3d: ...
    def ToArray(self, ) -> list: ...
    def ToString(self, format: str, provider: IFormatProvider) -> str: ...
    def TransformBy(self, leftSide: Matrix3d) -> Vector3d: ...

class Vector3dCollection:
    """.NET: Autodesk.AutoCAD.Geometry.Vector3dCollection"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: Vector3d
    IsReadOnly: bool
    IsFixedSize: bool
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: Vector3d) -> int: ...
    def AddRange(self, range: list) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Vector3d) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> Vector3dCollectionEnumerator: ...
    def IndexOf(self, value: Vector3d) -> int: ...
    def Insert(self, index: int, value: Vector3d) -> None: ...
    def Remove(self, value: Vector3d) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimToSize(self, ) -> None: ...

class Vector3dCollectionEnumerator:
    """.NET: Autodesk.AutoCAD.Geometry.Vector3dCollectionEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: Vector3d
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...
