# Auto-generated — Civil 26 — Autodesk.AutoCAD.GraphicsSystem

class CertificationData:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.CertificationData"""
    def __init__(self, *args) -> None: ...
    HardwareID: int
    CertificationStatus: int
    SoftwareFeatureLevel: int
    HardwareFeatureLevel: int
    FailedDevices: str
    TuningDate: str
    ProductDriverURL: str
    DriverVersion: str
    CardName: str

class ClientViewInfo:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ClientViewInfo"""
    def __init__(self, *args) -> None: ...
    ViewportObjectId: int
    AcadWindowId: int
    ViewportId: int

class ConfigWasModifiedEventHandler:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ConfigWasModifiedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class Configuration(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.GraphicsSystem.Configuration"""
    def __init__(self, *args) -> None: ...
    GenerateVertexNormals: bool
    Transparency: Quality
    DiscardBackFaces: bool
    Handedness: Handedness
    RedrawOnWindowExpose: bool
    AdaptiveDegradation: bool
    FrameRate: int
    CurveTessellationTolerance: int
    SurfaceTessellationTolerance: int
    MaxLODs: int
    DynamicTessellation: bool
    DefaultHardwareAcceleratedDriver: DriverInfo
    HardwareAcceleratedDriver: DriverInfo
    CurrentDisplayDriver: DriverInfo
    DriverSearchPath: str
    DriverRevision: int
    DriverVersion: int
    DriverName: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Configure(self, ) -> bool: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Configuration: ...
    def DegradationChainPosition(self, channel: DegradationChannel) -> int: ...
    def DegradationChannelAt(self, order: int) -> DegradationChannel: ...
    def GetCanDegradeChannel(self, channel: DegradationChannel) -> bool: ...
    def GetCertificationData(self, ) -> CertificationData: ...
    def GetEffectList(self, type: EffectListType) -> List: ...
    def GetFeatureAvailableVal(self, A_0: int) -> int: ...
    def GetFeatureMode(self, ) -> FeatureModeType: ...
    def GetFeatureModeAvailable(self, ) -> int: ...
    def GetFeatureRecommendedVal(self, A_0: int) -> int: ...
    def GetFeatureUsedVal(self, A_0: int) -> int: ...
    def GetHardwareAcceleratedDrivers(self, ) -> list: ...
    def GetVirtualDeviceName(self, ) -> str: ...
    def IsFeatureAvailable(self, A_0: int) -> bool: ...
    def IsFeatureEnabled(self, A_0: int) -> bool: ...
    def IsFeatureRecommended(self, A_0: int) -> bool: ...
    def IsHardwareAccelerationAvailable(self, ) -> bool: ...
    def IsHardwareAccelerationEnabled(self, ) -> bool: ...
    def IsHardwareAccelerationRecommended(self, ) -> bool: ...
    def IsInConfiguring(self, ) -> bool: ...
    def IsNoHardwareOverrideEnabled(self, ) -> bool: ...
    def Restore(self, ) -> None: ...
    def SaveToRegistry(self, ) -> None: ...
    def SetCanDegradeChannel(self, channel: DegradationChannel, degrade: bool) -> None: ...
    def SetFeatureEnabled(self, __unnamed000: int, enable: bool) -> None: ...
    def SetFeatureMode(self, type: FeatureModeType) -> None: ...
    def SetFeatureUsedVal(self, __unnamed000: int, value: int) -> None: ...
    def ShiftDegradationChainPosition(self, channel: DegradationChannel, shiftDown: bool) -> None: ...
    def ShowConfigDialog(self, dlgType: str) -> bool: ...
    def setHardwareAcceleration(self, bEnable: bool) -> None: ...

class DefaultLightingType:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.DefaultLightingType"""
    def __init__(self, *args) -> None: ...
    ...

class DegradationChannel:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.DegradationChannel"""
    def __init__(self, *args) -> None: ...
    ...

class Device(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.GraphicsSystem.Device"""
    def __init__(self, *args) -> None: ...
    DeviceRenderType: RendererType
    BackgroundColor: Color
    IsValid: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Add(self, view: View) -> bool: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool, graphicsKernelPointer: IntPtr) -> Device: ...
    def Erase(self, view: View) -> bool: ...
    def EraseAll(self, ) -> None: ...
    def GetSnapshot(self, rectangle: Rectangle) -> Bitmap: ...
    def Invalidate(self, rect: Rectangle) -> None: ...
    def OnDisplayChange(self, bitsPerPixel: int, xRes: int, yRes: int) -> None: ...
    def OnRealizeBackgroundPalette(self, ) -> None: ...
    def OnRealizeForegroundPalette(self, ) -> None: ...
    def OnSize(self, size: Size) -> None: ...
    def SetLogicalPalette(self, palette: list) -> None: ...
    def SetPhysicalPalette(self, palette: list) -> None: ...
    def Update(self, updatedRect: Rectangle) -> None: ...

class DeviceType:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.DeviceType"""
    def __init__(self, *args) -> None: ...
    ...

class DriverInfo:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.DriverInfo"""
    def __init__(self, *args) -> None: ...
    Driver: str
    Path: str
    HardwareAccelerated: bool

class EffectListType:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.EffectListType"""
    def __init__(self, *args) -> None: ...
    ...

class EffectStatus:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.EffectStatus"""
    def __init__(self, *args) -> None: ...
    FeatureLevel: int
    Enabled: int
    Recommended: int
    Available: int
    EffectName: str
    EffectUniqueString: int

class ErrorStatus:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ErrorStatus"""
    def __init__(self, *args) -> None: ...
    ...

class FeatureModeType:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.FeatureModeType"""
    def __init__(self, *args) -> None: ...
    ...

class GetInterfaceFunction:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.GetInterfaceFunction"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, objectId: int, bNeedsValidation: bool, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> Drawable: ...
    def Invoke(self, objectId: int, bNeedsValidation: bool) -> Drawable: ...

class GraphicsKernel(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.GraphicsSystem.GraphicsKernel"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class GsToBeUnloadedEventHandler:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.GsToBeUnloadedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class Handedness:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.Handedness"""
    def __init__(self, *args) -> None: ...
    ...

class HighlightStyle:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.HighlightStyle"""
    def __init__(self, *args) -> None: ...
    ...

class InvalidationHint:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.InvalidationHint"""
    def __init__(self, *args) -> None: ...
    ...

class KernelDescriptor(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.GraphicsSystem.KernelDescriptor"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def addRequirement(self, A_0: int) -> None: ...
    def supports(self, A_0: int) -> bool: ...

class LinePattern:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.LinePattern"""
    def __init__(self, *args) -> None: ...
    ...

class LineWeight:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.LineWeight"""
    def __init__(self, *args) -> None: ...
    ...

class Manager(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.GraphicsSystem.Manager"""
    def __init__(self, *args) -> None: ...
    ActiveModels: list
    ActiveGraphicsKernels: list
    DeviceIndependentDisplaySize: Size
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def AcquireGraphicsKernel(desc: KernelDescriptor) -> GraphicsKernel: ...
    def CreateAutoCADDevice(self, __unnamed000: GraphicsKernel, hwnd: IntPtr) -> Device: ...
    def CreateAutoCADModel(self, A_0: GraphicsKernel) -> Model: ...
    def CreateAutoCADOffScreenDevice(self, A_0: GraphicsKernel) -> Device: ...
    def CreateAutoCADView(self, __unnamed000: GraphicsKernel, drawable: Drawable) -> View: ...
    def CreateAutoCADViewport(self, __unnamed000: GraphicsKernel, vp: ViewportTableRecord) -> View: ...
    def CreateView(self, A_0: Device) -> View: ...
    def CreateViewport(self, __unnamed000: Device, vp: ViewportTableRecord) -> View: ...
    def DestroyView(self, view: View, vp: ViewportTableRecord) -> None: ...
    def GetActiveModels(self, db: Database) -> list: ...
    def GetCurrent3dAcGsView(self, viewportNumber: int) -> View: ...
    def GetCurrentAcGsView(self, viewportNumber: int) -> View: ...
    def GetDBModel(self, A_0: GraphicsKernel) -> Model: ...
    def GetGUIDevice(self, A_0: GraphicsKernel) -> Device: ...
    def GetGsModel(self, mode: TransientDrawingMode, subDrawingMode: int, viewportNumber: int) -> Model: ...
    def GetOffScreenDevice(self, A_0: GraphicsKernel) -> Device: ...
    def GetOffScreenView(self, A_0: GraphicsKernel, A_1: ClientViewInfo) -> View: ...
    def ObtainAcGsView(self, viewportNumber: int, createIfNone: KernelDescriptor) -> View: ...
    @staticmethod
    def ReleaseGraphicsKernel(kernel: GraphicsKernel) -> None: ...
    def SetViewFromViewport(self, view: View, viewportNumber: int) -> None: ...
    def SetViewportFromView(self, viewportNumber: int, view: View, regenRequired: bool, rescaleRequired: bool, syncRequired: bool) -> None: ...

class Model(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.GraphicsSystem.Model"""
    def __init__(self, *args) -> None: ...
    Selectable: bool
    ShadowPlaneLocation: float
    RenderType: RenderType
    SectioningVisualStyle: ObjectId
    EnableSectioning: bool
    LinetypesEnabled: bool
    BackgroundId: ObjectId
    VisualStyle: VisualStyle
    VisualStyleId: ObjectId
    ViewClippingOverride: bool
    Transform: Matrix3d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def AddSceneGraphRoot(self, pRoot: Drawable) -> bool: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool, graphicsKernelPointer: IntPtr) -> Model: ...
    def EraseSceneGraphRoot(self, pRoot: Drawable) -> bool: ...
    def Invalidate(self, hint: InvalidationHint) -> None: ...
    def OnAdded(self, added: Drawable, parentId: int) -> None: ...
    def OnErased(self, erased: Drawable, parentId: int) -> None: ...
    def OnModified(self, modified: Drawable, parentId: int) -> None: ...
    def OnPaletteModified(self, ) -> None: ...
    def SetExtents(self, point3dx: Point3d, point3dy: Point3d) -> None: ...
    def SetSectioning(self, pts: Point3dCollection, upVector: Vector3d, top: float, bottom: float) -> bool: ...

class Node(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.GraphicsSystem.Node"""
    def __init__(self, *args) -> None: ...
    Drawable: Drawable
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Projection:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.Projection"""
    def __init__(self, *args) -> None: ...
    ...

class Quality:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.Quality"""
    def __init__(self, *args) -> None: ...
    ...

class ReleaseInterfaceFunction:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ReleaseInterfaceFunction"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, __unnamed000: Drawable, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, A_0: Drawable) -> None: ...

class RenderType:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.RenderType"""
    def __init__(self, *args) -> None: ...
    ...

class RendererType:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.RendererType"""
    def __init__(self, *args) -> None: ...
    ...

class StereoParameters:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.StereoParameters"""
    def __init__(self, *args) -> None: ...
    Parallax: float
    Magnitude: float

class View(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.GraphicsSystem.View"""
    def __init__(self, *args) -> None: ...
    BackgroundId: ObjectId
    VisualStyle: VisualStyle
    VisualStyleId: ObjectId
    Device: Device
    StereoParameters: StereoParameters
    EnableStereo: bool
    ExceededBounds: bool
    IsVisible: bool
    IsInteractive: bool
    IsValid: bool
    ObjectToDeviceMatrix: Matrix3d
    WorldToDeviceMatrix: Matrix3d
    ScreenMatrix: Matrix3d
    ProjectionMatrix: Matrix3d
    ViewingMatrix: Matrix3d
    BackClip: float
    EnableBackClip: bool
    FrontClip: float
    EnableFrontClip: bool
    FieldHeight: float
    FieldWidth: float
    IsPerspective: bool
    UpVector: Vector3d
    Target: Point3d
    Position: Point3d
    ViewportBorderVisibility: bool
    ViewportBorderProperties: ViewportBorderProperties
    ViewportExtents: Extents2d
    ViewportObjectId: ObjectId
    AcadWindowId: int
    ViewportId: IntPtr
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Add(self, drawable: Drawable, model: Model) -> bool: ...
    def BeginInteractivity(self, frameRateInHZ: float) -> None: ...
    def ClearFrozenLayers(self, ) -> None: ...
    def Clone(self, cloneViewParameters: bool, cloneGeometry: bool) -> View: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool, autoCADView: bool, graphicsKernelPointer: IntPtr) -> View: ...
    def Dolly(self, x: float, y: float, z: float) -> None: ...
    def EnableDefaultLighting(self, bEnable: bool, type: DefaultLightingType) -> None: ...
    def EndInteractivity(self, ) -> None: ...
    def Erase(self, drawable: Drawable) -> bool: ...
    def EraseAll(self, ) -> None: ...
    def ExtentsInView(self, minPoint: Point3d, maxPoint: Point3d) -> bool: ...
    def Flush(self, ) -> None: ...
    def FreezeLayer(self, layerId: IntPtr) -> None: ...
    def GetModel(self, drw: Drawable) -> Model: ...
    def GetModelList(self, ) -> list: ...
    def GetNumPixelsInUnitSquare(self, givenWorldpt: Point3d, includePerspective: bool) -> Point2d: ...
    def GetSnapshot(self, rectangle: Rectangle) -> Bitmap: ...
    def Hide(self, ) -> None: ...
    def Invalidate(self, rect: Rectangle) -> None: ...
    def InvalidateCachedViewportGeometry(self, ) -> None: ...
    def Orbit(self, x: float, y: float) -> None: ...
    def Pan(self, x: float, y: float) -> None: ...
    def PointInView(self, point: Point3d) -> bool: ...
    def RemoveViewportClipRegion(self, ) -> None: ...
    def RenderToImage(self, settings: Drawable, rectScreen: Rectangle, flipImage: bool) -> Bitmap: ...
    def Roll(self, angle: float) -> None: ...
    def SetView(self, position: Point3d, target: Point3d, upVector: Vector3d, fieldWidth: float, fieldHeight: float, projection: Projection) -> None: ...
    def SetViewportClipRegion(self, contours: int, counts: list, points: list) -> None: ...
    def Show(self, ) -> None: ...
    def ThawLayer(self, layerId: IntPtr) -> None: ...
    def Update(self, ) -> None: ...
    def Zoom(self, factor: float) -> None: ...
    def ZoomExtents(self, minPoint: Point3d, maxPoint: Point3d) -> None: ...
    def ZoomWindow(self, lowerLeft: Point2d, upperRight: Point2d) -> None: ...

class ViewEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ViewEventArgs"""
    def __init__(self, *args) -> None: ...
    View: View

class ViewToBeDestroyedEventHandler:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ViewToBeDestroyedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: ViewEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: ViewEventArgs) -> None: ...

class ViewToBeUpdatedEventHandler:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ViewToBeUpdatedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: ViewUpdateEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: ViewUpdateEventArgs) -> None: ...

class ViewUpdateEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ViewUpdateEventArgs"""
    def __init__(self, *args) -> None: ...
    viewUpdateFlags: ViewUpdateFlags
    View: View

class ViewUpdateFlags:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ViewUpdateFlags"""
    def __init__(self, *args) -> None: ...
    ...

class ViewWasCreatedEventHandler:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ViewWasCreatedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: ViewEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: ViewEventArgs) -> None: ...

class ViewWasUpdatedEventHandler:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ViewWasUpdatedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: ViewUpdateEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: ViewUpdateEventArgs) -> None: ...

class ViewportBorderProperties:
    """.NET: Autodesk.AutoCAD.GraphicsSystem.ViewportBorderProperties"""
    def __init__(self, *args) -> None: ...
    Weight: int
    Color: Color
