# Auto-generated — Civil 26 — Autodesk.AutoCAD.Publishing

class AboutToBeginBackgroundPublishingEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Publishing.AboutToBeginBackgroundPublishingEventArgs"""
    def __init__(self, *args) -> None: ...
    JobWillPublishInBackground: bool
    DsdData: DsdData
    def ReadPrivateSection(self, sectionName: str) -> IDictionaryEnumerator: ...
    def WritePrivateSection(self, sectionName: str, data: IDictionaryEnumerator) -> None: ...

class AboutToBeginBackgroundPublishingEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.AboutToBeginBackgroundPublishingEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: AboutToBeginBackgroundPublishingEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: AboutToBeginBackgroundPublishingEventArgs) -> None: ...

class AboutToBeginPublishingEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Publishing.AboutToBeginPublishingEventArgs"""
    def __init__(self, *args) -> None: ...
    PlotLogger: PlotLogger
    JobWillPublishInBackground: bool
    DsdData: DsdData
    def ReadPrivateSection(self, sectionName: str) -> IDictionaryEnumerator: ...
    def WritePrivateSection(self, sectionName: str, data: IDictionaryEnumerator) -> None: ...

class AboutToBeginPublishingEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.AboutToBeginPublishingEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: AboutToBeginPublishingEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: AboutToBeginPublishingEventArgs) -> None: ...

class AboutToEndPublishingEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.AboutToEndPublishingEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PublishEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PublishEventArgs) -> None: ...

class AboutToMoveFileEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.AboutToMoveFileEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PublishEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PublishEventArgs) -> None: ...

class BeginAggregationEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Publishing.BeginAggregationEventArgs"""
    def __init__(self, *args) -> None: ...
    DwfPassword: str
    DwfFileName: str
    PlotLogger: PlotLogger
    def AddGlobalPropertyRange(self, properties: list) -> None: ...
    def AddGlobalResourceRange(self, resources: list) -> None: ...

class BeginAggregationEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.BeginAggregationEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: BeginAggregationEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: BeginAggregationEventArgs) -> None: ...

class BeginEntityEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.BeginEntityEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PublishEntityEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PublishEntityEventArgs) -> None: ...

class BeginPublishingSheetEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Publishing.BeginPublishingSheetEventArgs"""
    def __init__(self, *args) -> None: ...
    PlotLogger: PlotLogger
    UniqueId: str
    DsdEntry: DsdEntry

class BeginPublishingSheetEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.BeginPublishingSheetEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: BeginPublishingSheetEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: BeginPublishingSheetEventArgs) -> None: ...

class BeginSheetEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.BeginSheetEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PublishSheetEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PublishSheetEventArgs) -> None: ...

class CancelledOrFailedPublishingEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.CancelledOrFailedPublishingEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PublishEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PublishEventArgs) -> None: ...

class Dwf3dNavigationTreeNode(RXObject):
    """.NET: Autodesk.AutoCAD.Publishing.Dwf3dNavigationTreeNode"""
    def __init__(self, *args) -> None: ...
    IsBlock: bool
    Children: Dwf3dNavigationTreeNodeCollection
    IsGroup: bool
    DisplayName: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def GetKeys(self, ) -> list: ...
    def SetKeys(self, keys: list) -> None: ...

class Dwf3dNavigationTreeNodeCollection:
    """.NET: Autodesk.AutoCAD.Publishing.Dwf3dNavigationTreeNodeCollection"""
    def __init__(self, *args) -> None: ...
    Item: Dwf3dNavigationTreeNode
    Count: int
    def Add(self, node: Dwf3dNavigationTreeNode) -> None: ...
    def Remove(self, node: Dwf3dNavigationTreeNode) -> None: ...

class DwfNode:
    """.NET: Autodesk.AutoCAD.Publishing.DwfNode"""
    def __init__(self, *args) -> None: ...
    NodeName: str
    NodeId: int

class EPlotAttribute:
    """.NET: Autodesk.AutoCAD.Publishing.EPlotAttribute"""
    def __init__(self, *args) -> None: ...
    Value: str
    Name: str
    NsUrl: str
    Ns: str

class EPlotAttributeCollection:
    """.NET: Autodesk.AutoCAD.Publishing.EPlotAttributeCollection"""
    def __init__(self, *args) -> None: ...
    Item: EPlotAttribute
    Count: int
    SyncRoot: object
    IsSynchronized: bool
    def Add(self, value: EPlotAttribute) -> None: ...
    def Clear(self, ) -> None: ...
    def CopyTo(self, array: Array, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class EPlotProperty:
    """.NET: Autodesk.AutoCAD.Publishing.EPlotProperty"""
    def __init__(self, *args) -> None: ...
    Attributes: EPlotAttributeCollection
    Value: str
    Name: str
    Category: str
    Units: str
    Type: str
    def AddEPlotAttribute(self, ns: str, nsUrl: str, attName: str, attValue: str) -> None: ...
    def AddEplotAttribute(self, att: EPlotAttribute) -> None: ...

class EPlotPropertyBag:
    """.NET: Autodesk.AutoCAD.Publishing.EPlotPropertyBag"""
    def __init__(self, *args) -> None: ...
    Properties: EPlotPropertyCollection
    References: StringCollection
    NamespaceLocation: str
    NamespaceUrl: str
    Id: str

class EPlotPropertyCollection:
    """.NET: Autodesk.AutoCAD.Publishing.EPlotPropertyCollection"""
    def __init__(self, *args) -> None: ...
    Item: EPlotProperty
    Count: int
    SyncRoot: object
    IsSynchronized: bool
    def Add(self, value: EPlotProperty) -> None: ...
    def Clear(self, ) -> None: ...
    def CopyTo(self, array: Array, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class EPlotResource:
    """.NET: Autodesk.AutoCAD.Publishing.EPlotResource"""
    def __init__(self, *args) -> None: ...
    Path: str
    Mime: str
    Role: str

class EndEntityEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.EndEntityEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PublishEntityEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PublishEntityEventArgs) -> None: ...

class EndPublishEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.EndPublishEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PublishEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PublishEventArgs) -> None: ...

class EndSheetEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.EndSheetEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PublishSheetEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PublishSheetEventArgs) -> None: ...

class InitPublishOptionsDialogEventHandler:
    """.NET: Autodesk.AutoCAD.Publishing.InitPublishOptionsDialogEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PublishUIEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PublishUIEventArgs) -> None: ...

class OptionsDialogResult:
    """.NET: Autodesk.AutoCAD.Publishing.OptionsDialogResult"""
    def __init__(self, *args) -> None: ...
    PlotConfig: PlotConfig
    DsdData: DsdData
    Status: Nullable

class PublishEntityEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Publishing.PublishEntityEventArgs"""
    def __init__(self, *args) -> None: ...
    EffectiveBlockLayerId: ObjectId
    Entity: Entity
    UniqueEntityId: str
    IsCancelled: bool
    PlotLogger: PlotLogger
    def Add3DDwfProperty(self, category: str, name: str, value: str) -> bool: ...
    def AddNodeToMap(self, entityId: ObjectId, objIds: ObjectIdCollection, nodeId: int) -> bool: ...
    def AddPropertiesIds(self, properties: EPlotPropertyBag, node: DwfNode) -> bool: ...
    def AddPropertyBag(self, properties: EPlotPropertyBag) -> bool: ...
    def Cancel(self, ) -> None: ...
    def Flush(self, ) -> None: ...
    def GetCurrentEntityNode(self, objIds: ObjectIdCollection) -> DwfNode: ...
    def GetEntityNode(self, entityId: ObjectId, objIds: ObjectIdCollection) -> int: ...
    def GetGraphicIDs(self, ) -> list: ...
    def GetNextAvailableNode(self, ) -> int: ...
    def GetNode(self, nodeId: int) -> DwfNode: ...
    def SetCurrentNode(self, nodeId: int, objIds: ObjectIdCollection) -> bool: ...
    def SetNodeName(self, nodeId: int, nodeName: str) -> bool: ...
    def getEntityBlockRefPath(self, ) -> ObjectIdCollection: ...

class PublishEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Publishing.PublishEventArgs"""
    def __init__(self, *args) -> None: ...
    IsMultiSheetDwf: bool
    DwfPassword: str
    TemporaryDwfFileName: str
    DwfFileName: str

class PublishSheetEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Publishing.PublishSheetEventArgs"""
    def __init__(self, *args) -> None: ...
    Dwf3dNavigationTreeNode: Dwf3dNavigationTreeNode
    PublishingTo3DDwf: bool
    EffectivePlotOffsetYDevice: int
    EffectivePlotOffsetXDevice: int
    EffectivePlotOffsetY: float
    EffectivePlotOffsetX: float
    LayoutBoundsMaxY: float
    LayoutBoundsMaxX: float
    LayoutBoundsMinY: float
    LayoutBoundsMinX: float
    PlotBoundsMaxY: float
    PlotBoundsMaxX: float
    PlotBoundsMinY: float
    PlotBoundsMinX: float
    CanonicalMediaName: str
    PlotToFileName: str
    PlotToFilePath: str
    Configuration: str
    StepsPerInch: float
    MaxBoundsY: float
    MaxBoundsX: float
    PrintableBoundsY: float
    PrintableBoundsX: float
    LayoutMarginMaxY: float
    LayoutMarginMaxX: float
    LayoutMarginMinY: float
    LayoutMarginMinX: float
    DisplayMaxY: float
    DisplayMaxX: float
    DisplayMinY: float
    DisplayMinX: float
    AreScalingLineWeights: bool
    ArePlottingLineWeights: bool
    AreLinesHidden: bool
    IsScaleSpecified: bool
    ViewPlotted: str
    PlotWindowMaxY: float
    PlotWindowMaxX: float
    PlotWindowMinY: float
    PlotWindowMinX: float
    OriginY: float
    OriginX: float
    DrawingScale: float
    PaperScale: float
    PlotPaperUnit: PlotPaperUnit
    PlotRotation: PlotRotation
    PlotType: PlotType
    IsModelLayout: bool
    PlotLayoutId: ObjectId
    UniqueLayoutId: str
    IsPlotJobCancelled: bool
    Database: Database
    PlotLogger: PlotLogger
    def AddPagePropertyRange(self, properties: list) -> None: ...
    def AddPageResourceRange(self, resources: list) -> None: ...

class PublishUIEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Publishing.PublishUIEventArgs"""
    def __init__(self, *args) -> None: ...
    JobWillPublishInBackground: bool
    DsdData: DsdData
    IUnknown: IUnknown
    def ReadPrivateSection(self, sectionName: str) -> IDictionaryEnumerator: ...
    def WritePrivateSection(self, sectionName: str, data: IDictionaryEnumerator) -> None: ...

class Publisher(MarshalByRefObject):
    """.NET: Autodesk.AutoCAD.Publishing.Publisher"""
    def __init__(self, *args) -> None: ...
    CurrentPublishedSheetSetPath: str
    def FireAboutToBeginBackgroundPublishing(self, e: AboutToBeginBackgroundPublishingEventArgs) -> None: ...
    def FireAboutToBeginPublishing(self, e: AboutToBeginPublishingEventArgs) -> None: ...
    def FireAboutToEndPublishing(self, e: PublishEventArgs) -> None: ...
    def FireAboutToMoveFile(self, e: PublishEventArgs) -> None: ...
    def FireBeginAggregation(self, e: BeginAggregationEventArgs) -> None: ...
    def FireBeginEntity(self, e: PublishEntityEventArgs) -> None: ...
    def FireBeginPublishingSheet(self, e: BeginPublishingSheetEventArgs) -> None: ...
    def FireBeginSheet(self, e: PublishSheetEventArgs) -> None: ...
    def FireCancelledOrFailedPublishing(self, e: PublishEventArgs) -> None: ...
    def FireEndEntity(self, e: PublishEntityEventArgs) -> None: ...
    def FireEndPublish(self, e: PublishEventArgs) -> None: ...
    def FireEndSheet(self, e: PublishSheetEventArgs) -> None: ...
    def FireInitPublishOptionsDialog(self, e: PublishUIEventArgs) -> None: ...
    def PublishDsd(self, dsdFile: str, plotProgressDialog: PlotProgressDialog) -> int: ...
    def PublishExecute(self, dsdData: DsdData, plotConfig: PlotConfig) -> None: ...
    def PublishSelectedLayouts(self, bOverride: bool) -> None: ...
    def ShowDwfOptionsDialog(self, dsdData: DsdData, plotConfig: PlotConfig, optionsDialogTitle: str) -> OptionsDialogResult: ...
    def ShowPublishDialog(self, dsdData: DsdData, plotConfig: PlotConfig, namePageSetups: StringCollection, namePageSetupPaths: StringCollection, optionsDialogTitle: str, optionsButtonText: str) -> None: ...
