# Auto-generated — Civil 26 — Autodesk.AutoCAD.Runtime

class AngularUnitFormat:
    """.NET: Autodesk.AutoCAD.Runtime.AngularUnitFormat"""
    def __init__(self, *args) -> None: ...
    ...

class CommandClassAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.CommandClassAttribute"""
    def __init__(self, *args) -> None: ...
    Type: Type
    TypeId: object

class CommandFlags:
    """.NET: Autodesk.AutoCAD.Runtime.CommandFlags"""
    def __init__(self, *args) -> None: ...
    ...

class CommandMethodAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.CommandMethodAttribute"""
    def __init__(self, *args) -> None: ...
    HelpTopic: str
    HelpFileName: str
    ContextMenuExtensionType: Type
    Flags: CommandFlags
    GroupName: str
    LocalizedNameId: str
    GlobalName: str
    TypeId: object

class Converter:
    """.NET: Autodesk.AutoCAD.Runtime.Converter"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AngleToString(value: float, units: AngularUnitFormat, precision: int) -> str: ...
    @staticmethod
    def DistanceToString(value: float, units: DistanceUnitFormat, precision: int) -> str: ...
    @staticmethod
    def RawAngleToString(value: float, units: AngularUnitFormat, precision: int) -> str: ...
    @staticmethod
    def StringToAngle(value: str, units: AngularUnitFormat) -> float: ...
    @staticmethod
    def StringToDistance(value: str, units: DistanceUnitFormat) -> float: ...
    @staticmethod
    def StringToRawAngle(value: str, units: AngularUnitFormat) -> float: ...

class DeferredAssemblyLoadEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Runtime.DeferredAssemblyLoadEventArgs"""
    def __init__(self, *args) -> None: ...
    MayHaveCommands: bool
    MayHaveExtensionApplication: bool
    LoadedAssembly: Assembly

class DeferredAssemblyLoadEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.DeferredAssemblyLoadEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DeferredAssemblyLoadEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DeferredAssemblyLoadEventArgs) -> None: ...

class Dictionary(RXObject):
    """.NET: Autodesk.AutoCAD.Runtime.Dictionary"""
    def __init__(self, *args) -> None: ...
    Item: RXObject
    Count: int
    IsSorted: bool
    IsCaseSensitive: bool
    DeletesObjects: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def At(self, id: int) -> RXObject: ...
    def AtKeyAndIdPut(self, newKey: str, id: int, value: RXObject) -> None: ...
    def AtPut(self, key: str, value: RXObject, retId: int) -> RXObject: ...
    def Contains(self, id: int) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IDictionaryEnumerator: ...
    def IdAt(self, key: str) -> int: ...
    def KeyAt(self, id: int) -> str: ...
    def Remove(self, id: int) -> RXObject: ...
    def ResetKey(self, id: int, newKey: str) -> None: ...

class DisposableWrapper(MarshalByRefObject):
    """.NET: Autodesk.AutoCAD.Runtime.DisposableWrapper"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(type: Type, unmanagedPointer: IntPtr, autoDelete: bool) -> DisposableWrapper: ...
    def Dispose(self, ) -> None: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...

class DistanceUnitFormat:
    """.NET: Autodesk.AutoCAD.Runtime.DistanceUnitFormat"""
    def __init__(self, *args) -> None: ...
    ...

class DynamicLinker(RXObject):
    """.NET: Autodesk.AutoCAD.Runtime.DynamicLinker"""
    def __init__(self, *args) -> None: ...
    ProductLcid: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def GetLoadedModules(self, ) -> StringCollection: ...
    def IsAppBusy(self, moduleName: str) -> bool: ...
    def IsAppMdiAware(self, moduleName: str) -> bool: ...
    def IsApplicationLocked(self, moduleName: str) -> bool: ...
    def IsModuleLoaded(self, fileName: str) -> bool: ...
    def LoadApp(self, appName: str, printIt: bool, asCmd: bool) -> None: ...
    def LoadModule(self, fileName: str, printIt: bool, asCmd: bool) -> None: ...
    def SetAppBusy(self, moduleName: str, busyFlag: bool) -> None: ...
    def UnloadApp(self, appName: str, asCmd: bool) -> None: ...
    def UnloadModule(self, fileName: str, asCmd: bool) -> None: ...

class DynamicLinkerEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Runtime.DynamicLinkerEventArgs"""
    def __init__(self, *args) -> None: ...
    FileName: str

class EnvVarExistsConditionAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.EnvVarExistsConditionAttribute"""
    def __init__(self, *args) -> None: ...
    TypeId: object
    def Evaluate(self, ) -> bool: ...

class ErrorStatus:
    """.NET: Autodesk.AutoCAD.Runtime.ErrorStatus"""
    def __init__(self, *args) -> None: ...
    ...

class Exception(Exception):
    """.NET: Autodesk.AutoCAD.Runtime.Exception"""
    def __init__(self, *args) -> None: ...
    ErrorStatus: ErrorStatus
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...

class ExtensionApplicationAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.ExtensionApplicationAttribute"""
    def __init__(self, *args) -> None: ...
    Type: Type
    TypeId: object

class ExtensionLoader(MarshalByRefObject):
    """.NET: Autodesk.AutoCAD.Runtime.ExtensionLoader"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def IsLoaded(fileName: str) -> bool: ...
    @staticmethod
    def Load(fileName: str) -> Assembly: ...

class ExtractOption:
    """.NET: Autodesk.AutoCAD.Runtime.ExtractOption"""
    def __init__(self, *args) -> None: ...
    ...

class ExtractionType:
    """.NET: Autodesk.AutoCAD.Runtime.ExtractionType"""
    def __init__(self, *args) -> None: ...
    ...

class Factory:
    """.NET: Autodesk.AutoCAD.Runtime.Factory"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Create(type: Type) -> object: ...

class FileExistsConditionAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.FileExistsConditionAttribute"""
    def __init__(self, *args) -> None: ...
    TypeId: object
    def Evaluate(self, ) -> bool: ...

class FileHasClosedEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.FileHasClosedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, e: FileOperationsEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, e: FileOperationsEventArgs) -> None: ...

class FileOpenAbortedEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.FileOpenAbortedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, e: FileOperationsEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, e: FileOperationsEventArgs) -> None: ...

class FileOperations:
    """.NET: Autodesk.AutoCAD.Runtime.FileOperations"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class FileOperationsEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Runtime.FileOperationsEventArgs"""
    def __init__(self, *args) -> None: ...
    VetoStatus: VetoStatusType
    FilePath: str
    ReloadNested: bool
    ReloadPrimary: bool
    ReferenceFile: bool
    KnownToBeUnmodified: bool
    ReadOnly: bool
    def Dispose(self, ) -> None: ...
    def Veto(self, status: VetoStatusType) -> bool: ...

class FileWillOpenEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.FileWillOpenEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, e: FileOperationsEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, e: FileOperationsEventArgs) -> None: ...

class ICommandLineCallable:
    """.NET: Autodesk.AutoCAD.Runtime.ICommandLineCallable"""
    def __init__(self, *args) -> None: ...
    ContextMenuExtensionType: Type
    HelpTopic: str
    HelpFileName: str
    Flags: CommandFlags
    GroupName: str
    LocalizedNameId: str
    GlobalName: str

class ICondition:
    """.NET: Autodesk.AutoCAD.Runtime.ICondition"""
    def __init__(self, *args) -> None: ...
    def Evaluate(self, ) -> bool: ...

class IExtensionApplication:
    """.NET: Autodesk.AutoCAD.Runtime.IExtensionApplication"""
    def __init__(self, *args) -> None: ...
    def Initialize(self, ) -> None: ...
    def Terminate(self, ) -> None: ...

class IJavaScriptCallable:
    """.NET: Autodesk.AutoCAD.Runtime.IJavaScriptCallable"""
    def __init__(self, *args) -> None: ...
    EntryPoint: str

class IJavaScriptCallableInternal:
    """.NET: Autodesk.AutoCAD.Runtime.IJavaScriptCallableInternal"""
    def __init__(self, *args) -> None: ...
    EntryPoint: str

class IMenuItem:
    """.NET: Autodesk.AutoCAD.Runtime.IMenuItem"""
    def __init__(self, *args) -> None: ...
    Items: IEnumerable
    Icon: Icon
    Checked: bool
    Visible: bool
    Enabled: bool
    Text: str
    def OnClicked(self, eventArgs: EventArgs) -> None: ...

class IPointCloudExtractionProgressCallback:
    """.NET: Autodesk.AutoCAD.Runtime.IPointCloudExtractionProgressCallback"""
    def __init__(self, *args) -> None: ...
    def Cancel(self, ) -> None: ...
    def Cancelled(self, ) -> bool: ...
    def End(self, ) -> None: ...
    def UpdateCaption(self, caption: str) -> None: ...
    def UpdateProgress(self, progress: int) -> None: ...
    def UpdateRemainTime(self, remainTime: float) -> None: ...

class Interop:
    """.NET: Autodesk.AutoCAD.Runtime.Interop"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AttachUnmanagedObject(obj: DisposableWrapper, unmanagedPointer: IntPtr, autoDelete: bool) -> None: ...
    @staticmethod
    def Check(returnValue: int) -> None: ...
    @staticmethod
    def CheckAds(returnValue: int) -> None: ...
    @staticmethod
    def CheckAdsForCancel(returnValue: int) -> bool: ...
    @staticmethod
    def CheckBool(returnValue: bool) -> None: ...
    @staticmethod
    def CheckBoolean(returnValue: int) -> None: ...
    @staticmethod
    def CheckNull(returnValue: IntPtr) -> None: ...
    @staticmethod
    def DetachUnmanagedObject(obj: DisposableWrapper) -> None: ...
    @staticmethod
    def SetAutoDelete(obj: DisposableWrapper, value: bool) -> None: ...
    @staticmethod
    def ThrowExceptionForErrorStatus(errorStatus: int) -> None: ...

class JSInteropApplicationAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.JSInteropApplicationAttribute"""
    def __init__(self, *args) -> None: ...
    Type: Type
    TypeId: object

class JavaScriptCallableInternalAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.JavaScriptCallableInternalAttribute"""
    def __init__(self, *args) -> None: ...
    EntryPoint: str
    TypeId: object

class JavaScriptCallbackAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.JavaScriptCallbackAttribute"""
    def __init__(self, *args) -> None: ...
    EntryPoint: str
    TypeId: object

class JavaScriptClassAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.JavaScriptClassAttribute"""
    def __init__(self, *args) -> None: ...
    Type: Type
    TypeId: object

class LispDataType:
    """.NET: Autodesk.AutoCAD.Runtime.LispDataType"""
    def __init__(self, *args) -> None: ...
    ...

class LispFunctionAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.LispFunctionAttribute"""
    def __init__(self, *args) -> None: ...
    HelpTopic: str
    HelpFileName: str
    LocalizedNameId: str
    GlobalName: str
    TypeId: object

class Marshaler:
    """.NET: Autodesk.AutoCAD.Runtime.Marshaler"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AcValueToObject(acValueObj: IntPtr) -> object: ...
    @staticmethod
    def BitmapInfoToBitmap(bitmapInfo: IntPtr) -> Bitmap: ...
    @staticmethod
    def BitmapToBitmapInfo(bitmap: Bitmap) -> IntPtr: ...
    @staticmethod
    def CopyToManagedFullSubentityPath(path: IntPtr) -> FullSubentityPath: ...
    @staticmethod
    def CopyToUnmanagedFullSubentityPath(path: FullSubentityPath, newPath: IntPtr) -> None: ...
    @staticmethod
    def GetInternalArray(col: Vector3dCollection) -> list: ...
    @staticmethod
    def ObjectToAcValue(obj: object, acValueObj: IntPtr) -> None: ...
    @staticmethod
    def ObjectToResbuf(o: object, rb: IntPtr) -> None: ...
    @staticmethod
    def ObjectsToResbuf(objects: list) -> IntPtr: ...
    @staticmethod
    def ResbufToObject(rb: IntPtr) -> object: ...
    @staticmethod
    def ResbufToTypedValues(resbuf: IntPtr) -> list: ...
    @staticmethod
    def SetInternalArray(col: Vector3dCollection, newArray: list, count: int) -> None: ...
    @staticmethod
    def TypedValuesToResbuf(values: list) -> IntPtr: ...

class ModuleLoadAbortedEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.ModuleLoadAbortedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DynamicLinkerEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DynamicLinkerEventArgs) -> None: ...

class ModuleLoadedEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.ModuleLoadedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DynamicLinkerEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DynamicLinkerEventArgs) -> None: ...

class ModuleLoadingEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.ModuleLoadingEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DynamicLinkerEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DynamicLinkerEventArgs) -> None: ...

class ModuleUnloadAbortedEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.ModuleUnloadAbortedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DynamicLinkerEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DynamicLinkerEventArgs) -> None: ...

class ModuleUnloadedEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.ModuleUnloadedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DynamicLinkerEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DynamicLinkerEventArgs) -> None: ...

class ModuleUnloadingEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.ModuleUnloadingEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: DynamicLinkerEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: DynamicLinkerEventArgs) -> None: ...

class Overrule(RXObject):
    """.NET: Autodesk.AutoCAD.Runtime.Overrule"""
    def __init__(self, *args) -> None: ...
    Overruling: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def AddOverrule(targetClass: RXClass, overrule: Overrule, bAtLast: bool) -> None: ...
    @staticmethod
    def HasOverrule(overruledSubject: RXObject, targetClass: RXClass) -> bool: ...
    def IsApplicable(self, overruledSubject: RXObject) -> bool: ...
    @staticmethod
    def RemoveOverrule(targetClass: RXClass, overrule: Overrule) -> None: ...
    def SetCustomFilter(self, ) -> None: ...
    def SetExtensionDictionaryEntryFilter(self, entryName: str) -> None: ...
    def SetIdFilter(self, ids: list) -> None: ...
    def SetNoFilter(self, ) -> None: ...
    def SetXDataFilter(self, registeredApplicationName: str) -> None: ...

class PerDocumentClassAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.PerDocumentClassAttribute"""
    def __init__(self, *args) -> None: ...
    Type: Type
    TypeId: object

class PointCloudExtractResult:
    """.NET: Autodesk.AutoCAD.Runtime.PointCloudExtractResult"""
    def __init__(self, *args) -> None: ...
    ...

class PointCloudExtractor(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Runtime.PointCloudExtractor"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def AppendLineProfile(profile: PointCloudExtractResult, spaceId: ObjectId, layer: str, color: Color) -> ObjectIdCollection: ...
    @staticmethod
    def AppendPolylineProfile(profile: PointCloudExtractResult, spaceId: ObjectId, layer: str, color: Color, polylineWidth: float) -> ObjectIdCollection: ...
    @staticmethod
    def Extract(pointCloud: PointCloudEx, planZDirection: Vector3d, planXDirection: Vector3d, pointOnPlan: Point3d, extractOption: ExtractOption, progress: IPointCloudExtractionProgressCallback) -> PointCloudExtractResult: ...

class ProfileCurve2d(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Runtime.ProfileCurve2d"""
    def __init__(self, *args) -> None: ...
    Arc: CircularArc2d
    LineSeg: LineSegment2d
    IsArc: bool
    IsSegment: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class ProfileCurveType:
    """.NET: Autodesk.AutoCAD.Runtime.ProfileCurveType"""
    def __init__(self, *args) -> None: ...
    ...

class ProgressMeter(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Runtime.ProgressMeter"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def MeterProgress(self, ) -> None: ...
    def SetLimit(self, max: int) -> None: ...
    def Start(self, displayString: str) -> None: ...
    def Stop(self, ) -> None: ...

class RXClass(RXObject):
    """.NET: Autodesk.AutoCAD.Runtime.RXClass"""
    def __init__(self, *args) -> None: ...
    MyParent: RXClass
    ProxyFlags: int
    ClassVersion: Version
    Name: str
    DxfName: str
    AppName: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def AddX(self, runtimeClass: RXClass, protocolExtension: RXObject) -> IntPtr: ...
    def Create(self, ) -> RXObject: ...
    def DelX(self, runtimeClass: RXClass) -> IntPtr: ...
    def GetRuntimeType(self, ) -> Type: ...
    def GetX(self, runtimeClass: RXClass) -> IntPtr: ...
    def IsDerivedFrom(self, runtimeClass: RXClass) -> bool: ...
    def QueryX(self, runtimeClass: RXClass) -> IntPtr: ...

class RXObject(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Runtime.RXObject"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Clone(self, ) -> object: ...
    def CompareTo(self, obj: object) -> int: ...
    def CopyFrom(self, source: RXObject) -> None: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> RXObject: ...
    @staticmethod
    def GetClass(type: Type) -> RXClass: ...
    def GetRXClass(self, ) -> RXClass: ...
    def QueryX(self, protocolClass: RXClass) -> IntPtr: ...
    def X(self, protocolClass: RXClass) -> IntPtr: ...

class Registry:
    """.NET: Autodesk.AutoCAD.Runtime.Registry"""
    def __init__(self, *args) -> None: ...
    CurrentConfig: RegistryKey
    ClassesRoot: RegistryKey
    CurrentUser: RegistryKey
    LocalMachine: RegistryKey

class RegistryKey:
    """.NET: Autodesk.AutoCAD.Runtime.RegistryKey"""
    def __init__(self, *args) -> None: ...
    ValueCount: int
    SubKeyCount: int
    def Close(self, ) -> None: ...
    def CreateSubKey(self, subkey: str, permissionCheck: RegistryKeyPermissionCheck, registryOptions: RegistryOptions, registrySecurity: RegistrySecurity) -> RegistryKey: ...
    def DeleteSubKey(self, subkey: str) -> None: ...
    def DeleteSubKeyTree(self, subkey: str) -> None: ...
    def DeleteValue(self, name: str) -> None: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def GetBaseKey(hKey: RegistryHive) -> RegistryKey: ...
    def GetSubKeyNames(self, ) -> list: ...
    def GetValue(self, name: str, defaultValue: object, options: RegistryValueOptions) -> object: ...
    def GetValueKind(self, name: str) -> RegistryValueKind: ...
    def GetValueNames(self, ) -> list: ...
    @staticmethod
    def OpenBaseKey(hKey: RegistryHive, view: RegistryView) -> RegistryKey: ...
    def OpenSubKey(self, name: str, permissionCheck: RegistryKeyPermissionCheck, rights: RegistryRights) -> RegistryKey: ...
    def SetValue(self, name: str, value: object, kind: RegistryValueKind) -> None: ...

class RuntimeSystem:
    """.NET: Autodesk.AutoCAD.Runtime.RuntimeSystem"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Initialize(hostServices: HostApplicationServices, localId: int) -> None: ...
    @staticmethod
    def Main(arg: IntPtr, argLength: int) -> int: ...
    @staticmethod
    def Terminate() -> None: ...

class SecuredApplicationAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.SecuredApplicationAttribute"""
    def __init__(self, *args) -> None: ...
    ClientPublicKey: str
    ClientSignature: str
    OurSignature: str
    License: str
    TypeId: object

class ShowExceptionDialogHandler:
    """.NET: Autodesk.AutoCAD.Runtime.ShowExceptionDialogHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, e: Exception, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, e: Exception) -> None: ...

class SynchronizationContext(SynchronizationContext):
    """.NET: Autodesk.AutoCAD.Runtime.SynchronizationContext"""
    def __init__(self, *args) -> None: ...
    def CreateCopy(self, ) -> SynchronizationContext: ...
    def OperationCompleted(self, ) -> None: ...
    def OperationStarted(self, ) -> None: ...
    def Post(self, d: SendOrPostCallback, state: object) -> None: ...
    def Send(self, d: SendOrPostCallback, state: object) -> None: ...
    def Wait(self, waitHandles: list, waitAll: bool, millisecondsTimeout: int) -> int: ...

class SystemObjects:
    """.NET: Autodesk.AutoCAD.Runtime.SystemObjects"""
    def __init__(self, *args) -> None: ...
    Variables: Variables
    DynamicLinker: DynamicLinker
    ServiceDictionary: Dictionary
    ClassDictionary: Dictionary

class SystemVariableEnumerator(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Runtime.SystemVariableEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: Variable
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class UnhandledExceptionFilter:
    """.NET: Autodesk.AutoCAD.Runtime.UnhandledExceptionFilter"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CerOrShowExceptionDialog(e: Exception) -> None: ...

class Utilities:
    """.NET: Autodesk.AutoCAD.Runtime.Utilities"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetErrorStatus(eStatus: ErrorStatus) -> str: ...
    @staticmethod
    def GetRedirectedRegistryValue(subPath: str, propertyName: str) -> str: ...
    @staticmethod
    def GetRedirectedRegistryValueMap(subPath: str) -> IDictionary: ...
    @staticmethod
    def GetReservedString(reservedType: ReservedStringEnumType, bGetLocalized: bool) -> str: ...
    @staticmethod
    def TranslateReservedString(pGlobalName: str) -> str: ...

class Variable(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Runtime.Variable"""
    def __init__(self, *args) -> None: ...
    Range: RangeInfo
    TypeFlags: int
    Storage: StorageType
    SecondaryType: SecondaryTypeInfo
    PrimaryType: int
    Name: str
    IsLocked: bool
    IsReadOnly: bool
    Value: object
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Reset(self, ) -> None: ...

class VariableChangedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Runtime.VariableChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    NewValue: object
    OldValue: object
    def Dispose(self, ) -> None: ...

class VariableChangedEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.VariableChangedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: VariableChangedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: VariableChangedEventArgs) -> None: ...

class VariableChangingEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Runtime.VariableChangingEventArgs"""
    def __init__(self, *args) -> None: ...
    IsResetting: bool
    NewValue: object
    OldValue: object
    def Dispose(self, ) -> None: ...
    def Veto(self, reason: str) -> None: ...

class VariableChangingEventHandler:
    """.NET: Autodesk.AutoCAD.Runtime.VariableChangingEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: VariableChangingEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: VariableChangingEventArgs) -> None: ...

class Variables(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Runtime.Variables"""
    def __init__(self, *args) -> None: ...
    Item: Variable
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def GetAllNames(self, ) -> list: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def Reset(self, filter: StorageType) -> None: ...

class WrapperAttribute(Attribute):
    """.NET: Autodesk.AutoCAD.Runtime.WrapperAttribute"""
    def __init__(self, *args) -> None: ...
    WrappedClass: str
    TypeId: object
