# Auto-generated — Revit 2027 — Autodesk.Revit.Creation

class Application(APIObject):
    """.NET: Autodesk.Revit.Creation.Application"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    def NewAreaCreationData(self, areaView: ViewPlan, point: UV) -> AreaCreationData: ...
    def NewBoundingBoxUV(self, min_u: float, min_v: float, max_u: float, max_v: float) -> BoundingBoxUV: ...
    def NewBoundingBoxXYZ(self, ) -> BoundingBoxXYZ: ...
    def NewCategorySet(self, ) -> CategorySet: ...
    def NewColor(self, ) -> Color: ...
    def NewCombinableElementArray(self, ) -> CombinableElementArray: ...
    def NewCurveArrArray(self, ) -> CurveArrArray: ...
    def NewCurveArray(self, ) -> CurveArray: ...
    def NewCurveLoopsProfile(self, curveLoops: CurveArrArray) -> CurveLoopsProfile: ...
    def NewDWFExportOptions(self, ) -> DWFExportOptions: ...
    def NewDWFXExportOptions(self, ) -> DWFXExportOptions: ...
    def NewDoubleArray(self, ) -> DoubleArray: ...
    def NewElementId(self, ) -> ElementId: ...
    def NewElementSet(self, ) -> ElementSet: ...
    def NewFBXExportOptions(self, ) -> FBXExportOptions: ...
    def NewFaceArray(self, ) -> FaceArray: ...
    def NewFamilyInstanceCreationData(self, location: XYZ, symbol: FamilySymbol, referenceDirection: XYZ, host: Element, structuralType: StructuralType) -> FamilyInstanceCreationData: ...
    def NewFamilySymbolProfile(self, familySymbol: FamilySymbol) -> FamilySymbolProfile: ...
    def NewGBXMLImportOptions(self, ) -> GBXMLImportOptions: ...
    def NewGeometryOptions(self, ) -> Options: ...
    def NewInstanceBinding(self, categorySet: CategorySet) -> InstanceBinding: ...
    def NewIntersectionResultArray(self, ) -> IntersectionResultArray: ...
    def NewPointOnEdge(self, edgeReference: Reference, locationOnCurve: PointLocationOnCurve) -> PointOnEdge: ...
    def NewPointOnEdgeEdgeIntersection(self, edgeReference1: Reference, edgeReference2: Reference) -> PointOnEdgeEdgeIntersection: ...
    def NewPointOnEdgeFaceIntersection(self, edgeReference: Reference, faceReference: Reference, orientWithEdge: bool) -> PointOnEdgeFaceIntersection: ...
    def NewPointOnFace(self, faceReference: Reference, uv: UV) -> PointOnFace: ...
    def NewPointOnPlane(self, planeReference: Reference, position: UV, xvec: UV, offset: float) -> PointOnPlane: ...
    def NewPointRelativeToPoint(self, hostPointReference: Reference) -> PointRelativeToPoint: ...
    def NewProjectPosition(self, ew: float, ns: float, elevation: float, angle: float) -> ProjectPosition: ...
    def NewReferenceArray(self, ) -> ReferenceArray: ...
    def NewReferencePointArray(self, ) -> ReferencePointArray: ...
    def NewSpaceSet(self, ) -> SpaceSet: ...
    def NewTypeBinding(self, categorySet: CategorySet) -> TypeBinding: ...
    def NewUV(self, u: float, v: float) -> UV: ...
    def NewVertexIndexPair(self, iTop: int, iBottom: int) -> VertexIndexPair: ...
    def NewVertexIndexPairArray(self, ) -> VertexIndexPairArray: ...
    def NewViewSet(self, ) -> ViewSet: ...
    def NewXYZ(self, x: float, y: float, z: float) -> XYZ: ...

class AreaCreationData:
    """.NET: Autodesk.Revit.Creation.AreaCreationData"""
    def __init__(self, *args) -> None: ...
    TagPoint: UV

class Document(ItemFactoryBase):
    """.NET: Autodesk.Revit.Creation.Document"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    def NewArea(self, areaView: ViewPlan, point: UV) -> Area: ...
    def NewAreaBoundaryConditions(self, hostElement: Element, X_Translation: TranslationRotationValue, X_TranslationSpringModulus: float, Y_Translation: TranslationRotationValue, Y_TranslationSpringModulus: float, Z_Translation: TranslationRotationValue, Z_TranslationSpringModulus: float) -> BoundaryConditions: ...
    def NewAreaBoundaryLine(self, sketchPlane: SketchPlane, geometryCurve: Curve, areaView: ViewPlan) -> ModelCurve: ...
    def NewAreaTag(self, areaView: ViewPlan, room: Area, point: UV) -> AreaTag: ...
    def NewAreas(self, dataList: List) -> ElementSet: ...
    def NewCrossFitting(self, connector1: Connector, connector2: Connector, connector3: Connector, connector4: Connector) -> FamilyInstance: ...
    def NewCurtainSystem(self, faces: FaceArray, curtainSystemType: CurtainSystemType) -> CurtainSystem: ...
    def NewCurtainSystem2(self, faces: ReferenceArray, curtainSystemType: CurtainSystemType) -> ICollection: ...
    def NewElbowFitting(self, connector1: Connector, connector2: Connector) -> FamilyInstance: ...
    def NewExtrusionRoof(self, profile: CurveArray, refPlane: ReferencePlane, level: Level, roofType: RoofType, extrusionStart: float, extrusionEnd: float) -> ExtrusionRoof: ...
    def NewFamilyInstance(self, location: XYZ, symbol: FamilySymbol, host: Element, level: Level, structuralType: StructuralType) -> FamilyInstance: ...
    def NewFascia(self, FasciaType: FasciaType, reference: Reference) -> Fascia: ...
    def NewFlexDuct(self, connector1: Connector, connector2: Connector, ductType: FlexDuctType) -> FlexDuct: ...
    def NewFlexPipe(self, connector1: Connector, connector2: Connector, pipeType: FlexPipeType) -> FlexPipe: ...
    def NewFootPrintRoof(self, footPrint: CurveArray, level: Level, roofType: RoofType, footPrintToModelCurvesMapping: ModelCurveArray) -> FootPrintRoof: ...
    def NewGutter(self, GutterType: GutterType, reference: Reference) -> Gutter: ...
    def NewLineBoundaryConditions(self, hostElement: Element, X_Translation: TranslationRotationValue, X_TranslationSpringModulus: float, Y_Translation: TranslationRotationValue, Y_TranslationSpringModulus: float, Z_Translation: TranslationRotationValue, Z_TranslationSpringModulus: float, X_Rotation: TranslationRotationValue, X_RotationSpringModulus: float) -> BoundaryConditions: ...
    def NewMechanicalSystem(self, baseEquipmentConnector: Connector, connectors: ConnectorSet, ductSystemType: DuctSystemType) -> MechanicalSystem: ...
    def NewOpening(self, hostElement: Element, profile: CurveArray, bPerpendicularFace: bool) -> Opening: ...
    def NewPipingSystem(self, baseEquipmentConnector: Connector, connectors: ConnectorSet, pipingSystemType: PipeSystemType) -> PipingSystem: ...
    def NewPointBoundaryConditions(self, reference: Reference, X_Translation: TranslationRotationValue, X_TranslationSpringModulus: float, Y_Translation: TranslationRotationValue, Y_TranslationSpringModulus: float, Z_Translation: TranslationRotationValue, Z_TranslationSpringModulus: float, X_Rotation: TranslationRotationValue, X_RotationSpringModulus: float, Y_Rotation: TranslationRotationValue, Y_RotationSpringModulus: float, Z_Rotation: TranslationRotationValue, Z_RotationSpringModulus: float) -> BoundaryConditions: ...
    def NewRoom(self, room: Room, circuit: PlanCircuit) -> Room: ...
    def NewRoomBoundaryLines(self, sketchPlane: SketchPlane, curves: CurveArray, view: View) -> ModelCurveArray: ...
    def NewRoomTag(self, roomId: LinkElementId, point: UV, viewId: ElementId) -> RoomTag: ...
    def NewRooms2(self, phase: Phase, count: int) -> ICollection: ...
    def NewSlabEdge(self, SlabEdgeType: SlabEdgeType, reference: Reference) -> SlabEdge: ...
    def NewSpace(self, level: Level, phase: Phase, point: UV) -> Space: ...
    def NewSpaceBoundaryLines(self, sketchPlane: SketchPlane, curves: CurveArray, view: View) -> ModelCurveArray: ...
    def NewSpaceTag(self, space: Space, point: UV, view: View) -> SpaceTag: ...
    def NewSpaces2(self, level: Level, phase: Phase, view: View) -> ICollection: ...
    def NewSpotCoordinate(self, view: View, reference: Reference, origin: XYZ, bend: XYZ, end: XYZ, refPt: XYZ, hasLeader: bool) -> SpotDimension: ...
    def NewSpotElevation(self, view: View, reference: Reference, origin: XYZ, bend: XYZ, end: XYZ, refPt: XYZ, hasLeader: bool) -> SpotDimension: ...
    def NewTakeoffFitting(self, connector: Connector, curve: MEPCurve) -> FamilyInstance: ...
    def NewTeeFitting(self, connector1: Connector, connector2: Connector, connector3: Connector) -> FamilyInstance: ...
    def NewTransitionFitting(self, connector1: Connector, connector2: Connector) -> FamilyInstance: ...
    def NewUnionFitting(self, connector1: Connector, connector2: Connector) -> FamilyInstance: ...

class FamilyInstanceCreationData:
    """.NET: Autodesk.Revit.Creation.FamilyInstanceCreationData"""
    def __init__(self, *args) -> None: ...
    RotateAngle: float
    Axis: Line

class FamilyItemFactory(ItemFactoryBase):
    """.NET: Autodesk.Revit.Creation.FamilyItemFactory"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    def NewAngularDimension(self, view: View, arc: Arc, firstRef: Reference, secondRef: Reference, dimensionType: DimensionType) -> Dimension: ...
    def NewArcLengthDimension(self, view: View, arc: Arc, arcRef: Reference, firstRef: Reference, secondRef: Reference, dimensionType: DimensionType) -> Dimension: ...
    def NewBlend(self, isSolid: bool, profile1: CurveArray, profile2: CurveArray, sketchPlane: SketchPlane) -> Blend: ...
    def NewControl(self, controlShape: ControlShape, view: View, origin: XYZ) -> Control: ...
    def NewCurveByPoints(self, points: ReferencePointArray) -> CurveByPoints: ...
    def NewDiameterDimension(self, view: View, arcRef: Reference, origin: XYZ) -> Dimension: ...
    def NewExtrusion(self, isSolid: bool, profile: CurveArrArray, sketchPlane: SketchPlane, end: float) -> Extrusion: ...
    def NewExtrusionForm(self, isSolid: bool, profile: ReferenceArray, direction: XYZ) -> Form: ...
    def NewFormByCap(self, isSolid: bool, profile: ReferenceArray) -> Form: ...
    def NewFormByThickenSingleSurface(self, isSolid: bool, singleSurfaceForm: Form, thickenDir: XYZ) -> Form: ...
    def NewLinearDimension(self, view: View, line: Line, references: ReferenceArray, dimensionType: DimensionType) -> Dimension: ...
    def NewLoftForm(self, isSolid: bool, profiles: ReferenceArrayArray) -> Form: ...
    def NewModelText(self, text: str, modelTextType: ModelTextType, sketchPlane: SketchPlane, position: XYZ, horizontalAlign: HorizontalAlign, depth: float) -> ModelText: ...
    def NewOpening(self, host: Element, profile: CurveArray) -> Opening: ...
    def NewRadialDimension(self, view: View, arcRef: Reference, origin: XYZ, dimensionType: DimensionType) -> Dimension: ...
    def NewReferencePoint(self, A_0: PointElementReference) -> ReferencePoint: ...
    def NewRevolution(self, isSolid: bool, profile: CurveArrArray, sketchPlane: SketchPlane, axis: Line, startAngle: float, endAngle: float) -> Revolution: ...
    def NewRevolveForms(self, isSolid: bool, profile: ReferenceArray, axis: Reference, startAngle: float, endAngle: float) -> FormArray: ...
    def NewSweep(self, isSolid: bool, path: CurveArray, pathPlane: SketchPlane, profile: SweepProfile, profileLocationCurveIndex: int, profilePlaneLocation: ProfilePlaneLocation) -> Sweep: ...
    def NewSweptBlend(self, isSolid: bool, path: Curve, pathPlane: SketchPlane, bottomProfile: SweepProfile, topProfile: SweepProfile) -> SweptBlend: ...
    def NewSweptBlendForm(self, isSolid: bool, path: ReferenceArray, profiles: ReferenceArrayArray) -> Form: ...
    def NewSymbolicCurve(self, curve: Curve, sketchPlane: SketchPlane) -> SymbolicCurve: ...

class ItemFactoryBase(APIObject):
    """.NET: Autodesk.Revit.Creation.ItemFactoryBase"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    def NewAlignment(self, view: View, reference1: Reference, reference2: Reference) -> Dimension: ...
    def NewDetailCurve(self, view: View, geometryCurve: Curve) -> DetailCurve: ...
    def NewDetailCurveArray(self, view: View, geometryCurveArray: CurveArray) -> DetailCurveArray: ...
    def NewDimension(self, view: View, line: Line, references: ReferenceArray, dimensionType: DimensionType) -> Dimension: ...
    def NewFamilyInstance(self, location: XYZ, symbol: FamilySymbol, referenceDirection: XYZ, host: Element, structuralType: StructuralType) -> FamilyInstance: ...
    def NewFamilyInstances2(self, dataList: List) -> ICollection: ...
    def NewGroup(self, elementIds: ICollection) -> Group: ...
    def NewModelCurve(self, geometryCurve: Curve, sketchPlane: SketchPlane) -> ModelCurve: ...
    def NewModelCurveArray(self, geometryCurveArray: CurveArray, sketchPlane: SketchPlane) -> ModelCurveArray: ...
    def NewReferencePlane(self, bubbleEnd: XYZ, freeEnd: XYZ, cutVec: XYZ, pView: View) -> ReferencePlane: ...
    def NewReferencePlane2(self, bubbleEnd: XYZ, freeEnd: XYZ, thirdPnt: XYZ, pView: View) -> ReferencePlane: ...
    def PlaceGroup(self, location: XYZ, groupType: GroupType) -> Group: ...

class eRefFace:
    """.NET: Autodesk.Revit.Creation.eRefFace"""
    def __init__(self, *args) -> None: ...
    ...
