# Auto-generated — Civil 26 — Autodesk.AutoCAD.DatabaseServices.Internal

class CompareReturnStatus:
    """.NET: Autodesk.AutoCAD.DatabaseServices.Internal.CompareReturnStatus"""
    def __init__(self, *args) -> None: ...
    ...

class DcDocsFile:
    """.NET: Autodesk.AutoCAD.DatabaseServices.Internal.DcDocsFile"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def getPermissions(sFilepath: str) -> Permissions: ...
    @staticmethod
    def isDCDOCSFileSource(sFilepath: str) -> bool: ...

class DrawingCompare:
    """.NET: Autodesk.AutoCAD.DatabaseServices.Internal.DrawingCompare"""
    def __init__(self, *args) -> None: ...
    def CompareDwgFiles(self, file1name: str, file2name: str) -> CompareReturnStatus: ...
    def OnDiffDetected(self, drawingId: int, handle: int, changeType: int) -> None: ...

class FieldEngine:
    """.NET: Autodesk.AutoCAD.DatabaseServices.Internal.FieldEngine"""
    def __init__(self, *args) -> None: ...
    EvaluationOption: int

class ObjectDiffEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.DatabaseServices.Internal.ObjectDiffEventArgs"""
    def __init__(self, *args) -> None: ...
    ChangeType: int
    DrawingId: int
    ObjHandle: Handle

class ObjectDiffEventHandler:
    """.NET: Autodesk.AutoCAD.DatabaseServices.Internal.ObjectDiffEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: ObjectDiffEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: ObjectDiffEventArgs) -> None: ...

class Permissions:
    """.NET: Autodesk.AutoCAD.DatabaseServices.Internal.Permissions"""
    def __init__(self, *args) -> None: ...
    ...
