# Auto-generated — Civil 26 — Autodesk.AutoCAD.Internal.Forms

class ControlRenderer:
    """.NET: Autodesk.AutoCAD.Internal.Forms.ControlRenderer"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ScrollBar(control: Control) -> bool: ...
    @staticmethod
    def ScrollToControlSkip(control: ScrollableControl, message: int) -> None: ...

class HelpProvider:
    """.NET: Autodesk.AutoCAD.Internal.Forms.HelpProvider"""
    def __init__(self, *args) -> None: ...
    ToolTip: ControlToolTip
    ContextHelpFileName: str
    HelpFileName: str
    HelpPrefix: str
    HelpTopic: str
    def Add(self, comp: object, id: str) -> None: ...
    def InvokeHelp(self, topicToDisplay: str) -> None: ...
    def Remove(self, comp: object) -> None: ...
    def SetToolTip(self, comp: object, content: object, includeChildItems: bool) -> None: ...
    def ctrl_HelpRequested(self, sender: object, hlpevent: HelpEventArgs) -> None: ...

class ToolStripDefaultRenderer(ToolStripSystemRenderer):
    """.NET: Autodesk.AutoCAD.Internal.Forms.ToolStripDefaultRenderer"""
    def __init__(self, *args) -> None: ...
    Themed: bool
    Palette: ToolStripDefaultRenderer
    Dialog: ToolStripDefaultRenderer
