# Auto-generated — Civil 26 — Autodesk.AutoCAD.Internal.PreviousInput

class AcPiMonitorReactorImpl:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.AcPiMonitorReactorImpl"""
    def __init__(self, *args) -> None: ...
    ...

class CommandLineMonitor:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.CommandLineMonitor"""
    def __init__(self, *args) -> None: ...
    CurrentInputControlFlags: InputControlFlags
    CurrentSSGetConsumedPickfirst: bool
    CurrentSSGetIsManual: bool
    CurrentSSGetKeywordsUsed: ArrayList
    CurrentInitgetKeywords: str
    LastCommandName: str
    LastNotifiedSSGetCount: int
    CurrentSSGetCount: int
    CurrentNestingCount: int
    CurrentPointOut2dFlag: bool
    CurrentPointOut2d: ValueType
    CurrentPointOutFlag: bool
    CurrentPointOut: ValueType
    CurrentDoubleOut: float
    CurrentIntOut: int
    CurrentStringOut: str
    CurrentSSControlsIn: str
    CurrentKeywordsIn: str
    CurrentPointInFlag: bool
    CurrentPointIn: ValueType
    CurrentInitgetFlags: int
    CurrentModes: InputModes
    CurrentMode: InputModes
    CurrentReturnStatus: PromptStatus
    CurrentPrompt: str
    CurrentCommandName: str
    def EnableSsGetFilter(self, on: bool) -> None: ...

class CommandLineMonitorServices:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.CommandLineMonitorServices"""
    def __init__(self, *args) -> None: ...
    def ActiveCommandFlags(self, ) -> CommandFlags: ...
    def CommandActiveBits(self, ) -> int: ...
    def CommandNestedDepth(self, ) -> int: ...
    def GetCommandLineMonitor(self, doc: Document) -> CommandLineMonitor: ...
    def GetLocalCommandName(self, globalCmdName: str) -> str: ...
    @staticmethod
    def Instance() -> CommandLineMonitorServices: ...
    def IsCurrentCommandTransparent(self, ) -> bool: ...

class GetAngleEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.GetAngleEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: GetInputEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: GetInputEventArgs) -> None: ...

class GetDistanceEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.GetDistanceEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: GetInputEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: GetInputEventArgs) -> None: ...

class GetInputEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.GetInputEventArgs"""
    def __init__(self, *args) -> None: ...
    ReturnStatus: PromptStatus
    Value: object
    Mode: InputModes

class GetInputEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.GetInputEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: GetInputEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: GetInputEventArgs) -> None: ...

class InputControlFlags:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.InputControlFlags"""
    def __init__(self, *args) -> None: ...
    ...

class InputModes:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.InputModes"""
    def __init__(self, *args) -> None: ...
    ...

class InputStringEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.InputStringEventArgs"""
    def __init__(self, *args) -> None: ...
    Value: str

class InputStringEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.InputStringEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: InputStringEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: InputStringEventArgs) -> None: ...

class SelectEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.SelectEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class SelectOperationEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.SelectOperationEventArgs"""
    def __init__(self, *args) -> None: ...
    GroupName: str
    SelectionFlags: int
    IsCrossingBox: bool
    IsCancel: bool
    Points: Point3dCollection
    IsSubSelection: bool
    IsAdding: bool
    SelectionMode: SelectionMode

class SelectOperationEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.PreviousInput.SelectOperationEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: SelectOperationEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: SelectOperationEventArgs) -> None: ...
