# Auto-generated — Civil 26 — Autodesk.AutoCAD.Internal.PropertyInspector

class AcEdPropertyInspectorReactorImpl:
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.AcEdPropertyInspectorReactorImpl"""
    def __init__(self, *args) -> None: ...
    ...

class CategoryCollectable(CollectableObject):
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.CategoryCollectable"""
    def __init__(self, *args) -> None: ...
    Weight: int
    CategoryId: int
    Name: str
    Description: str
    Properties: CollectionVector
    CollectableName: str
    ObjectCollectableKind: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def IsCollapsed(self, ) -> bool: ...
    def IsEqual(self, category: CategoryCollectable, check: CHECK_LEVEL, flags: int) -> bool: ...
    def RemoveDynamicCollectables(self, deleteProperty: bool) -> None: ...
    def Sync(self, category: CategoryCollectable, inequalityFlags: int, literalUnion: bool) -> None: ...
    def ToggleState(self, ) -> int: ...

class CategoryInequalityFlags:
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.CategoryInequalityFlags"""
    def __init__(self, *args) -> None: ...
    ...

class CollectableObject(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.CollectableObject"""
    def __init__(self, *args) -> None: ...
    CollectableName: str
    Weight: int
    ObjectCollectableKind: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class CollectionVector(DisposableWrapper):
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.CollectionVector"""
    def __init__(self, *args) -> None: ...
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Add(self, vector: CollectionVector) -> None: ...
    def ApplyOemFilter(self, general: str, zeroBased: bool) -> None: ...
    def Cleanup(self, zeroBased: bool) -> None: ...
    def Count(self, ) -> int: ...
    def DestroyControls(self, zeroBased: bool) -> None: ...
    def FindCategory(self, name: str, categoryId: int, parentCategoryId: int, zeroBased: bool) -> CategoryCollectable: ...
    def InsertAt(self, index: int, value: CollectableObject) -> None: ...
    def Item(self, index: int) -> CollectableObject: ...
    def NestCategories(self, zeroBased: bool) -> None: ...
    def Print(self, logFile: str, append: bool) -> None: ...
    def RemoveAll(self, ) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def RemoveDynamicCollectables(self, ) -> None: ...
    def SetAt(self, index: int, value: CollectableObject) -> None: ...
    def SetCategoryWeight(self, categoryName: str, weight: int, zeroBased: bool) -> None: ...
    def Sort(self, begin: int, finish: int) -> None: ...
    def SortVectorByWeights(self, begin: int, finish: int) -> None: ...

class ObjectPropertyManagerProperties:
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.ObjectPropertyManagerProperties"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ClassIsVetoed(cls: RXClass, isQPContext: bool) -> bool: ...
    @staticmethod
    def ConvertBlkrefToXref(objId: ObjectId) -> bool: ...
    @staticmethod
    def GetCategoryId(prop: PropertyCollectable) -> int: ...
    @staticmethod
    def GetDisplayName(obj: DBObject) -> str: ...
    @staticmethod
    def GetDisplayNameGuts(pUnk: IUnknown) -> str: ...
    @staticmethod
    def GetMultiplePropertyGuids(cls: RXClass, GUIDs: StringCollection) -> bool: ...
    @staticmethod
    def GetNonEntityObjectTypes(isTooltipsContext: bool) -> Dictionary: ...
    @staticmethod
    def GetProperties(obj: DBObject, bFilterable: bool, bQPContext: bool) -> CollectionVector: ...
    @staticmethod
    def GetPropertiesForSubtype(obj: DBObject, bFilterable: bool, sGUID: str, bQPContext: bool) -> CollectionVector: ...
    @staticmethod
    def GetPropertiesForSubtypeGuts(pUnk: IUnknown, bFilterable: bool, sGUID: str, bQPContext: bool) -> CollectionVector: ...
    @staticmethod
    def GetPropertiesGuts(pUnk: IUnknown, bFilterable: bool, bQPContext: bool) -> CollectionVector: ...
    @staticmethod
    def GetSubtypes(cls: RXClass, GUIDs: StringCollection, displayNames: StringCollection) -> bool: ...
    @staticmethod
    def GiveClassChanceToCreate(cls: RXClass, db: Database, pEntOut: Entity, sGUID: str) -> ObjectId: ...
    @staticmethod
    def IsDynamicProperty(prop: PropertyCollectable, GUIDs: StringCollection) -> bool: ...

class ObjectPropertyManagerPropertyUtility:
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.ObjectPropertyManagerPropertyUtility"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetIUnknownFromObject(obj: DBObject, bAttachToObject: bool) -> IntPtr: ...
    @staticmethod
    def GetIUnknownFromObjectId(objId: ObjectId) -> IntPtr: ...
    @staticmethod
    def GetTypeInfo(obj: object, lcid: int) -> ITypeInfo: ...
    @staticmethod
    def ObjectSupportsNonDBResidency(obj: DBObject) -> bool: ...

class PropertyCategoryId:
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.PropertyCategoryId"""
    def __init__(self, *args) -> None: ...
    ...

class PropertyCollectable(CollectableObject):
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.PropertyCollectable"""
    def __init__(self, *args) -> None: ...
    CollectableName: str
    dispid: int
    Visible: int
    weight: int
    MemberId: int
    DISP: object
    Name: str
    Description: str
    Weight: int
    ObjectCollectableKind: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def GetValue(self, unknown: IntPtr, value: object) -> bool: ...
    def IsEqual(self, propertyCollectable: PropertyCollectable, check: CHECK_LEVEL, flags: int) -> bool: ...
    def Skip(self, ) -> bool: ...
    def Sync(self, propertyCollectable: PropertyCollectable, inequalityFlags: int) -> None: ...

class PropertyInequalityFlags:
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.PropertyInequalityFlags"""
    def __init__(self, *args) -> None: ...
    ...

class PropertyInspectorEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.PropertyInspectorEventArgs"""
    def __init__(self, *args) -> None: ...
    OPMModeFlag: int
    ParentWindow: IntPtr
    Value: object
    Property: object

class PropertyInspectorEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.PropertyInspectorEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: PropertyInspectorEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: PropertyInspectorEventArgs) -> None: ...

class PropertyInspectorEventManager:
    """.NET: Autodesk.AutoCAD.Internal.PropertyInspector.PropertyInspectorEventManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Instance() -> PropertyInspectorEventManager: ...
