# Auto-generated — Civil 26 — Autodesk.AutoCAD.Internal.Reactors

class AcEdIPEReactorImpl:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.AcEdIPEReactorImpl"""
    def __init__(self, *args) -> None: ...
    ...

class AcEdOPMObjectFilterReactorImpl:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.AcEdOPMObjectFilterReactorImpl"""
    def __init__(self, *args) -> None: ...
    ...

class AcEdUcsReactorImpl:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.AcEdUcsReactorImpl"""
    def __init__(self, *args) -> None: ...
    ...

class AcEdViewFinalChangeReactorImpl:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.AcEdViewFinalChangeReactorImpl"""
    def __init__(self, *args) -> None: ...
    ...

class AcSunViewportMonitorReactorImpl:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.AcSunViewportMonitorReactorImpl"""
    def __init__(self, *args) -> None: ...
    ...

class AcVsESWDictionaryReactor:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.AcVsESWDictionaryReactor"""
    def __init__(self, *args) -> None: ...
    ...

class AcVsESWObjectReactor:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.AcVsESWObjectReactor"""
    def __init__(self, *args) -> None: ...
    ...

class ApplicationDockLayoutChangedEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ApplicationDockLayoutChangedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class ApplicationDocumentFrameChangedEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ApplicationDocumentFrameChangedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class ApplicationEventManager:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ApplicationEventManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Instance() -> ApplicationEventManager: ...

class ApplicationMainWindowMovedEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ApplicationMainWindowMovedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class ApplicationMainWindowSizedEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ApplicationMainWindowSizedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: ApplicationMainWindowStateChangedEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: ApplicationMainWindowStateChangedEventArgs) -> None: ...

class ApplicationMainWindowStateChangedEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ApplicationMainWindowStateChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    NewSize: ValueType
    ChangeType: StateChangeType

class ApplicationMainWindowVisibleChangedEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ApplicationMainWindowVisibleChangedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...

class CuiEventManager:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.CuiEventManager"""
    def __init__(self, *args) -> None: ...
    def FreeCustomizationSectionHandle(self, handle: GCHandle) -> None: ...
    def GetCustomizationSectionHandle(self, menuGroupName: str) -> GCHandle: ...
    @staticmethod
    def Instance() -> CuiEventManager: ...

class CuiLoadEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.Reactors.CuiLoadEventArgs"""
    def __init__(self, *args) -> None: ...
    CurrentWorkspaceId: str
    CurrentWorkspaceName: str

class DictionaryEventManager:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.DictionaryEventManager"""
    def __init__(self, *args) -> None: ...
    Enabled: bool
    def Dispose(self, ) -> None: ...

class IPEEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.Reactors.IPEEventArgs"""
    def __init__(self, *args) -> None: ...
    Entity: Entity
    ExitStatus: IPEExitStatus

class IPEEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.IPEEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: IPEEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: IPEEventArgs) -> None: ...

class IPEEventManager:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.IPEEventManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Instance() -> IPEEventManager: ...
    def invokeSetIPEMacroMode(self, iMode: int) -> None: ...
    def invokeSetIPEString(self, contents: str) -> None: ...

class LoadRibbonEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.LoadRibbonEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: CuiLoadEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: CuiLoadEventArgs) -> None: ...

class OPMObjectFilterEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.Reactors.OPMObjectFilterEventArgs"""
    def __init__(self, *args) -> None: ...
    EntityName: str
    EntityCLSID: Guid

class OPMObjectFilterEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.OPMObjectFilterEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: OPMObjectFilterEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: OPMObjectFilterEventArgs) -> None: ...

class OPMObjectFilterEventManager:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.OPMObjectFilterEventManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Instance() -> OPMObjectFilterEventManager: ...

class SunViewportMonitorEventManager:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.SunViewportMonitorEventManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Instance() -> SunViewportMonitorEventManager: ...

class TableSubSelectFilter:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.TableSubSelectFilter"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Instance() -> TableSubSelectFilter: ...

class TableSubSelectFilterEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.Reactors.TableSubSelectFilterEventArgs"""
    def __init__(self, *args) -> None: ...
    Reposition: bool
    Selected: bool
    TableId: ObjectId

class TableSubSelectFilterEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.TableSubSelectFilterEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: TableSubSelectFilterEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: TableSubSelectFilterEventArgs) -> None: ...

class UcsEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.Reactors.UcsEventArgs"""
    def __init__(self, *args) -> None: ...
    Matrix3dValue: Matrix3d

class UcsEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.UcsEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: UcsEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: UcsEventArgs) -> None: ...

class UcsEventManager:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.UcsEventManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def instance() -> UcsEventManager: ...

class ViewChangeEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ViewChangeEventArgs"""
    def __init__(self, *args) -> None: ...
    UsedY: int
    UsedX: int

class ViewFinalChangeEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ViewFinalChangeEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: ViewChangeEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: ViewChangeEventArgs) -> None: ...

class ViewFinalChangeEventManager:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ViewFinalChangeEventManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Instance() -> ViewFinalChangeEventManager: ...

class ViewResizeEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ViewResizeEventArgs"""
    def __init__(self, *args) -> None: ...
    UsedSplit: bool
    UsedEY: float
    UsedEX: float
    UsedSY: float
    UsedSX: float

class ViewResizeEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.ViewResizeEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: ViewResizeEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: ViewResizeEventArgs) -> None: ...

class VisualStyleEventManager:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.VisualStyleEventManager"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def Instance() -> VisualStyleEventManager: ...
    def SetDataBase(self, acadDatabase: Database, bUpdateUI: bool) -> None: ...

class VsESWDictionaryEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.VsESWDictionaryEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object) -> None: ...

class VsESWObjectEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.VsESWObjectEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object) -> None: ...

class WorkspaceEventArgs(EventArgs):
    """.NET: Autodesk.AutoCAD.Internal.Reactors.WorkspaceEventArgs"""
    def __init__(self, *args) -> None: ...
    CustomizationSection: CustomizationSection
    Workspace: Workspace
    Id: str
    Name: str

class WorkspaceRestoreEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.WorkspaceRestoreEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: WorkspaceEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: WorkspaceEventArgs) -> None: ...

class WorkspaceRibbonSaveEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.WorkspaceRibbonSaveEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: WorkspaceEventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: WorkspaceEventArgs) -> None: ...

class WorkspaceSettingsSavedEventHandler:
    """.NET: Autodesk.AutoCAD.Internal.Reactors.WorkspaceSettingsSavedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, sender: object, e: EventArgs, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, sender: object, e: EventArgs) -> None: ...
