# Auto-generated — Revit 2027 — Autodesk.Revit.DB.Structure.StructuralSections

class StructuralElementDefinitionData:
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralElementDefinitionData"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    IsMirrored: bool
    Section: StructuralSection
    Normal: XYZ
    EndShortening: float
    StartShortening: float
    ZOffset: float
    YOffset: float
    ZJust: ZJustification
    YJust: YJustification
    CenterCurve: Curve
    Curve: Curve
    def Dispose(self, ) -> None: ...

class StructuralSection:
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSection"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str
    def Dispose(self, ) -> None: ...
    def GetBoundarySize(self, ) -> UV: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class StructuralSectionAnalysisParams:
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionAnalysisParams"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    def Dispose(self, ) -> None: ...

class StructuralSectionCParallelFlange(StructuralSectionGeneralU):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionCParallelFlange"""
    def __init__(self, *args) -> None: ...
    BoltDiameter: float
    BoltSpacing: float
    ClearWebHeight: float
    WebToeOfFillet: float
    SlopedFlangeAngle: float
    FlangeToeOfFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionCProfile(StructuralSectionGeneralC):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionCProfile"""
    def __init__(self, *args) -> None: ...
    LipLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionCProfileWithFold(StructuralSectionGeneralCEx):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionCProfileWithFold"""
    def __init__(self, *args) -> None: ...
    FoldLength: float
    LipLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionCProfileWithLips(StructuralSectionGeneralC):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionCProfileWithLips"""
    def __init__(self, *args) -> None: ...
    LipLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionCSlopedFlange(StructuralSectionGeneralU):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionCSlopedFlange"""
    def __init__(self, *args) -> None: ...
    BoltDiameter: float
    BoltSpacing: float
    ClearWebHeight: float
    WebToeOfFillet: float
    SlopedFlangeAngle: float
    FlangeToeOfFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionColdFormed(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionColdFormed"""
    def __init__(self, *args) -> None: ...
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionConcreteCross(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionConcreteCross"""
    def __init__(self, *args) -> None: ...
    CantileverHeight: float
    CantileverLength: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionConcreteI(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionConcreteI"""
    def __init__(self, *args) -> None: ...
    WebThickness: float
    BottomFlangeWidth: float
    BottomFlangeThickness: float
    TopFlangeWidth: float
    TopFlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionConcreteL(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionConcreteL"""
    def __init__(self, *args) -> None: ...
    CutHeight: float
    CutWidth: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionConcretePolygon(StructuralSectionRound):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionConcretePolygon"""
    def __init__(self, *args) -> None: ...
    PolygonDefinition: StructuralSectionPolygonDefinition
    Sides: int
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Diameter: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionConcreteRectangle(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionConcreteRectangle"""
    def __init__(self, *args) -> None: ...
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionConcreteRectangleCut(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionConcreteRectangleCut"""
    def __init__(self, *args) -> None: ...
    BottomCutHeight: float
    BottomCutWidth: float
    TopCutHeight: float
    TopCutWidth: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionConcreteRound(StructuralSectionRound):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionConcreteRound"""
    def __init__(self, *args) -> None: ...
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Diameter: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionConcreteT(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionConcreteT"""
    def __init__(self, *args) -> None: ...
    CantileverHeight: float
    CantileverLength: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionErrorCode:
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionErrorCode"""
    def __init__(self, *args) -> None: ...
    ...

class StructuralSectionGeneralC(StructuralSectionColdFormed):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralC"""
    def __init__(self, *args) -> None: ...
    LipLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionGeneralCEx(StructuralSectionColdFormed):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralCEx"""
    def __init__(self, *args) -> None: ...
    FoldLength: float
    LipLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionGeneralF(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralF"""
    def __init__(self, *args) -> None: ...
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionGeneralH(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralH"""
    def __init__(self, *args) -> None: ...
    OuterFillet: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionGeneralI(StructuralSectionHotRolled):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralI"""
    def __init__(self, *args) -> None: ...
    SlopedFlangeAngle: float
    WebToeOfFillet: float
    FlangeToeOfFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str
    def GetFlangeThicknessInFlangeCenter(self, ) -> float: ...
    def GetFlangeThicknessInQuarterWidth(self, ) -> float: ...

class StructuralSectionGeneralLA(StructuralSectionColdFormed):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralLA"""
    def __init__(self, *args) -> None: ...
    LipLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionGeneralLZ(StructuralSectionColdFormed):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralLZ"""
    def __init__(self, *args) -> None: ...
    LipLength: float
    BottomFlangeLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionGeneralR(StructuralSectionRound):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralR"""
    def __init__(self, *args) -> None: ...
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Diameter: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionGeneralS(StructuralSectionRound):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralS"""
    def __init__(self, *args) -> None: ...
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Diameter: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionGeneralShape:
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralShape"""
    def __init__(self, *args) -> None: ...
    ...

class StructuralSectionGeneralT(StructuralSectionHotRolled):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralT"""
    def __init__(self, *args) -> None: ...
    SlopedWebAngle: float
    WebToeOfFillet: float
    TopWebFillet: float
    SlopedFlangeAngle: float
    FlangeToeOfFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str
    def GetFlangeThicknessInFlangeCenter(self, ) -> float: ...
    def GetFlangeThicknessInQuarterWidth(self, ) -> float: ...
    def GetWebThicknessInHeightCenter(self, ) -> float: ...

class StructuralSectionGeneralU(StructuralSectionHotRolled):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralU"""
    def __init__(self, *args) -> None: ...
    WebToeOfFillet: float
    SlopedFlangeAngle: float
    FlangeToeOfFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str
    def GetFlangeThicknessInFlangeCenter(self, ) -> float: ...
    def GetFlangeThicknessInWidthCenter(self, ) -> float: ...

class StructuralSectionGeneralW(StructuralSectionHotRolled):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionGeneralW"""
    def __init__(self, *args) -> None: ...
    TopWebFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionHotRolled(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionHotRolled"""
    def __init__(self, *args) -> None: ...
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionIParallelFlange(StructuralSectionGeneralI):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionIParallelFlange"""
    def __init__(self, *args) -> None: ...
    BoltDiameter: float
    BoltSpacing: float
    ClearWebHeight: float
    SlopedFlangeAngle: float
    WebToeOfFillet: float
    FlangeToeOfFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionISlopedFlange(StructuralSectionGeneralI):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionISlopedFlange"""
    def __init__(self, *args) -> None: ...
    BoltDiameter: float
    BoltSpacing: float
    ClearWebHeight: float
    SlopedFlangeAngle: float
    WebToeOfFillet: float
    FlangeToeOfFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionISplitParallelFlange(StructuralSectionGeneralT):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionISplitParallelFlange"""
    def __init__(self, *args) -> None: ...
    BoltDiameter: float
    BoltSpacing: float
    ClearWebHeight: float
    SlopedWebAngle: float
    WebToeOfFillet: float
    TopWebFillet: float
    SlopedFlangeAngle: float
    FlangeToeOfFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionISplitSlopedFlange(StructuralSectionGeneralT):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionISplitSlopedFlange"""
    def __init__(self, *args) -> None: ...
    BoltDiameter: float
    BoltSpacing: float
    ClearWebHeight: float
    SlopedWebAngle: float
    WebToeOfFillet: float
    TopWebFillet: float
    SlopedFlangeAngle: float
    FlangeToeOfFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionIWelded(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionIWelded"""
    def __init__(self, *args) -> None: ...
    WebHeight: float
    WebThickness: float
    BottomFlangeWidth: float
    BottomFlangeThickness: float
    TopFlangeWidth: float
    TopFlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionIWideFlange(StructuralSectionHotRolled):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionIWideFlange"""
    def __init__(self, *args) -> None: ...
    BoltDiameter: float
    BoltSpacingBetweenRows: float
    BoltSpacingTwoRows: float
    BoltSpacing: float
    WebToeOfFillet: float
    FlangeToeOfFillet: float
    ClearWebHeight: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionLAngle(StructuralSectionGeneralW):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionLAngle"""
    def __init__(self, *args) -> None: ...
    BoltDiameterShorterFlange: float
    BoltDiameterLongerFlange: float
    BoltSpacingShorterFlange: float
    BoltSpacing2LongerFlange: float
    BoltSpacing1LongerFlange: float
    TopWebFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionLProfile(StructuralSectionGeneralLA):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionLProfile"""
    def __init__(self, *args) -> None: ...
    LipLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionLProfileWithLips(StructuralSectionGeneralLA):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionLProfileWithLips"""
    def __init__(self, *args) -> None: ...
    LipLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionPipeStandard(StructuralSectionGeneralR):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionPipeStandard"""
    def __init__(self, *args) -> None: ...
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Diameter: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionPolygonDefinition:
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionPolygonDefinition"""
    def __init__(self, *args) -> None: ...
    ...

class StructuralSectionRectangleHSS(StructuralSectionGeneralH):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionRectangleHSS"""
    def __init__(self, *args) -> None: ...
    OuterFillet: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionRectangleParameterized(StructuralSectionGeneralF):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionRectangleParameterized"""
    def __init__(self, *args) -> None: ...
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionRectangular(StructuralSection):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionRectangular"""
    def __init__(self, *args) -> None: ...
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionRectangularBar(StructuralSectionGeneralF):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionRectangularBar"""
    def __init__(self, *args) -> None: ...
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionRound(StructuralSection):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionRound"""
    def __init__(self, *args) -> None: ...
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Diameter: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionRoundBar(StructuralSectionGeneralS):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionRoundBar"""
    def __init__(self, *args) -> None: ...
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Diameter: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionRoundHSS(StructuralSectionGeneralR):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionRoundHSS"""
    def __init__(self, *args) -> None: ...
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Diameter: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionShape:
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionShape"""
    def __init__(self, *args) -> None: ...
    ...

class StructuralSectionSigmaProfile(StructuralSectionColdFormed):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionSigmaProfile"""
    def __init__(self, *args) -> None: ...
    TopBendLength: float
    MiddleBendLength: float
    BendWidth: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionSigmaProfileWithFold(StructuralSectionColdFormed):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionSigmaProfileWithFold"""
    def __init__(self, *args) -> None: ...
    TopBendLength: float
    MiddleBendLength: float
    LipLength: float
    BendWidth: float
    FoldWidth: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionSigmaProfileWithLips(StructuralSectionColdFormed):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionSigmaProfileWithLips"""
    def __init__(self, *args) -> None: ...
    TopBendLength: float
    MiddleBendLength: float
    LipLength: float
    BendWidth: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionStructuralTees(StructuralSectionGeneralT):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionStructuralTees"""
    def __init__(self, *args) -> None: ...
    BoltDiameter: float
    BoltSpacingWeb: float
    BoltSpacing: float
    SlopedWebAngle: float
    WebToeOfFillet: float
    TopWebFillet: float
    SlopedFlangeAngle: float
    FlangeToeOfFillet: float
    FlangeFillet: float
    WebFillet: float
    WebThicknessLocation: float
    WebThickness: float
    FlangeThicknessLocation: float
    FlangeThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionUserDefined(StructuralSectionRectangular):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionUserDefined"""
    def __init__(self, *args) -> None: ...
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionUtils:
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionUtils"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetStructuralElementDefinitionData(document: Document, elementId: ElementId, data: StructuralElementDefinitionData) -> StructuralSectionErrorCode: ...
    @staticmethod
    def GetStructuralSection(document: Document, elementId: ElementId) -> StructuralSection: ...
    @staticmethod
    def SetStructuralSection(document: Document, familySymbolId: ElementId, structuralSection: StructuralSection) -> bool: ...

class StructuralSectionZProfile(StructuralSectionGeneralLZ):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionZProfile"""
    def __init__(self, *args) -> None: ...
    LipLength: float
    BottomFlangeLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str

class StructuralSectionZProfileWithLips(StructuralSectionGeneralLZ):
    """.NET: Autodesk.Revit.DB.Structure.StructuralSections.StructuralSectionZProfileWithLips"""
    def __init__(self, *args) -> None: ...
    LipLength: float
    BottomFlangeLength: float
    InnerFillet: float
    WallDesignThickness: float
    WallNominalThickness: float
    NameKey: str
    CentroidVertical: float
    CentroidHorizontal: float
    Height: float
    Width: float
    IsValidObject: bool
    ShearAreaWeakAxis: float
    ShearAreaStrongAxis: float
    WarpingConstant: float
    TorsionalModulus: float
    TorsionalMomentOfInertia: float
    PlasticModulusWeakAxis: float
    PlasticModulusStrongAxis: float
    ElasticModulusWeakAxis: float
    ElasticModulusStrongAxis: float
    MomentOfInertiaWeakAxis: float
    MomentOfInertiaStrongAxis: float
    NominalWeight: float
    Perimeter: float
    SectionArea: float
    PrincipalAxesAngle: float
    StructuralSectionShapeName: str
    StructuralSectionGeneralShape: StructuralSectionGeneralShape
    StructuralSectionShape: StructuralSectionShape
    AnalysisParams: StructuralSectionAnalysisParams
    SectionNameKey: str
