# Auto-generated — Revit 2027 — Autodesk.Revit.DB.DirectContext3D

class Camera:
    """.NET: Autodesk.Revit.DB.DirectContext3D.Camera"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    FarDistance: float
    NearDistance: float
    VerticalOffset: float
    VerticalExtent: float
    HorizontalOffset: float
    HorizontalExtent: float
    TargetDistance: float
    ProjectionMethod: ProjectionMethod
    UpDirection: XYZ
    ViewDirection: XYZ
    EyePosition: XYZ
    def Dispose(self, ) -> None: ...
    def Transform(self, trf: Transform) -> None: ...

class ClipPlane:
    """.NET: Autodesk.Revit.DB.DirectContext3D.ClipPlane"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    Normal: XYZ
    Origin: XYZ
    def Dispose(self, ) -> None: ...

class DirectContext3DDocumentUtils:
    """.NET: Autodesk.Revit.DB.DirectContext3D.DirectContext3DDocumentUtils"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetDirectContext3DHandleInstances(aDocument: Document, handleCategory: ElementId) -> ISet: ...
    @staticmethod
    def GetDirectContext3DHandleTypes(aDocument: Document, handleCategory: ElementId) -> ISet: ...
    @staticmethod
    def IsADirectContext3DHandleCategory(categoryId: ElementId) -> bool: ...
    @staticmethod
    def IsADirectContext3DHandleInstance(aDocument: Document, elementId: ElementId) -> bool: ...
    @staticmethod
    def IsADirectContext3DHandleType(aDocument: Document, elementId: ElementId) -> bool: ...

class DirectContext3DHandleOverrides:
    """.NET: Autodesk.Revit.DB.DirectContext3D.DirectContext3DHandleOverrides"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Assign(self, other: DirectContext3DHandleOverrides) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetDirectContext3DHandleSettings(self, aDoc: Document, elementId: ElementId) -> DirectContext3DHandleSettings: ...
    def IsEqual(self, other: DirectContext3DHandleOverrides) -> bool: ...
    def SetDirectContext3DHandleSettings(self, aDoc: Document, elementId: ElementId, newSettings: DirectContext3DHandleSettings) -> None: ...

class DirectContext3DHandleSettings:
    """.NET: Autodesk.Revit.DB.DirectContext3D.DirectContext3DHandleSettings"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    Visibility: bool
    def Assign(self, other: DirectContext3DHandleSettings) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetColor(self, ) -> Color: ...
    def GetTransparency(self, ) -> int: ...
    def IsEqual(self, other: DirectContext3DHandleSettings) -> bool: ...
    def SetColor(self, color: Color) -> None: ...
    def SetTransparency(self, transparency: int) -> None: ...
    def SetVisibility(self, visibility: bool) -> None: ...

class DrawContext:
    """.NET: Autodesk.Revit.DB.DirectContext3D.DrawContext"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def FlushBuffer(vertexBuffer: VertexBuffer, vertexCount: int, indexBuffer: IndexBuffer, indexCount: int, vertexFormat: VertexFormat, effectInstance: EffectInstance, primitiveType: PrimitiveType, start: int, primitiveCount: int) -> None: ...
    @staticmethod
    def GetCamera() -> Camera: ...
    @staticmethod
    def GetClipPlanes() -> IList: ...
    @staticmethod
    def GetClipRectangle() -> Rectangle: ...
    @staticmethod
    def GetOverrideColor(color: Color) -> bool: ...
    @staticmethod
    def GetOverrideTransparency(transparency: float) -> bool: ...
    @staticmethod
    def GetViewRectangle() -> Rectangle: ...
    @staticmethod
    def IsAvailable() -> bool: ...
    @staticmethod
    def IsInterrupted() -> bool: ...
    @staticmethod
    def IsTransparentPass() -> bool: ...
    @staticmethod
    def SetWorldTransform(trf: Transform) -> None: ...

class EffectInstance:
    """.NET: Autodesk.Revit.DB.DirectContext3D.EffectInstance"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def IsValid(self, ) -> bool: ...
    def MatchesFormat(self, vertexFormat: VertexFormat) -> bool: ...
    def SetAmbientColor(self, color: Color) -> None: ...
    def SetColor(self, color: Color) -> None: ...
    def SetDiffuseColor(self, color: Color) -> None: ...
    def SetEmissiveColor(self, color: Color) -> None: ...
    def SetGlossiness(self, glossiness: float) -> None: ...
    def SetSpecularColor(self, color: Color) -> None: ...
    def SetTransparency(self, transparency: float) -> None: ...

class IDirectContext3DServer:
    """.NET: Autodesk.Revit.DB.DirectContext3D.IDirectContext3DServer"""
    def __init__(self, *args) -> None: ...
    def CanExecute(self, dBView: View) -> bool: ...
    def GetApplicationId(self, ) -> str: ...
    def GetBoundingBox(self, dBView: View) -> Outline: ...
    def GetSourceId(self, ) -> str: ...
    def RenderScene(self, dBView: View, displayStyle: DisplayStyle) -> None: ...
    def UseInTransparentPass(self, dBView: View) -> bool: ...
    def UsesHandles(self, ) -> bool: ...

class IndexBuffer:
    """.NET: Autodesk.Revit.DB.DirectContext3D.IndexBuffer"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def GetIndexStreamLine(self, ) -> IndexStreamLine: ...
    def GetIndexStreamPoint(self, ) -> IndexStreamPoint: ...
    def GetIndexStreamTriangle(self, ) -> IndexStreamTriangle: ...
    def GetMappedHandle(self, ) -> IntPtr: ...
    def IsValid(self, ) -> bool: ...
    def Map(self, sizeInShortInts: int) -> None: ...
    def Unmap(self, ) -> None: ...

class IndexLine(IndexPrimitive):
    """.NET: Autodesk.Revit.DB.DirectContext3D.IndexLine"""
    def __init__(self, *args) -> None: ...
    Index1: int
    Index0: int
    IsValidObject: bool
    @staticmethod
    def GetSizeInShortInts() -> int: ...

class IndexPoint(IndexPrimitive):
    """.NET: Autodesk.Revit.DB.DirectContext3D.IndexPoint"""
    def __init__(self, *args) -> None: ...
    Index: int
    IsValidObject: bool
    @staticmethod
    def GetSizeInShortInts() -> int: ...

class IndexPrimitive:
    """.NET: Autodesk.Revit.DB.DirectContext3D.IndexPrimitive"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...

class IndexStream:
    """.NET: Autodesk.Revit.DB.DirectContext3D.IndexStream"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...

class IndexStreamLine(IndexStream):
    """.NET: Autodesk.Revit.DB.DirectContext3D.IndexStreamLine"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def AddLine(self, line: IndexLine) -> None: ...
    def AddLines(self, lines: IList) -> None: ...

class IndexStreamPoint(IndexStream):
    """.NET: Autodesk.Revit.DB.DirectContext3D.IndexStreamPoint"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def AddPoint(self, point: IndexPoint) -> None: ...
    def AddPoints(self, points: IList) -> None: ...

class IndexStreamTriangle(IndexStream):
    """.NET: Autodesk.Revit.DB.DirectContext3D.IndexStreamTriangle"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def AddTriangle(self, triangle: IndexTriangle) -> None: ...
    def AddTriangles(self, triangles: IList) -> None: ...

class IndexTriangle(IndexPrimitive):
    """.NET: Autodesk.Revit.DB.DirectContext3D.IndexTriangle"""
    def __init__(self, *args) -> None: ...
    Index2: int
    Index1: int
    Index0: int
    IsValidObject: bool
    @staticmethod
    def GetSizeInShortInts() -> int: ...

class PrimitiveType:
    """.NET: Autodesk.Revit.DB.DirectContext3D.PrimitiveType"""
    def __init__(self, *args) -> None: ...
    ...

class ProjectionMethod:
    """.NET: Autodesk.Revit.DB.DirectContext3D.ProjectionMethod"""
    def __init__(self, *args) -> None: ...
    ...

class Vertex:
    """.NET: Autodesk.Revit.DB.DirectContext3D.Vertex"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...

class VertexBuffer:
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexBuffer"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def GetMappedHandle(self, ) -> IntPtr: ...
    def GetVertexStreamPosition(self, ) -> VertexStreamPosition: ...
    def GetVertexStreamPositionColored(self, ) -> VertexStreamPositionColored: ...
    def GetVertexStreamPositionNormal(self, ) -> VertexStreamPositionNormal: ...
    def GetVertexStreamPositionNormalColored(self, ) -> VertexStreamPositionNormalColored: ...
    def IsValid(self, ) -> bool: ...
    def Map(self, sizeInFloats: int) -> None: ...
    def Unmap(self, ) -> None: ...

class VertexFormat:
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexFormat"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def IsValid(self, ) -> bool: ...

class VertexFormatBits:
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexFormatBits"""
    def __init__(self, *args) -> None: ...
    ...

class VertexPosition(Vertex):
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexPosition"""
    def __init__(self, *args) -> None: ...
    Position: XYZ
    IsValidObject: bool
    @staticmethod
    def GetSizeInFloats() -> int: ...

class VertexPositionColored(Vertex):
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexPositionColored"""
    def __init__(self, *args) -> None: ...
    Position: XYZ
    IsValidObject: bool
    def GetColor(self, ) -> ColorWithTransparency: ...
    @staticmethod
    def GetSizeInFloats() -> int: ...
    def SetColor(self, color: ColorWithTransparency) -> None: ...

class VertexPositionNormal(Vertex):
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexPositionNormal"""
    def __init__(self, *args) -> None: ...
    Normal: XYZ
    Position: XYZ
    IsValidObject: bool
    @staticmethod
    def GetSizeInFloats() -> int: ...

class VertexPositionNormalColored(Vertex):
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexPositionNormalColored"""
    def __init__(self, *args) -> None: ...
    Normal: XYZ
    Position: XYZ
    IsValidObject: bool
    def GetColor(self, ) -> ColorWithTransparency: ...
    @staticmethod
    def GetSizeInFloats() -> int: ...
    def SetColor(self, color: ColorWithTransparency) -> None: ...

class VertexStream:
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexStream"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...

class VertexStreamPosition(VertexStream):
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexStreamPosition"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def AddVertex(self, vertex: VertexPosition) -> None: ...
    def AddVertices(self, vertices: IList) -> None: ...

class VertexStreamPositionColored(VertexStream):
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexStreamPositionColored"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def AddVertex(self, vertex: VertexPositionColored) -> None: ...
    def AddVertices(self, vertices: IList) -> None: ...

class VertexStreamPositionNormal(VertexStream):
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexStreamPositionNormal"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def AddVertex(self, vertex: VertexPositionNormal) -> None: ...
    def AddVertices(self, vertices: IList) -> None: ...

class VertexStreamPositionNormalColored(VertexStream):
    """.NET: Autodesk.Revit.DB.DirectContext3D.VertexStreamPositionNormalColored"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def AddVertex(self, vertex: VertexPositionNormalColored) -> None: ...
    def AddVertices(self, vertices: IList) -> None: ...
