# Auto-generated — Revit 2027 — Autodesk.Revit.DB.ExtensibleStorage

class AccessLevel:
    """.NET: Autodesk.Revit.DB.ExtensibleStorage.AccessLevel"""
    def __init__(self, *args) -> None: ...
    ...

class ContainerType:
    """.NET: Autodesk.Revit.DB.ExtensibleStorage.ContainerType"""
    def __init__(self, *args) -> None: ...
    ...

class DataStorage(Element):
    """.NET: Autodesk.Revit.DB.ExtensibleStorage.DataStorage"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    DemolishedPhaseId: ElementId
    CreatedPhaseId: ElementId
    OwnerViewId: ElementId
    ViewSpecific: bool
    AssemblyInstanceId: ElementId
    LevelId: ElementId
    UniqueId: str
    IsTransient: bool
    Id: ElementId
    GroupId: ElementId
    IsModifiable: bool
    VersionGuid: Guid
    WorksetId: WorksetId
    Pinned: bool
    BoundingBox: BoundingBoxXYZ
    Geometry: GeometryElement
    DesignOption: DesignOption
    Document: Document
    Location: Location
    ParametersMap: ParameterMap
    Parameters: ParameterSet
    Parameter: Parameter
    Parameter: Parameter
    Parameter: Parameter
    Category: Category
    Name: str
    @staticmethod
    def Create(doc: Document) -> DataStorage: ...

class Entity:
    """.NET: Autodesk.Revit.DB.ExtensibleStorage.Entity"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    SchemaGUID: Guid
    Schema: Schema
    def Clear(self, fieldName: str) -> None: ...
    def Dispose(self, ) -> None: ...
    def Get(self, fieldName: str, unitTypeId: ForgeTypeId) -> FieldType: ...
    def IsValid(self, ) -> bool: ...
    def ReadAccessGranted(self, ) -> bool: ...
    def RecognizedField(self, field: Field) -> bool: ...
    def Set(self, fieldName: str, value: FieldType, unitTypeId: ForgeTypeId) -> None: ...
    def WriteAccessGranted(self, ) -> bool: ...

class ExtensibleStorageFilter(ElementQuickFilter):
    """.NET: Autodesk.Revit.DB.ExtensibleStorage.ExtensibleStorageFilter"""
    def __init__(self, *args) -> None: ...
    SchemaGuid: Guid
    IsValidObject: bool
    Inverted: bool

class Field:
    """.NET: Autodesk.Revit.DB.ExtensibleStorage.Field"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    SubSchema: Schema
    KeyType: Type
    ValueType: Type
    Documentation: str
    ContainerType: ContainerType
    SubSchemaGUID: Guid
    Schema: Schema
    FieldName: str
    def CompatibleUnit(self, unitTypeId: ForgeTypeId) -> bool: ...
    def Dispose(self, ) -> None: ...
    def GetSpecTypeId(self, ) -> ForgeTypeId: ...
    def SubEntityReadAccessGranted(self, ) -> bool: ...
    def SubEntityWriteAccessGranted(self, ) -> bool: ...

class FieldBuilder:
    """.NET: Autodesk.Revit.DB.ExtensibleStorage.FieldBuilder"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def NeedsSubSchemaGUID(self, ) -> bool: ...
    def NeedsUnits(self, ) -> bool: ...
    def Ready(self, ) -> bool: ...
    def SetDocumentation(self, documentation: str) -> FieldBuilder: ...
    def SetSpec(self, specTypeId: ForgeTypeId) -> FieldBuilder: ...
    def SetSubSchemaGUID(self, guid: Guid) -> FieldBuilder: ...

class Schema:
    """.NET: Autodesk.Revit.DB.ExtensibleStorage.Schema"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    Documentation: str
    VendorId: str
    ApplicationGUID: Guid
    WriteAccessLevel: AccessLevel
    ReadAccessLevel: AccessLevel
    SchemaName: str
    GUID: Guid
    def Dispose(self, ) -> None: ...
    def GetField(self, name: str) -> Field: ...
    def ListFields(self, ) -> IList: ...
    @staticmethod
    def ListSchemas() -> IList: ...
    @staticmethod
    def Lookup(guid: Guid) -> Schema: ...
    def ReadAccessGranted(self, ) -> bool: ...
    def WriteAccessGranted(self, ) -> bool: ...

class SchemaBuilder:
    """.NET: Autodesk.Revit.DB.ExtensibleStorage.SchemaBuilder"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def AcceptableName(self, name: str) -> bool: ...
    def AddArrayField(self, fieldName: str, fieldType: Type) -> FieldBuilder: ...
    def AddMapField(self, fieldName: str, keyType: Type, valueType: Type) -> FieldBuilder: ...
    def AddSimpleField(self, fieldName: str, fieldType: Type) -> FieldBuilder: ...
    def Dispose(self, ) -> None: ...
    def Finish(self, ) -> Schema: ...
    @staticmethod
    def GUIDIsValid(guid: Guid) -> bool: ...
    def Ready(self, ) -> bool: ...
    def SetApplicationGUID(self, applicationGUID: Guid) -> SchemaBuilder: ...
    def SetDocumentation(self, documentation: str) -> SchemaBuilder: ...
    def SetReadAccessLevel(self, readAccessLevel: AccessLevel) -> SchemaBuilder: ...
    def SetSchemaName(self, schemaName: str) -> SchemaBuilder: ...
    def SetVendorId(self, vendorId: str) -> SchemaBuilder: ...
    def SetWriteAccessLevel(self, writeAccessLevel: AccessLevel) -> SchemaBuilder: ...
    @staticmethod
    def VendorIdIsValid(vendorId: str) -> bool: ...
