# Auto-generated — Revit 2027 — Autodesk.Revit.DB.ExternalService

class DisparityResponse:
    """.NET: Autodesk.Revit.DB.ExternalService.DisparityResponse"""
    def __init__(self, *args) -> None: ...
    ...

class ExecutionPolicy:
    """.NET: Autodesk.Revit.DB.ExternalService.ExecutionPolicy"""
    def __init__(self, *args) -> None: ...
    ...

class ExternalService:
    """.NET: Autodesk.Revit.DB.ExternalService.ExternalService"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    NumberOfServers: int
    SupportActivation: bool
    IsSerializable: bool
    VendorId: str
    Description: str
    Name: str
    ServiceId: ExternalServiceId
    def AddServer(self, server: IExternalServer) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetDefaultServerId(self, ) -> Guid: ...
    def GetOptions(self, ) -> ExternalServiceOptions: ...
    def GetPublicAccessKey(self, ) -> Guid: ...
    def GetRegisteredServerIds(self, ) -> IList: ...
    def GetServer(self, serverId: Guid) -> IExternalServer: ...
    def IsRegisteredServerId(self, serverId: Guid) -> bool: ...
    def RemoveServer(self, serverId: Guid) -> None: ...

class ExternalServiceId(GuidEnum):
    """.NET: Autodesk.Revit.DB.ExternalService.ExternalServiceId"""
    def __init__(self, *args) -> None: ...
    Guid: Guid

class ExternalServiceOptions:
    """.NET: Autodesk.Revit.DB.ExternalService.ExternalServiceOptions"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    SupportActivation: bool
    IsSelfsynchronizing: bool
    IsRecordable: bool
    IsPublic: bool
    def Dispose(self, ) -> None: ...

class ExternalServiceRegistry:
    """.NET: Autodesk.Revit.DB.ExternalService.ExternalServiceRegistry"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ExecuteService(executionKey: Guid, serverId: Guid, data: IExternalData) -> ExternalServiceResult: ...
    @staticmethod
    def GetService(serviceId: ExternalServiceId) -> ExternalService: ...
    @staticmethod
    def GetServices() -> IList: ...
    @staticmethod
    def RegisterService(service: ISingleServerService, defaultServerId: Guid, options: ExternalServiceOptions) -> Guid: ...

class ExternalServiceResult:
    """.NET: Autodesk.Revit.DB.ExternalService.ExternalServiceResult"""
    def __init__(self, *args) -> None: ...
    ...

class ExternalServices:
    """.NET: Autodesk.Revit.DB.ExternalService.ExternalServices"""
    def __init__(self, *args) -> None: ...
    ...

class IExternalData:
    """.NET: Autodesk.Revit.DB.ExternalService.IExternalData"""
    def __init__(self, *args) -> None: ...
    ...

class IExternalServer:
    """.NET: Autodesk.Revit.DB.ExternalService.IExternalServer"""
    def __init__(self, *args) -> None: ...
    def GetDescription(self, ) -> str: ...
    def GetName(self, ) -> str: ...
    def GetServerId(self, ) -> Guid: ...
    def GetServiceId(self, ) -> ExternalServiceId: ...
    def GetVendorId(self, ) -> str: ...

class IExternalService:
    """.NET: Autodesk.Revit.DB.ExternalService.IExternalService"""
    def __init__(self, *args) -> None: ...
    def Execute(self, server: IExternalServer, document: Document, data: IExternalData) -> bool: ...
    def GetDescription(self, ) -> str: ...
    def GetName(self, ) -> str: ...
    def GetServiceId(self, ) -> ExternalServiceId: ...
    def GetVendorId(self, ) -> str: ...
    def IsValidServer(self, server: IExternalServer) -> bool: ...
    def OnServersChanged(self, document: Document, cause: ServerChangeCause, oldServers: IList) -> None: ...
    def OnServersDisparity(self, document: Document, oldServers: IList) -> DisparityResponse: ...

class IMultiServerService:
    """.NET: Autodesk.Revit.DB.ExternalService.IMultiServerService"""
    def __init__(self, *args) -> None: ...
    def CanExecute(self, server: IExternalServer, document: Document, data: IExternalData) -> bool: ...

class ISingleServerService:
    """.NET: Autodesk.Revit.DB.ExternalService.ISingleServerService"""
    def __init__(self, *args) -> None: ...
    ...

class MultiServerService(ExternalService):
    """.NET: Autodesk.Revit.DB.ExternalService.MultiServerService"""
    def __init__(self, *args) -> None: ...
    ExecutionPolicy: ExecutionPolicy
    IsValidObject: bool
    NumberOfServers: int
    SupportActivation: bool
    IsSerializable: bool
    VendorId: str
    Description: str
    Name: str
    ServiceId: ExternalServiceId
    def GetActiveServerIds(self, document: Document) -> IList: ...
    def SetActiveServers(self, serverIds: IList, document: Document) -> None: ...
    def SetServerState(self, serverId: Guid, document: Document, bActive: bool) -> bool: ...

class ServerChangeCause:
    """.NET: Autodesk.Revit.DB.ExternalService.ServerChangeCause"""
    def __init__(self, *args) -> None: ...
    ...

class SingleServerService(ExternalService):
    """.NET: Autodesk.Revit.DB.ExternalService.SingleServerService"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    NumberOfServers: int
    SupportActivation: bool
    IsSerializable: bool
    VendorId: str
    Description: str
    Name: str
    ServiceId: ExternalServiceId
    def GetActiveServerId(self, document: Document) -> Guid: ...
    def SetActiveServer(self, serverId: Guid, document: Document) -> None: ...
    def UnsetActiveServer(self, document: Document) -> None: ...
