# Auto-generated — Revit 2027 — Autodesk.Revit.DB.Fabrication

class DesignToFabricationConverter:
    """.NET: Autodesk.Revit.DB.Fabrication.DesignToFabricationConverter"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Convert(self, selection: ISet, serviceId: int) -> DesignToFabricationConverterResult: ...
    def Dispose(self, ) -> None: ...
    def GetConvertedFabricationParts(self, ) -> ISet: ...
    def GetConvertedFabricationPartsWithInvalidConnections(self, ) -> IDictionary: ...
    def GetDesignElementAndFabricationPartsWithDifferentOffsets(self, ) -> IDictionary: ...
    def GetDesignElementAndFabricationPartsWithOpenConnectors(self, ) -> IDictionary: ...
    def GetElementsWithOpenConnector(self, ) -> ISet: ...
    def GetPartialConvertFailureResults(self, ) -> IList: ...
    def SetMapForFamilySymbolToFabricationPartType(self, typeMappings: IDictionary) -> DesignToFabricationMappingResult: ...

class DesignToFabricationConverterResult:
    """.NET: Autodesk.Revit.DB.Fabrication.DesignToFabricationConverterResult"""
    def __init__(self, *args) -> None: ...
    ...

class DesignToFabricationMappingResult:
    """.NET: Autodesk.Revit.DB.Fabrication.DesignToFabricationMappingResult"""
    def __init__(self, *args) -> None: ...
    ...

class FabricationAncillaryType:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationAncillaryType"""
    def __init__(self, *args) -> None: ...
    ...

class FabricationAncillaryUsageType:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationAncillaryUsageType"""
    def __init__(self, *args) -> None: ...
    ...

class FabricationCustomDataType:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationCustomDataType"""
    def __init__(self, *args) -> None: ...
    ...

class FabricationHandlePosition:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationHandlePosition"""
    def __init__(self, *args) -> None: ...
    ...

class FabricationNetworkChangeService:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationNetworkChangeService"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def ApplyChange(self, ) -> FabricationNetworkChangeServiceResult: ...
    def ChangeService(self, selection: ISet, serviceId: int, paletteId: int, restrictPalette: bool) -> FabricationNetworkChangeServiceResult: ...
    def ChangeSize(self, selection: ISet, fabricationPartSizeMaps: ISet) -> FabricationNetworkChangeServiceResult: ...
    def Dispose(self, ) -> None: ...
    def GetDeletePartFailureState(self, ) -> bool: ...
    def GetElementsThatFailed(self, ) -> ISet: ...
    def GetInLinePartTypes(self, ) -> ISet: ...
    def GetMapOfAllSizesForStraights(self, ) -> ISet: ...
    def GetPartTypeMappingState(self, ) -> bool: ...
    def GetPartTypesforMapping(self, ) -> ISet: ...
    def GetStraightsThatWereNotChanged(self, ) -> ISet: ...
    def SetDeletePartFailureState(self, state: bool) -> None: ...
    def SetMapOfInLinePartTypes(self, fabricationPartTypes: IDictionary) -> None: ...
    def SetMapOfSizesForStraights(self, fabricationPartSizeMaps: ISet) -> None: ...
    def SetPaletteId(self, paletteId: int) -> None: ...
    def SetPartTypeMappingState(self, state: bool) -> None: ...
    def SetPartTypesforMapping(self, fabricationPartTypes: IDictionary) -> None: ...
    def SetRestrictPalette(self, restrictPalette: bool) -> None: ...
    def SetSelection(self, selection: ISet) -> FabricationNetworkChangeServiceResult: ...
    def SetServiceId(self, serviceId: int) -> None: ...

class FabricationNetworkChangeServiceResult:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationNetworkChangeServiceResult"""
    def __init__(self, *args) -> None: ...
    ...

class FabricationPartCompareType:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationPartCompareType"""
    def __init__(self, *args) -> None: ...
    ...

class FabricationPartFitResult:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationPartFitResult"""
    def __init__(self, *args) -> None: ...
    ...

class FabricationPartJustification:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationPartJustification"""
    def __init__(self, *args) -> None: ...
    ...

class FabricationPartPlacementUtils:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationPartPlacementUtils"""
    def __init__(self, *args) -> None: ...
    ...

class FabricationPartRouteEnd:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationPartRouteEnd"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    @staticmethod
    def CreateFromCenterline(element: Element, ptAt: XYZ) -> FabricationPartRouteEnd: ...
    @staticmethod
    def CreateFromConnector(connnector: Connector) -> FabricationPartRouteEnd: ...
    def Dispose(self, ) -> None: ...

class FabricationPartSizeMap:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationPartSizeMap"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    AllowMultipleServiceSizes: bool
    MappedServiceId: int
    MappedProfileType: ConnectorProfileType
    IsMappedProductList: bool
    MappedDepth: float
    MappedWidthDiameter: float
    PaletteId: int
    ServiceId: int
    ProfileType: ConnectorProfileType
    IsProductList: bool
    Depth: float
    WidthDiameter: float
    SizeString: str
    def Dispose(self, ) -> None: ...

class FabricationSaveJobOptions:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationSaveJobOptions"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    AddHolesForTaps: bool
    def Dispose(self, ) -> None: ...

class FabricationUtils:
    """.NET: Autodesk.Revit.DB.Fabrication.FabricationUtils"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ExportToPCF(document: Document, ids: IList, filename: str) -> None: ...
    @staticmethod
    def ValidateConnectivity(document: Document, connector1: Connector, connector2: Connector) -> bool: ...

class PartialFailureResults:
    """.NET: Autodesk.Revit.DB.Fabrication.PartialFailureResults"""
    def __init__(self, *args) -> None: ...
    ...

class ValidationStatus:
    """.NET: Autodesk.Revit.DB.Fabrication.ValidationStatus"""
    def __init__(self, *args) -> None: ...
    ...
