# Auto-generated — Revit 2027 — Autodesk.Revit.DB.IFC

class IFCImportAction:
    """.NET: Autodesk.Revit.DB.IFC.IFCImportAction"""
    def __init__(self, *args) -> None: ...
    ...

class IFCImportIntent:
    """.NET: Autodesk.Revit.DB.IFC.IFCImportIntent"""
    def __init__(self, *args) -> None: ...
    ...

class IFCImportOptions:
    """.NET: Autodesk.Revit.DB.IFC.IFCImportOptions"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    ForceImport: bool
    LinkPosition: IFCLinkPosition
    LinkOrientation: IFCLinkOrientation
    RevitLinkFileName: str
    CreateLinkInstanceOnly: bool
    Action: IFCImportAction
    AutocorrectOffAxisLines: bool
    AutoJoin: bool
    Intent: IFCImportIntent
    def Dispose(self, ) -> None: ...
    def GetConversionData(self, ) -> LinkConversionData: ...
    def GetExtraOptions(self, ) -> IDictionary: ...
    def SetExtraOptions(self, options: IDictionary) -> None: ...

class IFCLinkOrientation:
    """.NET: Autodesk.Revit.DB.IFC.IFCLinkOrientation"""
    def __init__(self, *args) -> None: ...
    ...

class IFCLinkPosition:
    """.NET: Autodesk.Revit.DB.IFC.IFCLinkPosition"""
    def __init__(self, *args) -> None: ...
    ...
