# Auto-generated — Revit 2027 — Autodesk.Revit.DB.Lighting

class AdvancedLossFactor(LossFactor):
    """.NET: Autodesk.Revit.DB.Lighting.AdvancedLossFactor"""
    def __init__(self, *args) -> None: ...
    VoltageLossFactor: float
    TemperatureLossFactor: float
    SurfaceDepreciationLossFactor: float
    LuminaireDirtDepreciation: float
    LampTiltLossFactor: float
    LampLumenDepreciation: float
    BallastLossFactor: float
    IsValidObject: bool
    LossFactorValue: float

class BasicLossFactor(LossFactor):
    """.NET: Autodesk.Revit.DB.Lighting.BasicLossFactor"""
    def __init__(self, *args) -> None: ...
    LossFactor: float
    IsValidObject: bool
    LossFactorValue: float

class CircleLightShape(LightShape):
    """.NET: Autodesk.Revit.DB.Lighting.CircleLightShape"""
    def __init__(self, *args) -> None: ...
    EmitDiameter: float
    IsValidObject: bool

class ColorPreset:
    """.NET: Autodesk.Revit.DB.Lighting.ColorPreset"""
    def __init__(self, *args) -> None: ...
    ...

class CustomInitialColor(InitialColor):
    """.NET: Autodesk.Revit.DB.Lighting.CustomInitialColor"""
    def __init__(self, *args) -> None: ...
    Temperature: float
    IsValidObject: bool
    TemperatureValue: float

class HemisphericalLightDistribution(LightDistribution):
    """.NET: Autodesk.Revit.DB.Lighting.HemisphericalLightDistribution"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool

class InitialColor:
    """.NET: Autodesk.Revit.DB.Lighting.InitialColor"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    TemperatureValue: float
    def Clone(self, ) -> InitialColor: ...
    def Dispose(self, ) -> None: ...

class InitialFluxIntensity(InitialIntensity):
    """.NET: Autodesk.Revit.DB.Lighting.InitialFluxIntensity"""
    def __init__(self, *args) -> None: ...
    Flux: float
    IsValidObject: bool
    InitialIntensityValue: float

class InitialIlluminanceIntensity(InitialIntensity):
    """.NET: Autodesk.Revit.DB.Lighting.InitialIlluminanceIntensity"""
    def __init__(self, *args) -> None: ...
    Illuminance: float
    Distance: float
    IsValidObject: bool
    InitialIntensityValue: float

class InitialIntensity:
    """.NET: Autodesk.Revit.DB.Lighting.InitialIntensity"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    InitialIntensityValue: float
    def Clone(self, ) -> InitialIntensity: ...
    def Dispose(self, ) -> None: ...

class InitialLuminousIntensity(InitialIntensity):
    """.NET: Autodesk.Revit.DB.Lighting.InitialLuminousIntensity"""
    def __init__(self, *args) -> None: ...
    Luminosity: float
    IsValidObject: bool
    InitialIntensityValue: float

class InitialWattageIntensity(InitialIntensity):
    """.NET: Autodesk.Revit.DB.Lighting.InitialWattageIntensity"""
    def __init__(self, *args) -> None: ...
    Wattage: float
    Efficacy: float
    IsValidObject: bool
    InitialIntensityValue: float

class LightDimmingColor:
    """.NET: Autodesk.Revit.DB.Lighting.LightDimmingColor"""
    def __init__(self, *args) -> None: ...
    ...

class LightDistribution:
    """.NET: Autodesk.Revit.DB.Lighting.LightDistribution"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Clone(self, ) -> LightDistribution: ...
    def Dispose(self, ) -> None: ...

class LightDistributionStyle:
    """.NET: Autodesk.Revit.DB.Lighting.LightDistributionStyle"""
    def __init__(self, *args) -> None: ...
    ...

class LightFamily:
    """.NET: Autodesk.Revit.DB.Lighting.LightFamily"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def GetLightDistributionStyle(self, ) -> LightDistributionStyle: ...
    @staticmethod
    def GetLightFamily(document: Document) -> LightFamily: ...
    def GetLightShapeStyle(self, ) -> LightShapeStyle: ...
    def GetLightSourceTransform(self, ) -> Transform: ...
    def GetLightType(self, index: int) -> LightType: ...
    def GetLightTypeName(self, index: int) -> str: ...
    def GetNumberOfLightTypes(self, ) -> int: ...
    def SetLightDistributionStyle(self, lightDistributionStyle: LightDistributionStyle) -> None: ...
    def SetLightShapeStyle(self, lightShapeStyle: LightShapeStyle) -> None: ...

class LightGroup:
    """.NET: Autodesk.Revit.DB.Lighting.LightGroup"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    Id: ElementId
    Name: str
    def AddLight(self, lightId: ElementId) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetLights(self, ) -> ICollection: ...
    def RemoveLight(self, lightId: ElementId) -> None: ...

class LightGroupManager:
    """.NET: Autodesk.Revit.DB.Lighting.LightGroupManager"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def CreateGroup(self, name: str) -> LightGroup: ...
    def DeleteGroup(self, groupId: ElementId) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetGroups(self, ) -> IList: ...
    def GetLightDimmer(self, viewId: ElementId, lightId: ElementId) -> float: ...
    @staticmethod
    def GetLightGroupManager(document: Document) -> LightGroupManager: ...
    def IsLightGroupOn(self, viewId: ElementId, groupId: ElementId) -> bool: ...
    def IsLightOn(self, viewId: ElementId, lightId: ElementId) -> bool: ...
    def SetLightDimmer(self, viewId: ElementId, lightId: ElementId, dimmingValue: float) -> None: ...
    def SetLightGroupOn(self, viewId: ElementId, groupId: ElementId, turnOn: bool) -> None: ...
    def SetLightOn(self, viewId: ElementId, lightId: ElementId, turnOn: bool) -> None: ...

class LightShape:
    """.NET: Autodesk.Revit.DB.Lighting.LightShape"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Clone(self, ) -> LightShape: ...
    def Dispose(self, ) -> None: ...

class LightShapeStyle:
    """.NET: Autodesk.Revit.DB.Lighting.LightShapeStyle"""
    def __init__(self, *args) -> None: ...
    ...

class LightType:
    """.NET: Autodesk.Revit.DB.Lighting.LightType"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    DimmingColor: LightDimmingColor
    ColorFilter: Color
    def Dispose(self, ) -> None: ...
    def GetInitialColor(self, ) -> InitialColor: ...
    def GetInitialIntensity(self, ) -> InitialIntensity: ...
    def GetLightDistribution(self, ) -> LightDistribution: ...
    def GetLightShape(self, ) -> LightShape: ...
    @staticmethod
    def GetLightType(document: Document, typeId: ElementId) -> LightType: ...
    @staticmethod
    def GetLightTypeFromInstance(document: Document, instanceId: ElementId) -> LightType: ...
    def GetLossFactor(self, ) -> LossFactor: ...
    def SetInitialColor(self, initialColor: InitialColor) -> None: ...
    def SetInitialIntensity(self, initialIntensity: InitialIntensity) -> None: ...
    def SetLightDistribution(self, lightDistribution: LightDistribution) -> None: ...
    def SetLightShape(self, lightShape: LightShape) -> None: ...
    def SetLossFactor(self, lossFactor: LossFactor) -> None: ...

class LineLightShape(LightShape):
    """.NET: Autodesk.Revit.DB.Lighting.LineLightShape"""
    def __init__(self, *args) -> None: ...
    EmitLength: float
    IsValidObject: bool

class LossFactor:
    """.NET: Autodesk.Revit.DB.Lighting.LossFactor"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    LossFactorValue: float
    def Clone(self, ) -> LossFactor: ...
    def Dispose(self, ) -> None: ...

class PhotometricWebLightDistribution(LightDistribution):
    """.NET: Autodesk.Revit.DB.Lighting.PhotometricWebLightDistribution"""
    def __init__(self, *args) -> None: ...
    TiltAngle: float
    PhotometricWebFile: str
    IsValidObject: bool

class PointLightShape(LightShape):
    """.NET: Autodesk.Revit.DB.Lighting.PointLightShape"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool

class PresetInitialColor(InitialColor):
    """.NET: Autodesk.Revit.DB.Lighting.PresetInitialColor"""
    def __init__(self, *args) -> None: ...
    Preset: ColorPreset
    IsValidObject: bool
    TemperatureValue: float

class RectangleLightShape(LightShape):
    """.NET: Autodesk.Revit.DB.Lighting.RectangleLightShape"""
    def __init__(self, *args) -> None: ...
    EmitWidth: float
    EmitLength: float
    IsValidObject: bool

class SphericalLightDistribution(LightDistribution):
    """.NET: Autodesk.Revit.DB.Lighting.SphericalLightDistribution"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool

class SpotLightDistribution(LightDistribution):
    """.NET: Autodesk.Revit.DB.Lighting.SpotLightDistribution"""
    def __init__(self, *args) -> None: ...
    TiltAngle: float
    SpotFieldAngle: float
    SpotBeamAngle: float
    IsValidObject: bool
