# Auto-generated — Revit 2027 — Autodesk.Revit.DB.PointClouds

class CloudPoint:
    """.NET: Autodesk.Revit.DB.PointClouds.CloudPoint"""
    def __init__(self, *args) -> None: ...
    ...

class IPointCloudAccess:
    """.NET: Autodesk.Revit.DB.PointClouds.IPointCloudAccess"""
    def __init__(self, *args) -> None: ...
    def CreatePointSetIterator(self, rFilter: PointCloudFilter, density: float, viewId: ElementId) -> IPointSetIterator: ...
    def Free(self, ) -> None: ...
    def GetColorEncoding(self, ) -> PointCloudColorEncoding: ...
    def GetExtent(self, ) -> Outline: ...
    def GetName(self, ) -> str: ...
    def GetOffset(self, ) -> XYZ: ...
    def GetUnitsToFeetConversionFactor(self, ) -> float: ...
    def ReadPoints(self, rFilter: PointCloudFilter, viewId: ElementId, buffer: IntPtr, nBufferSize: int) -> int: ...

class IPointCloudEngine:
    """.NET: Autodesk.Revit.DB.PointClouds.IPointCloudEngine"""
    def __init__(self, *args) -> None: ...
    def CreatePointCloudAccess(self, identifier: str) -> IPointCloudAccess: ...
    def Free(self, ) -> None: ...

class IPointSetIterator:
    """.NET: Autodesk.Revit.DB.PointClouds.IPointSetIterator"""
    def __init__(self, *args) -> None: ...
    def Free(self, ) -> None: ...
    def ReadPoints(self, buffer: IntPtr, bufferSize: int) -> int: ...

class PointCloudColorEncoding:
    """.NET: Autodesk.Revit.DB.PointClouds.PointCloudColorEncoding"""
    def __init__(self, *args) -> None: ...
    ...

class PointCloudColorSettings:
    """.NET: Autodesk.Revit.DB.PointClouds.PointCloudColorSettings"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    Color2: Color
    Color1: Color
    def Assign(self, other: PointCloudColorSettings) -> None: ...
    def Dispose(self, ) -> None: ...
    def IsEqual(self, other: PointCloudColorSettings) -> bool: ...

class PointCloudEngineRegistry:
    """.NET: Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetSupportedEngines() -> IList: ...
    @staticmethod
    def IsEngineFileBased(identifier: str) -> bool: ...
    @staticmethod
    def RegisterPointCloudEngine(identifier: str, engine: IPointCloudEngine, isFileBased: bool) -> None: ...
    @staticmethod
    def UnregisterPointCloudEngine(identifier: str) -> None: ...

class PointCloudFilter:
    """.NET: Autodesk.Revit.DB.PointClouds.PointCloudFilter"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Clone(self, ) -> PointCloudFilter: ...
    def Dispose(self, ) -> None: ...
    def PrepareForCell(self, min: XYZ, max: XYZ, numTests: int) -> None: ...
    def TestCell(self, min: XYZ, max: XYZ) -> int: ...
    def TestPoint(self, point: CloudPoint) -> bool: ...

class PointCloudFilterFactory:
    """.NET: Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CreateMultiPlaneFilter(planes: IList, exactPlaneCount: int) -> PointCloudFilter: ...

class PointCloudFilterUtils:
    """.NET: Autodesk.Revit.DB.PointClouds.PointCloudFilterUtils"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetFilteredOutline(filter: PointCloudFilter, box: Outline) -> Outline: ...

class PointCloudOverrideSettings:
    """.NET: Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    ColorMode: PointCloudColorMode
    Visible: bool
    def Assign(self, other: PointCloudOverrideSettings) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetModeOverride(self, mode: PointCloudColorMode) -> PointCloudColorSettings: ...
    def IsEqual(self, other: PointCloudOverrideSettings) -> bool: ...
    def SetModeOverride(self, mode: PointCloudColorMode, colorSettings: PointCloudColorSettings) -> None: ...

class PointCloudOverrides:
    """.NET: Autodesk.Revit.DB.PointClouds.PointCloudOverrides"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    @staticmethod
    def ArePointCloudOverrideSettingsValid(tag: str, settings: PointCloudOverrideSettings) -> bool: ...
    def Assign(self, other: PointCloudOverrides) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetPointCloudRegionOverrideSettings(self, elementId: ElementId, regionTag: str, doc: Document) -> PointCloudOverrideSettings: ...
    def GetPointCloudScanOverrideSettings(self, elementId: ElementId, scanTag: str, doc: Document) -> PointCloudOverrideSettings: ...
    def IsEqual(self, other: PointCloudOverrides) -> bool: ...
    def SetPointCloudRegionOverrideSettings(self, elementId: ElementId, newSettings: PointCloudOverrideSettings, regionTag: str, doc: Document) -> None: ...
    def SetPointCloudScanOverrideSettings(self, elementId: ElementId, newSettings: PointCloudOverrideSettings, scanTag: str, doc: Document) -> None: ...

class PointCollection:
    """.NET: Autodesk.Revit.DB.PointClouds.PointCollection"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    Count: int
    def Dispose(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetPointBufferPointer(self, ) -> IntPtr: ...
    def GetPointIterator(self, ) -> PointIterator: ...

class PointIterator:
    """.NET: Autodesk.Revit.DB.PointClouds.PointIterator"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    CurrentObject: object
    Current: CloudPoint
    def Dispose(self, ) -> None: ...
    def Free(self, ) -> None: ...
    def IsDone(self, ) -> bool: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...
