# Auto-generated — Revit 2027 — Autodesk.Revit.DB.Steel

class SteelElementProperties(APIObject):
    """.NET: Autodesk.Revit.DB.Steel.SteelElementProperties"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    UniqueID: Guid
    IsReadOnly: bool
    @staticmethod
    def AddFabricationInformationForRevitElements(aDoc: Document, elementIds: IList) -> IList: ...
    @staticmethod
    def GetFabricationUniqueID(aDoc: Document, reference: Reference) -> Guid: ...
    @staticmethod
    def GetReference(aDoc: Document, guid: Guid) -> Reference: ...
    @staticmethod
    def GetSteelElementProperties(pElement: Element) -> SteelElementProperties: ...
