# Auto-generated — Revit 2027 — Autodesk.Revit.UI.Macros

class ApplicationEntryPoint(UIApplication):
    """.NET: Autodesk.Revit.UI.Macros.ApplicationEntryPoint"""
    def __init__(self, *args) -> None: ...
    AddinFolder: str
    IsValidObject: bool
    IsViewerModeActive: bool
    Application: Application
    MainWindowHandle: IntPtr
    ProductIsRS: bool
    ActiveAddInId: AddInId
    LoadedApplications: ExternalApplicationArray
    DrawingAreaExtents: Rectangle
    MainWindowExtents: Rectangle
    ActiveUIDocument: UIDocument
    def CreateRibbonPanel(self, tab: Tab, panelName: str) -> RibbonPanel: ...
    def CreateRibbonTab(self, tabName: str) -> None: ...
    def FinishInitializationEO(self, ) -> None: ...
    def GetRibbonPanels(self, tabName: str) -> List: ...
    def Initialize(self, obj: object, addinFolder: str) -> None: ...
    def OnShutdownEO(self, ) -> None: ...
