# Auto-generated — Revit 2027 — Autodesk.Revit.UI.Mechanical

class DuctFittingAndAccessoryPressureDropUIData:
    """.NET: Autodesk.Revit.UI.Mechanical.DuctFittingAndAccessoryPressureDropUIData"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def GetUIDataItems(self, ) -> IList: ...
    def GetUnits(self, ) -> Units: ...

class DuctFittingAndAccessoryPressureDropUIDataItem:
    """.NET: Autodesk.Revit.UI.Mechanical.DuctFittingAndAccessoryPressureDropUIDataItem"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def GetDuctFittingAndAccessoryData(self, ) -> DuctFittingAndAccessoryData: ...
    def GetEntity(self, ) -> Entity: ...
    def SetEntity(self, entity: Entity) -> None: ...

class IDuctFittingAndAccessoryPressureDropUIServer:
    """.NET: Autodesk.Revit.UI.Mechanical.IDuctFittingAndAccessoryPressureDropUIServer"""
    def __init__(self, *args) -> None: ...
    def GetDBServerId(self, ) -> Guid: ...
    def ShowSettings(self, data: DuctFittingAndAccessoryPressureDropUIData) -> bool: ...
