# Auto-generated — Revit 2027 — Autodesk.Revit.UI.Plumbing

class IPipeFittingAndAccessoryPressureDropUIServer:
    """.NET: Autodesk.Revit.UI.Plumbing.IPipeFittingAndAccessoryPressureDropUIServer"""
    def __init__(self, *args) -> None: ...
    def GetDBServerId(self, ) -> Guid: ...
    def ShowSettings(self, data: PipeFittingAndAccessoryPressureDropUIData) -> bool: ...

class PipeFittingAndAccessoryPressureDropUIData:
    """.NET: Autodesk.Revit.UI.Plumbing.PipeFittingAndAccessoryPressureDropUIData"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def GetUIDataItems(self, ) -> IList: ...
    def GetUnits(self, ) -> Units: ...

class PipeFittingAndAccessoryPressureDropUIDataItem:
    """.NET: Autodesk.Revit.UI.Plumbing.PipeFittingAndAccessoryPressureDropUIDataItem"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def GetEntity(self, ) -> Entity: ...
    def GetPipeFittingAndAccessoryData(self, ) -> PipeFittingAndAccessoryData: ...
    def SetEntity(self, entity: Entity) -> None: ...
