# Auto-generated — Revit 2027 — Autodesk.Revit.UI.Selection

class ISelectionFilter:
    """.NET: Autodesk.Revit.UI.Selection.ISelectionFilter"""
    def __init__(self, *args) -> None: ...
    def AllowElement(self, elem: Element) -> bool: ...
    def AllowReference(self, reference: Reference, position: XYZ) -> bool: ...

class ObjectSnapTypes:
    """.NET: Autodesk.Revit.UI.Selection.ObjectSnapTypes"""
    def __init__(self, *args) -> None: ...
    ...

class ObjectType:
    """.NET: Autodesk.Revit.UI.Selection.ObjectType"""
    def __init__(self, *args) -> None: ...
    ...

class PickBoxStyle:
    """.NET: Autodesk.Revit.UI.Selection.PickBoxStyle"""
    def __init__(self, *args) -> None: ...
    ...

class PickedBox:
    """.NET: Autodesk.Revit.UI.Selection.PickedBox"""
    def __init__(self, *args) -> None: ...
    Max: XYZ
    Min: XYZ

class SelectableInViewFilter(ElementSlowFilter):
    """.NET: Autodesk.Revit.UI.Selection.SelectableInViewFilter"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    Inverted: bool

class Selection:
    """.NET: Autodesk.Revit.UI.Selection.Selection"""
    def __init__(self, *args) -> None: ...
    IsValidObject: bool
    def Dispose(self, ) -> None: ...
    def GetElementIds(self, ) -> ICollection: ...
    def GetReferences(self, ) -> IList: ...
    def PickBox(self, style: PickBoxStyle, statusPrompt: str) -> PickedBox: ...
    def PickElementsByRectangle(self, selectionFilter: ISelectionFilter, statusPrompt: str) -> IList: ...
    def PickObject(self, objectType: ObjectType, selectionFilter: ISelectionFilter, statusPrompt: str) -> Reference: ...
    def PickObjects(self, objectType: ObjectType, selectionFilter: ISelectionFilter, statusPrompt: str, pPreSelected: IList) -> IList: ...
    def PickPoint(self, snapSettings: ObjectSnapTypes, statusPrompt: str) -> XYZ: ...
    def SetElementIds(self, elementIds: ICollection) -> None: ...
    def SetReferences(self, references: IList) -> None: ...
