# Auto-generated — Civil 26 — Autodesk.Aec

class BuiltInType:
    """.NET: Autodesk.Aec.BuiltInType"""
    def __init__(self, *args) -> None: ...
    ...

class BuiltInUnit:
    """.NET: Autodesk.Aec.BuiltInUnit"""
    def __init__(self, *args) -> None: ...
    ...

class DisplayOptionWithRespectToCutPlane:
    """.NET: Autodesk.Aec.DisplayOptionWithRespectToCutPlane"""
    def __init__(self, *args) -> None: ...
    ...

class ProductInformation:
    """.NET: Autodesk.Aec.ProductInformation"""
    def __init__(self, *args) -> None: ...
    ...

class UnitStatus:
    """.NET: Autodesk.Aec.UnitStatus"""
    def __init__(self, *args) -> None: ...
    ...
