# Auto-generated — Civil 26 — Autodesk.Aec.Geometry

class BoundBox2d(DisposableWrapper):
    """.NET: Autodesk.Aec.Geometry.BoundBox2d"""
    def __init__(self, *args) -> None: ...
    MaxPoint: Point2d
    MinPoint: Point2d
    Depth: float
    Width: float
    Area: float
    IsValid: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Clone(self, ) -> object: ...
    def ClosestPoint(self, testPoint: Point2d) -> Point2d: ...
    def ContainsPoint(self, point: Point2d) -> bool: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, bAutoDelete: bool) -> BoundBox2d: ...
    def Enlarge(self, amount: float) -> None: ...
    def FurthestPoint(self, testPoint: Point2d) -> Point2d: ...
    def Init(self, ) -> None: ...
    def IntersectWith(self, boundBox: BoundBox2d) -> bool: ...
    def Set(self, minX: float, minY: float, maxX: float, maxY: float) -> None: ...

class BoundBox3d(DisposableWrapper):
    """.NET: Autodesk.Aec.Geometry.BoundBox3d"""
    def __init__(self, *args) -> None: ...
    MaxPoint: Point3d
    MinPoint: Point3d
    Height: float
    Depth: float
    Width: float
    Volume: float
    IsValid: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Clone(self, ) -> object: ...
    def ClosestPoint(self, testPoint: Point3d) -> Point3d: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, bAutoDelete: bool) -> BoundBox3d: ...
    def FurthestPoint(self, testPoint: Point3d) -> Point3d: ...
    def Init(self, ) -> None: ...
    def IntersectWith(self, boundBox: BoundBox3d) -> bool: ...
    def Set(self, minX: float, minY: float, minZ: float, maxX: float, maxY: float, maxZ: float) -> None: ...
    def TransformBy(self, xform: Matrix3d) -> None: ...

class CompoundCurve2d(ImpObject):
    """.NET: Autodesk.Aec.Geometry.CompoundCurve2d"""
    def __init__(self, *args) -> None: ...
    Attribute: Attribute
    DirtyFlag: bool
    Vertices: CompoundCurve2dVertexCollection
    Length: float
    EndPoint: Point2d
    StartPoint: Point2d
    IsSelfIntersecting: bool
    IsContinuous: bool
    IsClosed: bool
    SegmentCount: int
    Database: Database
    Description: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def AddSegment(self, segment: Segment2d, appendAtEnd: bool) -> None: ...
    def AddSegmentAt(self, index: int, segment: Segment2d) -> None: ...
    def AddSegmentsFrom(self, points: Point2dCollection, appendAtEnd: bool) -> None: ...
    def CleanupVertices(self, doChange: bool) -> int: ...
    def DirectionAtParameter(self, segmentIndex: int, segmentParameter: float) -> Vector2d: ...
    def EvaluatePointAtParameter(self, segmentIndex: int, segmentParameter: float) -> Point2d: ...
    def Extent(self, topLeft: Point2d, bottomRight: Point2d) -> None: ...
    def GetBetween(self, startIndex: int, startParameter: float, endIndex: int, endParameter: float) -> CompoundCurve2d: ...
    def GetClosestParameterTo(self, point: Point2d, segmentIndex: int, segmentParameter: float) -> None: ...
    def GetParameterAtLength(self, distance: float, segmentIndex: int, segmentParameter: float, useStartParameterAtJoints: bool, fromStart: bool) -> bool: ...
    def GetParameterAtPoint(self, point: Point2d, segmentIndex: int, segmentParameter: float, useStartParameterAtJoints: bool) -> bool: ...
    def InsertVertex(self, newPoint: Point2d) -> None: ...
    def IntersectWith(self, curve: CompoundCurve2d, points: Point2dCollection, indices1: IntegerCollection, parameters1: DoubleCollection, indices2: IntegerCollection, parameters2: DoubleCollection) -> bool: ...
    def IntersectionParameter(self, curve: Curve2d, point: Point2d, segmentIndex: int, segmentParameter: float, closestToStart: bool) -> bool: ...
    def IsEqualTo(self, otherCompCurve: CompoundCurve2d) -> bool: ...
    def JoinColinearPossible(self, segment: Segment2d, nextSegment: Segment2d) -> bool: ...
    def JoinColinearSegments(self, ) -> None: ...
    def LengthToParameter(self, segmentIndex: int, segmentParameter: float, fromStart: bool) -> float: ...
    def LengthToPoint(self, pointOnCurve: Point2d, fromStart: bool) -> float: ...
    def MoveVertex(self, vertex: CompoundCurve2dVertex, offset: Vector2d) -> None: ...
    def OrientAboutPoint(self, point: Point2d) -> None: ...
    def OrientAboutTopLeftCorner(self, ) -> None: ...
    def PopSegment(self, removeFromEnd: bool) -> Segment2d: ...
    def PopSegmentAt(self, index: int) -> Segment2d: ...
    def RemoveAllSegments(self, ) -> None: ...
    def RemoveSegment(self, removeFromEnd: bool) -> None: ...
    def RemoveSegmentAt(self, index: int) -> None: ...
    def ReplaceSegmentAt(self, index: int, withThis: Segment2d) -> Segment2d: ...
    def Reverse(self, reverseInPlace: bool) -> None: ...
    def Scale(self, x: float, y: float) -> None: ...
    def Segment(self, index: int) -> Segment2d: ...
    def TransferSegmentDataForJoin(self, segmentToKeep: Segment2d, segmentToDelete: Segment2d) -> None: ...
    def TransferSegmentsFrom(self, compoundCurve: CompoundCurve2d, appendAtEnd: bool) -> None: ...
    def TransformBy(self, matrix: Matrix2d) -> None: ...
    def TranslateBy(self, vector: Vector2d) -> None: ...
    def UpdateTransientData(self, ) -> None: ...

class CompoundCurve2dVertex(DisposableWrapper):
    """.NET: Autodesk.Aec.Geometry.CompoundCurve2dVertex"""
    def __init__(self, *args) -> None: ...
    Point: Point2d
    NextSegment: Segment2d
    PreviousSegment: Segment2d
    CompoundCurve: CompoundCurve2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Clone(self, ) -> object: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, bAutoDelete: bool) -> CompoundCurve2dVertex: ...

class CompoundCurve2dVertexCollection(DisposableWrapper):
    """.NET: Autodesk.Aec.Geometry.CompoundCurve2dVertexCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: CompoundCurve2dVertex
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def CopyTo(self, array: list, start: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class CompoundSegment2d(Segment2d):
    """.NET: Autodesk.Aec.Geometry.CompoundSegment2d"""
    def __init__(self, *args) -> None: ...
    GraphicSystemMarker: int
    Attribute: Attribute
    IsCurveCircularArc2d: bool
    IsCurveLineSegment2d: bool
    CurveDirectionPositive: bool
    IsClosed: bool
    EndParameter: float
    StartParameter: float
    Interval: Interval
    MidPoint: Point2d
    BoundBox2d: BoundBox2d
    SegmentPosition: SegmentPosition
    Visible: bool
    Bulge: float
    Length: float
    EndPoint: Point2d
    StartPoint: Point2d
    Curve: Curve2d
    Database: Database
    Description: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Polyline2d(CompoundCurve2d):
    """.NET: Autodesk.Aec.Geometry.Polyline2d"""
    def __init__(self, *args) -> None: ...
    Attribute: Attribute
    DirtyFlag: bool
    Vertices: CompoundCurve2dVertexCollection
    Length: float
    EndPoint: Point2d
    StartPoint: Point2d
    IsSelfIntersecting: bool
    IsContinuous: bool
    IsClosed: bool
    SegmentCount: int
    Database: Database
    Description: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def ClipEnd(self, clipLine: Line2d) -> None: ...
    def ClipStart(self, clipLine: Line2d) -> None: ...
    def GetAfter(self, startIndex: int, startParameter: float) -> Polyline2d: ...
    def GetBefore(self, endIndex: int, endParameter: float) -> Polyline2d: ...

class Profile(ImpObject):
    """.NET: Autodesk.Aec.Geometry.Profile"""
    def __init__(self, *args) -> None: ...
    HasHiddenEdge: bool
    Attribute: Attribute
    Rings: RingCollection
    DirtyFlag: bool
    Vertices: CompoundCurve2dVertexCollection
    CenterOfGravity: Point2d
    Centroid: Point2d
    IsSelfIntersecting: bool
    RingCount: int
    Database: Database
    Description: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def AddRing(self, ring: Ring) -> None: ...
    def AddRingsFrom(self, profile: Profile) -> None: ...
    def Area(self, tolerance: float) -> float: ...
    def CalculateSegmentPositions(self, extrusionDirection: ProfileExtrusionDirection, calculateOnlyForNonMarked: bool) -> None: ...
    def CleanupVertices(self, doChange: bool) -> int: ...
    def ConsistentlyOrientRings(self, ) -> None: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, bAutoDelete: bool) -> Profile: ...
    @staticmethod
    def CreateCircle(width: float, height: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreateFromEntity(entity: Entity, toWcs: Matrix3d) -> Profile: ...
    @staticmethod
    def CreateIsoscelesTriangle(width: float, height: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreateLeftHandSideRightAngleTriangle(width: float, height: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreateOval(width: float, height: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreatePolygon(sideCount: int, sideLength: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreateQuarterCircle(width: float, height: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreateQuarterCircularRing(width: float, height: float, thickness: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreateRectangle(width: float, height: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreateRightHandSideRightAngleTriangle(width: float, height: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreateSemiCircle(width: float, height: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreateSemiCircularRing(width: float, height: float, thickness: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def CreateUShape(width: float, height: float, thickness: float, rotation: float, translation: Vector2d) -> Profile: ...
    @staticmethod
    def Equals(profile1: Profile, profile2: Profile) -> bool: ...
    def Extent(self, topLeft: Point2d, bottomRight: Point2d) -> None: ...
    def GetClosestParameterTo(self, point: Point2d, ringIndex: int, segmentIndex: int, segmentParameter: float) -> None: ...
    def GetExtrusion(self, direction: Vector3d, deviation: float, maxFacetsOnCircle: int) -> Body: ...
    def IntersectWith(self, profile: Profile, tolerance: Tolerance) -> Profile: ...
    def IsEqualTo(self, otherProfile: Profile) -> bool: ...
    def IsTopologicallyEquivalent(self, otherProfile: Profile, offsets: IntegerCollection) -> bool: ...
    def IsValidProfile(self, performAdditionalChecksOnRing: bool) -> bool: ...
    def IsValidRingNesting(self, checkingLevel: int) -> bool: ...
    def JoinColinearSegments(self, ) -> None: ...
    def MirrorSegmentPositions(self, ) -> None: ...
    def ModifySegmentPositions(self, oldExtrusionDirection: ProfileExtrusionDirection, newExtrusionDirection: ProfileExtrusionDirection) -> None: ...
    def OffsetUniform(self, distance: float) -> Profile: ...
    def OffsetUniformRingAt(self, index: int, distance: float) -> Profile: ...
    def OrientAboutPoint(self, point: Point2d) -> None: ...
    def OrientAboutTopLeftCorner(self, ) -> None: ...
    def Perimeter(self, tolerance: float) -> float: ...
    def PointInProfile(self, point: Point2d) -> ProfileResult: ...
    def PopRingAt(self, index: int) -> Ring: ...
    def RemoveAllRings(self, ) -> None: ...
    def RemoveRingAt(self, index: int) -> None: ...
    def RemoveVoidRings(self, ) -> None: ...
    def Ring(self, index: int) -> Ring: ...
    def RingInProfile(self, ring: Ring) -> ProfileResult: ...
    def Scale(self, x: float, y: float) -> None: ...
    def SetExtent(self, width: float, height: float) -> None: ...
    def Split(self, line: Line2d) -> Profile: ...
    def SubtractProfile(self, profile: Profile, tolerance: Tolerance) -> Profile: ...
    def TransferRingsFrom(self, profile: Profile) -> None: ...
    def TransformBy(self, matrix: Matrix2d) -> None: ...
    def TranslateBy(self, vector: Vector2d) -> None: ...
    def UnionWith(self, profile: Profile, tolerance: Tolerance) -> Profile: ...
    def UpdateTransientData(self, ) -> None: ...

class ProfileExtrusionDirection:
    """.NET: Autodesk.Aec.Geometry.ProfileExtrusionDirection"""
    def __init__(self, *args) -> None: ...
    ...

class ProfileResult:
    """.NET: Autodesk.Aec.Geometry.ProfileResult"""
    def __init__(self, *args) -> None: ...
    ...

class Ring(CompoundCurve2d):
    """.NET: Autodesk.Aec.Geometry.Ring"""
    def __init__(self, *args) -> None: ...
    Segments: Segment2dCollection
    IsCircle: bool
    Centroid: Point2d
    Area: float
    IsValidRing: bool
    IsVoid: bool
    Attribute: Attribute
    DirtyFlag: bool
    Vertices: CompoundCurve2dVertexCollection
    Length: float
    EndPoint: Point2d
    StartPoint: Point2d
    IsSelfIntersecting: bool
    IsContinuous: bool
    IsClosed: bool
    SegmentCount: int
    Database: Database
    Description: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def CalculateSegmentPositions(self, topLeft: Point2d, bottomRight: Point2d, extrusionDirection: ProfileExtrusionDirection, calculateOnlyForNonMarked: bool) -> None: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, bAutoDelete: bool) -> Ring: ...
    def GetExtrusion(self, direction: Vector3d, deviation: float, maxFacetsPerSegment: int) -> Body: ...
    def GetFace(self, deviation: float, maxFacetsPerSegment: int) -> Body: ...
    def IsContainedBy(self, otherRing: Ring) -> bool: ...
    def IsTopologicallyEquivalent(self, otherRing: Ring, offset: int) -> bool: ...
    def MirrorSegmentPositions(self, ) -> None: ...
    def ModifySegmentPositions(self, oldExtrusionDirection: ProfileExtrusionDirection, newExtrusionDirection: ProfileExtrusionDirection) -> None: ...
    def PointInRing(self, point: Point2d) -> ProfileResult: ...

class RingCollection(DisposableWrapper):
    """.NET: Autodesk.Aec.Geometry.RingCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Ring
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def CopyTo(self, array: list, start: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class Segment2d(ImpObject):
    """.NET: Autodesk.Aec.Geometry.Segment2d"""
    def __init__(self, *args) -> None: ...
    Attribute: Attribute
    IsCurveCircularArc2d: bool
    IsCurveLineSegment2d: bool
    CurveDirectionPositive: bool
    IsClosed: bool
    EndParameter: float
    StartParameter: float
    Interval: Interval
    MidPoint: Point2d
    BoundBox2d: BoundBox2d
    SegmentPosition: SegmentPosition
    Visible: bool
    Bulge: float
    Length: float
    EndPoint: Point2d
    StartPoint: Point2d
    Curve: Curve2d
    Database: Database
    Description: str
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def CanMoveStartEndPoint(self, oldStartEndPoint: Point2d, newStartEndPoint: Point2d) -> bool: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, bAutoDelete: bool) -> Segment2d: ...
    def DirectionAtParameter(self, parameter: float) -> Vector2d: ...
    def DistanceTo(self, point: Point2d, tolerance: Tolerance) -> float: ...
    def EvaluateLength(self, fromParameter: float, toParameter: float, tolerance: Tolerance) -> float: ...
    def EvaluatePoint(self, parameter: float) -> Point2d: ...
    def Extent(self, topLeft: Point2d, bottomRight: Point2d) -> None: ...
    def GetBounds(self, lowerBoundParameter: float, upperBoundParameter: float) -> None: ...
    def GetClosestPointTo(self, point: Point2d, tolerance: Tolerance) -> PointOnCurve2d: ...
    def GetCurvature(self, point: Point2d) -> float: ...
    def GetPointOnCurve2d(self, parameter: float) -> PointOnCurve2d: ...
    def GetProjectedIntersectionPoints(self, segment: Segment2d, point1: Point2d, point2: Point2d) -> int: ...
    def IntersectSegments(self, segment: Segment2d, count: int, point1: Point2d, point2: Point2d) -> bool: ...
    def IntersectWith(self, line: LinearEntity2d, count: int, point1: Point2d, point2: Point2d, tolerance: Tolerance) -> bool: ...
    def IntersectWithCurve(self, segment: Curve2d, count: int, point1: Point2d, point2: Point2d) -> bool: ...
    def IsColinearTo(self, line: LinearEntity2d, tolerance: Tolerance) -> bool: ...
    def IsExtending(self, oldStartEndPoint: Point2d, newStartEndPoint: Point2d) -> bool: ...
    def IsOn(self, point: Point2d, parameter: float, tolerance: Tolerance) -> bool: ...
    def IsOnSameUnboundedCurveAs(self, segment: Segment2d) -> bool: ...
    def MoveStartEndPoint(self, oldStartEndPoint: Point2d, newStartEndPoint: Point2d) -> None: ...
    def ParameterAtLength(self, datumParameter: float, length: float, positiveParameterDirection: bool, tolerance: Tolerance) -> float: ...
    def ParameterOf(self, point: Point2d, tolerance: Tolerance) -> float: ...
    def Reverse(self, ) -> None: ...
    def Scale(self, x: float, y: float) -> None: ...
    @staticmethod
    def SegmentPositionName(position: SegmentPosition) -> str: ...
    def Split(self, point: Point2d) -> Segment2d: ...
    def Tangent(self, point: Point2d, line: Line2d, tolerance: Tolerance) -> bool: ...
    def TransferJoinedSegmentData(self, segment: Segment2d) -> None: ...
    def TransformBy(self, matrix: Matrix2d) -> None: ...

class Segment2dCollection(DisposableWrapper):
    """.NET: Autodesk.Aec.Geometry.Segment2dCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Segment2d
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def CopyTo(self, array: list, start: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class SegmentPosition:
    """.NET: Autodesk.Aec.Geometry.SegmentPosition"""
    def __init__(self, *args) -> None: ...
    ...
