# Auto-generated — Civil 26 — Autodesk.Aec.Modeler

class Body(Entity):
    """.NET: Autodesk.Aec.Modeler.Body"""
    def __init__(self, *args) -> None: ...
    PhysicalVertices: list
    PhysicalEdges: list
    Vertices: VertexCollection
    Curves: CurveCollection
    Surfaces: SurfaceCollection
    Faces: FaceCollection
    ContainsNonManifoldEdges: bool
    IsNegated: bool
    IsNull: bool
    Interval: Point3dCollection
    IsValid: bool
    Next: Body
    Products: Point3d
    Moments: Point3d
    Centroid: Point3d
    Volume: float
    Area: float
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Add(body1: Body, body2: Body) -> Body: ...
    def Align(self, source1: Point3d, source2: Vector3d, source3: Vector3d, destination1: Point3d, destination2: Vector3d, destination3: Vector3d) -> Body: ...
    @staticmethod
    def AxisRevolution(points: Point3dCollection, vertexData: list, numberOfVertices: int, polygonNormal: Vector3d, axis: LineSegment3d, revolutionAngle: float, approximation: int, scaleTwistFixedPoint: Point3d, scaleFactor: float, twistAngle: float) -> Body: ...
    def BooleanOperation(self, body: Body, type: BooleanOperatorType) -> Body: ...
    @staticmethod
    def Box(corner: Point3d, sizes: Vector3d) -> Body: ...
    def BreakEdge(self, p1: Point3d, p2: Point3d) -> Edge: ...
    def ChangeVertexCoordinates(self, changedVertices: list, changedVertexCoordinates: Point3dCollection, checkPlanarity: bool) -> None: ...
    def CleanUpNonManifoldEdgesAndCoincidentFaces(self, ) -> None: ...
    def ClosestDistanceOfRayIntersection(self, ray: LineSegment3d, tolerance: float) -> float: ...
    def ClosestEntityOfRayIntersection(self, ray: LineSegment3d, tolerance: float) -> Entity: ...
    def Combine(self, body: Body) -> Body: ...
    @staticmethod
    def Cone(axis: LineSegment3d, baseNormal: Vector3d, radius1: float, radius2: float, surfaceFacets: int) -> Body: ...
    def Contains(self, point: Point3d) -> PointInBodyLocation: ...
    def ConvertToTerrainBody(self, height: float, checkValidity: bool) -> list: ...
    @staticmethod
    def ConvexHull(points: Point3dCollection) -> Body: ...
    def Copy(self, ) -> Body: ...
    def CopyGeometryFrom(self, body: Body, matrix: Matrix3d) -> None: ...
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Body: ...
    @staticmethod
    def Cylinder(axis: LineSegment3d, baseNormal: Vector3d, radius: float, surfaceFacets: int) -> Body: ...
    def DecomposeIntoLumps(self, ) -> BodyCollection: ...
    def DeleteEmptyFaces(self, ) -> None: ...
    def DeleteFaceIntervals(self, ) -> None: ...
    def DeleteFaceIntervalsAndPlanes(self, ) -> None: ...
    def DeleteMarkedCurves(self, flag: int) -> None: ...
    def DeleteMarkedFaces(self, flag: int) -> None: ...
    def DeleteMarkedSurfaces(self, flag: int) -> None: ...
    def DeleteMarkedVertices(self, flag: int) -> None: ...
    def DeleteUnusedVerticesSurfacesCurves(self, ) -> None: ...
    def DeleteVertexSurfaceData(self, ) -> None: ...
    @staticmethod
    def EndPointRevolution(points: Point3dCollection, vertexData: list, numberOfVertices: int, polygonNormal: Vector3d, revolutionAngle: float, approximation: int) -> Body: ...
    @staticmethod
    def Equals(body1: Body, body2: Body) -> bool: ...
    def EvaluateVertexSurfaceData(self, ) -> None: ...
    def ExtractFace(self, faceToExtract: Face) -> Body: ...
    def ExtractShell(self, faceInTheShell: Face) -> Body: ...
    @staticmethod
    def Extrusion(points: Point3dCollection, vertexData: list, numberOfVertices: int, polygonNormal: Vector3d, extrusionVector: Vector3d, scaleTwistFixedPoint: Point3d, scaleFactor: float, twistAngle: float) -> Body: ...
    @staticmethod
    def ExtrusionAlongPath(startProfile: Body, endProfile: Body, pathPolygon: Point3dCollection, pathVertexData: list, numberOfPathVertices: int, pathIsClosed: bool, checkBodyValidity: bool, scaleTwistFixedPoint: Point3d, scaleFactor: float, twistAngle: float, morphingMap: MorphingMap, calculateMorphingMapAutomatically: bool, startProfileSignificantVertices: IntegerCollection, endProfileSignificantVertices: IntegerCollection) -> Body: ...
    def FindEdge(self, p1: Point3d, p2: Point3d) -> Edge: ...
    def FindFace(self, plane: Plane) -> list: ...
    def FindVertex(self, point: Point3d) -> Vertex: ...
    def GenerateUnspecifiedSurfaces(self, angleTolerance: float, minNumberOfFacesInSurface: int) -> None: ...
    def GenerateUnspecifiedSurfacesFromApproximationEdges(self, minNumberOfFacesInSurface: int) -> None: ...
    def GetAllEdgesReferencingVertex(self, value: Vertex) -> list: ...
    def GetIsValid(self, level: ValidityCheckingLevel) -> bool: ...
    def GetVertexMax(self, dir: Vector3d) -> Vertex: ...
    def GetVertexMin(self, dir: Vector3d) -> Vertex: ...
    def MakeArcTessellationsInExtrusionsCoincident(self, referenceExtrusion: Body, extrusionVector: Vector3d) -> bool: ...
    def MergeCoincidentVertices(self, ) -> bool: ...
    def MergeCoplanarFaces(self, edgeBetweenFaces: Edge) -> None: ...
    def MergeEqualSurfaces(self, ) -> None: ...
    def Mirror(self, plane: Plane) -> Body: ...
    def Modified(self, ) -> None: ...
    def MoveFace(self, faceToMove: Face, vector: Vector3d, keepAdjacentFacePlanesFixed: bool, keepFaceGeometryFixed: bool) -> Face: ...
    @staticmethod
    def Multiply(body1: Body, body2: Body) -> Body: ...
    @staticmethod
    def Negate(body: Body) -> Body: ...
    @staticmethod
    def Pipe(axis: LineSegment3d, baseNormal: Vector3d, outerRadius: float, innerRadius: float, surfaceFacets: int) -> Body: ...
    @staticmethod
    def PipeConic(axis: LineSegment3d, baseNormal: Vector3d, outerRadius1: float, innerRadius1: float, outerRadius2: float, innerRadius2: float, surfaceFacets: int) -> Body: ...
    def PlaneIntersectsBody(self, plane: Plane) -> bool: ...
    def ProfilesOrdered(self, body: Body) -> bool: ...
    @staticmethod
    def Pyramid(points: Point3dCollection, vertexData: list, numberOfVertices: int, polygonNormal: Vector3d, pyramidApex: Point3d) -> Body: ...
    def RayIntersectionStatus(self, ray: LineSegment3d, tolerance: float) -> RayBodyIntersection: ...
    @staticmethod
    def RectangleToCircleReducer(baseCorner: Point3d, baseSizes: Vector2d, topCircle: CircularArc3d, surfaceFacets: int) -> Body: ...
    @staticmethod
    def ReducingElbow(elbowCenter: Point3d, endCenter1: Point3d, endCenter2: Point3d, endRadius1: float, endRadius2: float, majorSurfaceFacets: int, minorSurfaceFacets: int) -> Body: ...
    def Rotate(self, axis: LineSegment3d, angle: float) -> Body: ...
    def SaveToSAT(self, fileName: str, colorsAlso: bool) -> None: ...
    def Scale(self, fixedPoint: Point3d, xyzFactors: Vector3d) -> Body: ...
    def Section(self, plane: Plane, keepInputBodyWhenFails: bool) -> None: ...
    def SetApproximatingEdgeAndBridgeEdgeFlags(self, mark: bool) -> None: ...
    def SetColor(self, value: ColorType) -> None: ...
    def SetCurveFlags(self, tag: OnOff, flag: int) -> None: ...
    def SetEdgeFlags(self, tag: OnOff, flag: int) -> None: ...
    def SetFaceFlags(self, tag: OnOff, flag: int) -> None: ...
    def SetHiddenLineParameters(self, display: HiddenLinesDisplay, displayApproximationEdges: bool, displayBridgeEdges: bool) -> None: ...
    def SetSurfaceFlags(self, tag: OnOff, flag: int) -> None: ...
    def SetVertexFlags(self, tag: OnOff, flag: int) -> None: ...
    @staticmethod
    def Skin(profiles: BodyCollection, numberOfProfiles: int, isClosed: bool, checkPlanarity: bool, morphingMaps: list, markInnerProfileEdgesAsApproximation: bool, checkInputProfiles: bool) -> Body: ...
    @staticmethod
    def Sphere(center: Point3d, radius: float, surfaceFacets: int) -> Body: ...
    def StitchFaces(self, splitEdges: bool, orientFaces: bool, addMissingFaces: bool) -> None: ...
    def Stretch(self, line: LineSegment3d) -> Body: ...
    @staticmethod
    def Subtract(body: Body, plane: Plane) -> Body: ...
    @staticmethod
    def Tetrahedron(points: Point3dCollection) -> Body: ...
    @staticmethod
    def Torus(axis: LineSegment3d, majorRadius: float, minorRadius: float, majorSurfaceFacets: int, minorSurfaceFacets: int) -> Body: ...
    @staticmethod
    def TorusExtension(axis: LineSegment3d, majorRadius: float, minorRadius: float, majorSurfaceFacets: int, minorSurfaceFacets: int) -> Body: ...
    def Transform(self, matrix: Matrix3d) -> Body: ...
    def Translate(self, vector: Vector3d) -> Body: ...
    def TriangulateAllFaces(self, ) -> None: ...
    def TriangulateFace(self, face: Face) -> None: ...

class BodyCollection(DisposableWrapper):
    """.NET: Autodesk.Aec.Modeler.BodyCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Body
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Add(self, value: Body) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Body) -> bool: ...
    def CopyTo(self, array: list, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: Body) -> int: ...
    def Insert(self, index: int, value: Body) -> None: ...
    def Remove(self, value: Body) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class BooleanOperatorType:
    """.NET: Autodesk.Aec.Modeler.BooleanOperatorType"""
    def __init__(self, *args) -> None: ...
    ...

class CircleCurve(Curve):
    """.NET: Autodesk.Aec.Modeler.CircleCurve"""
    def __init__(self, *args) -> None: ...
    Circle: CircularArc3d
    Approx: int
    Radius: float
    Axis: LineSegment3d
    Origin: Point3d
    Transf: Matrix3d
    Copy: Curve
    Type: CurveType
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class ColorType:
    """.NET: Autodesk.Aec.Modeler.ColorType"""
    def __init__(self, *args) -> None: ...
    ...

class ConeSurface(RevolutionSurface):
    """.NET: Autodesk.Aec.Modeler.ConeSurface"""
    def __init__(self, *args) -> None: ...
    Apex: Point3d
    Approximation: int
    TanAngle: float
    Radius: float
    StartDir: Vector3d
    Axis: LineSegment3d
    Copy: Surface
    Type: SurfaceType
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Curve(Entity):
    """.NET: Autodesk.Aec.Modeler.Curve"""
    def __init__(self, *args) -> None: ...
    Copy: Curve
    Type: CurveType
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Transform(self, matrix: Matrix3d, transfType: TransfType, stretchVector: Vector3d) -> bool: ...

class CurveCollection:
    """.NET: Autodesk.Aec.Modeler.CurveCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Curve
    def Add(self, value: Curve) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Curve) -> bool: ...
    def CopyTo(self, array: list, start: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: Curve) -> int: ...
    def Insert(self, index: int, value: Curve) -> None: ...
    def Remove(self, value: Curve) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class CurveType:
    """.NET: Autodesk.Aec.Modeler.CurveType"""
    def __init__(self, *args) -> None: ...
    ...

class CylinderSurface(RevolutionSurface):
    """.NET: Autodesk.Aec.Modeler.CylinderSurface"""
    def __init__(self, *args) -> None: ...
    Approx: int
    Radius: float
    StartDir: Vector3d
    Axis: LineSegment3d
    Copy: Surface
    Type: SurfaceType
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class DirectionType:
    """.NET: Autodesk.Aec.Modeler.DirectionType"""
    def __init__(self, *args) -> None: ...
    ...

class Edge(Entity):
    """.NET: Autodesk.Aec.Modeler.Edge"""
    def __init__(self, *args) -> None: ...
    EulerEdge: Edge
    IsEulerEdge: bool
    IsApprox: bool
    IsBridge: bool
    AngleBetweenFacesIsStraight: bool
    AngleBetweenFacesIsConcave: bool
    AngleBetweenFacesIsConvex: bool
    IsManifold: bool
    IsOnFullCircle: bool
    IsOnCircle: bool
    Surface: Surface
    Plane: Plane
    VertexNormal: Vector3d
    Normal: Vector3d
    Line: LineSegment3d
    UnitVector: Vector3d
    Vector: Vector3d
    Point: Point3d
    AngleBetweenEdges: float
    AngleBetweenFaces: float
    Circle: CircularArc3d
    PrevSkipBridge: Edge
    NextSkipBridge: Edge
    PartnerBridgeEdge: Edge
    Color: ColorType
    Curve: Curve
    Partner: Edge
    Face: Face
    Vertex: Vertex
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def AddPartner(self, partnerEdge: Edge) -> None: ...
    def CanMergeWithPrevious(self, sameColorOnly: bool) -> bool: ...
    def Collapse(self, ) -> None: ...
    def GetAllConnectedEdgesSharingVertex(self, ) -> list: ...
    def GetAllEdgesEndingInVertex(self, ) -> list: ...
    def GetAllEdgesSharingSameFaces(self, connectedSequenceOnly: bool) -> list: ...
    def GetAllEdgesStartingFromVertex(self, ) -> list: ...
    def HasPartner(self, edge: Edge) -> bool: ...
    def Merge(self, ) -> None: ...
    def MergeLoopsAddBridgeEdge(self, innerEdge: Edge) -> None: ...
    def MergeLoopsSharingEdge(self, ) -> None: ...
    def OrderPartnerEdgesAroundEulerEdge(self, ) -> None: ...
    def RemovePartner(self, ) -> None: ...
    def SetColor(self, colorType: ColorType, partnersAlso: bool) -> None: ...
    def SetCurve(self, curve: Curve, partnersAlso: bool) -> None: ...
    def Split(self, vertex: Vertex) -> None: ...

class EdgeCollection:
    """.NET: Autodesk.Aec.Modeler.EdgeCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Edge
    def Add(self, value: Edge) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Edge) -> bool: ...
    def CopyTo(self, array: list, start: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: Edge) -> int: ...
    def Insert(self, index: int, value: Edge) -> None: ...
    def Remove(self, value: Edge) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class Entity(DisposableWrapper):
    """.NET: Autodesk.Aec.Modeler.Entity"""
    def __init__(self, *args) -> None: ...
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    @staticmethod
    def Create(unmanagedPointer: IntPtr, autoDelete: bool) -> Entity: ...

class ErrorCode:
    """.NET: Autodesk.Aec.Modeler.ErrorCode"""
    def __init__(self, *args) -> None: ...
    ...

class Face(Entity):
    """.NET: Autodesk.Aec.Modeler.Face"""
    def __init__(self, *args) -> None: ...
    IsSelfIntersecting: bool
    Plane: Plane
    Area: float
    Edges: EdgeCollection
    Attribute: None
    FaceColor: ColorType
    Surface: Surface
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def AreaOfMass(self, body: Body, dae: bool, dbe: bool) -> float: ...
    def CentroidOfMass(self, body: Body, dae: bool, dbe: bool) -> Point3d: ...
    def DecomposeIntoContiguousFaces(self, body: Body) -> list: ...
    def DeleteInterval(self, ) -> None: ...
    def DeletePlane(self, ) -> None: ...
    def DeleteProjectionInterval(self, ) -> None: ...
    def ExtractAllLoops(self, ) -> ArrayList: ...
    def InsertHoles(self, holeFaces: list, body: Body) -> list: ...
    def IsPlanar(self, epsilon: float) -> bool: ...
    def IsPointInside(self, point: Point3d) -> bool: ...
    def Lift(self, transform: Matrix3d, checkPlanarity: bool, owningBody: Body) -> None: ...
    def Modified(self, ) -> None: ...
    def Negate(self, ) -> None: ...
    def Paint(self, body: Body, color: ColorType, dae: bool, dbe: bool) -> None: ...
    def PerimeterOfMass(self, body: Body, dae: bool, dbe: bool) -> float: ...
    def SetSpecifiedColor(self, value: ColorType, edgesAlso: bool, partnerEdgesAlso: bool) -> None: ...
    def Split(self, edgeA: Edge, edgeB: Edge, body: Body) -> Face: ...

class FaceCollection:
    """.NET: Autodesk.Aec.Modeler.FaceCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Face
    def Add(self, item: Face) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: Face) -> bool: ...
    def CopyTo(self, array: list, start: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: Face) -> int: ...
    def Insert(self, index: int, item: Face) -> None: ...
    def Remove(self, item: Face) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class HiddenLineDrawingImprove:
    """.NET: Autodesk.Aec.Modeler.HiddenLineDrawingImprove"""
    def __init__(self, *args) -> None: ...
    ...

class HiddenLinesDisplay:
    """.NET: Autodesk.Aec.Modeler.HiddenLinesDisplay"""
    def __init__(self, *args) -> None: ...
    ...

class IEdgeOperation:
    """.NET: Autodesk.Aec.Modeler.IEdgeOperation"""
    def __init__(self, *args) -> None: ...
    def Add(self, A_0: Edge) -> int: ...
    def GetAt(self, A_0: int) -> Edge: ...
    def GetCount(self, ) -> int: ...
    def Insert(self, A_0: int, A_1: Edge) -> None: ...
    def RemoveAll(self, ) -> None: ...
    def RemoveAt(self, A_0: int) -> None: ...

class ListFlags:
    """.NET: Autodesk.Aec.Modeler.ListFlags"""
    def __init__(self, *args) -> None: ...
    ...

class MorphingMap(DisposableWrapper):
    """.NET: Autodesk.Aec.Modeler.MorphingMap"""
    def __init__(self, *args) -> None: ...
    IsIdentity: bool
    IsNull: bool
    Elements: MorphingMapElementCollection
    Null: MorphingMap
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Clone(self, ) -> object: ...
    def CreateFromTwoPointLoops(self, pointLoopA: Point2dCollection, pointLoopB: Point2dCollection) -> None: ...
    def Initialize(self, ) -> None: ...
    def Normalize(self, numberOfEdgesA: int, numberOfEdgesB: int) -> None: ...
    def Print(self, ) -> None: ...
    def RemapIndices(self, fromIndexMap: IntegerCollection, toIndexMap: IntegerCollection) -> None: ...
    def SetToExplicitIdentityMap(self, numberOfEdges: int) -> None: ...

class MorphingMapElement:
    """.NET: Autodesk.Aec.Modeler.MorphingMapElement"""
    def __init__(self, *args) -> None: ...
    ...

class MorphingMapElementCollection:
    """.NET: Autodesk.Aec.Modeler.MorphingMapElementCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: MorphingMapElement
    def Add(self, item: MorphingMapElement) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: MorphingMapElement) -> bool: ...
    def CopyTo(self, array: list, start: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: MorphingMapElement) -> int: ...
    def Insert(self, index: int, item: MorphingMapElement) -> None: ...
    def Remove(self, item: MorphingMapElement) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class OnOff:
    """.NET: Autodesk.Aec.Modeler.OnOff"""
    def __init__(self, *args) -> None: ...
    ...

class PointInBodyLocation:
    """.NET: Autodesk.Aec.Modeler.PointInBodyLocation"""
    def __init__(self, *args) -> None: ...
    ...

class PolygonVertexData(DisposableWrapper):
    """.NET: Autodesk.Aec.Modeler.PolygonVertexData"""
    def __init__(self, *args) -> None: ...
    Curve: Curve
    Surface: Surface
    Bulge: float
    IsCenterLeft: bool
    Approximation: int
    Circle: CircularArc3d
    Type: PolygonVertexDataType
    IsArc: bool
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Clone(self, ) -> object: ...

class PolygonVertexDataType:
    """.NET: Autodesk.Aec.Modeler.PolygonVertexDataType"""
    def __init__(self, *args) -> None: ...
    ...

class RayBodyIntersection:
    """.NET: Autodesk.Aec.Modeler.RayBodyIntersection"""
    def __init__(self, *args) -> None: ...
    ...

class RevolutionSurface(Surface):
    """.NET: Autodesk.Aec.Modeler.RevolutionSurface"""
    def __init__(self, *args) -> None: ...
    StartDir: Vector3d
    Axis: LineSegment3d
    Copy: Surface
    Type: SurfaceType
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class SphereSurface(RevolutionSurface):
    """.NET: Autodesk.Aec.Modeler.SphereSurface"""
    def __init__(self, *args) -> None: ...
    Approx: int
    Radius: float
    Center: Point3d
    StartDir: Vector3d
    Axis: LineSegment3d
    Copy: Surface
    Type: SurfaceType
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class StateFlags:
    """.NET: Autodesk.Aec.Modeler.StateFlags"""
    def __init__(self, *args) -> None: ...
    ...

class Surface(Entity):
    """.NET: Autodesk.Aec.Modeler.Surface"""
    def __init__(self, *args) -> None: ...
    Copy: Surface
    Type: SurfaceType
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Circle(self, plane: Plane, line: LineSegment3d) -> CircularArc3d: ...
    def ContainsPoint(self, point: Point3d) -> bool: ...
    def IsEqual(self, surface: Surface) -> bool: ...
    def Normal(self, point: Point3d) -> Vector3d: ...
    def Transform(self, matrix: Matrix3d, transfType: TransfType, stretchVector: Vector3d) -> bool: ...

class SurfaceCollection:
    """.NET: Autodesk.Aec.Modeler.SurfaceCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Surface
    def Add(self, item: Surface) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: Surface) -> bool: ...
    def CopyTo(self, array: list, start: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: Surface) -> int: ...
    def Insert(self, index: int, item: Surface) -> None: ...
    def Remove(self, item: Surface) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class SurfaceType:
    """.NET: Autodesk.Aec.Modeler.SurfaceType"""
    def __init__(self, *args) -> None: ...
    ...

class TorusSurface(RevolutionSurface):
    """.NET: Autodesk.Aec.Modeler.TorusSurface"""
    def __init__(self, *args) -> None: ...
    MinorApprox: int
    MajorApprox: int
    MinorRadius: float
    MajorRadius: float
    Center: Point3d
    StartDir: Vector3d
    Axis: LineSegment3d
    Copy: Surface
    Type: SurfaceType
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class TransfType:
    """.NET: Autodesk.Aec.Modeler.TransfType"""
    def __init__(self, *args) -> None: ...
    ...

class UnspecifiedCurve(Curve):
    """.NET: Autodesk.Aec.Modeler.UnspecifiedCurve"""
    def __init__(self, *args) -> None: ...
    Copy: Curve
    Type: CurveType
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class UnspecifiedSurface(Surface):
    """.NET: Autodesk.Aec.Modeler.UnspecifiedSurface"""
    def __init__(self, *args) -> None: ...
    Copy: Surface
    Type: SurfaceType
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr

class Utility:
    """.NET: Autodesk.Aec.Modeler.Utility"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ArcToBulge(point1: Point2d, point2: Point2d, pointOnArc: Point2d, pointCenter: Point2d) -> float: ...
    @staticmethod
    def BodiesEqual(body1: Body, body2: Body) -> bool: ...
    @staticmethod
    def BodyFromObject(entity: Entity, blockReferencePath: ObjectIdCollection) -> Body: ...
    @staticmethod
    def BottomLeftMostEdge(face: Face) -> Edge: ...
    @staticmethod
    def BulgeToCircle(point1: Point2d, point2: Point2d, bulge: float) -> CircularArc2d: ...
    @staticmethod
    def CreateUnspecifiedSurface(body: Body, vertexCount: int, vertexList: Point3dCollection, faceListSize: int, faceList: IntegerCollection) -> UnspecifiedSurface: ...
    @staticmethod
    def DisplayFailedBodyMsg(err: ErrorCode, operation: Operation) -> None: ...
    @staticmethod
    def EntityBodiesInterfere(firstEntity: Entity, firstObjectBlockReferencePath: ObjectIdCollection, secondEntity: Entity, secondObjectBlockReferencePath: ObjectIdCollection) -> bool: ...
    @staticmethod
    def FaceToProfile(face: Face, toXY: Matrix3d) -> Profile: ...
    @staticmethod
    def GetBodyExtrusionFromProfilesLineSeg(baseCurve: Curve3d, ecs: Matrix3d, profile: Profile, profileRotation: float, deviation: float, maxFacetsOnCircle: int) -> Body: ...
    @staticmethod
    def GetBodyFromCutPlane(baseCurve: Curve3d, ecs: Matrix3d, profile: Profile, cutPlaneNormal: Vector3d, startOffset: float, isFromEnd: bool) -> Body: ...
    @staticmethod
    def GetBodyFromCutPlanes(baseCurve: Curve3d, ecs: Matrix3d, startProfile: Profile, startCutPlaneNormal: Vector3d, startOffset: float, endProfile: Profile, endCutPlaneNormal: Vector3d, endOffset: float) -> Body: ...
    @staticmethod
    def GetBodyFromProfileAndTranslate(baseCurve: Curve3d, param: float, point: Point3d, ring: Ring, profileRotation: float, deviation: float, maxFacetsOnCircle: int) -> Body: ...
    @staticmethod
    def GetBodyFromProfilesCurveSweep(db: Database, points: Point3dCollection, pathVertexData: list, startProfileEcs: Matrix3d, endProfileEcs: Matrix3d, ecs: Matrix3d, startProfile: Profile, startRotation: float, endProfile: Profile, endRotation: float, extrusionDirection: ProfileExtrusionDirection) -> Body: ...
    @staticmethod
    def GetBodyFromRingCurveSweep(points: Point3dCollection, pathVertexData: list, startProfileEcs: Matrix3d, endProfileEcs: Matrix3d, ecs: Matrix3d, startRing: Ring, startRotation: float, endRing: Ring, endRotation: float, extrusionDirection: ProfileExtrusionDirection, deviation: float, maxFacetsOnCircle: int) -> Body: ...
    @staticmethod
    def GetBodySlice(body: Body, height: float, copyAttributes: bool) -> Profile: ...
    @staticmethod
    def GetConnectedFaces(originalBody: Body, selectedFace: Face, otherFaces: Body) -> Body: ...
    @staticmethod
    def GetDisconnectedBodies(originalBody: Body) -> BodyCollection: ...
    @staticmethod
    def GetHolesInFace(holeEdgeArrays: ArrayList, startEdge: Edge) -> Edge: ...
    @staticmethod
    def GetPointOnFace(face: Face, point: Point3d) -> bool: ...
    @staticmethod
    def InitFlagAndCount(body: Body, flag: int) -> int: ...
    @staticmethod
    def ListBody(body: Body, flags: ListFlags) -> None: ...
    @staticmethod
    def ModelerError(err: ErrorCode) -> str: ...
    @staticmethod
    def NumberOfEdges(edge: Edge) -> int: ...
    @staticmethod
    def NumberOfFaces(body: Body) -> int: ...
    @staticmethod
    def NumberOfVertices(body: Body) -> int: ...
    @staticmethod
    def SetParamOnBaseCurve(baseCurve: Curve3d, offset: float, isFromEnd: bool) -> None: ...
    @staticmethod
    def SetParamsOnBaseCurve(baseCurve: Curve3d, startOffset: float, endOffset: float) -> None: ...
    @staticmethod
    def SliceBody(body: Body, bottom: float, top: float) -> None: ...

class ValidityCheckingLevel:
    """.NET: Autodesk.Aec.Modeler.ValidityCheckingLevel"""
    def __init__(self, *args) -> None: ...
    ...

class Vertex(Entity):
    """.NET: Autodesk.Aec.Modeler.Vertex"""
    def __init__(self, *args) -> None: ...
    VertexSurfaceDataCollection: VertexSurfaceDataCollection
    Point: Point3d
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Modified(self, ) -> None: ...
    def Transform(self, matrix: Matrix3d) -> None: ...
    def VertexSurfaceData(self, edge: Edge) -> VertexSurfaceData: ...

class VertexCollection:
    """.NET: Autodesk.Aec.Modeler.VertexCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Vertex
    def Add(self, value: Vertex) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: Vertex) -> bool: ...
    def CopyTo(self, array: list, start: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: Vertex) -> int: ...
    def Insert(self, index: int, value: Vertex) -> None: ...
    def Remove(self, value: Vertex) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class VertexSurfaceData(Entity):
    """.NET: Autodesk.Aec.Modeler.VertexSurfaceData"""
    def __init__(self, *args) -> None: ...
    Normal: Vector3d
    Surface: Surface
    Flags: int
    AutoDelete: bool
    IsDisposed: bool
    UnmanagedObject: IntPtr
    def Transform(self, matrix: Matrix3d) -> None: ...

class VertexSurfaceDataCollection:
    """.NET: Autodesk.Aec.Modeler.VertexSurfaceDataCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: VertexSurfaceData
    def Add(self, value: VertexSurfaceData) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, value: VertexSurfaceData) -> bool: ...
    def CopyTo(self, array: list, start: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, value: VertexSurfaceData) -> int: ...
    def Insert(self, index: int, value: VertexSurfaceData) -> None: ...
    def Remove(self, value: VertexSurfaceData) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
