# Auto-generated — Civil 26 — Autodesk.AutoCAD.Internal.Render.RapidRT

class PairedImage:
    """.NET: Autodesk.AutoCAD.Internal.Render.RapidRT.PairedImage"""
    def __init__(self, *args) -> None: ...
    UnmanagedBitmap: Image
    ManagedBitMap: Bitmap
    def Dispose(self, ) -> None: ...

class RenderUtil:
    """.NET: Autodesk.AutoCAD.Internal.Render.RapidRT.RenderUtil"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CreateCustomPreset(presetName: str, presetDescription: str, basePresetName: str) -> ErrorStatus: ...
    @staticmethod
    def DeleteCustomPreset(presetName: str) -> ErrorStatus: ...
    @staticmethod
    def DoModalRenderSaveFileDlg(pStrPath: str, filterExtName: StringCollection, filterExt: StringCollection, caption: str, invalidFileName: str) -> bool: ...
    @staticmethod
    def GetSceneResString(id: int) -> str: ...
    @staticmethod
    def GetSceneResXMLBlob(id: int) -> list: ...
    @staticmethod
    def GetViewportImage() -> PairedImage: ...
    @staticmethod
    def RenameCustomPreset(presetName: str, newPresetName: str) -> ErrorStatus: ...
    @staticmethod
    def SaveImage(fileName: str, strFormat: str, imagePair: PairedImage) -> bool: ...
    @staticmethod
    def SaveRenderJobImage(fileName: str, strFormat: str, jobIndex: int, pDoc: Document) -> bool: ...
