# Auto-generated — Navisworks 24 — Autodesk.Navisworks.Internal.ApiImplementation

class ApiSecurity:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.ApiSecurity"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def IsAutodeskAssembly(assembly: Assembly) -> bool: ...
    @staticmethod
    def IsAutodeskPlugin(assemblyFilename: str, type: Type) -> bool: ...

class ApplicationAutomationImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.ApplicationAutomationImpl"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AddPluginAssembly(args: list) -> int: ...
    @staticmethod
    def AppendFile(args: list) -> int: ...
    @staticmethod
    def Benchmark(args: list) -> int: ...
    @staticmethod
    def CreateCache(args: list) -> int: ...
    @staticmethod
    def DisableProgress(args: list) -> int: ...
    @staticmethod
    def EnableProgress(args: list) -> int: ...
    @staticmethod
    def ExecuteAddInPlugin(args: list) -> int: ...
    @staticmethod
    def ExportNWD(args: list) -> int: ...
    @staticmethod
    def GenerateThumbnail(args: list) -> int: ...
    @staticmethod
    def GenerateThumbnailByRayTrace(args: list) -> int: ...
    @staticmethod
    def OpenFile(args: list) -> int: ...
    @staticmethod
    def Print(args: list) -> int: ...
    @staticmethod
    def PublishNWD(args: list) -> int: ...
    @staticmethod
    def SaveFile(args: list) -> int: ...

class ApplicationConfig:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.ApplicationConfig"""
    def __init__(self, *args) -> None: ...
    ...

class ApplicationImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.ApplicationImpl"""
    def __init__(self, *args) -> None: ...
    IsAutomationAction: bool
    Gui: GuiImpl
    @staticmethod
    def BeginAutomationAction() -> None: ...
    @staticmethod
    def CheckInitialised() -> None: ...
    @staticmethod
    def CheckUninitialised() -> None: ...
    @staticmethod
    def CreateDocument() -> Document: ...
    @staticmethod
    def CreateView(doc: Document, viewer: LcOwViewer) -> View: ...
    @staticmethod
    def DeclareExchangePackage(id: str, install_path: str, name: str, description: str, author: str, version: str) -> LcOpExchangePackage: ...
    @staticmethod
    def DestroyDocument(doc: Document) -> None: ...
    @staticmethod
    def DestroyView(view: View) -> None: ...
    @staticmethod
    def DispatchAutomationAction(action: str, args: ICollection) -> AutomationActionResult: ...
    @staticmethod
    def EndAutomationAction() -> None: ...
    @staticmethod
    def GarbageCollectNative() -> None: ...
    @staticmethod
    def InitialiseApi(config: ApplicationConfig) -> None: ...
    @staticmethod
    def InitialiseErrorHandling(config: ApplicationConfig) -> None: ...
    @staticmethod
    def InitialiseResources(config: ApplicationConfig) -> None: ...
    @staticmethod
    def IsApiInitialised() -> bool: ...
    @staticmethod
    def LoadPlugins() -> None: ...
    @staticmethod
    def Resolve(resolver: FileReferenceResolver, file: str, resolve_to_open: bool, resolved_to_open: str, resolve_to_store: bool, resolved_to_store: str) -> FileResolutionResponse: ...
    @staticmethod
    def SetClashPart(doc: Document, value: IDocumentClash) -> None: ...
    @staticmethod
    def SetGui(gui: IApplicationGui) -> None: ...
    @staticmethod
    def SetMainDocument(doc: Document) -> None: ...
    @staticmethod
    def SetTakeoffPart(doc: Document, value: IDocumentTakeoff) -> None: ...
    @staticmethod
    def SetTimelinerPart(doc: Document, value: IDocumentTimeliner) -> None: ...
    @staticmethod
    def TerminateApi() -> None: ...
    @staticmethod
    def TerminateErrorHandling() -> None: ...
    @staticmethod
    def TerminateResources() -> None: ...
    @staticmethod
    def UnloadPlugins() -> None: ...

class AssemblySwigAttribute(Attribute):
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.AssemblySwigAttribute"""
    def __init__(self, *args) -> None: ...
    TypeId: object

class AutomationActionResult:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.AutomationActionResult"""
    def __init__(self, *args) -> None: ...
    ...

class ClashImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.ClashImpl"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def InitialiseApi(document: Document) -> None: ...
    @staticmethod
    def TerminateApi(document: Document) -> None: ...

class CollectionImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.CollectionImpl`1"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AddRange(that: ICollection, from_: IEnumerable) -> None: ...
    @staticmethod
    def CopyFrom(that: ICollection, from_: IEnumerable) -> None: ...
    @staticmethod
    def CopyTo(that: IEnumerable, a: Array, arrayIndex: int) -> None: ...
    @staticmethod
    def Remove(that: IList, item: T) -> bool: ...
    @staticmethod
    def ValidateIndex(that: ICollection, index: int) -> None: ...
    @staticmethod
    def ValidateInsertIndex(that: ICollection, index: int) -> None: ...

class CollectionIntImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.CollectionIntImpl"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CopyFrom(that: ICollection, from_: LcUInt32Vector) -> None: ...
    @staticmethod
    def CopyTo(that: IEnumerable, to: LcUInt32Vector) -> None: ...

class DatabaseEventStateWatcher(LcOpSwigStateWatcher):
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.DatabaseEventStateWatcher"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def Add(watcher: DatabaseEventStateWatcher, handler: EventHandler, doc: Document, element_class: LcOpElementClass) -> None: ...
    def Notify(self, parts: LcOpStatePart, access: LcOpStateAccess) -> None: ...
    def NotifyElement(self, element: LcOpElementClass, undo_flags: LcOpStatePart, access: LcOpStateAccess) -> None: ...
    def RaiseResetEvent(self, ) -> None: ...
    @staticmethod
    def Remove(watcher: DatabaseEventStateWatcher, handler: EventHandler) -> None: ...

class EventDurationTrackingContext(TrackingContext):
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.EventDurationTrackingContext"""
    def __init__(self, *args) -> None: ...
    ...

class EventStateWatcher(LcOpSwigStateWatcher):
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.EventStateWatcher"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def Add(watcher: EventStateWatcher, handler: EventHandler, doc: Document, element_class: LcOpElementClass, pre_write: bool) -> None: ...
    def Notify(self, parts: LcOpStatePart, access: LcOpStateAccess) -> None: ...
    def NotifyElement(self, element: LcOpElementClass, undo_flags: LcOpStatePart, access: LcOpStateAccess) -> None: ...
    def NotifyEvent(self, evnt: LcOpStateEvent, access: LcOpStateAccess) -> None: ...
    def RaiseEvent(self, ) -> None: ...
    @staticmethod
    def Remove(watcher: EventStateWatcher, handler: EventHandler) -> None: ...
    def TryNotifyDelta(self, element: LcOpElementClass, baseDelta: LcOpDelta, undo_flags: LcOpStatePart, access: LcOpStateAccess) -> bool: ...

class FactoryDict:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.FactoryDict"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def FactoryDelegate(index: int) -> nwiFactoryDelegate: ...
    @staticmethod
    def Lookup(key: str) -> int: ...

class GuiImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.GuiImpl"""
    def __init__(self, *args) -> None: ...
    def Benchmark(self, output: str) -> None: ...
    def DisableProgressWhenAutomated(self, ) -> None: ...
    def EnableProgressWhenAutomated(self, ) -> None: ...
    def IsAutomated(self, ) -> bool: ...
    def Print(self, printer: str, driver: str, port: str) -> None: ...
    def PromptUserForPassword(self, password: SecureString, attrib: PublishProperties, filename: str) -> LcOpProgressUserDialogResponse: ...
    def ResolveInteractive(self, resolver: FileReferenceResolver, file: str, resolved_to_open: str) -> FileResolutionResponse: ...
    def ShowPublishInformation(self, attrib: PublishProperties, filename: str) -> LcOpProgressUserDialogResponse: ...

class IObjectManager:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.IObjectManager"""
    def __init__(self, *args) -> None: ...
    def AddObject(self, object: NativeHandle) -> None: ...

class ListEnumerator:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.ListEnumerator`1"""
    def __init__(self, *args) -> None: ...
    Current: T
    CurrentEx: object
    def Dispose(self, ) -> None: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class MicroEventTrackingContext(TrackingContext):
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.MicroEventTrackingContext"""
    def __init__(self, *args) -> None: ...
    ...

class ModelItemCollectionImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.ModelItemCollectionImpl"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ToCollection(items: IEnumerable) -> ModelItemCollection: ...
    @staticmethod
    def Where(that: ModelItemCollection, conditions: SearchConditionCollection, location: SearchLocations, pruneBelowMatch: bool) -> IEnumerable: ...
    @staticmethod
    def WhereInstanceGuid(that: IEnumerable, value: Guid) -> IEnumerable: ...

class NativeExportPluginAdaptor(AddInPlugin):
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.NativeExportPluginAdaptor"""
    def __init__(self, *args) -> None: ...
    ExportType: LcOpPluginCaps
    PluginRecord: PluginRecord
    DeveloperId: str
    Name: str
    Id: str
    def CanExecute(self, ) -> CommandState: ...
    def Execute(self, parameters: list) -> int: ...
    def TryShowHelp(self, ) -> bool: ...

class NativeHandleImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.NativeHandleImpl"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CanSafeTransferOwnershipFrom(from_: NativeHandle) -> bool: ...
    @staticmethod
    def CanSafeTransferOwnershipTo(to: NativeHandle) -> bool: ...
    @staticmethod
    def CheckOwnership(obj: NativeHandle) -> None: ...
    @staticmethod
    def CleanupAnyWeakRef(obj: NativeHandle) -> bool: ...
    @staticmethod
    def GetDocumentObject(obj: NativeHandle) -> Document: ...
    @staticmethod
    def GetHandle(obj: NativeHandle) -> IntPtr: ...
    @staticmethod
    def GetOwnership(obj: NativeHandle) -> NativeHandleOwnership: ...
    @staticmethod
    def GetParentObject(obj: NativeHandle) -> NativeHandle: ...
    @staticmethod
    def GetWeakRef(obj: NativeHandle) -> None: ...
    @staticmethod
    def InitDocumentObject(that: NativeHandle, source: NativeHandle) -> bool: ...
    @staticmethod
    def MarshalFromAscii(s: int) -> str: ...
    @staticmethod
    def MarshalFromUtf8(s: int) -> str: ...
    @staticmethod
    def MarshalGuid(from_: Guid, to: LcUGuid) -> None: ...
    @staticmethod
    def MarshalToAscii(buffer: LcUStringBuffer, s: str, argName: str) -> int: ...
    @staticmethod
    def MarshalToDateTimeTicks(dt: DateTime) -> int: ...
    @staticmethod
    def MarshalToUtf8(buffer: LcUStringBuffer, s: str) -> int: ...
    @staticmethod
    def ReleaseOwnership(obj: NativeHandle) -> None: ...
    @staticmethod
    def RuntimeChecks(obj: NativeHandle, qconst: bool) -> None: ...
    @staticmethod
    def SafeTransferOwnership(to: NativeHandle, from_: NativeHandle) -> bool: ...
    @staticmethod
    def SetDocumentObject(obj: NativeHandle, val: Document) -> None: ...
    @staticmethod
    def SetHandle(obj: NativeHandle, val: IntPtr) -> None: ...
    @staticmethod
    def SetParentObject(obj: NativeHandle, val: NativeHandle) -> None: ...
    @staticmethod
    def SetWeakRef(obj: NativeHandle, val: None) -> None: ...

class NativeHandleInit:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.NativeHandleInit"""
    def __init__(self, *args) -> None: ...
    ...

class NativeHandleOwnership:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.NativeHandleOwnership"""
    def __init__(self, *args) -> None: ...
    ...

class PluginExtensions:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.PluginExtensions"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AddCustomPlugin(name: str, developerId: str, displayName: str, toolTip: str, options: PluginOptions, plugin: CustomPlugin, interfaces: Collection) -> None: ...

class PluginLicenseAttribute(Attribute):
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.PluginLicenseAttribute"""
    def __init__(self, *args) -> None: ...
    Data: str
    TypeId: object

class ResolveInteractiveImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.ResolveInteractiveImpl"""
    def __init__(self, *args) -> None: ...
    def ResolveXRefInteractive(self, resolver: FileReferenceResolver, file: str, resolved_to_open: str) -> FileResolutionResponse: ...

class SaveCommonEventStateWatcher(LcOpSwigStateWatcher):
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.SaveCommonEventStateWatcher"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def Add(watcher: SaveCommonEventStateWatcher, handler: EventHandler, doc: Document, phase: LcOpSaveFileEventSaveFileEventPhase) -> None: ...
    def NotifyEvent(self, evnt: LcOpStateEvent, access: LcOpStateAccess) -> None: ...
    @staticmethod
    def Remove(watcher: SaveCommonEventStateWatcher, handler: EventHandler) -> None: ...

class SavedItemCollectionImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.SavedItemCollectionImpl`1"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def DeepCopyFrom(that: ICollection, from_: IEnumerable) -> None: ...
    @staticmethod
    def DeepCopyTo(that: IEnumerable, to: ICollection) -> None: ...

class SavedItemEventStateWatcher(LcOpSwigStateWatcher):
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.SavedItemEventStateWatcher"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def Add(watcher: SavedItemEventStateWatcher, handler: EventHandler, doc: Document, element_class: LcOpElementClass) -> None: ...
    def Notify(self, parts: LcOpStatePart, access: LcOpStateAccess) -> None: ...
    def NotifyElement(self, element: LcOpElementClass, undo_flags: LcOpStatePart, access: LcOpStateAccess) -> None: ...
    def RaiseResetEvent(self, ) -> None: ...
    @staticmethod
    def Remove(watcher: SavedItemEventStateWatcher, handler: EventHandler) -> None: ...
    def TryNotifyDelta(self, element: LcOpElementClass, baseDelta: LcOpDelta, undo_flags: LcOpStatePart, access: LcOpStateAccess) -> bool: ...

class SavedItemsElementImpl:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.SavedItemsElementImpl"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CheckCopyFromStatus(status: LcOpSavedItemsElementStatus) -> None: ...
    @staticmethod
    def CheckItemStatus(status: LcOpSavedItemsElementStatus, partName: str) -> None: ...
    @staticmethod
    def CheckMoveStatus(status: LcOpSavedItemsElementStatus, partName: str) -> None: ...
    @staticmethod
    def CreateIndexPath(el: LcOpSavedItemsElement, item: SavedItem, partName: str) -> Collection: ...
    @staticmethod
    def CreateReference(el: LcOpSavedItemsElement, item: SavedItem, partId: str, partName: str) -> SavedItemReference: ...
    @staticmethod
    def Initialise() -> None: ...
    @staticmethod
    def ResolveIndexPath(el: LcOpSavedItemsElement, path: IEnumerable) -> SavedItem: ...
    @staticmethod
    def Terminate() -> None: ...

class TrackingContext:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.TrackingContext"""
    def __init__(self, *args) -> None: ...
    def EndTracking(self, ) -> None: ...
    def GetCallerFileName(self, ) -> str: ...
    def GetCategory(self, ) -> CategorisationForTracking: ...
    def GetEndpointName(self, ) -> str: ...
    def IsNestedCall(self, ) -> bool: ...
    def StartTracking(self, ) -> None: ...

class UpdateFilesEventStateWatcher(LcOpSwigStateWatcher):
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.UpdateFilesEventStateWatcher"""
    def __init__(self, *args) -> None: ...
    IsReadOnly: bool
    IsDisposed: bool
    @staticmethod
    def Add(watcher: UpdateFilesEventStateWatcher, handler: EventHandler, doc: Document, phase: LcOpUpdateFilesEventPhase) -> None: ...
    def NotifyEvent(self, evnt: LcOpStateEvent, access: LcOpStateAccess) -> None: ...
    @staticmethod
    def Remove(watcher: UpdateFilesEventStateWatcher, handler: EventHandler) -> None: ...

class nwiFactoryDelegate:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.nwiFactoryDelegate"""
    def __init__(self, *args) -> None: ...
    Method: MethodInfo
    Target: object
    def BeginInvoke(self, init: NativeHandleInit, callback: AsyncCallback, obj: object) -> IAsyncResult: ...
    def EndInvoke(self, __unnamed000: NativeHandleInit, result: IAsyncResult) -> NativeHandle: ...
    def Invoke(self, init: NativeHandleInit) -> NativeHandle: ...
