# Auto-generated — Navisworks 24 — Autodesk.Navisworks.Internal.ApiImplementation.Data

class NavisworksConvert:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.Data.NavisworksConvert"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def TypeNameToDbType(Name: str) -> DbType: ...

class NavisworksSQLStatement:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.Data.NavisworksSQLStatement"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class SQLiteType:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.Data.SQLiteType"""
    def __init__(self, *args) -> None: ...
    ...

class SQLiteTypeNames:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.Data.SQLiteTypeNames"""
    def __init__(self, *args) -> None: ...
    ...

class TypeAffinity:
    """.NET: Autodesk.Navisworks.Internal.ApiImplementation.Data.TypeAffinity"""
    def __init__(self, *args) -> None: ...
    ...
